### PR TITLE
Fix for potential null pointer in DefaultNamed.java toString method.

### PR DESCRIPTION
**Pull request by DanVanAtta**
Fix for problem reported in -  #207

[Review on Reviewable](https://reviewable.io/reviews/triplea-game/triplea/209)

### CODE REVIEW

**Comment by veqryn** [comment]
It can not be null there, unless something somewhere else has gone seriously wrong (probably de-serialization).
All this pr does is hide the error so that noone will know about it.

**Comment by DanVanAtta** [comment]
Serialization/de-serialization allows objects to be created without calling the constructor. Thus, it very well *can* be null, and it is. See the example game file in the related issue for a repro case and real world example.

If this is not a good fix, can you suggest another fix that "saves" the save game from being completely ruined?

With respect to this being a bandaid, the real fix is ensuring it does not serialized when null. But the horse is out of the barn already.  Some player joined an in-progress game, this error was triggered, and then the whole game corrupted as it could no longer be continued. There is no reason to flag this error as a fatal that kills the whole game, so even suppressing it is better than the alternative.

**Comment by DanVanAtta** [comment]
"All this pr does is hide the error so that noone will know about it."

That is precisely the point of this PR. This NPE error has KILLED  a 14 HOUR game. Nobody gives a damn about the error, the point is to play the game. If this hides it so nobody ever knows about it and it never hurts anyone, then good. The goal is to play, not to craft error free code that kills a game for the smallest and non-impactful serialization oddity.

**Comment by DanVanAtta** [comment]
Sorry for getting heated - but you mentioned earlier dogma trumping pragmatism, this is a good example. 

With this patch, it would prevent the error from causing any problems. I'd rather work on removing the serialization stuff than digging into how/why this happens. It's not worth solving, my guess it would take a really long time to figure out exactly how/why this happened. Not worth it.

Meanwhile, my opponent has been sent a link to download and install a patched game with this fix so we can continue the game. In the meantime we've lost 4 hours of gameplay time. It's a nice consolation at least that at least the game has not been lost or ruined.

**Comment by DanVanAtta** [comment]
Added some logging so players will know when this error condition has happened.

**Comment by veqryn** [comment]
Looks better now.
I am fully aware of how serialization works and that it skips the constructor, which is why I brought it up.
You can actually see that I've done similar things in some other places (unit) where I was unable to find the root cause of the de-serialization error (which is most likely a circular dependency).

**Comment by ron-murhammer** [comment]
This is the first change that breaks Java 6 compatibility. Are we officially saying Java 7 is the minimum now?

**Comment by DanVanAtta** [comment]
Good point. Though the install4j stuff should be done soon and the next release should have java8 as a minimum. I don't think it makes any sense to wait the 2~4 months for the next release to see that as fact before we plan to move on. In support of that,  I think part of the hope is to allow for people to work in parallel and not serial.

**Pull request merged**
