### PR TITLE
Add sonarqube badges to README

### PR DESCRIPTION
**Pull request by DanVanAtta**
Adds a number of new badges:
- lines of code
- reliability rating
- security rating
- (sonar) vulnerabilities
- bugs
-code smells
-dupe line count %

 

## Functional Changes

[] New map or map update
[] New Feature
[] Feature update or enhancement
[] Feature Removal
[] Code Cleanup or refactor
[x] Configuration Change
[] Problem fix:  
[] Other:   

## Testing

[] Manual testing done

## Screens Shots

Screenshot from 2019-11-26 15-42-56

### CODE REVIEW

**Comment by RoiEXLab** [comment]
Hmm any idea if sonarcloud offers the badges in the flat-square look?

**Comment by DanVanAtta** [comment]
@RoiEXLab don't think so, did not see an option for it.

**Comment by RoiEXLab** [comment]
Hmm, it looks a little bit weird. I also checked the documentation. There really isn't any way. https://sonarcloud.io/web_api/api/project_badges
I see 2 options here:
1. Move all the sonarcloud badges into a dedicated line, so it isn't noticeable that much or
2. Use the "default" look for all of our badges. I really like the flat-square look more, but consistency on some level (global or per line) would be desireable

**Comment by DanVanAtta** [comment]
How about this?
Screenshot from 2019-11-27 16-03-09

We should also consider logical consistency as well. The previous grouping had our letter grades all on the same line, then line stats, then the various counts.

**Comment by DanVanAtta** [comment]
* I also swapped the coverage badge from codecov to sonar so that badge would have a consistent appearance.

**Pull request merged**
