### PR TITLE
Infrastructure: Update http run_server script

### PR DESCRIPTION
**Pull request by DanVanAtta**
1. Script can be no-arg and rely on default args assuming we will deploy configuration.yml
   file to proper directory.
2. Also corrects script arg "server". It is currently configured as a flag rather than
   as an arg. By using default args, we solve this.

 

## Functional Changes

[] New map or map update
[] New Feature
[] Feature update or enhancement
[] Feature Removal
[] Code Cleanup or refactor
[] Configuration Change
[] Bug fix:  
[] Other:   

## Testing

[] No manual testing done
[] Manually tested

### CODE REVIEW

**Comment by DanVanAtta** [comment]
It's pretty straight-forward, just a conditional in `main` method to check for args: https://github.com/triplea-game/triplea/blob/master/http-server/src/main/java/org/triplea/server/http/ServerApplication.java#L69

**Comment by RoiEXLab** [comment]
Ah, thanks for the clarification, I was wondering if this would be some sort of weird vagrant mechanism 😅

**Comment by RoiEXLab** [comment]
Oh and btw. I haven't had the time so far to review the large pr.
Because it's the first one in the list I didn't merge all the approved PRs so far, so if they're unrelated feel free to merge

**Comment by DanVanAtta** [comment]
Cool, thanks @RoiEXLab 
Vagrant is not doing a lot other than simulating a linode instance. For the most part the latest round of development is live against prerelease. I likely should be doing that against vagrant so that there is a dogfooding benefit.

**Pull request merged**
