### PR TITLE
Run dos2unix on all java files, modifies 337 files.

### PR DESCRIPTION
**Pull request by DanVanAtta**
Run dos2unix on all java files. Impacts about 1/3 of all files. That means there is a good chance most likely to modify these files on future PR. To avoid mixing those future changes and line ending consistency, a bulk change is being done with the one item now. This item (dos2unix, line ending correction) is a good one to do now too since line ending differences usually impact every line of a file and cause merge conflicts on every line (so if anyone changes any of these 337 between now and the PR is merged, we'll have a merge conflict - so this kind of change becomes much more difficult to do as time progresses. Now is the best time to make this specific change. I've also pruned back/simplified this PR to try and make it easier to review, and secondly to represent that this is the important change to do now to avoid merge conflicts. Other changes can sit more or less happily behind it. Less so the other way round).

Below are  verification commands that can be run. I've also verified that the code still compiles, tests, and  executes (can join lobby and launch a game) properly after this change.

  ## Below we check how many dos line endings we have. We check how many files have a dos line
  ## ending, and that no files have been modified. We then apply dos2unix. It is then verified
  ## that no dos line endings exist, and the number of modified files matches the file count
  ## that had dos line endings.

   # pre-counts, number of DOS line endings
~/work/triplea$ find . -name "*.java" | xargs grep "^M" | wc -l
81773
   # number of files with DOS line ending
~/work/triplea$ find . -name "*.java" | xargs grep -l "^M" | wc -l
337
   # number of modified files
~/work/triplea$ git status | grep modified | wc -l
0
   # total number of java files (we will modify one third of all files)
~/work/triplea$ find . -name "*.java" | wc -l
960

   ## >> applying dos2unix conversion here
~/work/triplea$ find . -name "*.java" | xargs dos2unix
dos2unix: converting file ./src/games/strategy/thread/LockUtil.java to Unix format ...
dos2unix: converting file ./src/games/strategy/thread/ThreadPool.java to Unix format ...
:
:

   ## now doing post check, we see we have 337 files modified, as expected, and no more dos line endings
dan@dan-desktop01:~/work/triplea$ git status | grep modified | wc -l
337
dan@dan-desktop01:~/work/triplea$ find . -name "*.java" | xargs grep -l "^M" | wc -l
0

### CODE REVIEW

**Comment by veqryn** [comment]
@ron-murhammer I will have a look at this patch tomorrow.  Can you please tell me if you have any work pending that you would like to get in before this patch ruins easy merging?

**Comment by DanVanAtta** [comment]
Using the magic ignore white space flag in github "?w=1", makes this diff very easy: https://github.com/triplea-game/triplea/pull/14/files?w=1

For the record and full disclosure, I don't know how *difficult* merges would be if you had conflicts with line endings. Git would need to do a merge, though automerge, what it would use by default, is quite powerful. Some other git work flows likely would require manual resolution.

**Comment by ron-murhammer** [comment]
Everything I was working on is committed.

My only suggestion is to try and do all formatting changes at once so that we don't have to worry about affecting other development moving forward.

**Comment by DanVanAtta** [comment]
I agree it's a good time to do mass changes that affect a lot of files. Though I don't think those changes should be part of this PR.

**Comment by DanVanAtta** [comment]
Now that we found the ignore whitespace flag, this has become a trivial pull request. Anything blocking this from being merged?

**Comment by veqryn** [comment]
time.
i'll take a look tonight.

**Comment by DanVanAtta** [comment]
Fixed merge conflict, happily enough diff still only shows white space differences: https://github.com/triplea-game/triplea/pull/14/files?w=1

**Comment by ron-murhammer** [comment]
So I guess my question is why do we need to make these consistent? Why choose dos2unix instead of unix2dos? How are we guaranteed that later on we don't end up with the different line breaks? This seems to indicate that using git settings is the best way to handle this but there are lots of various opinions in the thread: http://stackoverflow.com/questions/170961/whats-the-best-crlf-carriage-return-line-feed-handling-strategy-with-git

**Comment by veqryn** [comment]
Hm... i may have jumped the gun on this then.

I could not replicate your bash commands, xargs was not working for me.
I also did not feel fully comfortable accepting a patch/pull that touched all files, so I tried doing it myself to make sure of it.

I can back out the commit, pending what you have to say Redrum...

**Comment by DanVanAtta** [comment]
Since you reproduced this pull request and committed, no point in this branch, so will close.

Couple comments about pull request etiquette:
1. Unless there are immediate objections or action items, don't let the PR linger around. If the change adds benefit, merge it, don't wait. Waiting causing merge conflicts, and for the requester to hang around checking status, it just causes a lot of overhead. 
2. Don't include a "commit id" in your commit message "commit be232c0741ac9196653ae5be87a9e86f077131b1
Author: Chris Duncan <veqryn@hotmail.com>
Date:   Fri Jul 31 00:34:20 2015 -0600

    changing java files to unix line endings
    
    Change-Id: Ic9ef80613f5931edd7ef65ff57647be4518b10ac

The change-id doesn't make any sense, there is a SHA already generated for your commit.

3. Trust your tools. The github difference showed no differences beyond whitespace. I'm not sure why you really felt it was so necessary to be distrustful and reproduce the changes yourself. Ultimately I feel like we're being a bit too cautious. Velocity in this code base is already slow, unless we want to officially admit it is on life support and will never be more, we need to try and move a bit faster.

**Comment by DanVanAtta** [comment]
So I guess my question is why do we need to make these consistent? 
A mixture of dos and unix line endings can cause various problems. Notably unix devs and the corresponding tools can have a host of issues. Unix line endings cause no problem for windows. So it's that DOS line endings are bad. Mixing them in with unix line endings is also bad.

Why choose dos2unix instead of unix2dos? 
We have mostly unix line endings. DOS line endings are bad.

How are we guaranteed that later on we don't end up with the different line breaks? 
We aren't. Hopefully though people will do a self review, "git diff" will show mixed line endings, and so will pull requests AFAIK.


w.r.t : http://stackoverflow.com/questions/170961/whats-the-best-crlf-carriage-return-line-feed-handling-strategy-with-git

Enforcing the line endings in GIT is fine if people have a hard time not introducing DOS line endings.

**Pull request closed without merging**
