### PR TITLE
Release 1 8 0 7

### PR DESCRIPTION
**Pull request by veqryn**
Fixing issues introduced by https://github.com/triplea-game/triplea/commit/3c3e6077a6a4f461c0500dbd733585daca675c33#diff-baafe2209ef3b890ea000d7dca31772a

[Review on Reviewable](https://reviewable.io/reviews/triplea-game/triplea/100)

### CODE REVIEW

**Comment by veqryn** [comment]
@gaborbernat: Your previous patch, for the gradle build, is what broke our Mac app.
We need to be more careful about changes to core components of triplea that we know work.

**Comment by gaborbernat** [comment]
Hmmm will check and push a fix :)

**Comment by DanVanAtta** [comment]
- Can we get clarity on what the break was?
- FYI: In general revert is not a good thing to do.  A line item fix would have been preferable. This diff is incredibly difficult to decipher what has changed. I still am not sure what functionality changes have happened.
- @veqryn  The Travis build is now broken. That's breaking more stuff that used to work. I'm surprised a branch with a broken build was merged in.

**Comment by veqryn** [comment]
Right now, as far as I can tell, Travis doesn't actually do anything other than build the gradle build (which is incomplete, and we aren't using it anyway yet).
I did not revert his whole patch, only the 1 method that was broken (getRootFolder).  All I did was copy the code of what used to be before the patch, and then pasted it into the branch (and let it get formatted).
You can check back through the commit history (see here: https://github.com/triplea-game/triplea/commit/3c3e6077a6a4f461c0500dbd733585daca675c33#diff-baafe2209ef3b890ea000d7dca31772a) to see what his changes were, originally.

**Comment by DanVanAtta** [comment]
Travis ran Gradle, which ran tests. That is more functionality than we used to get from Ant+SVN. Travis has been helpful for identifying test failures and has helped out at least twice now to catch problems. So it is being used.

Gradle is almost complete as well with respect to feature parity of the build process. It can build an all_platforms.zip, and already that is 95% of the build process.

I appreciate the cleaner commit, but this PR was not clean. You also did not have anyone review it either. Opening a PR and then merging it right away is pointless. The point is for it to be reviewed. Part of the idea is that github operates largely on a peer system, code reviews are peer reviews.  

Last, can we get one or two sentences clear statements on what the break is? Did a path change somewhere, what was the symptom of the  problem even? Even in the smaller diff there is still a lot of changes...

**Comment by DanVanAtta** [comment]
I don't think there is any really further useful conversation to be had. So let me state what I'm thinking directly:
- I'm not totally happy with this, I would have liked to see this PR be reviewed and a statement be given about why it was a fix (or some indication of why we think this was the problem). At least then we could learn from prior mistakes and all be more aware of one more brittle element of this code base.

- Perhaps there should have been some acknowledgement at least that we were breaking the gradle tests and that would cause travis builds to break. It's one thing to say, this is an emergency cause we got some regressions we must fix, and if a cost of that is breaking Travis then so be it. But just reverting really quick saying this broke the build in one manner or another, then not clearly indicating why or that it was tested to verify that was really the case. Then Travis breaking almost as a surprise and a afterthought of, "oh well, we weren't really using it and it wasn't complete", that is a problem I can see. 

So, i don't disagree with the course of action per say, but I think the execution could have been more collaborative.

**Comment by gaborbernat** [comment]
Do you have an exact error we got? We'll need to create a unit test for
this :)

**Comment by veqryn** [comment]
The method contents were reverted to their previous state.  I do not understand your complaints about the PR contents!

The PR was merged right away so that Ron can fix the currently broken releases by rebuilding them.
A review would have been nice, but unnecessary: The previous state worked perfectly, and travis is not necessary for anything yet.  I should have mentioned here that travis and gradle would break, but I mentioned it here instead: https://github.com/triplea-game/triplea/issues/84

The original change/patch was found to be the problem by troubleshooting the issue.  I followed the error messages people were receiving all the way back up the chain, and found that the only possible thing that changed since 1805 was this method.  The particular error messages people were getting was posted here: http://www.axisandallies.org/forums/index.php?topic=36406.msg1440936#msg1440936
```
java.lang.IllegalStateException: No dice server folder:/Volumes/TripleA/Triplea.app/Contents/Resources/Java/dice_servers
   at games.strategy.engine.random.Properties DiceRoller.loadFromFile(PropertiesDiceRoller.java:41)
   at games.strategy.engine.framework.startup .ui.PBEMSetupPanel.loadDiceServer(PBEMSetupPanel.java:162)
   at games.strategy.engine.framework.startup .ui.PBEMSetupPanel.loadAll(PBEMSetupPanel.java:149)
   at games.strategy.engine.framework.startup .ui.PBEMSetupPanel.<init>(PBEMSetupPanel.java:91)
   at games.strategy.engine.framework.startup .mc.SetupPanelModel.showPBEM(SetupPanelModel.java:41)
   at games.strategy.engine.framework.startup .ui.MetaSetupPanel$2.actionPerformed(MetaSetupPanel.java:141)
```
Other people were complaining that triplea could not find any maps (the ones that come packaged with triplea), which again points to an issue with this method.

Possible issues with the original change are: the ways it is finding the root folder, the use of 'bin' (because we could be in any folder/directory one level up from root, such as bin, old, Java, temp, etc), etc.  These can be addressed in a later patch, because the priority right now is the 1807 release build.

**Comment by gaborbernat** [comment]
Thanks for the information. I think here the release numbering is faulty
too. We shouldn't be able to release a version twice, it should be a new
release, with a new release numbering :)

**Comment by DanVanAtta** [comment]
FYI, I'm getting pretty close to complete with a backwards compatible patch for the map search paths. Fixes the tests in gradle.

**Pull request merged**
