### PR TITLE
Add server mangement documentation

### PR DESCRIPTION
**Pull request by RoiEXLab**
As requested by @DanVanAtta

### CODE REVIEW

**Comment by ron-murhammer** [comment]
@RoiEXLab Awesome. Looks good to me. I'll give @DanVanAtta a chance to provide feedback.

**Comment by prastle** [comment]
we just need to impot to forum thread but yes ty
@RoiEXLab great stuff with new bot server

**Comment by prastle** [comment]
since both of u reading and @DanVanAtta   can we make marti a separate server?  and then figure out what we doing with warclub etc? just a thought

**Comment by DanVanAtta** [comment]
@prastle happy to discuss server allocation more, but probably better to do so in gitter or a dedicated github issue. But to respond, warclub/marti is not trivial to migrate (maybe not possible). We could move the lobby off of that server, but given how much extra horsepower we have on that one server, I think we may be stuck with warclub and marti on the current server.

**Comment by prastle** [comment]
Np was just a thought.

**Pull request merged**
