### PR TITLE
Inline constant params1

### PR DESCRIPTION
**Pull request by DanVanAtta**
This change is [Reviewable](https://reviewable.io/reviews/triplea-game/triplea/714)

### CODE REVIEW

**Comment by RoiEXLab** [comment]
What IDE are you using to perform this huge auto replacements?

**Comment by DanVanAtta** [comment]
intelliJ

**Comment by RoiEXLab** [comment]
Free or paid?

**Comment by DanVanAtta** [comment]
AFAIK  the 30 day trial gives full access, I could be wrong though. To answer your question, I do have paid license for it

**Pull request merged**
