### PR TITLE
Game chooser locking problem causing UI lock-up 

### PR DESCRIPTION
**Pull request by DanVanAtta**
Perhaps because i have some partially broken maps in my home folder, I'm not sure why, but ever since integrating the latest re-formatting change I'm getting a deadlock on game launch. The game start just spins. I got a stack trace and found where the code was stalled. It could be fixed by removing a synchronized tag from the method. The synchronization in this class is pretty clearly not correct. For a lot of the game set up panel code, the synchronization likely all needs to be removed (with respect, but I suspect that the majority of synchronization was not done correctly).

I rolled back my code history and this looks like it is an existing bug on current master in the repo and is not related to the travis CI changes.

[Review on Reviewable](https://reviewable.io/reviews/triplea-game/triplea/66)

### CODE REVIEW

**Comment by veqryn** [comment]
I did some basic logging, and the s_cachedGameModel is being accessed by multiple threads.
I doubt there is a deadlock, it might be that the game model is being loaded and you have a ton of maps being parsed.
Noone has reported an error or deadlock in this area in years.

**Comment by DanVanAtta** [comment]
If access to s_cachedGameModel were single threaded dead lock would not be possible.

I have 11 maps. 2 of which are being reported as out of date, I killed the game during download. Not too unreasonable considering I've had map downloads need upwards of 40 minutes.

Once in the 'deadlock' state I've let it sit for over 10 minutes and no progress has been made. Typically starting a local game, it launches in five or ten seconds (as with the patch it does). Considering the time to launch at least varies by so much, we do have something happening.

The lack of bug reports I do not know is 100% significant. Not everyone knows where/how to report bugs, and not everyone who hits this would be inclined to report. In addition it does look like not everyone would and that by re-installing everything you could maybe avoid it. Since a response to a bug report would ask for that anyways, perhaps the users have been abandoning the game or re-installing and patching it that way.

During the 15 minute mark of waiting for the game to load, here is the stack trace showing the dead lock. When the game starts there is a call into NewGameChooser.java that is not finishing. That call is grabbing a lock on the class. Then the Swing AWT thread comes along from the response of a button and tries to also do something with NewGameChooser.java. It waits to grab the lock. Now the AWT thread is waiting and the UI is frozen.

Here is the stack trace and the relevant code per thread. While I have a repro case I'm looking at it in more detail:

```
"Thread-7" #26 prio=6 os_prio=0 tid=0x00007f1e98359800 nid=0x341f runnable [0x00007f1e92dc8000]
   java.lang.Thread.State: RUNNABLE
	at sun.misc.URLClassPath.getLoader(URLClassPath.java:492)
	- eliminated <0x00000000d82455b8> (a sun.misc.URLClassPath)
	at sun.misc.URLClassPath.getNextLoader(URLClassPath.java:457)
	- locked <0x00000000d82455b8> (a sun.misc.URLClassPath)
	at sun.misc.URLClassPath.findResource(URLClassPath.java:187)
	at java.net.URLClassLoader$2.run(URLClassLoader.java:569)
	at java.net.URLClassLoader$2.run(URLClassLoader.java:567)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findResource(URLClassLoader.java:566)
	at java.lang.ClassLoader.getResource(ClassLoader.java:1093)
	at games.strategy.engine.framework.ui.NewGameChooserModel.populateFromZip(NewGameChooserModel.java:106)
	at games.strategy.engine.framework.ui.NewGameChooserModel.populate(NewGameChooserModel.java:79)
	at games.strategy.engine.framework.ui.NewGameChooserModel.<init>(NewGameChooserModel.java:33)
	at games.strategy.engine.framework.ui.NewGameChooser.refreshNewGameChooserModel(NewGameChooser.java:244)
	- locked <0x000000008346f1e0> (a java.lang.Class for games.strategy.engine.framework.ui.NewGameChooser)
	at games.strategy.engine.framework.startup.mc.GameSelectorModel$1.run(GameSelectorModel.java:365)
	at java.lang.Thread.run(Thread.java:745)

      if (!refreshedAlready) {
        new Thread(new Runnable() {
          @Override
          public void run() {
>>>            NewGameChooser.refreshNewGameChooserModel(); // this is where we enter the stack
          }
        }).start();
```

Stack trace for thread number 2, fired by button click (in this case I could trigger by selecting choose game):
```
"AWT-EventQueue-0" #14 prio=6 os_prio=0 tid=0x00007f1efc4ee000 nid=0x3416 waiting for monitor entry [0x00007f1ed0d68000]
   java.lang.Thread.State: BLOCKED (on object monitor)
	at games.strategy.engine.framework.ui.NewGameChooser.getNewGameChooserModel(NewGameChooser.java:235)
	- waiting to lock <0x000000008346f1e0> (a java.lang.Class for games.strategy.engine.framework.ui.NewGameChooser)
	at games.strategy.engine.framework.ui.NewGameChooser.createComponents(NewGameChooser.java:59)
	at games.strategy.engine.framework.ui.NewGameChooser.<init>(NewGameChooser.java:48)
	at games.strategy.engine.framework.ui.NewGameChooser.chooseGame(NewGameChooser.java:108)
	at games.strategy.engine.framework.startup.ui.GameSelectorPanel.selectGameFile(GameSelectorPanel.java:385)
	at games.strategy.engine.framework.startup.ui.GameSelectorPanel.access$2(GameSelectorPanel.java:373)
	at games.strategy.engine.framework.startup.ui.GameSelectorPanel$2.actionPerformed(GameSelectorPanel.java:190)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2346)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
	at org.pushingpixels.substance.internal.utils.RolloverButtonListener.mouseReleased(RolloverButtonListener.java:124)
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:290)
	at java.awt.Component.processMouseEvent(Component.java:6525)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6290)
	at java.awt.Container.processEvent(Container.java:2234)
	at java.awt.Component.dispatchEventImpl(Component.java:4881)
	at java.awt.Container.dispatchEventImpl(Container.java:2292)
	at java.awt.Component.dispatchEvent(Component.java:4703)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4898)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4533)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4462)
	at java.awt.Container.dispatchEventImpl(Container.java:2278)
	at java.awt.Window.dispatchEventImpl(Window.java:2750)
	at java.awt.Component.dispatchEvent(Component.java:4703)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```
	
  private void createComponents() {
    m_okButton = new JButton("OK");
    m_cancelButton = new JButton("Cancel");
    m_refreshGamesButton = new JButton("Refresh Game List");
                         //  <<<<<< This next line is where we try to grab a lock on getNewGameChooserModel() from the AWT thread >>>>>
    m_gameListModel = getNewGameChooserModel();
    m_gameList = new JList(m_gameListModel);
    m_infoPanel = new JPanel();
    m_infoPanel.setLayout(new BorderLayout());
    m_notesPanel = new JEditorPane();
```

**Comment by veqryn** [comment]
There is no possible way for this to deadlock there.
Waiting a long time while being blocked does not mean it is deadlocked, it just means that whatever process has the lock is doing something (or spinning endlessly).
Deadlock means thread A is waiting on thread B, while B is waiting on thread A.
I can not accept this patch/pull.

**Comment by DanVanAtta** [comment]
You are correct we do not have deadlock because there is no circular wait. We do on the other hand have a frozen UI because the AWT thread is waiting forever for a lock it will never get. 

I'm looking at the root cause of why the game chooser is not making progress. Likely I think there is an error condition during map parsing that is not being handled well perhaps.

In the meantime, the synchronization of this method is not done very well:
```
  public synchronized static void clearNewGameChooserModel() {
    if (s_cachedGameModel != null) {
      s_cachedGameModel.clear();
      s_cachedGameModel = null;
    }
  }
```
What are the consequences of it not being synchronized? Well two threads could go in and do the clear operation, and both could then set the cached game model to be null. With the lock, we instead make one thread to wait to then repeat the work of the other. There is no guarantee that nobody else would have come in and set the cached game model back to non-null again. 

But two threads executing clear together could be a problem. Particularly looking at that code we have some index stuff which could cause an index out of bounds maybe. But looking at what clear does, it removes elements from an internal data structure, a Vector. Well, this vector would be GC'd anyways once we set the s_cachedGameModel to null. This means we don't need to call the clear method at all. With the method being just "s_cachedGameModel = null", the operation is now  atomic and doesn't need to be synchronized.

So I believe the method *should* look like this:
```
  public static void clearNewGameChooserModel() {
      s_cachedGameModel = null;
  }
```
Otherwise, as is, I don't see the benefit of the current synchronize block - what is it doing correctly?  

As is I see two action items:
- update the clearNewGameChooserModel as described above.
- continue investigating why game chooser is never returning, figure out root cause, repro case and add a patch

**Comment by DanVanAtta** [comment]
The game freezing up and nothing to do to fix it but re-install is very concerning to  me. I'm still clearly in the middle of trying to understand this problem. I'll re-open with a root cause fix rather than a band-aid when I understand and can present the details in a more cohesive and comprehensible manner.

**Comment by veqryn** [comment]
Removing synchronization would allow both threads to be creating new models at the same time, which we do not want.
We also do not want a thread clearing the model while the other thread is building it.
It doesn't happen in our case, but I would rather two threads do the work twice, than have an inconsistent and possibly fatal state.

I suggest you spend a bit more time in debug mode, and follow the execution all the way through to see what is really going on.

**Comment by DanVanAtta** [comment]
The two models will be built on their own threads, so which one is undone in the assignment will be a race condition. Alternatively, if the constructor itself is not thread safe, we could have other thread safety problems elsewhere too  (nothing guarantees that this object isn't somewhere else at the same time independent of this lock and class).

I've made some further progress and have found the infinite loop causing the game model to never finish building. So the AWT thread locking up is certainly more a side effect. 

As discussed I do believe that we can safely remove synchronize from "refreshNewGameChooserModel". We can also remove the synchronize from "clearNewGameChooserModel" too if we remove the "clear" method call there. We likely do not have any listeners on the model that do anything when the model is cleared, so we may not need the call. In that case the method becomes atomic and no longer needs the lock.

Those updates for synchronization I'm not sure if I'll pursue, more interested in fixing the RC of the underlying problem, the infinite loop.

**Comment by veqryn** [comment]
You did not say why you think it is safe to remove synchronization.
What happens when you are populating the list of game entries, and clear it in the middle of populating it?
There is a very good reason why synchronization exists right there: to prevent this exact situation.

**Comment by DanVanAtta** [comment]
The method in question has two lines:
```
    clearNewGameChooserModel();
    s_cachedGameModel = new NewGameChooserModel();
```

clearNewGameChooserModel() has only a few lines, the methods is synchronized,  we essentially have four lines:
```
   if( s_cachedGameModel != null ) {
     s_cachedGameModel.clear();
     s_cachedGameModel = null;
   }
   s_cachedGameModel = new NewGameChooserModel();
```
Calling s_cachedGameModel.clear() doesn't interact with the NewGameChooserModel() that is created. No matter how many threads are simultaneously executing this code, each one will build their own copy of NewGameChooserModel and exactly one of them will be the last one to execute and will be the winner in setting s_cachedGameModel. 

Thread safety issues are around the call to the clear() method. Particularly if you get two threads in there, or try to call clear() when another thread just nulled out the object, then you'll get trouble. So between the two methods, the only needed synchronization that I see is this:


```
  public static void refreshNewGameChooserModel() {
    clearNewGameChooserModel();
    s_cachedGameModel = new NewGameChooserModel();
  }

  public static void clearNewGameChooserModel() {
    synchronized( this ) {
      if (s_cachedGameModel != null) {
        s_cachedGameModel.clear();
      }
    }
    s_cachedGameModel = null;
  }
```

For comparison, here is original;
```
  public static synchronized void refreshNewGameChooserModel() {
    clearNewGameChooserModel();
    s_cachedGameModel = new NewGameChooserModel();
  }

  public static synchronized void clearNewGameChooserModel() {
    if (s_cachedGameModel != null) {
      s_cachedGameModel.clear();
      s_cachedGameModel = null;
    }
  }
```

The only benefit of the clear() is that it calls listeners. I don't think we added any. If there are none native from swing, then we don't need the clear() method at all (it clears out an internal vector data list, but that would be GC'ed anyway when we orphan remove the only reference to the parent object)

**Comment by veqryn** [comment]
You are missing a large piece of this.
If we are trying to clear the model AFTER some thread has started but not finished creating a new model, then if they are not synchronized we will end up with a model that is not empty.  This not desirable.
The point of this is so that if we issue a Clear command, then there will NOT be a model until someone calls either Get or Refresh at a later time.

We also do not want multiple threads parsing the map files at the same time.  It takes a very large amount of memory to do this, and this is one of the reasons we moved to a cached model in the first place.

**Comment by DanVanAtta** [comment]
Good point about the ordering of clear and refresh. To be clear in our case we have three threads. We have a background loader thread, the AWT event thread that tries to access the cache for choosing a game, and a game launching thread that clears the data loaded by the background loader.

The game launching thread is driven by AWT events, so really we only have two threads to every worry about. The background loading thread and the game selection window thread. Alternatively the background loading thread and a game launching thread that calls clear.

So you do have it right now that a clear after refresh will result in the clear being the last operation. I'll point out though if we had another thread, a refresh, a refresh, then a clear, the clear might not be the winner, it'll be a race between the second refresh and the third clear operations. Since we have only two threads, we're okay.

But... The idea of blocking on a thread so we can cancel the work done by it is bothersome. Following that I figured out the impact, restart a game and you get a nice 5 second delay. Or at least I did and I do not have that many maps.

So, the behavior of a clear after refresh needs to be kept in places. But we don't need to keep the synchronize on the clear if the clear will notify the refresh that the results are to be forgotten.

I've submitted #74 as a follow up with that change - so that the clear does not block the launching of new games. With that patch you can pretty rapidly restart local games (I got a little bit dizzy doing so), and we don't lose the prior synchronization stuff. For example, if you click "choose game" right away when the game launches, the AWT is blocked until all games are loaded (as was the case before)

**Pull request closed without merging**
