### PR TITLE
Commit changelog.txt per .gitattributes modifications. 

### PR DESCRIPTION
**Pull request by DanVanAtta**
After the new .gitattributes file, it's impossible on CLI to keep git from thinking this file is not modified after a clean checkout, (I try reverting it, resetting, everything) perhaps it has the wrong line endings compared to the .gitattribute file.

[Review on Reviewable](https://reviewable.io/reviews/triplea-game/triplea/141)

### CODE REVIEW

**Comment by DanVanAtta** [comment]
@veqryn This is actually a really annoying thing to have happen with .gitattributes. Now many git operations fail because the file is modified, and there is no way to "un-modify" it except to commit this same change in every branch.

**Comment by veqryn** [comment]
I do not understand what you mean. What git operations are failing?  And because of the .gitattributes or the changelog.txt?
I just tried a bunch of things, and they were all successful.

**Comment by veqryn** [comment]
I think maybe your core.autocrlf settings are wrong.
Please change to 'false', because git it probably checking out the files and converting the line endings to just LF, in total violation of what .gitattributes was there to do.

**Comment by DanVanAtta** [comment]
is this not the same change as #142?

**Comment by DanVanAtta** [comment]
http://git-scm.com/docs/gitattributes
> [core]
	autocrlf = true
 This does not force normalization of all text files, but does ensure that text files that you introduce to the repository have their line endings normalized to LF when they are added, and that files that are already normalized in the repository stay normalized.


Can we instruct the map makers to install sublime or something and not use notepad for editting XML? It's really quite simple to just not use notepad, and meanwhile we get to completely avoid CRLF and the small headaches it causes.


Regardless, seems like this change is probably the same as #142. Though I'm unsure why #142 also changes an XML file that did not seem to also need to be changed for me as well.

**Comment by DanVanAtta** [comment]
Nope, not the core.autocrlt settings, same behavior no matter the value. The problem does look to be the line endings of the file do not correspond to the new values in .gitattributes, and so the problem is that .gitattributes *is* working, as opposed to is *not* working.

**Comment by DanVanAtta** [comment]
For example:
```
dan@dan-desk:~/work/triplea$ git pull --rebase . master
Cannot pull with rebase: You have unstaged changes.
```

Note the "unstaged changes" part.

So Git status shows:
	modified:   build.gradle
	modified:   changelog.txt


Then there is no way to unmodify those files. git checkout, reset, delete, git stash, anything, the .gitattributes changes it right away. This means that until I commit those files, I can't do anything on these branches, hence, breaking git operations.

**Comment by gaborbernat** [comment]
This is probably a non-windows issue, as on Windows the format is just right.

On 9/2/15, Dan Van Atta <notifications@github.com> wrote:
> For example:
> ```
> dan@dan-desk:~/work/triplea$ git pull --rebase . master
> Cannot pull with rebase: You have unstaged changes.
> ```
>
> Note the "unstaged changes" part.
>
> So Git status shows:
> 	modified:   build.gradle
> 	modified:   changelog.txt
>
>
> Then there is no way to unmodify those files. git checkout, reset, delete,
> git stash, anything, the .gitattributes changes it right away. This means
> that until I commit those files, I can't do anything on these branches,
> hence, breaking git operations.
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/triplea-game/triplea/pull/141#issuecomment-136974980


-- 
 Bernát Gábor
Student -  Budapest University of Technology and Economics - Computer
Engineering, M.Sc. - Budapest, Hungary
System Integrator - Gravity R&D | Rock Solid Recommendations - Budapest
office | 5-7 Expo ter | H-1101 | Budapest | Hungary

**Comment by DanVanAtta** [comment]
PR, updated, build.gradle causing same problem.

It's very severe of a problem since .gitattributes will re-apply changes, stashing does not work any more to hide changes since .gitattributes does its thing, and you can't then change branches, merge, pull, or do much of else other than commit.

**Comment by DanVanAtta** [comment]
The test that failed is a flaky threadpool test, fails sometime often. #109 removes our threadpool implementation. I think it helps with the failure rate (though TBH I think we may need to remove the test, even with a library threadpool implementation I want to say I've still observed sporadic failures)

**Comment by DanVanAtta** [comment]
@gaborbernat , could you check out this branch (master on  git@github.com:DanVanAtta/triplea.git), and see if git immediately updates the line endings? I'm wondering if this is .gitattributes or if there is a git formatting war or something.

**Comment by gaborbernat** [comment]
I'll do, give me 3 hours as I'm busy with work at the moment.

On 9/2/15, Dan Van Atta <notifications@github.com> wrote:
> @gaborbernat , could you check out this branch (master on
> git@github.com:DanVanAtta/triplea.git), and see if git immediately updates
> the line endings? I'm wondering if this is .gitattributes or if there is a
> git formatting war or something.
>
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/triplea-game/triplea/pull/141#issuecomment-136980740


-- 
 Bernát Gábor
Student -  Budapest University of Technology and Economics - Computer
Engineering, M.Sc. - Budapest, Hungary
System Integrator - Gravity R&D | Rock Solid Recommendations - Budapest
office | 5-7 Expo ter | H-1101 | Budapest | Hungary

**Comment by DanVanAtta** [comment]
Hmm, there is something wrong, I follow these steps that look to fix files git wants to automatically fix: http://stackoverflow.com/questions/1510798/trying-to-fix-line-endings-with-git-filter-branch-but-having-no-luck/1511273#1511273, now 125 files are modified.

**Comment by veqryn** [comment]
Something is definitely not right here.
If we need to, I will remove the .gitattributes file, and we will just go back to the old way of doing things.
But I'd like to give it a college try first.
I can test on my linux vm, but I need to make time when I am home, because that is on my desktop.

**Comment by gaborbernat** [comment]
I've been looking into this for the last 2 hours, will let you know if I
found out what's the fix

Bernát GÁBOR

**Pull request closed without merging**
