### PR TITLE
Add isSuicideOnHit Unit Attribute

### PR DESCRIPTION
**Pull request by ron-murhammer**
Addresses: https://forums.triplea-game.org/topic/323/unit-option-which-suicides-only-when-it-registers-a-hit-mines

Recommend reviewing without whitespace changes (?w=1).

**Functional Changes**
- Add new isSuicideOnHit unit attribute
- Implement logic to roll isSuicideOnHit unit types separately so the engine knows if they roll hits
- Implement logic to remove any isSuicideOnHit units that roll hits

**Testing**
- Added unit test to test basic functionality of "mine" unit using isSuicideOnHit attribute
- Did some actual manual gameplay testing with an edited version of TWW
- Save game compatibility seems fine

Example XML:
```
<attachment name="unitAttachment" attachTo="germanNavalMine" javaClass="games.strategy.triplea.attachments.UnitAttachment" type="unitType">
<option name="attack" value="0"/>
<option name="defense" value="0"/>
<option name="isSea" value="true"/>
<option name="isSub" value="true"/>
<option name="isAAforCombatOnly" value="true"/>
<option name="mayOverStackAA" value="true"/>
<option name="typeAA" value="navalmine"/>
<option name="targetsAA" value="Battleship:Cruiser:Destroyer:Submarine:Transport"/>
<option name="maxAAattacks" value="1"/>
<option name="maxRoundsAA" value="1"/>	
<option name="movement" value="0"/>
<option name="attackAA" value="2"/>
<option name="damageableAA" value="true"/>
<option name="canInvadeOnlyFrom" value="none"/>
<option name="isSuicideOnHit" value="true"/>
</attachment>
```

### CODE REVIEW

**Comment by Heppisorus** [comment]
I need a bigger thumbs up!

**Comment by ron-murhammer** [comment]
@ssoloff Yeah any map should work for testing. UnitAttachment should be fine (almost 100% sure on that since I just added a new boolean property). I'm more concerned on the MustFightBattle and Fire changes as they are part of delegates and game data (also just very core to the engine).

**Comment by ron-murhammer** [comment]
@ssoloff I ran some manual testing and made one fix to make sure the battle display actually remove any 'isSuicideOnHit' units that do get a hit. Everything else seems to work well.

**Comment by ssoloff** [comment]
@ron-murhammer I tested the following scenarios for compatibility:

* Create a save game from this branch and load in 3635.
* Create a save game from 3635 and load in this branch.
* Network game using a server from this branch and a 3635 client.
* Network game using a 3635 server and a client from this branch.

I observed no issues during play.

The `MustFightBattle` and `Fire` changes were just logic, right?  I didn't see any new fields or anything that would be persisted, so I think this PR is good from a compatibility standpoint.

**Comment by ron-murhammer** [comment]
@ssoloff Yeah, should be just logic. I purposely avoided adding/changing any member fields.

**Pull request merged**
