### PR TITLE
Update triplea_maps.yaml

### PR DESCRIPTION
**Pull request by merleyn**

### CODE REVIEW

**Comment by DanVanAtta** [comment]
Thanks for submitting, I fixed the indentation: https://github.com/triplea-game/triplea/pull/8966/commits/080fcc689209e1d002690ae0697dc4ea1780948e

**Comment by merleyn** [comment]
Thanks Dan, so what will be the next step?  As Frostions guide stops there.. ;)

**Comment by beelee1** [comment]
Experimental is misspelled here. It needs to be all upper case as well. Not sure how to fix with a fork/PR as it's not currently listed in mapsyaml. Also some things need to be added to the folder structure of https://github.com/triplea-maps/ww2_oil_and_snow_1st_edition/tree/master I'll work on that now but should wait until those are merged before merging this one.

**Comment by DanVanAtta** [comment]
Eagle eye @beelee1   =  D

RE: how to fix:

triplea-game admins can update proposed branches. Without that, you'd need to submit a PR into the branch that is being merged, this branch: merleyn:patch-1

To do that you'd need to add the fork 'merleyn/triplea-game' as a git remote, check out the branch 'merleyn:path-1', make changes locally, commit locally, push the updated branch to your fork, then submit a PR of the branch in your fork against merleyn:patch-1

**Comment by DanVanAtta** [comment]
@merleyn , this is the last step, once this is merged the repository will immediately be available for download from the game.

**Comment by DanVanAtta** [comment]
@merleyn couple notes, players will always download the latest from 'master' in your repository, so any changes you push will be available immediately. To cause a game prompt to ask players to update your map, bump the version number in this file, eg: `version: 1 -> version: 2`

**Comment by beelee1** [comment]
@DanVanAtta I'm pretty sure how to fix the naming issue. The maps/yaml name needs "1st Edition" added to it. Then the zip should have that name in downloaded maps ? However, I can't find "merleyn/triplea-game". Says no repo. I checked the forks here, says 91, and found a " merleyn /triplea " but that's not the right place either.

Not sure what a "git remote" is but I can look it up. I think I can figure it out if I can find  merleyn /
triplea-game . At any rate, i guess I'll reopen this until we get the name fixed. I guess the other option is to change the name in the xml ? Drop the 1st edition and do a PR to triplea-maps ?

Yea I tried this " git clone https://github.com/merleyn/triplea-game" but that didn't work either. This looks as if it'll take a while for me to get up to speed on

**Comment by DanVanAtta** [comment]
A remote is a repository. 'triplea-game/triplea' is one, 'danvanatta/triplea' is my fork of 'triplea'. You can find merleyn's repositories here: https://github.com/merleyn?tab=repositories. Though, you shouldn't need to since the map is forked into 'triplea-maps'. 

The zip name is for now controlled by the name of the repository. If we can make the entry in 'triplea_maps.yaml' match, then we are good. But it sounds like we need the 'map-name' xml entry to line up, which would involve an XML update. Here is the map repo in question: https://github.com/triplea-maps/ww2_oil_and_snow_1st_edition. I am surprised this is not all lining up as I didn't have any issues after downloading the map zip.

**Comment by beelee1** [comment]
hah was just updating when you posted :) I'll right I'll try it some more

**Comment by merleyn** [comment]
Okej, it seems same problem is still around: Map downloadable:  but Error when playing due to Name issue cause of zip file named 1st edition and underlaying map without.     Thanks a lot Dan and Beelee for trying to get his game onboard ,  I am trying to follow your disccusions but understand less than half of it.. Is there anything I can do from here to get the Map working in Trip,e A this weekend?     after 5 days Github issues I lost the track a bit ....       just let me know.....

**Comment by merleyn** [comment]
Okej, it seems same problem is still around: Map downloadable: but Error when playing due to Name issue cause of zip file named 1st edition and underlaying map without. Thanks a lot Dan and Beelee for trying to get his game onboard , I am trying to follow your disccusions but understand less than half of it.. Is there anything I can do from here to get the Map working in Trip,e A this weekend? after 5 days Github issues I lost the track a bit .... just let me know.....

**Comment by merleyn** [comment]
or should I/We  delete the whole repo ansd start all over again?

**Pull request merged**
