### PR TITLE
Mass replace anonymous inner classes with lambda

### PR DESCRIPTION
**Pull request by DanVanAtta**
This change is [Reviewable](https://reviewable.io/reviews/triplea-game/triplea/794)

### CODE REVIEW

**Comment by DanVanAtta** [comment]
@ron-murhammer  - any objections to replacing single-method anonymous inner classes with lambda? Please have a look at some of the changes when you have a chance and let me know. There are some places this is a really good cleanup, and worst case it is a marginal cleanup IMO. I'd like to get your input before investing time in the merge conflicts.

**Comment by ron-murhammer** [comment]
@DanVanAtta Looks like this needs rebased now.

**Comment by DanVanAtta** [comment]
@ron-murhammer  - I plan to re-apply the IDE tool to redo this rather than slog through lots of merge conflicts. But I wanted you to take a look at the diff here, to make sure you agree that overall this is an improvement. The first few classes in the diff are a bit 'meh' IMO, but eventually there are a good number of really nice cleanups when removing the anonymous inner class notation.

**Comment by ron-murhammer** [comment]
@DanVanAtta Yeah I think this is a good change. I only looked through the first 10 classes or so but think its a step in the right direction.

**Comment by RoiEXLab** [comment]
@DanVanAtta actually there is not too much to manually merge... I looked through it, and there are about 5 files with conflicts... I Made a pull request, you can either merge or close and then re-apply the tool

**Comment by DanVanAtta** [comment]
14 merge conflicts now : (
Pretty easy to just redo the auto-cleanup, will do that.

**Pull request closed without merging**
