### PR TITLE
Show test log

### PR DESCRIPTION
**Pull request by RoiEXLab**
This enables the test log in travis builds

This change is [Reviewable](https://reviewable.io/reviews/triplea-game/triplea/1232)

### CODE REVIEW

**Comment by RoiEXLab** [comment]
@DanVanAtta This one shouldn't take you too long to review

**Comment by DanVanAtta** [comment]
Nope, but more debating a bit. When we turned this on last, I found it difficult to find tests that had failed. Meanwhile, the extra output in Travis did not seem terribly useful. Thoughts @RoiEXLab ?

**Comment by RoiEXLab** [comment]
Well I normally do ctrl+f to find falling tests, or rerun them on my local branch in eclipse. 
That's why I see no downside on this PR...
Of You disagree I have no problem closing this issue without merging

**Comment by RoiEXLab** [comment]
Sry for typos - I'm on my phone

**Comment by DanVanAtta** [comment]
Yeah, I typically re-run tests locally to really debug them. In travis I'm only interested in what has failed generally, and with the clutter, ctrl-f is required (and then skipping over any info message that happens to have the word 'error' in it)

**Comment by DanVanAtta** [comment]
Don't particularly strongly disagree, but have trouble agreeing though, hence the hesitation.

**Comment by RoiEXLab** [comment]
@ron-murhammer Thougts 💭?

**Pull request closed without merging**
