### PR TITLE
Fix ClientFileSystemHelper#getRootFolder to actually return a folder

### PR DESCRIPTION
**Pull request by DanVanAtta**
The method is improperly returning the path of the '.triplea-root' touch
file rather than the parent folder of that file.

### CODE REVIEW

**Review by RoiEXLab — APPROVED** [review]
Wait, how wasn't this noticed until now? Isn't this code a couple years old by now?

**Comment by DanVanAtta** [comment]
Diffing on the file, this problem was introduced IIRC a year ago. It's been a very long time since we had a release.

Though, given we have not noticed even on prerelease versions - I wonder if somehow this is dead-code.

**Comment by frigoref** [comment]
@DanVanAtta, @RoiEXLab 
I have created some test cases for the class ClientFileSystemHelper and would ask for introducing them here.
https://github.com/frigoref/triplea/tree/fix/get-root-folder

One was a bit odd, so I would ask to check this carefully. Is the "service" here a system service that is only relevant for a running game and cannot be "properly" covered in a test case?
`@Test
  void getRootFolder() {
    assertThrows(ServiceNotAvailableException.class, () -> ClientFileSystemHelper.getRootFolder());
  }`

**Comment by RoiEXLab** [comment]
@frigoref IIRC this "service" is a mechanism that allows to abstract away some implementation details that differ for different environments. In this particular example there are 2 different service implementations for `ApplicationContext`: There's the `HeadedApplicationContext` which would be loaded for client environments and the `HeadlessApllicationContext` which would be loaded in server environments mostly our 'bots' as they're called.

#4055 Introduced this change, @ssoloff can probably provide a better explanation of how it works than I can. And I honestly have no Idea (or I did know in the past and simply forgot) how to register those services in the first place so they can be used by tests. I think you'll end up having to implement a dummy service yourself and somehow reference it in a special file inside the META-INF folder. Not sure if that's enough to make it work though.

**Comment by ssoloff** [comment]
@frigoref @RoiEXLab There was some discussion of tests interacting with `ServiceLoader` a few months ago on the [forum](https://forums.triplea-game.org/topic/2937/how-test-ui-elements-get-serviceloader-working).

**Pull request merged**
