### PR TITLE
Move on version for global

### PR DESCRIPTION
**Pull request by simon33-2**
## Overview
Moves on the version number for World War II Global repository

### CODE REVIEW

**Comment by beelee1** [comment]
@simon33-2 just a heads up but the default startup window in 10802, the latest prelease without issues, isn't showing up the same. It's just the two combat move first ones. Here's a couple shots:

screenshot from 2018-07-27 19-56-09

screenshot from 2018-07-27 19-59-05

works ok on 9687 and up to 10610. Anyway just thought I'd let you know as I had to go full screen to see what was up.

Once again, nice update : )

**Comment by simon33-2** [comment]
I can't duplicate any problem on Ubuntu. I've tried downloading build 10825, resetting the map folder and downloading the global package.

Is it platform dependent?

I also can't see the problem from your screen shots. Are you not able to select a different map?

**Comment by simon33-2** [comment]
Might be to do with the length of the filename for the xml.

**Comment by beelee1** [comment]
yea I was just looking at it some more and thought maybe it was worded differently or something. Anyway, point was I couldn't figure out how to start the game at first. Others may have that problem as well.

Seems weird that 10601, which is using the canada mod as well, doesn't do it. Idk if I should make a bug/issue or not. I don't want to spam the forum. : )

**Comment by simon33-2** [comment]
Oh I see. The filename of the map no longer wraps around to the next line.

Certainly annoying.

**Pull request merged**
