### PR TITLE
Confirm no post

### PR DESCRIPTION
**Pull request by simon33-2**
Replaces #1536

### CODE REVIEW

**Comment by simon33-2** [comment]
screenshot from 2017-02-20 14-22-16

Purpose of this PR is to insert the confirm dialog if done is clicked without "Post Turn Summary" being clicked.

**Comment by DanVanAtta** [comment]
What are your thoughts on adding a third option to post directly from the dialog and proceed? I'd also like to iterate once more on the dialog wording, but let's first discuss behavior. We could also alternatively have 'yes' post and continue, and 'no' will just continue without post.

**Comment by simon33-2** [comment]
That would need some error checking on the actual post action otherwise if you got an error on posting, you couldn't repost. AFAIK there is no error checking on posting at present or if there is, it doesn't do anything.

**Comment by DanVanAtta** [comment]
@simon33-2  pls fix the merge conflicts and then lets get this merged up.
Meanwhile I suspect there is probably a deeper fix here for the UX. Namely a user should not have to 'remember' to do so many different actions to simply play the game, they should be more intuitive or automated..

**Comment by simon33-2** [comment]
Didn't know there were any conflicts. I think the latest push should fix it?

**Comment by simon33-2** [comment]
I've updated this to only post the warning at the end turn post rather than the combat move post.

**Pull request merged**
