### PR TITLE
Checkstyle: Standardize import order and fix warnings (#1587)

### PR DESCRIPTION
**Pull request by ssoloff**
This PR changes the Checkstyle import order rule to match the default Eclipse code style import order, which is the prevalent import order used in the TripleA codebase.  It also fixes a few remaining actual violations of this rule.  This change reduces the Checkstyle warning count by ~4,800.

#### Functional changes
None.

#### Refactoring changes
* The imports in several files were reorganized to satisfy the Checkstyle import order rule.

#### Refactoring issues for review
None.

#### Other changes
* The Checkstyle import order rule was changed to match the default Eclipse code style import order.
* An Eclipse import order configuration was added to the Eclipse formatter settings folder.  It is intended to be imported into the IDE in the event the default Eclipse import order ever changes.  If this PR is accepted, I intend to submit a separate PR to update the [TripleA code format](http://www.triplea-game.org/dev_docs/dev/code_format) page on the website to reflect the addition of this file.

#### Other issues for review
None.

### CODE REVIEW

**Comment by DanVanAtta** [comment]
Would you be able or mind checking intellij that things work well with these configurations? @ssoloff 

There may be a larger discussion about going to a 100% standard format to make the setup simpler and avoid the custom format files (we didn't change too much, increased line length, which is relatively nice for this project).

**Comment by ssoloff** [comment]
> Would you be able or mind checking intellij that things work well with these configurations?

@DanVanAtta, I'm assuming you mean the following:

* Verify the Checkstyle plugin for IntelliJ behaves the same as the corresponding plugin for Eclipse with respect to the proposed Checkstyle configuration.
* Verify the built-in IntelliJ static analysis does not raise any import order warnings.

Please elaborate if I misunderstood your request.

**Comment by DanVanAtta** [comment]
I understand the checkstyle enforces an import ordering. In intellij there is an 'organize imports' (there is an  equivalent in eclipse). I'd like to be sure that the intellij organize imports does not cause checkstyle issues

**Comment by ssoloff** [comment]
> I understand the checkstyle enforces an import ordering. In intellij there is an 'organize imports' (there is an equivalent in eclipse). I'd like to be sure that the intellij organize imports does not cause checkstyle issues

@DanVanAtta: Whoops, misunderstood you.  Derp...

If you use the [Eclipse Code Formatter](https://plugins.jetbrains.com/plugin/6546-eclipse-code-formatter) plugin, per the [TripleA dev setup instructions](http://www.triplea-game.org/dev_docs/dev/setup), you can get IntelliJ to match the behavior of the Eclipse Organize Imports command.  I followed these [instructions](https://github.com/krasa/EclipseCodeFormatter#instructions) to do so.

Ultimately, my Eclipse Code Formatter plugin settings look like the following:

eclipse-code-formatter-settings

Where I had to specify custom values for the following properties:

* Eclipse Java formatter config file
* Import order > From file
  * Note that the default value for Import order > Manual configuration will work also because the `triplea.importorder` file matches the default Eclipse import order.

I also had to change the default values for the following properties on the **Editor > Code Style > Java > Imports** tab:

Property | New Value
:-- | :--
Class count to use import with '*' | 99
Name count to use static import with '*' | 99
Packages to Use Import with '*' | Clear list

After these changes, my settings look like the following:

editor-codestyle-java-imports-settings

I verified that running the Optimize Imports command (Ctrl+Alt+O) on several files resulted in the same import order as when the equivalent command is run in Eclipse.

Obviously, I could have missed something in the settings that results in the odd reorder that doesn't match Eclipse.  My best advice is to look for massive import changes in PRs authored in IntelliJ and identify what settings need to be tweaked to get parity with Eclipse.

**Pull request merged**
