### PR TITLE
New Map - Modern Warfare

### PR DESCRIPTION
**Pull request by Cestmoi02**
Hey, I wish to share my new map, Modern Warfare, with the community. I have tried transfering ownership in order to make the repository show up in "triplea - maps", but it didn't work. I hope it is ok to do it this way. If it doesn't, let me know what I can do to fix it. Thanks :)

### CODE REVIEW

**Comment by beelee1** [comment]
@Cestmoi02 yea my machine fried yesterday. This an old that only works sporadically and it's showing some stuff I haven't seen before so I'm gonna hold off doing anything for now. They'll be some others on soon enough to check it out.

One minor thing. New maps usually roll with "Experimental". Not a biggie, as there's been discussion about changing it. Like a lot of internet user groups, nothing was decided tho lol. The important thing is having it available. Word of mouth is still a good form of promotion.

**Comment by beelee1** [comment]
F it it can always be undone lol. It's just a game. lets see what happens :)

**Comment by beelee1** [comment]
well it failed with exit code 1. I thought it was 101 and meant you had an extra space at the end of everything, but i c no extra space.

I'd take up @RogerCooper on his offer of help

**Comment by Cestmoi02** [comment]
Ok, thanks. I'll do it tomorrow as rn it's quite late here in Europe and I'm going to bed. I'm sorry I used up so much of your time

**Comment by beelee1** [comment]
no worries brother were all good :)

**Comment by RogerCooper** [comment]
I downloaded your mod directly from Github. You should try directly creating the modern_warfare right off https://github.com/triplea-maps. I don't if TripleA even works off a sub-folder.

You may want to create an AI-friendly version of your mod by replacing political actions with random events.

**Comment by Cestmoi02** [comment]
I did make random events for the AI: one only needs to tick the Map Option "X (X being the name of the faction) is AI". It enables random events for that faction, although some of them are not random. The process is explained in the game notes accessed from the game, as are all differences from the Global 40 Rules. I'll try now to create the repository the way you said; again, the way I did everything up to this moment was based on the guide I found on the Triple A Forum in a pinned thread (in map making).
Once again thank you for your time with a newbie; I thought that the process of uploading a map is just as straightforward as making one :)

**Comment by beelee1** [comment]
_I thought that the process of uploading a map is just as straightforward as making one :)_

heh heh sadly I struggle with both :) 

Im not sure whats going on but the recent build fail says something about JDK 11.

**Comment by Cestmoi02** [comment]
@beelee1 I don't have JDK, only Java, but I don't see how the Java version on my end would have anything to do with the processing of the yaml file here on GitHub...

I tend to believe that the yaml file doesn't recognise maps that are not from triplea-maps, as @RogerCooper said. The problem is that I can't create any repository in triplea-maps. Surely there's some permission missing or something, but I can only create repositories in my own subfolder. Transfering ownership won't work, either, as I said in the other thread

**Comment by beelee1** [comment]
@Cestmoi02 hmm ... seems the same problem @TheDog-GH is having. You're not showing up with repo public ? Uggh I tried forking one from @asvitkine but it didn't work. @RoiEXLab I know your busy but can you help Dog and Cestmoi ? Sorry I can't figure it out

**Comment by TheDog-GH** [comment]
@Cestmoi02
I have very little idea of the working of GitHub, but as a guess, your paragraph starting with _As·Russia·masses·troops_ might be too long, so put 3 or 4 more <br> in.

Also maybe there is a hidden code in **full-scale** (as it line brakes), so I would paste the text into notepad or similar to remove hidden codes and then copy & paste from Notepad.  Or just delete full-scale within yaml file and retype it.

**Comment by Cestmoi02** [comment]
That could be something, especially because that's the paragraph that shows up in the error. I'll close up this request, then, and try a new one with more lines and copied directly from Notepad

**Pull request closed without merging**
