### PR TITLE
AI - Update casualty selection unit value calculation to consider

### PR DESCRIPTION
**Pull request by ron-murhammer**
dependents such as transported or unloaded units

[Review on Reviewable](https://reviewable.io/reviews/triplea-game/triplea/447)

### CODE REVIEW

**Comment by DanVanAtta** [comment]
Review status: 0 of 2 files reviewed at latest revision, 6 unresolved discussions.

---

*[src/games/strategy/triplea/ai/proAI/ProAI.java, line 382 \[r1\]](https://reviewable.io:443/reviews/triplea-game/triplea/447#-KAT7AFHxtLTQyn-5d5n:-KAT7AFHxtLTQyn-5d5o:637555375) ([raw file](https://github.com/triplea-game/triplea/blob/d0330a5d1bf2af653f4825db637ecbbfd5acd086/src/games/strategy/triplea/ai/proAI/ProAI.java#L382)):*
I see a problem here where pieces were moved from ProAI to avoid duplication, but not in large enough pieces to remove complexity from ProAI. For example here instead of having a cost calculator class that takes in the whole set of units and then does whatever else is needed, we have only some of the implementation of the cost calculator extracted. I suspect this is a large part of the reason why we have in effect two god classes rather than having ProAI and many other modular classes to support it.

---

*[src/games/strategy/triplea/ai/proAI/util/ProPurchaseUtils.java, line 271 \[r1\]](https://reviewable.io:443/reviews/triplea-game/triplea/447#-KATBZA3gWdar3JL_jNx:-KATBZA3gWdar3JL_jNy:-883300077) ([raw file](https://github.com/triplea-game/triplea/blob/d0330a5d1bf2af653f4825db637ecbbfd5acd086/src/games/strategy/triplea/ai/proAI/util/ProPurchaseUtils.java#L271)):*
This method is only used in one spot in ProAI and captures just a simple one-liner.  It doesn't seem like this is a very useful utility method.

This is the one usage: 
  ` Collections.sort(selectFromSorted, ProPurchaseUtils.getCostComparator());`

Could instead be quite simply:
```   Collections.sort(selectFromSorted, 
               (o1,o2) -> Double.compare( ProPurchaseUtils.getCost(o1), ProPurchaseUtils.getCost(o2)));```

Has some nice benifits:
 - removes the level of indirection in ProAI
 - saves a public method from ProPurchaseUtils, helps trim it down (it looks a bit like a god class)

---

*[src/games/strategy/triplea/ai/proAI/util/ProPurchaseUtils.java, line 285 \[r1\]](https://reviewable.io:443/reviews/triplea-game/triplea/447#-KAT8UdmIjqu1Bqr7QYo:-KAT8UdmIjqu1Bqr7QYp:-1352684625) ([raw file](https://github.com/triplea-game/triplea/blob/d0330a5d1bf2af653f4825db637ecbbfd5acd086/src/games/strategy/triplea/ai/proAI/util/ProPurchaseUtils.java#L285)):*
The error handling is a bit weak here, you won't know what is null if this triggers and would have to resort to a debug session or rewriting these couple lines to tell you what was null.

My recommendation to fix would be to write it as 4 sequential `Preconditions.checkNotNull` would be a minimal amount of error handling code and would let youknow exactly what was null based on the line number. 

---

*[src/games/strategy/triplea/ai/proAI/util/ProPurchaseUtils.java, line 293 \[r1\]](https://reviewable.io:443/reviews/triplea-game/triplea/447#-KAT9VQ5U_ZMepfZDxnG:-KAT9VQ68BYgTc0RqzaG:411150415) ([raw file](https://github.com/triplea-game/triplea/blob/d0330a5d1bf2af653f4825db637ecbbfd5acd086/src/games/strategy/triplea/ai/proAI/util/ProPurchaseUtils.java#L293)):*
An extra `if (rule == null)` here

---

*[src/games/strategy/triplea/ai/proAI/util/ProPurchaseUtils.java, line 296 \[r1\]](https://reviewable.io:443/reviews/triplea-game/triplea/447#-KAT5O1yXqLBCCHMLnHW:-KAT5O1zAMigQ04dZ0wd:1081138654) ([raw file](https://github.com/triplea-game/triplea/blob/d0330a5d1bf2af653f4825db637ecbbfd5acd086/src/games/strategy/triplea/ai/proAI/util/ProPurchaseUtils.java#L296)):*
The cost value will be more accurate if you divide it once before you return it rather than doing a division during each loop iteration. The total error in the calculation is incurred once at the end if you divide once, rather than being the sum of the error across each loop iteration.

---

*[src/games/strategy/triplea/ai/proAI/util/ProPurchaseUtils.java, line 311 \[r1\]](https://reviewable.io:443/reviews/triplea-game/triplea/447#-KATAXn3ctf_9cQcLil2:-KATAXn3ctf_9cQcLil3:-144599570) ([raw file](https://github.com/triplea-game/triplea/blob/5fbb65d60c3739b3d373b5842306596b41e7588a/src/games/strategy/triplea/ai/proAI/util/ProPurchaseUtils.java#L311)):*
Arg checks are removed here, but they were added to the previous method. They are both 'public static', seems inconsistent. 

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/triplea-game/triplea/447)*
<!-- Sent from Reviewable.io -->

**Comment by ron-murhammer** [comment]
Review status: 0 of 2 files reviewed at latest revision, 5 unresolved discussions.

---

*[src/games/strategy/triplea/ai/proAI/util/ProPurchaseUtils.java, line 271 \[r1\]](https://reviewable.io:443/reviews/triplea-game/triplea/447#-KATBZA3gWdar3JL_jNx:-KATYNlkyOvsLL2yttNM:919974866) ([raw file](https://github.com/triplea-game/triplea/blob/d0330a5d1bf2af653f4825db637ecbbfd5acd086/src/games/strategy/triplea/ai/proAI/util/ProPurchaseUtils.java#L271)):*
So these cost methods aren't currently used in many places but I'm planning to use them in many more. Most places currently use an outdated less accurate method of finding unit cost which is the unitValueMap (the backup in these methods). 

---

*[src/games/strategy/triplea/ai/proAI/util/ProPurchaseUtils.java, line 285 \[r1\]](https://reviewable.io:443/reviews/triplea-game/triplea/447#-KAT8UdmIjqu1Bqr7QYo:-KATZ46n5XSaPFtcqkmE:1521994352) ([raw file](https://github.com/triplea-game/triplea/blob/d0330a5d1bf2af653f4825db637ecbbfd5acd086/src/games/strategy/triplea/ai/proAI/util/ProPurchaseUtils.java#L285)):*
Honestly, I considered just removing these checks all together as none of these should really ever be null and would mean there is a much larger problem with the game data.

Actually, I went ahead and removed these in a follow on commit.

---

*[src/games/strategy/triplea/ai/proAI/util/ProPurchaseUtils.java, line 293 \[r1\]](https://reviewable.io:443/reviews/triplea-game/triplea/447#-KAT9VQ5U_ZMepfZDxnG:-KATZTyEtmpgHRKuMSpy:334681244) ([raw file](https://github.com/triplea-game/triplea/blob/d0330a5d1bf2af653f4825db637ecbbfd5acd086/src/games/strategy/triplea/ai/proAI/util/ProPurchaseUtils.java#L293)):*
Not following you here.

---

*[src/games/strategy/triplea/ai/proAI/util/ProPurchaseUtils.java, line 296 \[r1\]](https://reviewable.io:443/reviews/triplea-game/triplea/447#-KAT5O1yXqLBCCHMLnHW:-KAT_FnbOakmspm8TqMd:-1472203415) ([raw file](https://github.com/triplea-game/triplea/blob/d0330a5d1bf2af653f4825db637ecbbfd5acd086/src/games/strategy/triplea/ai/proAI/util/ProPurchaseUtils.java#L296)):*
I'm pretty sure that wouldn't work. Each rule can have a different number of units so you need to divide each rule cost for each unit. Example is say I have a rule that I get 4 units for 4 PUs (1 PU per unit) and a rule that I get 2 units for 7 PUs (3.5 PUs per unit). You can't add the total cost up then divide unless you find the LCD and convert all the costs. That would be way more complex...

---

*[src/games/strategy/triplea/ai/proAI/util/ProPurchaseUtils.java, line 311 \[r1\]](https://reviewable.io:443/reviews/triplea-game/triplea/447#-KATAXn3ctf_9cQcLil2:-KATaorENB83_yKB6a4q:-1359651737) ([raw file](https://github.com/triplea-game/triplea/blob/5fbb65d60c3739b3d373b5842306596b41e7588a/src/games/strategy/triplea/ai/proAI/util/ProPurchaseUtils.java#L311)):*
Yeah, they checks aren't needed. Also updated this method to be private.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/triplea-game/triplea/447)*

**Comment by DanVanAtta** [comment]
Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/games/strategy/triplea/ai/proAI/util/ProPurchaseUtils.java, line 271 \[r1\]](https://reviewable.io:443/reviews/triplea-game/triplea/447#-KATBZA3gWdar3JL_jNx:-KATlTL3FReBJAItoQ0U:575639267) ([raw file](https://github.com/triplea-game/triplea/blob/d0330a5d1bf2af653f4825db637ecbbfd5acd086/src/games/strategy/triplea/ai/proAI/util/ProPurchaseUtils.java#L271)):*
Before the costs methods are widely used, I noticed that only PU cost is considered. In some maps PU may not be the most important resource. Is there are a good way to support those maps? It looks like we'd have to have a 'meta-cost' function that aggregates different cost types together, this looks like the place for that.

---

*[src/games/strategy/triplea/ai/proAI/util/ProPurchaseUtils.java, line 293 \[r1\]](https://reviewable.io:443/reviews/triplea-game/triplea/447#-KAT9VQ5U_ZMepfZDxnG:-KATiCQJMX-g5UuqlaCz:698809766) ([raw file](https://github.com/triplea-game/triplea/blob/d0330a5d1bf2af653f4825db637ecbbfd5acd086/src/games/strategy/triplea/ai/proAI/util/ProPurchaseUtils.java#L293)):*
Ah, never mind, it looks like in reviewable only one line was added and none removed, but I see the indentation only changed.

---

*[src/games/strategy/triplea/ai/proAI/util/ProPurchaseUtils.java, line 296 \[r1\]](https://reviewable.io:443/reviews/triplea-game/triplea/447#-KAT5O1yXqLBCCHMLnHW:-KATk7p_DV5YEblsxOwC:-65578045) ([raw file](https://github.com/triplea-game/triplea/blob/d0330a5d1bf2af653f4825db637ecbbfd5acd086/src/games/strategy/triplea/ai/proAI/util/ProPurchaseUtils.java#L296)):*
I see what is going on more clearly now, thanks. I had thought `rule.getResults().totalValues()` would not vary, but it does.

Looks like we really could use a `rule.getCostPerUnit()` method that would do this calculation. It's not clear 'totalValues()' refers to the number of units you get when purchasing, I'd also guess we would have this code in other places as well. Not critical to make that change for this PR though.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/triplea-game/triplea/447)*

**Comment by DanVanAtta** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/games/strategy/triplea/ai/proAI/util/ProPurchaseUtils.java, line 271 \[r1\]](https://reviewable.io:443/reviews/triplea-game/triplea/447#-KATBZA3gWdar3JL_jNx:-KATlxg1T1EkdpqOJYuu:98172752) ([raw file](https://github.com/triplea-game/triplea/blob/d0330a5d1bf2af653f4825db637ecbbfd5acd086/src/games/strategy/triplea/ai/proAI/util/ProPurchaseUtils.java#L271)):*
Second item, even if you don't inline this function, the lambda equivalent will help the syntax here.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/triplea-game/triplea/447)*

**Comment by ron-murhammer** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/games/strategy/triplea/ai/proAI/util/ProPurchaseUtils.java, line 271 \[r1\]](https://reviewable.io:443/reviews/triplea-game/triplea/447#-KATBZA3gWdar3JL_jNx:-KAVlEgg_KEUXa9HaOpY:1811748238) ([raw file](https://github.com/triplea-game/triplea/blob/d0330a5d1bf2af653f4825db637ecbbfd5acd086/src/games/strategy/triplea/ai/proAI/util/ProPurchaseUtils.java#L271)):*
Yeah, adding non-PU support is on my list of things to tackle but is a pretty big change. These methods will most likely be moved to a separate class outside of PurchaseUtils and then functionality added to support multiple resources. One of the reasons I'd like to keep these methods and not inline them.

Good point. I think the lambda equivalent is more concise and just as readable so added commit to switch to it.

---

*[src/games/strategy/triplea/ai/proAI/util/ProPurchaseUtils.java, line 296 \[r1\]](https://reviewable.io:443/reviews/triplea-game/triplea/447#-KAT5O1yXqLBCCHMLnHW:-KAVhhXN6eqHofCHR3V0:2113767012) ([raw file](https://github.com/triplea-game/triplea/blob/d0330a5d1bf2af653f4825db637ecbbfd5acd086/src/games/strategy/triplea/ai/proAI/util/ProPurchaseUtils.java#L296)):*
Yeah, you could argue that this would be useful outside the AI. In general, this is comes up a lot when adding methods to the AI that maybe should really be part of engine. I tend to just add to the AI as most likely no one will ever use them outside the AI.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/triplea-game/triplea/447)*

**Comment by DanVanAtta** [comment]
*[src/games/strategy/triplea/ai/proAI/util/ProPurchaseUtils.java, line 296 \[r1\]](https://reviewable.io:443/reviews/triplea-game/triplea/447#-KAT5O1yXqLBCCHMLnHW:-KAWYVAp4ADpG8P0jwBe:412269419) ([raw file](https://github.com/triplea-game/triplea/blob/d0330a5d1bf2af653f4825db637ecbbfd5acd086/src/games/strategy/triplea/ai/proAI/util/ProPurchaseUtils.java#L296)):*
Even if only useful within the AI, I'd still suggest the change. It's a logical place to have that calculation and helps the AI code (consolidates complexity/redundancy). Plus with it extracted, you could more readily test that logic.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/triplea-game/triplea/447)*

**Comment by DanVanAtta** [comment]
*[src/games/strategy/triplea/ai/proAI/util/ProPurchaseUtils.java, line 271 \[r1\]](https://reviewable.io:443/reviews/triplea-game/triplea/447#-KATBZA3gWdar3JL_jNx:-KAWZLM_Reb-I6q3pnpA:-1164614855) ([raw file](https://github.com/triplea-game/triplea/blob/d0330a5d1bf2af653f4825db637ecbbfd5acd086/src/games/strategy/triplea/ai/proAI/util/ProPurchaseUtils.java#L271)):*
A quick and dirty way would perhaps be to treat all resource types as equal and sum them all up together. Having the AI figure out how to correctly value different resource types would be really tricky, bit of an interesting/difficult problem how to do that.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/triplea-game/triplea/447)*

**Comment by ron-murhammer** [comment]
Yeah, I've already discussed and put some thought into multiple resources. Mostly weighteing each one based on how much I have/produce as some maps have like an order of magnitude different amounts of resources so summing up wouldn't be very useful.

**Comment by DanVanAtta** [comment]
I see. Then another idea for you in case the country is not producing each resource type yet, would be to sum up all of the available resource productions across the map. With that you'll know the relative scarcity and could weight the resource types that way.

**Pull request merged**
