### PR TITLE
Add debug statements to travis 'do_release'

### PR DESCRIPTION
**Pull request by DanVanAtta**
## Functional Changes

[ ] New map or map update
[ ] New Feature
[ ] Feature update or enhancement
[ ] Feature Removal
[ ] Code Cleanup or refactor
[ ] Configuration Change
[ ] Bug fix

## Testing

[ ] Covered by existing automated tests
[ ] Covered by newly added automated tests
[ ] Manually tested
[ ] No testing done

### CODE REVIEW

**Comment by RoiEXLab** [comment]
IIRC @ssoloff once used some sort of debug mode to access the install4j key in travis, might be useful in the future to avoid having debug PRs like this

**Comment by DanVanAtta** [comment]
It's crazy this fixed the build.
@RoiEXLab the install4j step is already completed, the piece that failed is a clone of website was checked and then YAML splitter was run to update maps. The if statement is supposed to detect if any files had changed, and if so the if block is executed. Based on the failure, the if statement was true and the if block was executed, but the commit inside of it had nothing to commit and then failed.

We have been seeing that error message previously on green builds, we did not though have the "set -e" flag to halt the build if we encounter errors.

**Comment by RoiEXLab** [comment]
> It's crazy this fixed the build.

ikr 😅

**Comment by DanVanAtta** [comment]
yah, sadly fixes like that means we actually don't know what fixed the build. There is a dependency on the website repo here, but AFAIK nothing changed there.. 

I'm thinking to spend some time iterating on this, I think the first step is to see how stable the build is, rebuilding it, and then reverting the fix and adding it back in again to see if it is really making a difference.

**Pull request merged**
