### PR TITLE
Update servers.yml

### PR DESCRIPTION
**Pull request by Cernelius**

### CODE REVIEW

**Comment by Cernelius** [comment]
@asvitkine @DanVanAtta Please merge.

**Comment by Cernelius** [comment]
Or @ron-murhammer please merge.

**Comment by Cernelius** [comment]
Or @beelee1 please merge.

**Comment by DanVanAtta** [comment]
Format violations in this update; need to get those fixed before merge. It's a bit cryptic, but it looks like the issue is there needs to be no newline (line 9 deleted).

Can we make the message a bit more compelling? Perhaps reword to something like:
"Donation drive Oct-2023 is underway! TripleA relies on your support!  Without your donations we will be out of money before December. 100% of funds go to running the TripleA servers, donate here: <link>"

**Comment by Cernelius** [comment]
How do you create an empty line?

If you prefer a different message, please just close this PR and make an other one and merge it right away. I'm perfectly fine with whatever other message.

**Pull request merged**
