### PR TITLE
Add guava

### PR DESCRIPTION
**Pull request by DanVanAtta**
[Review on Reviewable](https://reviewable.io/reviews/triplea-game/triplea/117)

### CODE REVIEW

**Comment by ron-murhammer** [comment]
+1 for this as guava has some great utilities. 

@veqryn can you confirm you're alright with adding guava?

**Comment by veqryn** [comment]
I am fine with adding guava, with one giant exception:
I would personally like us to upgrade to java 8 before we use guava.  I do not want to make use of guava's functionality when something equivalent exists in java 8.  Lots of things in guava really only makes sense for projects that can not go beyond java 7.

**Comment by ron-murhammer** [comment]
@veqryn Do we have a timeline for upgrading to Java 8?

**Comment by veqryn** [comment]
Mac OS is the only thing holding us back in my opinion.  Not just the 'build' but also the fact that when you try to install it, mac says you require java 6.  And we have various things in our code that use an out of date apple java extension library that was built for java 6, and do not work with java 7/8.

**Comment by ron-murhammer** [comment]
@veqryn So assuming we resolve all the Mac OS issues then you are fine requiring all users to have Java 8? I know there are some issues around Java 8 and Windows XP.

**Comment by veqryn** [comment]
We can discuss that.  
I know that we were previously concerned about what percentage of users would be left behind if we upgraded to java 7 or 8.
However, the more time I spend with java 8, the more I love it.  Throw in the fact that oracle ceased support of java 7 several months ago, and that Windows XP has been out of support for years, and I think we have a compelling case that if we are going to upgrade anything, we should at least target java 8.

**Comment by DanVanAtta** [comment]
I like Java8. But there is evidence we need Guava beyond the Java7/8 convenience stuff. Notably PR #118 uses Guava for equals and hashcode. There is also quite a bit of obvious opportunity in the code base for more Guava library functionality, like Throwables that are not provided by Java7 or Java8. There is a *lot* to Guava that is really useful.

I wouldn't mind if when we get to Java8 to replace the equivalent Guava with Java8, but in the meantime there is benefit to Guava (#118 as an example), and chances are really good we'll need it anyways (#118 again is evidence of that, and there are a lot of easy to cite examples of Guava that we could easily and beneficially use in the code base)

**Comment by veqryn** [comment]
I would like us to not use guava for any place where java 8 could/should be used instead.  We should spend the time upgrading to full java 8.

In places where java 8 doesn't have anything, then we can use guava.

On a more specific note, I didn't see anywhere in 118 where guava was used for anything more than the toString function.

**Comment by DanVanAtta** [comment]
#118 uses guava for hashcode and equals as well:

```
  public int hashCode() {
-    final int prime = 31;
-    int result = 1;
-    result = prime * result + ((m_first == null) ? 0 : m_first.hashCode());
-    result = prime * result + ((m_second == null) ? 0 : m_second.hashCode());
-    return result;
+    return Objects.hash(first, second);
```

**Comment by DanVanAtta** [comment]
Other than waiting for install4j, is there anything else to do  to help to get to Java8?

**Comment by veqryn** [comment]
Isn't Objects.hash, just using java.util.Objects, not guava?

**Comment by DanVanAtta** [comment]
You're correct - it is Objects.hash, I was wrong. 

I'm not sure why I brought it up now - the toString example is enough for the point. A quick look and no obvious replacement in Java8 for this:
```
  @Override
   public String toString() {
-    return "[" + (m_first == null ? "null" : m_first.toString()) + ", "
-        + (m_second == null ? "null" : m_second.toString()) + "]";
+    return MoreObjects.toStringHelper(this)
+        .add("first", getFirst())
+        .add("second", getSecond())
+        .toString();
   }
```

If this is not already an example, I think chances are near certain there will be soon enough stuff in Guava that we will want that is not in Java8. I don't mind trying to help getting to Java8, but I don't think guava and J8 are mutually exclusive.

**Comment by veqryn** [comment]
Not saying they are mutually exclusive.
I would just like agreement to wait for java 8 to implement anything that java 8 can handle, and not implement it in guava in the mean time.
Out of pure curiosity, what format does the toStringHelper return stuff in?

**Comment by DanVanAtta** [comment]
Java8 is sounds close -  no strong objections here to converting stuff directly to Java8 rather than converting to Guava and *then* Java8.

About the toString output -  using the 118 branch:
```
  public static void main(String[] args ) {
    System.out.println(Tuple.of("abc", "123"));
  }
```
Output is:
```
Tuple{first=abc, second=123}
````


And I was curious then about how quotes are handled or backslashes, looks like whatever the string is, as expect it is just printed:

```
System.out.println(Tuple.of("\"I have a double quote", "i have a single ' quote, backslash \\"));
```
outputs:
```
Tuple{first="I have a double quote, second=i have a single ' quote, backslash \}
```

**Comment by veqryn** [comment]
Not bad, although I wonder if the previous toString was better, since it was shorter and had less cruft.

**Pull request merged**
