### PR TITLE
Revert "Added JUnit 5 Implemetation"

### PR DESCRIPTION
**Pull request by DanVanAtta**
This reverts commit 762bc50bdd2f7bfd0f0d8b67c5fb6ceedd907497.

Avoids this error:
```
org.junit.platform.launcher.listeners.TestExecutionSummary.getTotalFailureCount()J
	at org.junit.platform.console.tasks.ExecuteTestsTask.computeExitCode(ExecuteTestsTask.java:101)
	at org.junit.platform.console.tasks.ExecuteTestsTask.executeTests(ExecuteTestsTask.java:65)
	at org.junit.platform.console.tasks.ExecuteTestsTask.lambda$execute$0(ExecuteTestsTask.java:52)
	at org.junit.platform.console.tasks.ExecuteTestsTask$$Lambda$3/1851691492.call(Unknown Source)
	at 
```

---
This change is [Reviewable](https://reviewable.io/reviews/triplea-game/triplea/1007)

### CODE REVIEW

**Comment by DanVanAtta** [comment]
FYI @RoiEXLab , please see the error above.

**Comment by RoiEXLab** [comment]
@DanVanAtta No objections in this change, since JUnit 5 is not completely released yet... Another option would have been to try out the latest version (released yesterday) - but it might just be enough to readd JUnit 5 at a later more stable day.

The Error: It seems that this is a JUnit related error, and not really affecting any tests, e.g. I think that this is an error, which occured while attempting to get the totalFailurecount (notice the J at the end).
The changelog of the newest Junit 5 update mentions something like fixed failure listings, but I'm not sure, if this is what our problem is...
I'm probably going to run a couple tests with the newest update, and will tell you if the error is still occuring...

**Comment by RoiEXLab** [comment]
@DanVanAtta I actually like the JUnit 5 update a lot, since the gradle output is so much better (especcially the summary at the end)

**Comment by DanVanAtta** [comment]
The summary is a good addition. It is paramount though that the tests be stable.

**Pull request merged**
