### PR TITLE
Update old jars

### PR DESCRIPTION
**Pull request by DanVanAtta**
Remove 20M worth of 'old' jars, adding in the latest 1.8.0.9 to the old folder to help prep for going to 1.9.0.0

this latest Jar is 11M, it is a fat jar, while the others are not. This is likely going to be necessary since we are pruning libs in 1.9.0.0

I have not thoroughly checked that the old jar functionality works really well. AFAIK it is a bit flaky to begin with.. Regardless, removing the old jars and adding in the latest is the right thing to do for the moment.

---
This change is [Reviewable](https://reviewable.io/reviews/triplea-game/triplea/819)

### CODE REVIEW

**Comment by RoiEXLab** [comment]
I actually did ask myself why those were still there 2 days ago...

**Comment by DanVanAtta** [comment]
They support the ability to play 'old' versions of the game. The code to do so is not the most robust, I have not had the best experience with it working well. One fine day we will solve the backwards compatibility problem in a robust way that would not need 'old' jars.

**Comment by ron-murhammer** [comment]
@DanVanAtta I don't know if this is a good idea at this point. We can probably remove 1.5.x jar and maybe 1.6.x jar but should definitely still keep 1.7.x jar if its functional IMO. Though if cleaning up the jars has broken all these old jars then we might not have much choice.

**Comment by DanVanAtta** [comment]
We can keep 1.7.x in the mix. I was thinking that is a relatively old version, but no strong objection here to keeping it around. Will update accordingly, stay tuned..

**Comment by DanVanAtta** [comment]
Updated.

**Pull request merged**
