### PR TITLE
Map Prop Name Updates

### PR DESCRIPTION
**Pull request by DanVanAtta**
Addresses parts of #1033 

Map propety name updates:
- Impassible -> Impassable
- Naval Bombard Casualty Return Fire Restricted ->  - Naval Bombard Casualty Return Fire
- 'Battleships repair ..' -> 'Units repair..' 

We will need to bump the map versions in the index file after this is merged, a similar change has been done to all maps (new map versions are ready)

This change is [Reviewable](https://reviewable.io/reviews/triplea-game/triplea/1047)

### CODE REVIEW

**Comment by Cernelius** [comment]
Thanks for addressing my issue, but you are not actually doing what I'm suggesting.

This change:
"Naval Bombard Casualties Return Fire Restricted"->"Naval Bombard Casualties Return Fire"
is not anymore what I'm proposing and I'm (and have always been) against it being made in this limited way, as it would be inconsistent with the v1 ruleset.

This option can't be just kept doing what it currently does, changing the name only, since its default is wrong as well, not just the name (**it is the name that is right, while the behaviour is wrong, not the other way round!**). By v1 rules (that are the TripleA default) casualties from naval bombard are able to return fire, thus this should be the default in TripleA.
Consequently, if you do the above name change, you must also change the default of this option from false to true.
On the other hand, as @ron-murhammer pointed out, the default of any properties is false in the engine.
Thus, since changing only the name of this property to do what it does is unacceptable, because incoherent with the rules (it would be the only property not having the default set on v1 rules), and also changing upside down both the name and the default is unacceptable, because it would be the only option being default true, then the only solution is to **change upside down the behaviour**, leaving both the name and the engine default exactly as they are, but doing the following changes in all xml:
**"Naval Bombard Casualties Return Fire Restricted" value="true"->"Naval Bombard Casualties Return Fire Restricted" value="false"**
**"Naval Bombard Casualties Return Fire Restricted" value="false"->"Naval Bombard Casualties Return Fire Restricted" value="true"**

Please, reread the edited first post of the issue you are addressing, as I've recently made changes to it, based on the discussion (and removing " Restricted" was my suggestion only as long as also the engine default would have been changed from "false" to "true").
If you or anyone disagree with any my proposals and want to do only part of them or do them in a different manner it would be opportune anything being mentioned in the relative issue, or at least not presenting the changes as looking like doing what I'm currently suggesting, as I've also stated:

> Please, if any developer willingly to do any of the above changes don't want to make some of them or want to make some of them in a different way or just don't get the point of some of them, let me know specifically which ones you are in disagreement or in doubt with and I will explain you why you should do them the way I said.
> While I'm of course favourable if all the above changes are fully made exactly the way I said, I may be contrary to make any of them if only some of them are made or if they are made in a different way than I said.

It is particularly bad having this option not working by v1 rules default, because not only everything relevant for v1 rules is set (or supposed to be set) to v1 rules default, in all other cases, but the fact that casualties are not able to return fire is a silly rule of v2 only, that didn't apply to v1, and was discontinued (thankfully!) in v3 and all successive versions as well (v3, v4, v5, v6 and the Global series).
It would be really silly to make an exception to the v1 ruleset for this property only, especially considering that this property is nothing else but a failed v2 rulechange tryout, that was sconfessed and never reproposed in any following versions, comprising the current v5, v6 and Global 2nd Edition (thus nothing else than v2 only has this weird rule that casualties from naval bombard are unable to return fire, which also makes really no sense).

Seriously, let's not have some properties default v1 and some other default v2 and whatnot, as this would be very confusing. All TripleA properties so far are supposed to be default v1, and I definitively advise you not making a random mix-up of rulesets for the defaults. I rather then leave this option doing the opposite of what it says, since that way at least it would be v1 coherent in what it says, if not in what it does!

Mapmakers should be safely assured that all properties not being set will default to v1 rules, not having to wonder if this one or that other one will work by v1 or v2 or whatnot rules!

You can find my proposed change in the current Issue you referenced and it is:

> Engine behaviour changes:
> **Naval Bombard Casualties Return Fire Restricted** invert behaviour (to behave as true like it now does as false, and vice versa)
> 
> XML only changes:
> **"Naval Bombard Casualties Return Fire Restricted" value="true"->"Naval Bombard Casualties Return Fire Restricted" value="false"**
> **"Naval Bombard Casualties Return Fire Restricted" value="false"->"Naval Bombard Casualties Return Fire Restricted" value="true"**
> (on the assumption that the mapmakers set the option on what it does, not on what it says)

Moreover, in case it is relevant (I'm not sure), you should also assure that, assuming the specific property is not set in the map's xml, having this property:
_property name="WW2V2" value="false"_
then naval bombard casualties must be able to return fire;
instead, having this property:
_property name="WW2V2" value="true"_
then naval bombard casualties must be unable to return fire (because this is how it works in v2 only, nowhere else, and surely not v1 = TripleA default ruleset).

This is also relevant on the users' side, since a mapmaker might choose to have the "WW2V2" as a user's settable option, and in this case naval bombard casualties should be able to return fire, if the user chooses to play by Classic rules (unticking the "WW2V2" option), while they should be unable to return fire, if the user chooses to play by Revises rules (ticking the "WW2V2" option).

Let's be fully coherent, please, as we almost already are (**everything must be default v1**).

Side note, if you intended to do this change, and then also change the engine default from "false" to "true", I want to make you notice that suggestion of mine is obsolete, as @ron-murhammer is against having any options defaulting to true, thus I assume he won't agree with you on this matter.

**Comment by DanVanAtta** [comment]
The bombard prop name is more descriptive of what it does now.  It's better that it accurately match rather than not. Nothing has changed with respect to v1 and v2 rules being mixed by default for better or worse.

**Comment by Cernelius** [comment]
No.

This means that now not only the behaviour, but also the name are wrong, while before the behaviour only was, while the name was just fine, as well as its default.

So, again, I'm against this change. But if you want to do it anyway, I can't stop you. I just wanted to be very clear this is definitively not a change proposed by me.

This is all.

Thanks anyway.

**Comment by Cernelius** [comment]
Just noticed that actually 2 out of 3 things done so far (...) have not been done following my directions, and, unsurprisingly, I'm against both, and I'm perplexed by the fact that also @ron-murhammer  agreed to them, the way they are, apparently.

So, to sum it up:

1.
Impassible -> Impassable

This is the only one thing correctly done; just be sure to do the same in the map.properties, as well, since having it not coherent would be worse than having it semantically wrong.

2.
Naval Bombard Casualty Return Fire Restricted -> Naval Bombard Casualty Return Fire

This indeed assures that the option is well telling and it is doing exactly what it says, but I'm strongly against with change too, for the reasons I amply detailed.

I want especially make you notice (again) that, by doing it that way, you are keeping the following property bugged:

		<property name="WW2V2" value="false" editable="false">
				<boolean/>
		</property>

Because when this property is "false" you are supposed to have the game playing by v1 rules, and when this property is "true" you are supposed to have the game playing by v2 rules.
Currently if that property is "false" the game will indeed play by v1 rules, except that the naval bombard will keep working by v2 rules, instead, which is bad, since it virtually makes this option half-useless on the Classic part (there is not much of a point having a property setting Classic / Revised rules, if it is not actually doing it correctly, but mixing rulesets up).

While having the property doing exactly what it says might arguably be a partial step forward, I don't think much so, because, in doing that, you are legalising (or should I say setting in stone) a bugged engine behaviour, that I guess was incautiously bugged along the way, since originally TripleA was supposed to support v1 only, thus I assume both this property and the related bug were not there, originally, but were added at some point after having expanded TripleA to cover the v2 ruleset too.
As I said, this is especially problematic, since the standard v1 ruleset is often chosen by new / inexperienced mapmakers (beside, of course, experienced mapmakers that specifically wanted to have it, instead of v2, v3 or whatever), that are very unlikely to be able to spot that the naval bombardment is bugged and needs to be specifically correctly set.
This likely means that we will keep having all v1 rules maps bugged, which is especially upsetting, for a gamer's perspective, since, when you are playing a v1 Rules game, you expect everything working fine, and then you suddenly notice that your bombard casualties are not returning fire! There are several examples.
It should not happen that when you are playing a v1 based game some rule happens working by v2 rules, as this can really seriously damage your gameplay (naval bombard casualties unable to return fire relevantly increases the power of bombard, and makes quite harder being safe from it).
For example, would you be happy if, when you are playing WaW, which is v2 Rules based, thus you assume you are playing Revised rules, you suddenly notice that your naval bombard is limited by the number of unloaded units, or that your transports are unable to fight, or whatever (v3 Rules), and nothing anywhere was telling you that single case deviation from the general rules? I believe you would not. It is quite irritating, actually. It is the same thing if you are playing by v1 Rules, and something randomly works by v2 Rules, instead.

If you really want to legalise this bug by changing the option (and the default) to say what it does, then I would definitively suggest that you update all maps working by v1 rules, but not having this option specified, so to have that option set this way:

		<property name="Naval Bombard Casualties Return Fire" value="true" editable="false">
			<boolean/>
		</property>

Meaning that the above property should be, then, added to all maps satisfying both the following conditions:

The following property is absent or set false:
property name="WW2V2"

The following property is absent:
property name="Naval Bombard Casualties Return Fire"

Albeit this is a sub-optimal solution, this is actually the way Veqryn decided to go (I disagree), but he only did the above change for the "World War II Classic" map and related mods, as you can read here:
https://sourceforge.net/p/triplea/bugs/1082/
He tagged it as "closed-fixed", but it is not true (he should have tagged it as "closed-wont-fix"); only the default for the specific "WWII Classic" games and mods was fixed, but the default is still wrong in the engine and the property still does the opposite of what it says.
Don't ask me to give you a list of all maps working by v1 Rules, as I would not be able to furnish it, but surely there are a bunch (for some it is relevant, like "Games of Thrones", since they have ships able to bombard, for some other it is not, like "270BC", since they don't have ships able to bombard).

3.
Battleships repair->Units repair

This was not the change I suggested, and I think it is a bad idea, making things even worse. The changes I suggested, as per the Issue you are referencing, are:

**Battleships repair at end of round->Units Repair Hits End Turn**
**Battleships repair at beginning of round->Units Repair Hits Start Turn**

Changing only "Battleship repair" to "Units repair" is a bad idea, for 2 reasons:

- Since the v3 ruleset was added to TripleA, there are two kind of "repair": the repair related to taking hits in battles and the repair related to taking damages from SBR etc.. As long as the option was called "Battleships repair" it was fairly obvious we were talking about battle damages, but if you change it to "Units repair" there is no way a regular user can know if we are talking about reparing battleships etc. or repairing bombed factories etc..

- I have no idea why you are refusing to change "end of round" to "end of turn", or something like that, so (sorry if I'm probably wrong, but let's say this will help anyone with little TripleA experience to understand what we are talking about) I'm just going to assume that you don't actually know what's the meaning of "round" and what's the meaning of "turn" (again, I realise you most likely do). In a normal map (which means all basic maps but the mixed turn of Americans and Chinese in World War II v3), turn means the full sequence of phases of a single player, while round means the sum up of all turns, orderly.
So, if you say "Battleships repair at end of round" in "WWII Classic" or "WWII Revised" it means that all battleships will repair at the end of the Americans turn (which is the last turn of the round), while they actually repair at the end of each turn. If you say "Battleships repair at beginning of round" in "WWII Classic" or "WWII Revised" it means that all battleships will repair at the start of the Russians turn (which is the first turn of the round), while they actually repair at the start of the owner's turn.
Now that I think about it, also my suggestions are not that clear, because the "Battleships repair at end of round" have them repaired at the end of any turns, while the "Battleships repair at beginning of round" have them repaired at the start of the owner's turn only (not anyone's). Thus it might be advisable to reformulate the name-changes as to clarify this, albeit I don't believe this is really that much needed, and I don't know how this should be spelled out, thus my suggestions can stay.

I will try to reformulate my suggestions as them to be more clear. I didn't do it before, because I guessed it would have sufficed (as I asked) developers to be clear on what points they are not getting my suggestions, and I would have explained those points, specifically.
Nevertheless, this is going to be a time consuming task, that will require me some more hours, and I shall do it in the Issue that this Pull is referencing.
I would just ask you (again) to not go ahead like this, doing changes in a different way than I suggested, but being clear on the referenced Issue on whatever you intend to do in a different or partial manner, instead of just doing it.

Thanks again for your time and attention.

**Pull request merged**
