### PR TITLE
Move end of line comments to preceding line and (auto and by-hand) format everything.

### PR DESCRIPTION
**Pull request by DanVanAtta**
A sed script was first used to move all end of line comments to the previous line. Then everything was formatted and eclipse clean was run. Then several iterations of by-hand corrections of everything changed then occurred. Previously all code but not comments were formatted, so the auto formatting mostly changed comments. Formatting fixes were then mostly focused on comments. The few comments on commented out lines were usually removed along with the commented out line. While scanning classes and correcting, a few obvious opportunistic fixes happened, notably for example removing large commented out code chunks, removing empty @param javadoc comments, or removing a few comments that were completely trivial or no longer made sense.

[Review on Reviewable](https://reviewable.io/reviews/triplea-game/triplea/149)

### CODE REVIEW

**Comment by ron-murhammer** [comment]
@DanVanAtta Not sure I like this. What's the reason to move all end of line comments to the previous line? In many cases, I think the end of line comments are good and putting them on a separate line makes it harder to read. I'm guessing you were trying to deal with some of the cases where the end of line comments are wider then the new max width but not sure this is the best way to handle it.

An example would be:
- continue; // skip non-air units
+          // skip non-air units
+          continue;

I think this is better as 1 line as its just a simple comment on why the continue is being used in the loop. Thoughts?

**Comment by DanVanAtta** [comment]
A number of reasons to not fix that right now:
- Easier to find and fix those examples if we really want than to repeat the work without the comment move.
- The EOL comment is a bit subjective, and often it is questionable. Writing a whole lot of end of line commentary precipitated a lot of this problem. The comment reading flow is very odd too. If the comment is large, then why does the comment have to restate or clarify what the line of code that was read already conveyed? Should we spend more time writing more expressive code maybe than more commentary to explain inexpressive code. Last, it's also an odd argument, if the comment is really short, then why didn't the code say it? Also if really short, a two or three word light weight comment before line is easy to read. Otherwise the comment is long, then we get odd line breaks and an avoidable formatting overhead problem, and *really* questionable why long comments would be EOL.
- Due to .gitattributes, until the #151 patch is merged, this branch can't be re-based without forcing commits that will conflict with #151. Not my favorite situation since this PR touches almost all the code and *will* get merge conflicts soon, possibly a lot of them.



A bit of a longer response:

Google Java style more or less has a statement about this:
https://google.github.io/styleguide/javaguide.html#s4.3-one-statement-per-line
> Each statement is followed by a line-break.

So to some extent I think it is subjective and a matter of getting used to. In general you can never fault a comment for being on the prior line, but there can be a gray area when it is at the end of line.

When it comes down to it, if you need a quick end of line comment, I really wonder if you can't make the code more expressive, example:
```
private static final int MAX_LENGTH = 1000 * 200; // roughly 1000 chat messages
```

Any idea what the 200 means? Does the comment tell you anything? Did you spend a bit of extra time wondering if the "1000" matches up by accident, or was this updated to handle 200,000 messages, and we didn't update the comment? Or do you already know what the 200 is because you skimmed down the page and saw the final variable name that told you what it was?

The below is more verbose, thanks to Java syntax fluff, but at least you can read it in less than 2 seconds and move on.
```
 private static final int MAX_MESSAGES = 1000;
 private static final int AVG_MESSAGE_LENGTH = 200;
 private static final int MAX_LENGTH = MAX_MESSAGES * AVG_MESSAGE_LENGTH;
```

The short example you spotted I think is a bit more of an exception than a rule. I'd debate what those few words even really provide. Is the rest of the loop so jumbled that it is not already obvious? Can the read be sure the comment has not drifted from the implementation if there is a *lot* of code to handle non-air units. So for this example:
```
+ // skip non-air units
+ continue;
```
Why is the comment not already obvious? Shouldn't we fix that? If the comment said *why* we can skip non-air units, then it would be longer, and likely need its own line. If the *why* is obvious to the prior statement, then is the comment really needed, or are we dual narrating what the code already is saying?


Given for the majority moving to the prior line is correct, and end of line comments are somewhat debatable and arguably a code smell, and the prior line move then allowed mass formatting to format more or less correctly (if some hand correction needed, but *only* in about 50 files and not hundreds).





Okay, and finally a numerical answer for you. Some scripting can tell us how many of these short line comments we actually (below will be a distribution of line length, follow by count, the longest comment length is 29 (the count includes the "//" and is word count - some commented out code is excluded but numbers are somewhat polluted by commented out code):

```
      1 29    // There is one comment with 28 words
      2 27
      3 26
     15 25
     33 24
     61 23
     65 22
    121 21
    125 20
    108 19
    143 18
    122 17
    186 16
    191 15
    245 14
    309 13
    379 12
    446 11
    437 10
    569 9
    613 8
    618 7
    644 6
    708 5
    653 4
    390 3
    372 2   // There are 371 one word comments 
```

Here are the greps to get that data:

```
find . -name "*java" | xargs cat | grep "^ *//" | grep -v ";" | sed 's/^ *//g' > comments
awk '{print NF}' comments  > line_lengths
sort -rn line_lengths  | uniq -c | less 
```
(The above find gets all "//" style comments that have whitespace only in front of them. Exclude semi colon since that is problably a commented out code line. The sed then trims leading white space for reading convenience. The awk on the next line prints per line the number of words in the line. Then we sort uniq to count, and those counts give us the distribution).


The comment in question had 3 words, so "4" in the above chart and is one of 653 examples. The 2 are probably mostly commented out code, so should be skeptical about that one. So we can see the next 5 or 6 categories have similar counts, so we can see short examples like this are less than 10%. Probably a EOL comment that is more than 5 words really is going to really start wanting to be on the prior line, there are a lot of counts higher than 6 in the distribution. 

So, maybe not ideal, but something we can do to improve where we are, and allow the formatter to be run without fear of changing all the comments in a file.  (note: the last half of this is probably poorly edited, I appreciate you bearing with me on that)

**Comment by DanVanAtta** [comment]
resolved merge conflicts, expecting tests to pass and should be merge-able.

**Comment by DanVanAtta** [comment]
Overall, I think its a step in the right direction, but not as clean as it could be. Particularly the "programming by side effects" elements. Extracting existing code into testable modules and then modifying those with a resourceData object IMO would be a good way to go to. The private methods look to be easily extractable concise objects that you could test.

As is, it is hard to say if it correctly fixes everything, and you may have some NPE possibilities.

**Comment by veqryn** [comment]
what about only moving them, if they are at or beyond 100 characters from the left side?

**Comment by DanVanAtta** [comment]
I would need to be convinced with some evidence of how many comments would be improved, how many fewer hand corrections would be needed, and how many merge conflicts would exist if we did that and then merged the hand corrections-in.

Perhaps not mentioned, I've hand-reviewed all the comment format changes in full 3 times now. It takes a solid 35 minutes just to go through them all. On the whole, the formatting is a good compromise between tedious hand corrections and bulk updates. 

Given the requirement of minimal content changes in favor of just formatting changes, given the number of hand-corrections already done, I don't think we can achieve a better scripting / hand fixing balance than what has been done already. 

To boot, in many cases the end of line comments required hand correction, so the number of instances where we would benefit from better scripting is reduced.

Finally, the proposed script logic would still require a lot of hand corrections, for example the code below would not fixing (these example I went through by hand and fixed each and every one of them that I could find. On my last pass of the code I did not find any left to fix):

```
abc.javaFoo(); // comment starts
               // and is wrapped 
               // already in the code
xyz.moreBar();
```
Would be, and this would need fixing. Painful too if the comment is wrapped more than couple of lines, in some cases it was a dozen or more.
```
// comment starts
abc.javaFoo();
// and is wrapped 
// already in the code
xyz.moreBar();
```

I suppose also finally, with additional scripting complexity, I do wonder if we are spending our time/efforts on the right things. I would rather spend time on better comments instead of formatting them more.

**Comment by veqryn** [comment]
@ron-murhammer I had a quick look at some of the changed files, and everything seems fine.  I am good to merge this, but I wanted to know your opinion on this, and your preference on whether to merge this or your AI patch first?

**Comment by ron-murhammer** [comment]
@veqryn @DanVanAtta I'm fine merging this as well. Overall, I think it improves comment formatting though in some cases its worse but those can be handled manually as we encounter them. I'll leave it up to Dan to which he'd prefer be merged first. I can always just copy the 5 AI files I changed back over top of these formatting changes if we merge this first.

**Comment by DanVanAtta** [comment]
@ron-murhammer , I'm a bit curious why you wouldn't use `git mergetool` to resolve the conflict?

**Comment by ron-murhammer** [comment]
For these types of formatting changes its easier to just clean it up in this case that dealing with reviewing all the conflicts.

**Pull request merged**
