### PR TITLE
Remove Warclub Play by Forum

### PR DESCRIPTION
**Pull request by RoiEXLab**
The server will be shut down at the end of the year

### CODE REVIEW

**Comment by RoiEXLab** [comment]
@ssoloff So to clarify: Is an Exception thrown _and then_ it will work afterwards, or is an exception thrown as long as the user doesn't do anything about it?
In both cases we probably want to delete the cache file on the first startup, but if it's just a one-time exception this issue wouldn't be that severe

**Comment by ssoloff** [comment]
@RoiEXLab 

> So to clarify: Is an Exception thrown and then it will work afterwards, or is an exception thrown as long as the user doesn't do anything about it?

The former.  The exception will only be thrown once because, after it is raised, the bean cache will be empty (which is why all of the user's other stored credentials are lost, as well).  So, yes, the severity of this issue is relatively low.

**Comment by RoiEXLab** [comment]
I wonder what could be done about this to prevent this in the future.
First thought was to simply swallow the first error, but that can't be the solution because there's no way to tell if it's really the first error.
Any suggestions?

**Comment by ssoloff** [comment]
@RoiEXLab Yeah, the problem is the totality of using the default serialization format.  Without taking control of `IBean` persistence somehow, I don't think there's anything you can do to save the rest of the data.  However, using an alternate persistence mechanism requires a breaking compatibility change with the current bean cache anyway, so we're back to the same problem.

So, I can only think of the following two short-term options:

1. Merge this PR with the understanding that any user that has a saved tripleawarclub.org PBF configuration will have to re-enter _all_ of their saved PBEM/PBF configurations.  The question here is how many users would this actually affect?  Since the release of 1.9.0.0.3635, have there been a lot of users still using tripleawarclub.org for PBF?
1. Compromise a bit by leaving the `TripleAWarClubForumPoster` class in-place along with any instance fields and the `serializationUID` field so that it can still be deserialized.  However, remove all of its other members that are not required by the superclass, stub out the methods required by the superclass, and mark the class as deprecated.  We can then remove it completely in the next incompatible release.

BTW, I just noticed this, but regardless of which option you choose, you should also remove _src/main/resources/games/strategy/triplea/help/tripleAWarClubForum.html_, as it is no longer required.

**Comment by RoiEXLab** [comment]
@ssoloff
>  Since the release of 1.9.0.0.3635, have there been a lot of users still using tripleawarclub.org for PBF?

According to @prastle the tripleawarclub.org forum is pretty much dead. Just a few random posts of users who didn't read the main page. 
Perhaps he could confirm this behaviour...

**Comment by prastle** [comment]
@RoiEXLab Ya 7 posts since mid June 2017.  It is safe to say it is dead.

**Comment by RoiEXLab** [comment]
@ssoloff I think going with optioon 1 is probably the better choice here.
Leaving it up to you to merge though.
Agree we should point this out in the release notes or something labelled as "known issue"

**Comment by ssoloff** [comment]
@RoiEXLab Agreed.  It sounds like the number of affected users will be minimal.

@ron-murhammer Just calling your attention to this discussion if you haven't been following.  Please advise if you disagree on the decision here; we can always revert before the next stable release and go with a different option, if necessary.

**Pull request merged**
