### PR TITLE
Remove game notes action tab

### PR DESCRIPTION
**Pull request by DanVanAtta**
Several discussions have happened in forums, generall agreed that the
game notes in the action tabs is not particularly useful. To keep things
simpler, this update remove the game notes tab.

## Release Notes

REMOVE|Removed game notes 'action' tab, game notes are now only available from the 'help > game notes' menu.

### CODE REVIEW

**Comment by beelee1** [comment]
I agree but just want to point out that you can't move the map when accessing the game notes from the help tab. It'd be nice if you could. Not a biggy but still a difference.

**Comment by Cernelius** [comment]
I'm against this change unless it is also assured that the notes always stay above the map view. I'm referring to the following issue, which impacts the game notes as well as the unit help window.
https://github.com/triplea-game/triplea/issues/8607

Even in case that would be fixed, it has so far happened so frequently that windows have issues of various kind that I would suggest keeping this rather useless tab just as a fall-back for future issues with windows.

Besides, I think this is something which should be better discussed in forum (just ask users if they like reading notes in the tabs any better than via the menu).

**Comment by beelee1** [comment]
@Cernelius I think it was talked about in forum. i had meant to comment but forgot about it until seeing it here.

**Comment by DanVanAtta** [comment]
> @Cernelius I think it was talked about in forum. i had meant to comment but forgot about it until seeing it here.

Yes, it was. I'm not sure where the thread is, the consensus between several folks  was that it's not useful.

**Comment by DanVanAtta** [comment]
Fixing the always on top seems easy enough actually, will follow up.

**Pull request merged**
