### PR TITLE
Update Over The Top to 1.1.0 and change category

### PR DESCRIPTION
**Pull request by jdimeo**
@DanVanAtta You had mentioned changing the category on our map after it went live, are we ready to do that?

I just pushed out a new release which addressed some balance issues and clarified a few things in the game notes based on feedback we received on the forum.

Thanks!

### CODE REVIEW

**Review by DanVanAtta — APPROVED** [review]

**Comment by DanVanAtta** [comment]
@jdimeo could you merge the latest into this branch?

**Comment by jdimeo** [comment]
> @jdimeo could you merge the latest into this branch?

@DanVanAtta I'm sorry- I'm not sure I know what you mean. The latest changes to my map are live on the `master` branch, but I'm bumping the version so that people who have already downloaded it would get the new version.

**Comment by DanVanAtta** [comment]
ie, merge the latest triplea-game/master into jdmieo/triplea-game/patch-3

I think the latest has fixes for the integration tests, should fix that for this branch by simply updating. Otherwise we will need to look at why there is a build failure.

**Comment by jdimeo** [comment]
I edited the file from the web UI and opened the PR right away so it seems really unlikely that a commit slipped in in the seconds between me forking and opening the PR, but I'll clone and inspect

**Comment by DanVanAtta** [comment]
I triggered the build job to re-run. I agree the update in that check would be due to non-determinism (:disappointed: )

**Pull request merged**
