### PR TITLE
Debug menu and send bug reports

### PR DESCRIPTION
**Pull request by DanVanAtta**
In this PR:
- group show console, perf log, and show AI log options to a debug menu
- add a new  submit bug report submenu to the 'help' menu
- refactor most of the URL constants to a new enum class 'URLConstants'

[Review on Reviewable](https://reviewable.io/reviews/triplea-game/triplea/455)

### CODE REVIEW

**Comment by ron-murhammer** [comment]
@DanVanAtta - Looks like this needs rebased. The submit bug report idea is interesting. I think we should consider getting that added to the tutorial so people know about it. Hopefully we don't end up with 100s of reports after this is released though :)

**Comment by DanVanAtta** [comment]
Rebased, yeah - certainly one of the 'be careful what you wish for' situations. Getting it in the tutorial would be good  (devil's advocate in me argues that maybe it's better for new more experience players to submit higher quality bug reports, so it's okay to let the veterans stumble on this feature while new people are learning)

**Comment by ron-murhammer** [comment]
@DanVanAtta This needs rebased.

**Comment by DanVanAtta** [comment]
@ron-murhammer  now rebased onto latest master with conflicts resolved.

**Comment by DanVanAtta** [comment]
@ron-murhammer  updated to use swing action in the two spots + assigned 'D' as the hotkey for the debug menu. l think the `SwingAction.of()` stuff may have been on a parallel branch perhaps on the first iteration.

**Pull request merged**
