### PR TITLE
Add readme files for future sub-projects.

### PR DESCRIPTION
**Pull request by DanVanAtta**
The structure create here would have the lobby to client interaction be captured in a single library 'lobby-client'. Future plan is to have 'GameRunner' move to 'client', which would then in turn depend on 'lobby-client'. 'lobby-client' would start small, eventually it'll be the classes we use to talk to the lobby. With luck we'll be able to contain compatibility requirements to that library.

Last, there will be some common data model elements between client and lobby, those data models are hopefully kept to something of a minimum and would live in 'lobby-client-commonb', which both 'lobby' and 'lobby-client' would depend on.

#### For review

- the approach is reasonable, we're okay with having 'lobby-client' and 'lobby' be the points of communication, that it would be a project (jar lib) dependency between game-core and lobby-client.
- naming. I think biggest consideration is when a new client or lobby would start dropping in. We may start to see a web component integration come along in the next few years. I'm already working on a second server websocket based tech that will be easier to integrate new features. 
The convention implicitly implied here is that 'client' and 'lobby' will refer to the original/long-running java thick client and server. Meaning new clients or server projects would need a unique name

project_dependency

### CODE REVIEW

**Comment by ssoloff** [comment]
Here's my idealized view of subproject code dependencies:

modules

Subproject | Description
:-- | :--
`common` | General support code; could be broken down further e.g. `common-net`
`game-common` | Game engine and related domain models
`game-server` | Headless game server
`*-game-client` | Game clients for various UI frameworks
`lobby-common` | Domain models shared between lobby client and server
`lobby-server` | Headless lobby server
`*-lobby-client` | Lobby clients for various UI frameworks
`*-main-client` | Top-level main menu UI from which game and lobby are started; includes existing top-level UI features such as map management, engine settings, etc.

It's probably not 100% correct due to how our main menu UI behaves today.  For example, there may need to be a dependency from `*-main-client` to `game-common` in order to expose things like engine settings.  Obviously, we could get rid of `*-main-client` completely and have `*-game-client` depend on `*-lobby-client` in order to launch the lobby, but I was striving to keep those two separate initially.

Also, I suspect there will be a lot of "game server" code in `game-common` simply due to how integrated the server node functionality is within the game client.

Note that where I'm using `common` in subproject names, `core` would probably be just as appropriate.

**Comment by RoiEXLab** [comment]
@ssoloff 👍 For your suggestion, note however that the main-client needs a dependency on game-server too to keep the current hosting functionality

**Comment by ssoloff** [comment]
Thanks for pointing that out, @RoiEXLab.  As I said above, I knew I probably missed something related to the main menu operation. :smile:

**Comment by RoiEXLab** [comment]
@ssoloff No Problem, I double checked your diagram again and the only thing that might be problematic is the code inside the game server that registers itself in the public lobby game list.
Other than that everything else seems fine to me.

**Comment by DanVanAtta** [comment]
Thanks for feedback.

Few notes of caution:
⚠️ lobby-client should not interact with UI, it is low-level communication layer.
⚠️ careful to not mix architecture and sub-projects. They are related but are different.

Sub-projects:
- These are going to either be apps or libs
- Often formed around common dependencies and configuration
- Loosely related to project domains and large sub-domains

**Comment by DanVanAtta** [comment]
The general design though of having a client-lib on top of a major external component I think is really important. The client-lib layer is where domains mix and it is where we see inter-module dependencies. I'd like to see a 1:1 with any major integration, like a database or an external process/service. 

### First steps
To start immediately, sub-projects to model the build scripts and executables would make sense and is not too far from where we are today in some ways:

based_on_executable

### Next: Client and Server Lobby dependencies removed from game-core
deps_removed


### Tyrus Server will introduce another client-lib

The functionality at first will have no overlap between the different servers and the communication layer will be different between the two. This makes the client side of things a bit more interesting:
multi-client

-------

## Idealized Architecture

Above this line i think is most important as medium/long term projects are dependent on those plans. If we were to talk about an idealized architecture, to some extent the game engine defines a lot of it. `ServerModel` and `PlayerModel` for example are pretty major components, as well as the bridging structure where network connectivity is made 'transparent'. 

Pretty deep topic here, I don't want to get too far down the rabbit hole. If interested how I would diagram idealized architecture let me know and we can spin up a side-conversation.

**Comment by DanVanAtta** [comment]
@ssoloff bump, any comments?

**Comment by DanVanAtta** [comment]
#3232 starts the split.
Necessity is going to play a large role in how things are actually split up.

**Pull request closed without merging**
