### PR TITLE
Fixup for #1583

### PR DESCRIPTION
**Pull request by simon33-2**

### CODE REVIEW

**Comment by DanVanAtta** [comment]
Given the last round of testing on master, I did not see a need for these updates. @simon33-2 or @ron-murhammer, are either you aware of any compatibility problems on master?

**Comment by ssoloff** [comment]
@DanVanAtta See #1610, specifically [this comment](https://github.com/triplea-game/triplea/pull/1610#issuecomment-291384466).

**Comment by simon33-2** [comment]
It doesn't behave properly in the case where the game is saved while a battle is in progress. As ssoloff referred to above. This is important because that is the point that the defender is asked for the order of casualties in a PBEM/PBF game.

I don't think the current master can be considered stable without this change, in fact. So merge it please, before more conflicts are added. @DanVanAtta @ron-murhammer

**Comment by DanVanAtta** [comment]
It does look like this fixes a NPE. When loading a save game from 1.9.0.0.3635 with latest master during a battle, I get this stack trace:
```
java.lang.NullPointerException
	at games.strategy.util.Match.getMatches(Match.java:39)
	at games.strategy.triplea.delegate.MustFightBattle.getAttackerRetreatTerritories(MustFightBattle.java:1241)
	at games.strategy.triplea.delegate.MustFightBattle.canAttackerRetreat(MustFightBattle.java:1281)
	at games.strategy.triplea.delegate.MustFightBattle.canAttackerRetreatSubs(MustFightBattle.java:1299)
	at games.strategy.triplea.delegate.MustFightBattle.access$1800(MustFightBattle.java:50)
	at games.strategy.triplea.delegate.MustFightBattle$14.execute(MustFightBattle.java:912)
	at games.strategy.triplea.delegate.ExecutionStack.execute(ExecutionStack.java:41)
	at games.strategy.triplea.delegate.MustFightBattle.fight(MustFightBattle.java:330)
	at games.strategy.triplea.delegate.BattleTracker.fightBattleIfOnlyOne(BattleTracker.java:1180)
	at games.strategy.triplea.delegate.BattleDelegate.start(BattleDelegate.java:105)
	at games.strategy.engine.framework.ServerGame.startStep(ServerGame.java:498)
	at games.strategy.engine.framework.ServerGame.runStep(ServerGame.java:404)
	at games.strategy.engine.framework.ServerGame.startGame(ServerGame.java:259)
	at games.strategy.engine.framework.startup.launcher.LocalLauncher.launchInNewThread(LocalLauncher.java:61)
	at games.strategy.engine.framework.startup.launcher.AbstractLauncher.lambda$launch$788(AbstractLauncher.java:43)
	at java.lang.Thread.run(Thread.java:745)

```

Doing the same with this branch does not have a crash, the game is still playable. Still of some note, we still have a pop-up:
```
Current battle exists but is not on pending list:  Battle in:Ukraine S.S.R. battle type:Battle defender:Germans attacked by:Russians from:[Caucasus, Karelia S.S.R.] attacking with: [armour owned by Russians, armour owned by Russians, armour owned by Russians, fighter owned by Russians, fighter owned by Russians, infantry owned by Russians, infantry owned by Russians, infantry owned by Russians, infantry owned by Russians, infantry owned by Russians]
```
Looks like the game handles the condition okay, the above probably just needs to be a "logQuietly" instead of "logError" (there does seem to be a root cause fix in there too, that condition should probably not be violated). I've attached save game that repro's. Load the save and click through on the battle, should see a pop-up before the battle is over.
[test_save_1745.zip](https://github.com/triplea-game/triplea/files/1039156/test_save_1745.zip)



Seeing an error  pop-up is not expected. but the game is now playable when before it was not.

**Comment by DanVanAtta** [comment]
https://github.com/triplea-game/triplea/issues/1771 To follow up with the unexpected pop-up

**Comment by DanVanAtta** [comment]
Thanks for getting this fix in @simon33-2

**Comment by simon33-2** [comment]
No worries Dan.

When we bump the version to make incompatible changes, we should revert this change as one of the first actions.

**Pull request merged**
