### PR TITLE
Fix file permissions on a few files

### PR DESCRIPTION
**Pull request by ron-murhammer**
For some reason it appears just these couple of files have different permissions than the rest of them.

[Review on Reviewable](https://reviewable.io/reviews/triplea-game/triplea/288)

### CODE REVIEW

**Comment by DanVanAtta** [comment]
gradlew and the files in "scripts" are executable. Why 0644 for them? 0755 would be convenient to keep them executable after a git clone.

**Comment by ron-murhammer** [comment]
@DanVanAtta Valid point though then why aren't the rest of the files in /scripts executable? This was just to make everything consistent as those were the few files that flagged as having different permissions then the rest.

**Comment by DanVanAtta** [comment]
@ron-murhammer  Seems like all files in /scripts should be executable as well.

**Comment by ron-murhammer** [comment]
@DanVanAtta I'm fine either way as long as:
1. Things are consistent
2. Git doesn't keep trying to commit the changes to the files

Since I'm on a windows machine, I can't really play around with it. I'd say let's accept this PR, then if you want to play around with file permissions on Linux for executable files you can create another PR.

**Comment by DanVanAtta** [comment]
@ron-murhammer , can I modify this branch directly?

**Comment by DanVanAtta** [comment]
Better yet, @ron-murhammer , I submitted #289 to modify this branch and make all files in /scripts 0755. Please merge that and then I think we should then merge this one (#288)

**Comment by DanVanAtta** [comment]
I missed the gradle file, one sec before merging #288 @ron-murhammer

**Comment by DanVanAtta** [comment]
@290 now opened to update the gradlew file to 0755 @ron-murhammer

**Comment by DanVanAtta** [comment]
@ron-murhammer  - went ahead and merged it all. #289 and #290 modified this branch, and now #288 (this PR) is merged.

**Comment by ron-murhammer** [comment]
Yep. My git still wanted to change those files to non-executable so I needed to do this: http://stackoverflow.com/questions/1257592/how-do-i-remove-files-saying-old-mode-100755-new-mode-100644-from-unstaged-cha

**Pull request merged**
