### PR TITLE
Synchronize objects on game load

### PR DESCRIPTION
**Pull request by RoiEXLab**
@simon33-2 Still wasn't able to reproduce your issue.
Could you checkout my branch and test if this PR fixes the issue for you?

### CODE REVIEW

**Comment by simon33-2** [comment]
I'm afraid I can still reproduce the problem

**Comment by RoiEXLab** [comment]
No clue then...
@ssoloff Any Ideas?

**Comment by ssoloff** [comment]
@RoiEXLab Without being able to reproduce the problem, I'd just be guessing (probably incorrectly). :smile:

**Comment by RoiEXLab** [comment]
@ssoloff Just like I did

**Pull request closed without merging**
