### PR TITLE
Remove XmlUpdater tool

### PR DESCRIPTION
**Pull request by ssoloff**
This appears to have been a one-off tool written circa 2009 (e7ed262f6) to upgrade the map XML files from one version to the next.  It is most likely out-of-date and offers no value.  There have been only refactoring changes to this tool since it was first introduced.

@DanVanAtta @ron-murhammer Do either of you have any other insight into the purpose of this tool?  Is there any value in keeping it around?

### CODE REVIEW

**Comment by ron-murhammer** [comment]
No idea. Looks like it was used when some renamings had to be done way back when Hasbro complained.

**Comment by prastle** [comment]
Curious if roger still uses this?
Just a thought

**Comment by DanVanAtta** [comment]
Hard to think that the Hasbro threat was now that long ago. We can and should drop this code so we can stop maintaining it. A converter this old is not going to be used anymore, the 1.8 -> 1.9 conversion is still an ongoing thing. 

@ssoloff why is the game.dtd file showing up in the diff? I don't fully understand that.

**Comment by ron-murhammer** [comment]
@DanVanAtta It appears it used a dummy (empty) game.dtd file to avoid adding default values per this comment "use a dummy game.dtd, this prevents the xml parser from adding default values".

And yeah unless we want to turn this into some generic converter that we plan to use in the near future then I agree that it should just be removed.

**Comment by DanVanAtta** [comment]
IF we try to continue supporting the concept of 'bulk update', we will need such converter apps. I'd like for this to be the last one that we see, but it may not be the end of them.  Making the converter generic I don't think will work super well as conversions are pretty custom. Going that route, if we did, we'd probably need an app that had plugin-ins for various conversion strategies. It would get annoying to maintain that code I think IMO, just as in here; we likely would likely not drop old conversions until much later.

**Comment by DanVanAtta** [comment]
Thanks for answer on dtd file @ron-murhammer , summary, I think we're all in agreement to drop this code.

**Comment by ssoloff** [comment]
> why is the game.dtd file showing up in the diff?

> It appears it used a dummy (empty) game.dtd file to avoid adding default values per this comment "use a dummy game.dtd, this prevents the xml parser from adding default values".

What's funny is that the code didn't actually use this empty _game.dtd_ file.  If you look carefully, it uses the URL of a classpath resource named `""` as the system ID when validating:

https://github.com/triplea-game/triplea/blob/9314a36757dc7c2d39dd80a41c4e08f20507be15/game-core/src/main/java/tools/image/XmlUpdater.java#L48-L49

That URL just points to a folder on the file system.  Presumably, when the parser opens it, it will either get an empty stream or an error (which it probably ignores), and that leads to the same desired effect of using an empty DTD.  I thought maybe someone changed this code in the interim, but nope, that empty string in the `getResource()` call has been there since the beginning.

---

It sounds like there's agreement to remove this code, so I'm going to clear the PREVIEW label and open this PR up for general review.  Thanks!

**Pull request merged**
