### PR TITLE
Swing components

### PR DESCRIPTION
**Pull request by DanVanAtta**
[Review on Reviewable](https://reviewable.io/reviews/triplea-game/triplea/451)

### CODE REVIEW

**Comment by ron-murhammer** [comment]
@DanVanAtta - Looks like this needs rebased.

**Comment by DanVanAtta** [comment]
Will rebase once #449 is merged. Rebasing this now would require re-resolving the conflicts from #449.

It would be interested to know how/why #449 had merge conflicts. The first 5 or 6 PRs were stacked one after another on top of each other. When one of the bottom PRs had a merge conflict, it doesn't meant 1 merge conflict, it is 6 duplicated merge conflict. Branch 2 rebased on 1 would hit the same merge conflicts while doing the replay. Same for branch 3 and so forth.

It turns out there is a git command, `git rerere` command where I could record the merge conflict resolution and then replay it.. At this point I'm happy waiting for #449 and #450 to be merged. In which case if I then rebase this PR the conflicts will either all go away, or alternatively I'll *only* have to deal with the conflicts from the one brand new commit.

**Comment by DanVanAtta** [comment]
ready for review

**Comment by gaborbernat** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/games/strategy/triplea/printgenerator/SetupFrame.java, line 91 \[r1\]](https://reviewable.io:443/reviews/triplea-game/triplea/451#-KC-Ji2mjWZhSXoUvCkw:-KC-Ji2mjWZhSXoUvCkx:750012702) ([raw file](https://github.com/triplea-game/triplea/blob/768e31cead933598852e746acb7ee8cb7f268c51/src/games/strategy/triplea/printgenerator/SetupFrame.java#L91)):*
Again, no space between parameters. 

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/triplea-game/triplea/451)*

**Comment by DanVanAtta** [comment]
Review status: 3 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/games/strategy/triplea/printgenerator/SetupFrame.java, line 91 \[r1\]](https://reviewable.io:443/reviews/triplea-game/triplea/451#-KC-Ji2mjWZhSXoUvCkw:-KC-M3RRdCSL8-ea6q-v:-499146009) ([raw file](https://github.com/triplea-game/triplea/blob/768e31cead933598852e746acb7ee8cb7f268c51/src/games/strategy/triplea/printgenerator/SetupFrame.java#L91)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/triplea-game/triplea/451)*

**Comment by gaborbernat** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/triplea-game/triplea/451)*

**Pull request merged**
