### PR TITLE
Break up GameParser a bit and add tests for 'variableList' parsing

### PR DESCRIPTION
**Pull request by DanVanAtta**
## Overview
PR into: #4791

## Additional Review Notes
- Updates are bit more than surgical as needed some utilities to grab nodes and do XML parsing. The 'NodeFinder' should eventually be tested in turn as well. For now that is left for another day.
- I was really tempted to do the testing as a pure unit test with mocks. I decided against that as the mocking would perhaps have gotten to be a bit much and potentially overly coupled.

### CODE REVIEW

**Comment by RoiEXLab** [comment]
Props to you @DanVanAtta 0.11% coverage is huge 👍

**Comment by DanVanAtta** [comment]
100% coverage on GameDataParser.java @RoiEXLab  :smile: 

So at least the new code is now tested, which was the goal. GameParser.java will need I think a good bit more work to continue extracting sub-components that can be individually tested. Eventually with the sub-components tested, we'll be able to in-turn mock them in GameParser.java itself and eventually get good coverage.

**Comment by RoiEXLab** [comment]
@DanVanAtta Yeah, I should've pointed out that it's now 0.11% more ^^
PRs usually have trouble adding more than 0.01% coverage, even with added tests.

Good job anyways

**Comment by DanVanAtta** [comment]
@RoiEXLab thanks : )
Some of that 0.11% TBH is not quite real as some new code is executed but not tested.

@ron-murhammer FYI my last update added a checkstyle violation in the imports of GameDataVariableParser.java (extra new line after package)

**Pull request merged**
