### PR TITLE
Update triplea_maps.yaml

### PR DESCRIPTION
**Pull request by beelee1**
give this another shot

### CODE REVIEW

**Comment by beelee1** [comment]
Yay lol

@DanVanAtta yea so git uses main as the default both ways I tried it. This time I manually added a readme so I could clone the code and then added stuff my usual way. 

At any rate, maybe some sort of warning in triplea-maps or the yaml, telling people they need to rename to master ? Just a thought. It was definitely frustrating.

**Comment by DanVanAtta** [comment]
@beelee1 this is why I ask you which git client tool you are using. Git only has a concept of 'default' branch, it does not care what it is called, and actually by convention it is called 'master'. The 'main' seems to be specific to what you are using, which is why I ask.

**Comment by beelee1** [comment]
@DanVanAtta  what I did was go to triplea-maps, clicked on the green button that says "New", named the repo which took me to here:

…or create a new repository on the command line

echo "# testingmain" >> README.md
git init
git add README.md
git commit -m "first commit"
git branch -M main
git remote add origin https://github.com/triplea-maps/testingmain.git
git push -u origin main

as you can see it has main listed. I changed it to "master" the second time i tried it. Still didn't work. Kept "re-initializing". 

So then I made a new repo again and manually loaded a readme so I could clone it and then add my stuff via terminal. That repo also had "main" as it's branch, so I renamed it and then everything worked.

**Comment by DanVanAtta** [comment]
Thanks! I found where the new repository default was set to 'main' and switched that to 'master'

**Comment by beelee1** [comment]
Sweet !

**Pull request merged**
