### PR TITLE
Update triplea_maps.yaml

### PR DESCRIPTION
**Pull request by TheDog-GH**

### CODE REVIEW

**Comment by beelee1** [comment]
@TheDog-GH sorry idk whats up. I asked @RoiEXLab on @Cestmoi02 s post  Hopefully he'll have time before too long to help

**Comment by RoiEXLab** [comment]
What @beelee1 says. The repository is not public. This means the general public (including myself) can't see it. For me the link https://github.com/triplea-maps/arena_of_death/archive/master.zip leads nowhere. And it obviously needs to be public to work for users to download it.

**Comment by TheDog-GH** [comment]
@RoiEXLab 
Does this image show my map is Public?

image

.
Do I need a SSH Key?

image

**If so, how do I add one?**

.
I cannot see link below either, so I think Im missing something, but what?
https://github.com/triplea-maps/arena_of_death/archive/master.zip

.
I have been following Rogers guide.
https://forums.triplea-game.org/topic/3277/posting-scenarios-to-the-repository

**Comment by TheDog-GH** [comment]
I am using GitHub Desktop, so I might not need a SSH key?

image

**Comment by RoiEXLab** [comment]
@TheDog-GH The image does show your map is public but it's not true for the variant that is owned by `triplea-maps`

**Comment by TheDog-GH** [comment]
Failed

**Pull request closed without merging**
