### PR TITLE
Update triplea_maps.yaml

### PR DESCRIPTION
**Pull request by Navalland2**

### CODE REVIEW

**Comment by DanVanAtta** [comment]
@Navalland , I'm curious why the warning? It is unlikely for anyone already with this map installed to see it. Have you considered to change the version number from '1' to '2'? That will trigger a message to anyone with the map that they can download an update.

**Comment by Navalland2** [comment]
I though I had to edit YAML files for having it avaliable for bots also I didn't know that 0 was representing pre-release so in this update I turned it to 1.

**Comment by DanVanAtta** [comment]
I need to track down when bots get map updates. It's either only once when new maps are added or it's whenever there is an update to the game-engine (merge to master). The version number in this file does not indicate anything special, it's a release number essentially. You increment sequentially and whenever it increases players will be notified of a new map.

**Comment by DanVanAtta** [comment]
@Navalland2, the version number in the YAML file is perhaps what you are looking to change. 
I'm actually not sure if the version number in the map is even used anymore.

**Pull request closed without merging**
