### PR TITLE
Import doc

### PR DESCRIPTION
**Pull request by DanVanAtta**
Delete the  'dev_docs' folder on the website and bring them into this repo. After bringing them in(1st commit), I updated a few folder names to organize/clarify a bit in the following few commits. Since the documentation files will now be viewed from the github website and not as rendered markdown on github.io, the index.md files should be 'README.md' files (they then get picked up by default)

Removed from website repo here https://github.com/triplea-game/triplea-game.github.io/pull/226

Quoting that PR:
> Couple motivations and reasons for the move:

> - focuses website contents towards typical game players. This helps focus on having good help content and information useful for new and returning players
> - any content that may need to be updated in sync with the code will ideally now be located in the same repo as the code. For example, if we update something relating to maps, we'll be able to then update the map maker documentation in the same branch that modifies the code.

### CODE REVIEW

**Comment by DanVanAtta** [comment]
> Also the yaml frontmatter is no longer needed if the files are hosted here

I'm not removing that for now. I'd like to hold off to avoid churn, and it does not hurt for now to have it.

> The website's dev docs are being referenced from various locations (this icludes the new template files)

Yes, though they are not removed yet so those links are not broken. It's not critical we wait for those to be updated. Meanwhile the website docs are frozen (I'll take care of reconciling anything while there are duplicates if it becomes a problem with this forked copy, the website version should be removed in a few days)

> Those links should be updated as a part of this Pr. 

Ideally yes, but I'm still reviewing those files. There is way more risk of code churn here there is any other harm. Also there are documentation updates we do need, building that out further on the website is  not the direction we want to go. So let's kindly not get too worried about doing a full migration right now before we have deleted the website content.

**Comment by ron-murhammer** [comment]
I'm fine either way on the docs.

@RoiEXLab @ssoloff Do you have a preference on moving the dev docs here rather than the website?

**Comment by ssoloff** [comment]
:+1: moving the dev docs to this repo.

**Comment by DanVanAtta** [comment]
Add a number of commits after taking passes at cleaning up the docs. Did the following:
- reduced content, EG: prose -> lists
- removed a few pages that were out of date
- tried to prune information that we certainly had elsewhere
- cleaned out the 'older' doc folder that was a dumping ground for the stuff we used to include with the game client. Couple user facing pages there would go back to website, otherwise it was spread back into dev, map making, or deleted as out of date.

**Comment by DanVanAtta** [comment]
@RoiEXLab Any objection if update the contributing links after merge? Should be very quick to do, the old links are not broken after this merge, and it'll be easier to know what the updated URLs should be, sound okay?

**Comment by DanVanAtta** [comment]
Reflecting on this, the doc update is very difficult to review since I subtracted and re-arranged lines that were being added anyways.Since this is documentation, and there is still quite a bit to do on it (iterations here, not attempting to do all at once), I'll move forward with this plan. @RoiEXLab  you've some valid points, I do want to make sure they get addressed.

- Since we are adding, not breaking anything, and all docs, does not hurt to merge. I'll strip all but the first two commits, which are basically the big copy/paste dump. There is not much to review there other than where that documentation lives, and we have agreed on that. 
- I'll then put the prune/editting commits on a new branch, cut a new PR. With luck that should be mostly informational, and it's not necessarily the last iteration.
- Once that is done, we look to removing the website version of this documentation and finish updating any links

**Comment by DanVanAtta** [comment]
As mentioned, pruning/editting has been moved to this branch, opened for PR:
https://github.com/triplea-game/triplea/pull/1995

**Pull request merged**
