### PR TITLE
Replaced legacy httpClient (#1430 follow-up)

### PR DESCRIPTION
**Pull request by RoiEXLab**
This replaces the legacy httpClient with the new 4.5 version...
I haven't tested those changes, since I don't know where to find the corresponding menu items.
If you could test this on your own, or tell me where exactly they are used I'd be happy to test this...

### CODE REVIEW

**Comment by DanVanAtta** [comment]
Looks like this touches the various play by forum options. We could use some testing there regardless to catalog what is still working. IIRC only PFB for A&A.org is working.

The dice roller is also updated, that is perhaps more tricky to test. I'm afraid I don't have any very good suggestions. In general we could use some investment to make launching the dice roller more well known and easier (ie: documentation and/or a launch script)

**Comment by ron-murhammer** [comment]
Interesting. If this only touches PBF and dice roller then essentially you'd just need to test out a PBF game on A&A.org. We'd want to be pretty confident that is all it touches though.

**Comment by RoiEXLab** [comment]
The part with the dice roller is actually the part I'm most confident it'll work without problems... Just because it's so simple and doesn't require session cookies etc.

**Comment by RoiEXLab** [comment]
Hmm I never played Pbf before, What should I look out for?
Also how would I test the dice roller?

**Comment by RoiEXLab** [comment]
So I pressed the "test button" using the dice roller and the PBF on tripleawarclub.org
They seem to work fine, Since I don't have an axisandallies.org account (and I don't want to create one) I'd like you to test PBF on this website...
I'm at least getting correct error messages using invalid login credentials...

**Comment by RoiEXLab** [comment]
So, altough I didn't wanted to, I created an axisandallies account in order to test this stuff, and it turned out I had a small typo in my code (I forgot a 2).
All tests seem to work now, I will edit the title of this PR -> since the tests use the same method like the "real method"

**Comment by RoiEXLab** [comment]
@DanVanAtta @ron-murhammer That means, this PR is opened for reviewing now!

**Comment by RoiEXLab** [comment]
@DanVanAtta I'd like you to merge/review this PR quickly, so I can start coding the web apis for the upcoming forum without creating merge conflicts

**Comment by DanVanAtta** [comment]
For the API's, please raise some issues outlining some of the details involved. Looking for a brief overview of how tripleA does auth today, and what changes would be made to do auth using forum.

**Pull request merged**
