### PR TITLE
Use DiceRoll#rollDice instead of DiceRoll#airbattle

### PR DESCRIPTION
**Pull request by trevan**
The two methods are identical so combine them.

### CODE REVIEW

**Comment by DanVanAtta** [comment]
@trevan with Travis having disabled our builds, please be sure you are running the `./verify` script manually.
It looks like pretty soon we'll have most of the build checks restored as github actions.

**Comment by trevan** [comment]
@DanVanAtta , I ran `./verify` locally and it passed
```
BUILD SUCCESSFUL in 3m 37s
320 actionable tasks: 46 executed, 274 up-to-date
```

**Review by DanVanAtta — APPROVED** [review]

**Comment by DanVanAtta** [comment]
Thanks @trevan 

Github actions now runs everything except the smoke test project and integration tests (the PR checks that depend on having a database).  For context, the smoke test fires up a lobby, a bot, verifies the two connect and then has a simulated player join the lobby and then join the bot. One fine day it would launch a game and perhaps play through some scenarios or do an all-AI game to verify we hit no exceptions.

Anyways, w.r.t Github actions, with luck we'll have those last two pieces soon. (Side-note, it's still generally a good idea to run 'verify' or 'verify-no-tests' to avoid any problems post-push)

**Comment by trevan** [comment]
Hmm, this broke something.  I just ran a different AI game to test something and it is having issues.  I'm working on trying to understand how this broke that AI game.

**Comment by DanVanAtta** [comment]
Now reverted, thank you for finding a problem. Let's roll forward with a fix once we understand what went wrong.

**Pull request merged**
