### PR TITLE
Checkstyle: Fix line length violations (Part 2)

### PR DESCRIPTION
**Pull request by ssoloff**
This PR fixes violations of the Checkstyle LineLength rule.

I'm splitting fixes for the LineLength rule into multiple PRs because, while the number of changes is not particularly large, they do require a bit more scrutiny. So I'm trying to keep the PR smaller to not overwhelm the reviewer.

### CODE REVIEW

**Comment by simon33-2** [comment]
Can I suggest some better things to do:
- Fix the bugs in sub based combat
   - If the side being fired on has a destroyer, they shouldn't be asked for casualties until they know the number of hits from all units
   - if the side being fired on doesn't have a destroyer and the side firing has air, the side being fired on should know the number of hits from all units rather than needing to select air casualties first (or something like that)
- Auto place carriers and update the prompt for when air is moved in non combat to a sea zone with a an industrial complex and a carrier bought to be "Keep Moving"/"Place Carrier(s)" rather than "Keep Moving"/"End Move Phase". This needs to remove the carriers placed from the I guess there is a third possibility where you have some air that can be caught by a mobilising carrier and some which will be stranded. In that case I suggest that the new prompt is displayed, and then the old one.
- If there is only one unit to place in the unit picker, don't ask the user
- Scramble box - don't allow them to select scramble with 0 units selected. Similarly with vice versa.
- If there is only one potential unit placement location, auto place.
- Merge purchase and repair units - this is a rule violation at present. I have a suspicion that this can be done without a rule change but I can't see it?
- Allow repair of disabled facilities without edit for maps with combat move before purchase

How's that for a list?

**Comment by ssoloff** [comment]
@simon33-2 That looks like a good selection of features and fixes, and I'd be happy to contribute to some of them.  In fact, a few look like good candidates for me to increase my knowledge of game mechanics.  Are there already open issues for any of them?  Is so, could you edit your [comment](https://github.com/triplea-game/triplea/pull/1638#issuecomment-294029299) and reference the issue number?  I'll then bookmark the comment for later review.

However, I plan on starting to prototype the serialization proxy stuff this weekend, so, other than dropping a few more Checkstyle PRs for the remaining no-risk and low-risk violation fixes, I probably won't get to any other meaningful changes in the near future to avoid context switching.

**Comment by ssoloff** [comment]
Rebased against `master` at 240e942 (1.9.0.0.4043).

**Comment by simon33-2** [comment]
Not all of those have issues open.

**Pull request merged**
