### PR TITLE
Use Interface Types for ArrayList, HashSet and HashMap

### PR DESCRIPTION
**Pull request by RoiEXLab**
## Overview
This changes the declaration type of all ArrayList, HashSet and HashMap declarations to their respective interface type.

## Functional Changes
In theory none, I'm not entirely sure if a changed method signature could potentially break network compatibility to the lobby, I'll check this evening because I'm currently a bit in a hurry.

## Manual Testing Performed
None, yet.
EDIT: I verified I could join the lobby no problem, and could connect to the bot, (which told be that my version is too high) after disabling the client side version check,

### CODE REVIEW

**Comment by RoiEXLab** [comment]
```
SCHWERWIEGEND: Could not connect host: localhost, port: 3304, name: RoiEX, mac: <redacted>.
java.lang.RuntimeException: Could not connect host: localhost, port: 3304, name: RoiEX, mac: <redacted>.
	at games.strategy.net.ClientMessenger.<init>(ClientMessenger.java:90)
	at games.strategy.net.ClientMessenger.<init>(ClientMessenger.java:51)
	at games.strategy.engine.lobby.client.login.LobbyLogin.login(LobbyLogin.java:91)
	at games.strategy.engine.lobby.client.login.LobbyLogin.lambda$login$0(LobbyLogin.java:69)
	at games.strategy.engine.framework.ui.background.BackgroundTaskRunner$1.doInBackground(BackgroundTaskRunner.java:121)
	at javax.swing.SwingWorker$1.call(SwingWorker.java:295)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at javax.swing.SwingWorker.run(SwingWorker.java:334)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.net.ConnectException: Connection refused: no further information
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at games.strategy.net.ClientMessenger.<init>(ClientMessenger.java:86)
	... 10 more
```

Pretty sure this isn't supposed to happen, but this happens on master (master a couple of hours ago when it was 1.10.0.0.12570) as well.
Thoughts @ssoloff ?
Looking back at the diff I don't think there's anything that could break network compatibility with the lobby, I confused a helper class for integration tests with the actual implementation.

**Comment by ssoloff** [comment]
@RoiEXLab Are you running a lobby on your local machine?  It looks like there's nothing listening at `localhost:3304`.

I just tried connecting a 12570 lobby client to both the production lobby and to a local lobby running from `master` and had no issues connecting.

**Comment by RoiEXLab** [comment]
@ssoloff Ahhh that makes sense.
I think I forgot to reset my custom lobby override back to nothing the last time I fiddled around with local lobby test.
I'll check back later tonight if that's actually the case.
I didn't really look at the error because I was in a rush, again ^^

**Comment by RoiEXLab** [comment]
@ssoloff Did some basic network functionality testing with the current prod lobby.
I'm pretty sure the LGTM analysis is stuck, so because it's not required merging in without this check would be ok IMO.

**Pull request merged**
