### PR TITLE
Add commons-text as a dependency

### PR DESCRIPTION
**Pull request by trevan**
This brings in StringSubstitutor which allows creating a string template
with replacement strings in it of the format ${variable}.

## Additional Notes to Reviewer

If there is an existing string substitution library in the project, then I can use that.  But I wasn't able to find a one.
If there is another preferred library for string substitution, I can import that instead.

### CODE REVIEW

**Comment by DanVanAtta** [comment]
Any example intended usages? I'm interested how StringSubstitutor compares to String.format

**Comment by trevan** [comment]
```
String template = "${units} lost in ${territory}";
final String text =
        new StringSubstitutor(
                Map.of(
                    "units", MyFormatter.unitsToText(killedUnits),
                    "territory", location.getName()))
            .replace(template);
```

It allows named substitution.  So you could create multiple templates that have the variables in different orders or skip some variables.

**Comment by DanVanAtta** [comment]
For comparison, `String.format`:
```
String.format(
  "%s lost in %s",
  MyFormatter.unitsToText(killedUnits),
  location.getName()
);
```
Are there any particular cases you have in mind @trevan  where StringSubstitutor would be particularly useful?

**Comment by trevan** [comment]
@DanVanAtta , yes I'm creating a class that you can pass in different templates.  Some templates will have all of the variables (`${units} lost in ${territory}`), others will have less (`${units} killed by AA fire`), and some will be in different order (`${territory} had ${units} removed from it`).

**Comment by DanVanAtta** [comment]
Are you planning to submit multiple branches in parallel that rely on this as a common update?

**Comment by trevan** [comment]
Currently, it is just one branch.  Do you want me to close this and just add this dependency along with the branch?

**Comment by DanVanAtta** [comment]
Please do, it's a small enough change that seeing it in context would be helpful IMO.  OTOH if it were a common ancestor then submitting it first on its own would make a lot of sense.

**Comment by trevan** [comment]
No problem

**Pull request closed without merging**
