### PR TITLE
Added CTF2

### PR DESCRIPTION
**Pull request by RogerCooper**
Removed the description entirely.

### CODE REVIEW

**Comment by RoiEXLab** [comment]
@RogerCooper I have the impression so seem to struggle a little bit with the formatting tool, so here's some advice.
The only thing wrong with your PRs is that the files have too many trailing newlines. There should be a single trailing newline at the end and that's it. To be honest it's a bit hard to spot in the error message and I didn't notice it myself first, but once you know it it becomes really obvious.
Here is how it should look like in the online editor:
Screenshot
Just a single newline after the last line of text.

Also there's no need to create a new PR for every attempt. You can just go to the "Files changed" Tab and edit the files there using the online editor.

**Comment by DanVanAtta** [comment]
@RoiEXLab  thank you . @RogerCooper  , please combine all open map requests and submit as one; That will be the easiest way most likely to get everything submitted  (and avoids merge conflicts)

**Comment by RogerCooper** [comment]
Sorry, I was experimenting on trying to get anything in. Now that I know I need 1 blank line at the end, I should not have further problems.

**Comment by RogerCooper** [comment]
DanVanAtta, any progress on fixing the download issue with 2.6? Right now, I am only working in 2.5

**Comment by DanVanAtta** [comment]
> DanVanAtta, any progress on fixing the download issue with 2.6? Right now, I am only working in 2.5

Yes, some. If you use 2.6 and explicitly use the 'prerelease' server via the 'settings > testing' menu, downloads should work.

**Pull request closed without merging**
