### PR TITLE
Restore all map properties to Map Properties Maker (#1261)

### PR DESCRIPTION
**Pull request by ssoloff**
This PR restores all map properties to the Map Properties Maker tool that were removed as part of 75c1bf1.  As shown in [#1261](https://github.com/triplea-game/triplea/issues/1261#issuecomment-291000309), the latest Map Properties Maker tool no longer offers the complete set of properties available in `map.properties`.

#### Functional changes
* I partially reverted 75c1bf1 and 4415073 so that the Map Properties Maker will display all current map properties.

#### Functional issues for review
* @DanVanAtta, do you remember what the reason was for removing the ability to edit most of the map properties in 75c1bf1?  The OP is under the impression this is a regression in that it results in loss of functionality.  But I'm assuming there may have been a logical reason for the change that I can't deduce right now.

#### Refactoring changes
* I introduced new Checkstyle violations in this PR when I reverted 75c1bf1, which will trigger a build failure due to the newly-added enforcement of Checkstyle violation thresholds.  Unfortunately, those violations were due to the legacy naming convention used in the `MapProperties` class to facilitate reflection.  I fixed all naming convention violations in the `MapProperties` class by changing the applicable field/method casing from UPPER_SNAKE_CASE to CamelCase.

#### Refactoring issues for review
* Changing the casing of the fields/methods in `MapProperties` changes the appearance of the labels in the All Options dialog.  I'm not sure if this is going to confuse end users as I've never previously used the Map Properties Maker tool.

#### Testing
The tool now includes all the properties displayed in the 1.8.0.9 screencast previously [referenced](https://github.com/triplea-game/triplea/issues/1261#issuecomment-291000309) (excluding the screenshot stats properties, which were removed in #529), as shown below:

map-properties-maker-all-options-new-appearance

(NB: the original screenshot before the label changes were made is available [here](https://cloud.githubusercontent.com/assets/4826349/24738168/ed68a4be-1a61-11e7-9808-9a3447244ec3.png).)

I also verified that Map Properties Maker saves a non-empty `map.properties` file after editing a few properties using the above screen and spot-checked the file to ensure it contained the values I specified.  The OP reported that saving `map.properties` was broken, but I didn't do anything specific to fix it.  As documented [here](https://github.com/triplea-game/triplea/issues/1261#issuecomment-291029826), I observed exceptions being raised due to missing methods.  It's possible the exceptions (which no longer occur due to adding the missing methods) were the root cause of the failure to save `map.properties`, but I didn't pursue this investigation further.

:warning: @panther2 If possible, I'd appreciate if you could test this to verify that your original issue is fixed by this PR.  Are you able to build TripleA from source?  Unfortunately, I don't believe Travis is configured to save build artifacts for PRs.  So, if you can't build from source, I can upload a build someplace (I have a feeling a 30 MiB file is too large to attach to a GitHub issue).

### CODE REVIEW

**Comment by ssoloff** [comment]
@ron-murhammer Please hold off on merging this PR until further notice.  After the merge of #1618, it will fail the build because reverting commits 75c1bf1 and 4415073 re-introduced some Checkstyle warnings, and the Checkstyle warning threshold will be exceeded.

I'll rebase and fix them while waiting for @DanVanAtta's and @panther2's feedback.

**Comment by ron-murhammer** [comment]
@ssoloff Exactly what I was thinking. I assigned it to @DanVanAtta so he can take a look before this moves forward anyways.

**Comment by panther2** [comment]
@ssoloff 

> If possible, I'd appreciate if you could test this to verify that your original issue is fixed by this PR. Are you able to build TripleA from source? Unfortunately, I don't believe Travis is configured to save build artifacts for PRs. So, if you can't build from source, I can upload a build someplace (I have a feeling a 30 MiB file is too large to attach to a GitHub issue).

I will be happy to test, but lack the ability to build from Java source code, sorry. So it would be great if you could provide the binaries. Thank you. :smiley:

**Comment by simon33-2** [comment]
@ssoloff you should be able to create a release in your own fork by going into the code tab of your fork, clicking "releases" and "draft a new release". Then it can be downloaded by others.

**Comment by ssoloff** [comment]
@simon33-2 Good idea.  I hadn't thought of **manually** creating a release.  Before I read your comment, I was going to create a new branch and have Travis automatically deploy it to my fork like I did for #1584.  Your suggestion is easier because it lacks the overhead of creating the new branch and customizing `.travis.yml` for what will, most likely, only be a single release.

@panther2 As soon as I get the build green again, I will publish a private build to my fork as @simon33-2 suggested.  I'll let you know when it's ready to test.

**Comment by ssoloff** [comment]
I fixed the violations I introduced in my previous commit.  Unfortunately, those violations were due to the legacy naming convention used in the `MapProperties` class to facilitate reflection.  I went ahead and fixed all the naming convention violations in `MapProperties` because it wouldn't have made sense to only fix those I introduced.  (I will update the PR description with this refactoring change.)

The implication of this refactoring is that the labels in the map properties dialog have changed.  As you can see below, the labels have changed from UPPER_SNAKE_CASE to CamelCase:

map-properties-maker-all-options-new-appearance

Please advise if the new labels are going to be an issue for end users.  (Note that the content of `map.properties` is **not** affected by this change.)

@panther2, the changes encapsulated in this PR are available as release [1.9.0.0-private.1261.f3576ab](https://github.com/ssoloff/triplea/releases/tag/1.9.0.0-private.1261.f3576ab) from my fork.  Please test the Map Properties Maker whenever you have time.

**Comment by panther2** [comment]
Thank you, @ssoloff , for providing the binaries. I have tested map.properties now.
At first I was a bit confused, because the arrangement of the different options has changed. But in the end I have found **most** of the options.

While these are the options in 1809


it looks like this now in 19xx_test
1900test

I noticed, that in 1809 there are five more options compared to the new test version.
I am missing these 5 options in the new version:
- Screenshot_Stats_Enabled
- Screenshot_Stats_X
- Screenshot_Stats_Y
- Screenshot_Stats_Text_Color
- Screenshot_Stats_Border_Color

I don't know if those are needed, but anyway they are missing :wink:

At least I have been able to alter the given options in the new version and to create a full map.properties file, that has been correctly saved.

HTH :smiley:

**Comment by ssoloff** [comment]
Thanks for testing, @panther2!

To address your concerns:

#### Property order
The order in which the properties are displayed is dependent on the order in which the JVM returns the available methods on the `MapProperties` class.  The [Javadocs for `Class#getMethods()`](https://docs.oracle.com/javase/8/docs/api/java/lang/Class.html#getMethods--) explicitly states the results are not returned in a deterministic order:

> The elements in the returned array are not sorted and are not in any particular order.

It's possible that when I renamed methods in my last commit, it affected this order due to the non-determinism.  If you compare your 1.9.x screenshot to [mine](https://cloud.githubusercontent.com/assets/4826349/24811609/b1bd1542-1b94-11e7-83b8-40fa9cf2db5e.png) (which are based on the exact same code), you'll see that even they differ!  At first I thought it might be a difference between the JVM on Windows and Linux, but it's also just as likely that it is due to you and I using different locales (German vs. English).

It would be easy to sort the properties in lexicographical order before they are displayed.  That would ensure they are always in the same (relative) position in the future.  **Let me know if you think that is a worthwhile change.**

#### Screenshot stats properties
These were removed in #529, so they no longer exist in the engine to be referenced by the UI.  Therefore, they will no longer be present going forward.

**Comment by panther2** [comment]
Thank you for the explanation, @ssoloff .

I think I would not have noticed the different order of the properties, if I had not compared the older with the newer version. So I would be fine if you leave them as they are now. Only in case that they might be displayed arbitrarily or unsystematically, I would vote for a lexicographical sorting.

**Comment by ssoloff** [comment]
@panther2 I added code to sort the map properties lexicographically by name.  The dialog now appears as follows:

map-properties-maker-all-options-sorted

Please let me know if you're not ok with that, and I'll revert the change.

**Comment by panther2** [comment]
@ssoloff 
That looks perfectly sorted with only one minor exception (MapHeight and MapWidth). But as these values can already be added in a step prior to this dialogue I would say this is more or less a non-issue.
So let's go with lexicographical sorting :smiley:
Thank you!

**Comment by ssoloff** [comment]
@panther2 Cool, then we'll leave this PR in its current state and on-hold until @DanVanAtta has a chance to comment on my concern why the capability to edit all these properties was removed in 75c1bf1.  Thanks for your feedback!

BTW, with respect to MapHeight and MapWidth, are you seeing something different on your box than I presented in the above screenshot?  On my machine, MapHeight appears after MapHasRelief and before MapMapBlendAlpha, while MapWidth appears after MapUseTerritoryEffectMarkers and before ScreenshotTitleColor.  That appears to be sorted correctly...?

**Comment by panther2** [comment]
@ssoloff 
Sorry for the confusion ... of course this is sorted (lexicographically) correctly. I was just referring to a feeling that MapHeight and MapWidth "belong together" thematically.

**Comment by ssoloff** [comment]
@panther2 Got it.  I agree they should ideally be grouped together, but a blind sort is what it is. 😃  Thanks for the clarification.

**Comment by DanVanAtta** [comment]
I suspect 75c1bf1 was a mistake with too large of a cleaning spree. I was also unaware of the map makers use of reflection, I thought we had it narrowed down to just a few areas. Ideally we will mark anything that is needed by reflection and then work to remove the reflection mechanism.

**Comment by panther2** [comment]
Great work, thanks!
I am going to close #1261 now.

**Pull request merged**
