### PR TITLE
Fix attatch incorrect spelling

### PR DESCRIPTION
**Pull request by DanVanAtta**
There is an interesting mix of a misspelling where the word "attach" was spelled as "attatch"

Since next release will likely see a full map refresh, it's a good time to correct this. This PR changes the word "attatch" to "attach" pretty much everywhere in the game engine. We'll need to follow up with a similar change in the maps after this is merged.

[Review on Reviewable](https://reviewable.io/reviews/triplea-game/triplea/504)

### CODE REVIEW

**Comment by gaborbernat** [comment]
Reviewed 44 of 210 files at r1.
Review status: 44 of 190 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/games/strategy/common/swing/SwingComponents.java, line 1 \[r1\]](https://reviewable.io:443/reviews/triplea-game/triplea/504#-KC-JKxPqapFb1-HZgIm:-KC-JKxQSgQSRX3FX5t1:2019121283) ([raw file](https://github.com/triplea-game/triplea/blob/f91e9c1bf3b37229a06a76a052eed79d9330881d/src/games/strategy/common/swing/SwingComponents.java#L1)):*
What's with this class, shouldn't be part of another commit?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/triplea-game/triplea/504)*

**Comment by DanVanAtta** [comment]
now rebased @gaborbernat

**Comment by gaborbernat** [comment]
The game fails to start:

```
SAXParseException: game: Battle of Aventurica, line: 1043, column: 152, error: Element type "attatchment" must be declared.
SAXParseException: game: Battle of Aventurica, line: 1364, column: 8, error: The content of element type "game" must match "(info,loader,triplea?,diceSides?,map,resourceList?,playerList,unitList?,relationshipTypes?,territoryEffectList?,gam
ePlay,production?,technology?,attachmentList?,initialize?,propertyList?)".
SAXParseException: game: Elemental_Forces, line: 731, column: 26, error: Element type "attatchmentList" must be declared.
SAXParseException: game: Elemental_Forces, line: 736, column: 134, error: Element type "attatchment" must be declared.
SAXParseException: game: Elemental_Forces, line: 739, column: 135, error: Element type "attatchment" must be declared.

```

**Comment by DanVanAtta** [comment]
@gaborbernat , that is expected for any map not included with the game. Maps included with the game should play well. Once this is merged I'll do a mass update of the map repos

**Comment by ron-murhammer** [comment]
@DanVanAtta - We should probably wait to merge this until we are close to releasing since it breaks pre-release compatibility with all existing maps.

**Comment by DanVanAtta** [comment]
@ron-murhammer  that is a costly approach. It delays testing and integration. I would much prefer we start hammering on this now to find any potential problems sooner rather than later.

Also, we are pretty close to the next release. We agreed would target February/March.

Finally, who are we specifically  impacting by breaking pre-release map compatibility on a pre-release version? I honestly don't think we are helping anyone out, so we are potentially adding to our development and test burden with no tangible benefit.

**Comment by ron-murhammer** [comment]
@DanVanAtta Essentially, we can't use the pre-release to play any maps if we merge this until maps XMLs are updated with 'attach' instead of 'attatch' and re-downloaded. Pretty much all testers are blocked until that is completed. My point is we need to try to coordinate merging this with updating all the map XMLs.

**Comment by ron-murhammer** [comment]
@DanVanAtta I'd say when you are ready to update all the maps replacing attatch with attach then I'm good to merge this.

**Comment by DanVanAtta** [comment]
Okay, maps are all updated or a PR is in flight to update them. We'll need to advance the map versions in triplea_maps.yaml to pick up the new map versions. Will be working on a script to help with that task.

**Comment by ron-murhammer** [comment]
@DanVanAtta I'm good with this and #545.

**Comment by ron-murhammer** [comment]
@DanVanAtta Actually hold off on this. Won't this actually break all existing save games?

**Comment by DanVanAtta** [comment]
Parse exceptions are the problem when loading a save game, notably not a serialization exception.

There are already a number of smaller problems with the map migration, for example the "too many maps found", and double listing / casing issues. 

This migration is looking messy as is. I really think this is perhaps the best time if any to have a clean cutover from one version to another. Players are used to playing old saves on old versions, that's something I observed (unnecessarily) since about 1.8.0.3, and really saw a lot of it from 1.8.0.7 to 1.8.0.9 

I recommend we update the engine to use a new maps folder location. As discussed that has the side benefit that people can play out old map saves, since we will be asking that old maps be cleaned out.

**Comment by DanVanAtta** [comment]
Also for consideration. Rolling back the maps is possible, but it would be nice to not roll them back to eventually one day redo this change. Plus, it's hard to think of a better future date where we would want to redo it. Living with the inconsistency is very painful, we have both spellings as keys, and you just have to know which one to use.

**Comment by ron-murhammer** [comment]
@DanVanAtta I tend to agree that a new maps folder is probably the best way forward given some of the challenges. One thing we'll need to test is whether the game will properly launch an old jar, point to the old maps, and allow a user to play an old save.

**Comment by DanVanAtta** [comment]
Proceeding with merge for the "attatch" mispelling fix.

**Pull request merged**
