### PR TITLE
Added New World Order Variants

### PR DESCRIPTION
**Pull request by RogerCooper**

### CODE REVIEW

**Comment by Cernelius** [comment]
I understand that what you already added is this repository:
https://github.com/triplea-maps/New_World_Order_Variants
However, New World Order already had a number of variants, in this other repository:
https://github.com/triplea-maps/nwo_variants
Beside other specific variants of the same map, namely:
https://github.com/triplea-maps/new_world_order_lebowski_edition
https://github.com/triplea-maps/new_world_order1915lebowski

So, are you sure you want to have a map called "New_World_Order_Variants" when you already have a map called "nwo_variants".

By the way, what are the current naming conventions for maps? Where are they documented? For example, I seem to remember it was mandatory all being lower case, is it not now?

**Comment by Cernelius** [comment]
Here "nwo" is lower case:
https://github.com/triplea-maps/nwo_variants
and here it is upper case:
https://github.com/triplea-maps/NWO_Andrews

**Comment by RogerCooper** [comment]
I had submitted this as "New_World_Order_Variants". I know the casing is inconsistent, but I am generally posting other people's mods with minimal changes and I usually follow the style used by the mod creator. Feel free to make any changes you need to bring this into the repository.

**Comment by RogerCooper** [comment]
It might be better to just rename this "New_World_Order_Neutrals".

These general "*variants" mods have some issues. Can I an add a scenario into someone's else's "variants" mod?  Just because someone has downloaded a mod with some variants, doesn't mean they want every variant.

Another problem with 2.6 is that I need to copy over all the images, rather than having an XML-only mod that refers back to the original mod and gives an opportunity to download it.

**Comment by beelee1** [comment]
@RogerCooper  it says the yaml formatting failed. I think Cernel is right as the only thing I can find different is the upper case. The map name obviously can be upper case and you don't need the underscores, at least i don't see any other maps done that way.

maybe rename repo and try lower case

**Comment by RogerCooper** [comment]
I had forgotten to publishe the mod before adding to the yaml. That may have caused the failure. It is published now.

**Comment by Cernelius** [comment]
I'm just mostly saying that, in the moment TripleA has a map called "nwo_variants", if one wants to add more variants of New World Order, it seems logical to me to add such variants to the mentioned map, rather than adding a map called "New_World_Order_Variants". If the variants are too special, so they cannot be bundled together, I would say they deserve a more specific name, instead.

Unfortunately, I don't believe there are guide-lines about what makes a map derived from an other map a "variant".

**Pull request closed without merging**
