### PR TITLE
Remove Map Name Dependency

### LINKED ISSUE #1436: Map name and location should not rely on map folder name
Interesting case in: https://github.com/triplea-game/triplea/issues/1334

A map was downloaded and 'II' was converted to a different character. From then on there were errors loading the map since the map name did not match the map folder.

### PR DESCRIPTION
**Pull request by simon33-2**
Makes map names basically redundant. Had some test errors so decided to make the search for maps highly forgiving. Everything which currently works should work but what should also work is having a zip/repo with capitals in it, for example. Resolves #1436.

### CODE REVIEW

**Comment by simon33-2** [comment]
Tested this in a local and networked game but not sure how to test for a headless server?

**Comment by ron-murhammer** [comment]
@veqryn Is there any reason this wouldn't work? Just not sure on the history of the map name parameter.

**Comment by veqryn** [comment]
What does this PR do?


map name exists i think to allow separation of the "game" from the "UI".  This allow map skins, and it also allows game "mods", which are just a different game XML in a separate folder (separately zipped and separately distributed) but which point to the "main" game for all stuff they might need.

**Comment by simon33-2** [comment]
What does it do? It adds a few more possibilities searched in filenames. At present, if you have a repository with capital letters, the built zip file doesn't work. There's been a few problems caused by this one alone. There's also the issues of foreign language character mangling causing a mismatch between repository names. These issues are annoying and a hassle to fix.

I actually think these issues were created in 1.9 but I'm open to correction on that point.

**Comment by veqryn** [comment]
Can you give an example of the problem with capital letters, just so I can see better what you mean?
An example for the foreign language character mangling would be great too.

**Comment by simon33-2** [comment]
The foreign language one was two clicks away, in #1334.

Obviously, we've fixed all the ones with capital letters that we are aware of.
Here's an example of confusion caused: https://github.com/triplea-maps/Project/issues/64

There was also an issue with a map repo created with upper case characters in the name, now: https://github.com/triplea-maps/global_1940_redesign_house_rules

These issues are really frustrating because they work if you point your map directory at the directory you did a "git clone" in, as all right thinking people would. Then they don't work when users download the map.

**Comment by veqryn** [comment]
Ok, so a few more questions/comments:

1. If the map-name field gets removed, how do you plan to allow game 'mods' that reference a different folder than the folder they are downloaded in?
For example:
I have a folder called `world_war_ii_v3` which contains the standard games for v3 (ie: there are several game xml's in it, as well as all the artwork, assets, tiles, etc).
I also have a separate folder called `my_v3_mods`, which contains some game mods (ie: it just contains the game xml's, and they point to map-name `world_war_ii_v3` so that they can pull all the assets from there).
And I might also have a folder named `world_war_ii_v3-skin1` which contains no game xml's, but only different art assets, which should still be switchable to in the menu's when playing both the standard v3 games and the v3 mods.

2. It sounds like if people have mis-matching case, that should be fixed rather than making the engine more lenient.  People are having to move the code bases and maps over to github, and it can be fixed as they are moved.

3. If maps are being downloaded and then being renamed, then it sounds like the code that downloads and names the folders/files is at fault and should be fixed.

**Comment by simon33-2** [comment]
1. Support for that would be dropped with this pr. For adding negative value. What is the reason why this is needed and you can't update the map after download? 

2. Non-lower case is not supported in 1.9 for zipped files at all at present. Just doesn't work. There is more than one way to skin this cat, but what I have proposed would work.

3. Looks like forcing lower case was done quite intentionally.  I don't quite understand why you were prodded for comment if this was done without your knowledge.

**Comment by veqryn** [comment]
2. If that is the new requirement, then maps should be adjusted to this.  Lets not introduce more hacks.

3. If it was done intentionally, why make a hack to undo it on the game parsing side?

**Comment by veqryn** [comment]
1. That sounds like a major setback.

The game xml's and the game's assets are currently separate in the engine.
They are often distributed together, but many times they are not.
Skins are distributed separately.
Game XML Mods are distributed separately.  Many of the more popular games and mods are distributed in this way.
You are tying these back together, and I would say that is not a good move.

You ask, why couldn't you update the map after download?
The answer is that you are not updating the map, you are creating your own mod for the map.  And you would probably like to distribute it, and make updates to it, without having to worry about the original map download.
The old game download list is fully of "game mods" and "variations packs" like this.
Unless you want to include every single game xml with a given map, then it is best to leave them separate.

Example (these numbers are estimates from memory):
World War II v1 (aka: A&A Classic) is a popular map, one of the standard A&A maps, and is the original map that TripleA was created to play (https://sourceforge.net/projects/tripleamaps/files/maps/World%20War%20II%20Classic.zip).
The distribution (the zip file) of it contains the map's art assets (ie: tiles, unit graphics, etc), as well as 1-3 main game xml's that are the standard A&A games.
When someone goes into their game list, those 1-3 main game xml's are what they see as "playable games", with the folder and zip file being irrelevant at that point.
In addition to those main game xml's, there is a separate distribution of around 15 game xml's for popular mods of A&A Classic (https://sourceforge.net/projects/tripleamaps/files/maps/Classic_variations.zip).
These "classic variations" games were are separate because:
a) They were maintained by someone different than the maintainer of the main "World War II Classic".
b) They are updates separately than the main zip.
c) They are non-standard mods, while the games included in the main zip are only standard games.
d) Most people who want to play World War II Classic do not want their game list polluted with 15 games that they don't care about.
e) Curation on the main zip is very high, but there is no need for curation on a zip of mods and variations.


I think it is a good idea to continue the path of keeping game xml's and their art assets separate (or at least separable).

This PR would tie them together again, as a hack to fix a mostly unrelated issue that was created by moving maps to github.

Therefore, I do not think this PR is a good idea.

**Comment by simon33-2** [comment]
Ok - what do you suggest then?

**Comment by simon33-2** [comment]
Aren't you therefore saying that you also disagree with what was suggested as in issue in #1436 is in fact an issue?

**Comment by simon33-2** [comment]
I suppose it would be possible to keep the mapName property and just add to the list of search paths. Would that make everybody happy?

**Comment by veqryn** [comment]
When maps are uploaded to the new system (github, etc), some other things have to change to them right?
Such as converting `attatchment` to `attachment` in the game xml, and maybe some other stuff?

So, why not just correct the contents of the mapname field as part of being uploaded to github?
I feel like that is probably the best long term fix as it is a one time fix per map, keeping everything standardized.

**Comment by simon33-2** [comment]
Ok, I'm happy to drop the removal of the mapName property and just make it much more forgiving.

Probably, there was too much going on in this PR anyway. I'll log a new one.

**Pull request closed without merging**
