### PR TITLE
Last chance to get it right the first time

### PR DESCRIPTION
**Pull request by beelee1**
for a while anyway : )

## Functional Changes

[X] New map or map update
[ ] New Feature
[ ] Feature update or enhancement
[ ] Code Removal
[ ] Code Cleanup or refactor
[ ] Configuration Change
[ ] Bug fix
 

## Testing

[ ] Covered by existing automated tests
[ ] Covered by newly added automated tests
[ ] Manually tested
[X] No testing done

### CODE REVIEW

**Comment by DanVanAtta** [comment]
I updated the PR checklist to indicate this is a map update.

The image file referenced in the new config does not exist. There does exist:

`https://raw.githubusercontent.com/triplea-maps/charles_de_gaulle_1939/master/description/charles_de_gaulle_1939.png`

The file referenced in config is:
`https://raw.githubusercontent.com/triplea-maps/charles_de_gaulle_1939/master/description/TripleA_charles_de_gaulle_1939_mini.png`

Perhaps the "_mini" version was not uploaded?

**Comment by beelee1** [comment]
yea just read the error. Must've screwed up the image. I'll give it another go. Thanks

**Comment by DanVanAtta** [comment]
Heading to bed here, rest of the config update looks good @beelee1

**Comment by beelee1** [comment]
well I'm gonna close this and try again. I added a new description with the correct name but the patch thing doesn't seem to recognize it

**Pull request closed without merging**
