### PR TITLE
[PropertyUtil XML Property Loading]  Don't always assume properties begin with 'm_'

### PR DESCRIPTION
**Pull request by DanVanAtta**
Update PropertyUtil to check for a second Java class property name based on what is coming from XML. Rather than always prepending 'm_', we will also check if the non 'm_' version of the property name exists

[Review on Reviewable](https://reviewable.io/reviews/triplea-game/triplea/465)

### CODE REVIEW

**Comment by ron-murhammer** [comment]
@DanVanAtta - Is there any way we could write a unit test for this? Essentially, I don't think there is really any way to test that it works currently.

**Comment by DanVanAtta** [comment]
I'll give it a look. It's something that I will probably not spend too long on though. Any significant time would be better to get rid of the reflection and have an explicit object to XML property mapping. Said another way, if we spend significant time on this I'd rather get rid of the component entirely with something more robust

**Comment by DanVanAtta** [comment]
Now unit tested :+1: 

Learned the following:
- PropertyUtil reflective set is done by calling the setter method of the variable.
- PropertyUtil getter uses reflection to read private variable values directly. It was our code that prefixed the "m_", and the test successfully caught that as an error

**Comment by gaborbernat** [comment]
Reviewed 1 of 1 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/triplea-game/triplea/465)*

**Comment by gaborbernat** [comment]
the tests are great addition!

**Pull request merged**
