### PR TITLE
Highlight empty bots

### PR DESCRIPTION
**Pull request by RoiEXLab**
Per https://forums.triplea-game.org/topic/342/highlight-waiting-for-players-on-lobby-games
A really good and easy-to-implement idea IMO, the color isn't final
screenshot

### CODE REVIEW

**Comment by DanVanAtta** [comment]
Interesting idea. Overall, I'd like for us to establish a plan for what an end-vision would look like. Highlighting empty bots all the time might not be ideal. There is for certain a use case of "I need an empty" bot that this would help satisfy. I think solving that use case would go in hand in hand with the use case "has anyone hosted but not yet started a game?". An add-on to that would be map preferences, then dice preference as well. Sometimes as well people are interested in specific hosts, and whether you have a save game vs that person.

I think at question most is how someone would turn on and off these features, and how we could also present some additional filters without things being cluttered. A drop down with a set of check boxes and hot keys assigned might work. A pull out panel menu from the side of the screen could also be an option, just as well as some more old school menu bar checkboxes.

**Comment by prastle** [comment]
@RoiEXLab @DanVanAtta  some ideas were added here 
https://forums.triplea-game.org/topic/342/highlight-waiting-for-players-on-lobby-games

**Comment by RoiEXLab** [comment]
Closing until we work out a final idea.
Once we agreed on something I'll submit a fresh PR.

**Comment by Heppisorus** [comment]
lobby layout

Here's some food for thought.

First... I think we could eliminate EV (Engine Version) column as it seems truly redundant since you can only be on one version.

Second... I think we can eliminate the B (Bot) column since each Bot is labelled a Bot in the Host column.

The rest is really just building on some of the thoughts floating around already.  

Highlighting game currently waiting for players... which should really only be highlighted if there are any players in the Bot or host at all.

Adding a series of icons you can select for the Settings box.  Low Luck... Dice... Tech... no Tech... etc.

And a Tourney box to identify games that are part of an ongoing tourney.  

Just some idea's.

**Comment by Heppisorus** [comment]
To be honest the suggested "Settings" Column should have icons that auto populate based on the selections you have made in the Bot and in the "Map Options" windows.  However I was hesitant to suggest this as I don't know if all the maps have things like "Bid Phase" included inside the map themselves.  Thus potentially causing issues for the Setting box if you cannot manually input certain parameters.  Nor was I sure how much work would be involved in such a venture.

**Comment by Heppisorus** [comment]
Last point I have always wondered about is the value of the "Started" column.  I have personally never looked at it and I have never understood how it is a pertinent or valuable item.  I generally look at the: game type, number of players and the round they are in.  Seems to me as though we could eliminate that column as well in order to accommodate far more valuable and pertinent information. 

That being said, I have no idea whether it means anything to anyone else who plays on the lobby.

**Comment by Heppisorus** [comment]
Bearing in mind my motivation to remove the Started column are based on the need for clarity and space for move important info., rather than for more nefarious motives of organized gambling businesses.

**Comment by DanVanAtta** [comment]
Also a good suggestion I think to remove the 'started' column. I vaguely recall once or twice it being useful, but you can infer how long a game has been running by the game round. The kicker for me is that I don't believe the time zone info of started is correct, I've the perception that time zones are mixed in the display, so it's hardly useful from that perspective. Rather than fix/verify time zones, would make sense IMO to whack the column instead and remove it.

**Comment by Heppisorus** [comment]
Here is a more refined version of my thoughts for the use of space if we remove some of the less important and redundant information.
lobby layout 2

Couple follow up things to consider about these proposed changes...

1) Adding the names of the players currently in a game will achieve 2 things... a) It will eliminate people joining and leaving games frequently trying to find friends. b) It will make the MODS job much easier when trying to boot ghost players and tract down trouble makers and trolls.

2) The fixed icons for game feature could have a hover feature so that when you hover over the icons it would tell you what they are... ie. "Scramble rules in effect".

I realize this might all seem ambitious... so take the suggestions for what they are worth.  Just throwing idea's out there to cultivate more thought around what would be great features for all of us.

**Comment by RoiEXLab** [comment]
@Heppisorus It's a shame you aren't part of the developer team ^^
I really like your suggestion, hover overlays will be tricky, but the rest should be feasible to implement (I don't know how much information we have about the bots before actually joining them, might require some breaking changes)

**Comment by Heppisorus** [comment]
I wish I had the skills to pay the bills. I am as much part of the development team as I can be at this point. I am purely an idea man. I have no technical skills what-so-ever.

That being said... I can do graphics. So I am at the teams disposal for any and all graphics related needs. Your wish is my command.

As far as changes... I think changes that break things need to weighed between their value to enrich the environment and experience... and the level of inconvenience it will cause. If the result is a positive... then all that is needed is very clear communication to the community that changes will affect outstanding games... then a (generous) deadline is imposed that people are expected to accept.

I am a long term thinker... so for me its about being realistic. Something like an update that breaks compatibility needs maybe an 8 month window. If you can't finish a game in 8 months... well really? You clearly aren't that passionate about playing anyways. The remainder comes down to something like implementing a countdown in the Lobby. A ticker for each day so that no one can complain when the change occurs.

Anyways, please feel free to reach out to me whenever you want. I am always willing to help where I can... and (as you are well aware) I am willing to proffer my opinion on anything I have one about. =)

Sincerely, Hepps

**Comment by Heppisorus** [comment]
BTW an easy work around (or even in-term solution) to the hover issue is to simply put a guide inside the help tab. 

Realistically if we do a good job of making the icons visually identifiable to translate to a rule or setting (my examples are very quick and rudimentary ) ... then it would mean that people will grow accustom to their meaning (and position) fairly quickly.  It would only be for some of the games with many variable settings (ie. Global) that people would ever really have to reference the chart.

Realistically we don't need any info on unoccupied Bots.  Their settings can disappear if no one is in them.

**Comment by beelee1** [comment]
Like the only highlight when people are actually waiting Hepps.  I Know their is a lot that can be improved but would be nice to see this for starters while the rest gets hashed out.

**Comment by beelee1** [comment]
Here's a latest thought

Was thinking that you could have the games that someone is in and looking for players be as follows:

Using Global 40 colors

Canadian Red = Expert

French Blue = Intermediate

UK Khaki = Novice

Would be nice to use the underlayer ? like it looks in the map so it doesn't appear cartoonish. Or maybe the writing would be enough to prevent that.

Then use USA Green for games that are in progress. Leave the games with nobody in them the way it is now.

Just a thought : )

**Comment by prastle** [comment]
Keep it alive @beelee1

**Pull request closed without merging**
