### PR TITLE
Change log updates

### PR DESCRIPTION
**Pull request by DanVanAtta**
[Review on Reviewable](https://reviewable.io/reviews/triplea-game/triplea/518)

### CODE REVIEW

**Comment by DanVanAtta** [comment]
FYI @ron-murhammer  @gaborbernat , added a few commits from the two of you. The text on the change log is a bit rough, but at least a lot of the key changes have been added.

**Comment by gaborbernat** [comment]
I think we should group the changes, per domain, such as see all AI related enumerated, then game interface, and so on :) 

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved, some commit checks broke.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/triplea-game/triplea/518#-:-KC-GNjyiNAcLJ8pMEwQ:-336110452)*

**Comment by gaborbernat** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks broke.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/triplea-game/triplea/518)*

**Comment by DanVanAtta** [comment]
I agree, it's a bit tough to go through the list, could use grouping.

**Pull request merged**
