### PR TITLE
Rename "seperate" -> "separate"

### PR DESCRIPTION
**Pull request by ssoloff**
## Overview

Renames all misspellings of the root word _separate_.

## Functional Changes

None.

## Manual Testing Performed

None.

### CODE REVIEW

**Comment by RoiEXLab** [comment]
Hmm LGTM.com seems to have some problems with the PR. Should we just ignore it?

**Comment by RoiEXLab** [comment]
Correction: It seems to have a problem with the Base commit, your other PR is confusing it as well

**Comment by ssoloff** [comment]
The error from the LGTM log is

```
ERROR: Commit does not exist: a90260e5b90fe491d30936458a45bd4818526f0d > Missing unknown a90260e5b90fe491d30936458a45bd4818526f0d
```

Since a90260e5b does indeed exist, my guess is LGTM's incremental build process is not keeping up with the latest repo state.  No objection to skipping the LGTM analysis on my two active PRs, as they are basically just renames.

**Comment by RoiEXLab** [comment]
Yup, indeed looks like the website is out-of-date.
Screenshot

Ignoring this for now, maybe something @xcorail should know about 🤷‍♂️

**Comment by xcorail** [comment]
Hey folks,
Thanks for letting me know @RoiEXLab !

> Hmm LGTM.com seems to have some problems with the PR

We indeed had a problem with the PRs yesterday. It has been solved by now, and your PRs have been analyzed, as you can see in https://lgtm.com/projects/g/triplea-game/triplea/ci/

> Yup, indeed looks like the website is out-of-date.

The Overview page and the Integrations page (showing the PRs) are based on different data, this is why your more recent commits don't appear in the Overview, but appear in the PR view.

For a quicker answer, and a better time zone coverage, don't hesitate to use our [community forum](https://discuss.lgtm.com/). For example: https://discuss.lgtm.com/t/lgtm-seems-to-be-failing-with-bad-exit-code-during-checkout/1618
(But you can still tag me, no problem)

Cheers

**Pull request merged**
