### PR TITLE
Remove ant build

### PR DESCRIPTION
**Pull request by DanVanAtta**
This PR branch is based on #101
Gradle is at the point of no return (feature parity except for DMG build and now baked into the build/release process)

Was trying to see about removing the junit folder, found the file only used by ant, and we don't need the ant file anymore.

[Review on Reviewable](https://reviewable.io/reviews/triplea-game/triplea/108)

### CODE REVIEW

**Comment by ron-murhammer** [comment]
@DanVanAtta I disagree with removing the ant build at this point. I'd prefer to just keep it around until we successfully do the next release with gradle to ensure that we keep both functional. It may involve a little more work but I'd rather be safe than sorry.

**Comment by DanVanAtta** [comment]
Having seen build artifacts be automatically built and pushed with gradle, this is not needed. In the meantime it causes pain and needless work. If we are sorry we can look into the git history. We will not be sorry though. Again, all ant functionality except for DMG has been verified and replaced in gradle. The DMG in ANT is Java 6 only, we will not support it, so we need to throw that away anyways. So there is nothing to even to refer back to even anymore.

**Comment by DanVanAtta** [comment]
Meanwhile, it is a user complaint that the packaged distribution package is a jumble of files, so cleaning up these files and removing them is of value to users (and us as well since we wont' spend time on unneeded filed, like the hours already spent on fix_mac_icon.sh which is still waiting to be removed in another PR).

**Comment by ron-murhammer** [comment]
I would still prefer to keep the ant build functional until we have the successful release with gradle just in case.

@veqryn what are your thoughts? I'll leave it up to you as I've stated my concerns.

**Comment by DanVanAtta** [comment]
Once we have something merged so that gradle can build the all platforms zip and preferably the windows installer, then would be a good time to merge this. I agree that merging this now and having neither gradle nor a working ant build is not great. This work is probably better viewed in the context of: #106 , in that pull request not only does gradle build artifacts (zip and windows installer) but they are automatically pushed. This was PR was requested not long after that one, so from an independent perspective this is pr, #108 is a bit weird.

**Comment by veqryn** [comment]
We can remove the ant script in a couple months, after we know gradle is working and is a complete replacement for everything that ant used to do.

**Comment by DanVanAtta** [comment]
Why arbitrarily state a couple of months? Particularly when we have a gradle script that does do the replacement today. Only issue is that you guys haven't been willing to try it out.

**Comment by veqryn** [comment]
Correction: Haven't been willing to try it out for the stable release.

This by design, and our every intention: that part of accepting a lot of these new changes was that we would have a final stable release under the old system.

There have been a couple of issues with that release, and I would like the ant build script to remain in the repo for a little while longer so we can see that noone has any further issues with our release.

**Comment by DanVanAtta** [comment]
I've stated already this PR merge makes more sense after  work was done with gradle is merged. 

Also please see the issue opened about stable and non-stable releases. The concept may have been useful in the source forge days. I will for one say, I will *never* release code I think is unstable. I only push code that to the best of my knowledge and ability at the time, is stable. Developers have a rule number one, and that is don't break stuff. WE have a development process to ensure that, that over time the process has been proven to increase velocity and reduce defects. So the idea of having a release is unstable, is like saying, "we intentially didn't follow development process in this release and broke a bunch of stuff which we will be fixing now in the next release."

I'm going to close this since it is now only being taken out of context.

**Pull request closed without merging**
