### PR TITLE
Rename 'TripleA Map XML Creator' -> 'TripleA XML Creator'

### PR DESCRIPTION
**Pull request by DanVanAtta**

### CODE REVIEW

**Comment by DanVanAtta** [comment]
Just proposing a string change for now. I would not have thought for the class and package name to also be tied to the string value as well.

**Comment by ssoloff** [comment]
I don't know if this PR is related to this [discussion](https://github.com/triplea-game/triplea/issues/1860#issuecomment-307738782) in #1860, but should the button label under **Engine Preferences** be changed to "Run the XML Creator", as well?  Or are you already doing that as part of #2137?

**Comment by DanVanAtta** [comment]
Not quite related to #1860, the rename on this branch was suggested in #2137.

**Comment by ssoloff** [comment]
Got it.  Hadn't made it [this far](https://github.com/triplea-game/triplea/pull/2137#issuecomment-318792992) in the #2137 comments yet. :smile:

**Pull request merged**
