### PR TITLE
Bumping version on Global 1940 Redesign

### PR DESCRIPTION
**Pull request by beelee1**
Fixes map name so it will upload

### CODE REVIEW

**Comment by ssoloff** [comment]
@beelee1 Just want to confirm...  Is the version bump to account for [this commit](https://github.com/triplea-maps/global_1940_redesign_house_rules/commit/7ee8fc059c31220d6fc169fa35617fbaa0c45312) from April 2017?

**Comment by beelee1** [comment]
@ssoloff no there's a PR to [https://github.com/simon33-2/Global_1940_Redesign_HouseRules](url) that has to merge. Sorry i should have noted that. 

I guess proper procedure is to wait for that PR to merge before I create this one ?

**Comment by ssoloff** [comment]
> I guess proper procedure is to wait for that PR to merge before I create this one ?

Not necessarily.  I've seen map makers submit the YAML change with a note to "wait until PR such-and-such is merged."  But, yes, it is probably easier to just wait until that's already happened to avoid any confusion or premature version bumps. :smile:

**Comment by beelee1** [comment]
right on Thanks

**Pull request closed without merging**
