### PR TITLE
Cleanup tuv utils

### PR DESCRIPTION
**Pull request by ron-murhammer**
No functional changes.

- Fix checkstyle configuration error
- Address checkstyle violations in TuvUtils
- Add private constructor

### CODE REVIEW

**Comment by ron-murhammer** [comment]
@ssoloff Looks like Travis doesn't like the checkstyle path change I made. Thoughts on how to fix that?

**Comment by ssoloff** [comment]
@ron-murhammer Can you provide some background on why the path change was needed?  Did something change recently that broke this?

I went through a bunch of different configuration paths in #2025 and eventually settled on the absolute path from the repo root because none of the candidates that used some kind of macro worked both in Gradle and the IDE.

**Comment by ron-murhammer** [comment]
@ssoloff Checkstyle hasn't worked for me since the suppressions file was added. Just hadn't gotten around to trying to fix it til now. The absolute path doesn't seem to work and get can't find file.

**Comment by ssoloff** [comment]
@ron-murhammer I'm going to check out your branch to verify `${samedir}` doesn't cause any problems in my Eclipse environment.  I suspect it won't, but I'd like to make sure before we proceed down this route. :smile:  Might also have to have @DanVanAtta verify it works in IntelliJ.

In the meantime, see if you can use [`configProperties`](https://stackoverflow.com/questions/29602867/using-samedir-in-checkstyle-plugins-for-gradle-and-eclipse) to fix the Gradle build.

**Comment by ron-murhammer** [comment]
@ssoloff Pushed the fix and seems to work :)

**Comment by ssoloff** [comment]
@ron-murhammer Confirming that `${samedir}` works fine for me within Eclipse.  I think this is much cleaner than the repo-relative path. :+1:

One suggestion on the Gradle build script... it might be cleaner to re-use the `checkstyle` configuration's `configFile` property to get the config file directory.  I tried the following, and it seems to work:

```
configProperties = [samedir: configFile.parent]
```

**Comment by ron-murhammer** [comment]
@ssoloff Good idea. Gradle build seemed to work with that change for me locally. Guess let's see if the Travis build passes again.

**Pull request merged**
