### PR TITLE
Keep Junit launcher at 1.5.2

### PR DESCRIPTION
**Pull request by DanVanAtta**
With higher versions, IDEA can no longer run tests and
encounters an error:

```
org.junit.platform.commons.JUnitException: TestEngine with ID 'junit-vintage' failed to discover tests
Caused by: org.junit.platform.commons.JUnitException: Failed to parse version of junit:junit: 3.8.2
```

## Functional Changes

[] New map or map update
[] New Feature
[] Feature update or enhancement
[] Feature Removal
[] Code Cleanup or refactor
[] Configuration Change
[x] Problem fix:  
[] Other:   

## Testing
Verified this version is the difference between being able to run tests and not.

### CODE REVIEW

**Comment by RoiEXLab** [comment]
Any chance you found an issue for this somewhere, so we can keep track of it?

**Comment by DanVanAtta** [comment]
Haven't searched for it @RoiEXLab

**Comment by RoiEXLab** [comment]
@DanVanAtta The current test failure is interesting:
```
WARN  [2020-04-03 00:37:48,283] org.triplea.web.socket.MessageSender: Failed to send message: ServerMessageEnvelope(messageType=PLAYER_LEFT, payload={"value":"mod"})
! java.nio.channels.ClosedChannelException: null
! at org.eclipse.jetty.websocket.common.io.FrameFlusher.enqueue(FrameFlusher.java:109)
! at org.eclipse.jetty.websocket.common.io.AbstractWebSocketConnection.outgoingFrame(AbstractWebSocketConnection.java:507)
! at org.eclipse.jetty.websocket.common.extensions.ExtensionStack$Flusher.process(ExtensionStack.java:400)
! at org.eclipse.jetty.util.IteratingCallback.processing(IteratingCallback.java:241)
! at org.eclipse.jetty.util.IteratingCallback.iterate(IteratingCallback.java:224)
! at org.eclipse.jetty.websocket.common.extensions.ExtensionStack.outgoingFrame(ExtensionStack.java:277)
! at org.eclipse.jetty.websocket.common.WebSocketRemoteEndpoint.uncheckedSendFrame(WebSocketRemoteEndpoint.java:307)
! at org.eclipse.jetty.websocket.common.WebSocketRemoteEndpoint.sendAsyncFrame(WebSocketRemoteEndpoint.java:241)
! at org.eclipse.jetty.websocket.common.WebSocketRemoteEndpoint.sendStringByFuture(WebSocketRemoteEndpoint.java:404)
! at org.eclipse.jetty.websocket.jsr356.JsrAsyncRemote.sendText(JsrAsyncRemote.java:176)
! ... 7 common frames omitted
! Causing: java.util.concurrent.ExecutionException: java.nio.channels.ClosedChannelException
! at org.eclipse.jetty.util.FutureCallback.get(FutureCallback.java:122)
! at org.eclipse.jetty.util.FutureCallback.get(FutureCallback.java:30)
! at org.triplea.web.socket.MessageSender.sendMessage(MessageSender.java:27)
! at org.triplea.web.socket.MessageSender.lambda$accept$0(MessageSender.java:19)
! at org.triplea.java.Interruptibles.lambda$await$0(Interruptibles.java:41)
! at org.triplea.java.Interruptibles.awaitResult(Interruptibles.java:78)
! at org.triplea.java.Interruptibles.await(Interruptibles.java:39)
! at org.triplea.web.socket.MessageSender.lambda$accept$1(MessageSender.java:19)
! at java.base/java.lang.Thread.run(Thread.java:834)
WARN  [2020-04-03 00:37:48,351] org.triplea.modules.chat.ChatMessagingService: Messaging service error processing request, sending error message to client
! java.io.IOException: Broken pipe
! at java.base/sun.nio.ch.FileDispatcherImpl.writev0(Native Method)
! at java.base/sun.nio.ch.SocketDispatcher.writev(SocketDispatcher.java:51)
! at java.base/sun.nio.ch.IOUtil.write(IOUtil.java:182)
! at java.base/sun.nio.ch.IOUtil.write(IOUtil.java:130)
! at java.base/sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:496)
! at org.eclipse.jetty.io.ChannelEndPoint.flush(ChannelEndPoint.java:264)
! ... 16 common frames omitted
! Causing: org.eclipse.jetty.io.EofException: null
! at org.eclipse.jetty.io.ChannelEndPoint.flush(ChannelEndPoint.java:284)
! at org.eclipse.jetty.io.WriteFlusher.flush(WriteFlusher.java:393)
! at org.eclipse.jetty.io.WriteFlusher.write(WriteFlusher.java:277)
! at org.eclipse.jetty.io.AbstractEndPoint.write(AbstractEndPoint.java:380)
! at org.eclipse.jetty.websocket.common.io.FrameFlusher.flush(FrameFlusher.java:264)
! at org.eclipse.jetty.websocket.common.io.FrameFlusher.process(FrameFlusher.java:193)
! at org.eclipse.jetty.util.IteratingCallback.processing(IteratingCallback.java:241)
! at org.eclipse.jetty.util.IteratingCallback.iterate(IteratingCallback.java:224)
! at org.eclipse.jetty.websocket.common.io.AbstractWebSocketConnection.outgoingFrame(AbstractWebSocketConnection.java:509)
! at org.eclipse.jetty.websocket.common.io.AbstractWebSocketConnection.close(AbstractWebSocketConnection.java:184)
! at org.eclipse.jetty.websocket.common.io.AbstractWebSocketConnection.onFillable(AbstractWebSocketConnection.java:452)
! at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305)
! at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
! at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:117)
! at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:698)
! at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:804)
! at java.base/java.lang.Thread.run(Thread.java:834)
```

I assume it doesn't happen all the time, that's why I didn't restart the build

**Comment by DanVanAtta** [comment]
@RoiEXLab  created https://github.com/triplea-game/triplea/issues/6133 for the build failure

**Pull request merged**
