### PR TITLE
adding .gitattributes

### PR DESCRIPTION
**Pull request by veqryn**
[Review on Reviewable](https://reviewable.io/reviews/triplea-game/triplea/134)

### CODE REVIEW

**Comment by DanVanAtta** [comment]
Why should any files have DOS line endings? They do nothing except hurt shell scripts and grep commands and other standard file operations. It's easier and less error prone to just remove them all and don't introduce them.

**Comment by veqryn** [comment]
So, some of our users are on windows, and they should be able to open those files and edit them.
Using windows notepad, without carriage returns, these files open as a single line, which is completely unreadable.

**Comment by DanVanAtta** [comment]
Same thing could be said about DOS line endings and VI and unix users. Not only that but DOS line endings break command line tools like grep (ie:  egrep -c "$" file.txt, will return the wrong value)

Is there actually a use case where notepad is required to edit a file? To boot, notepad will add DOS line endings to files automatically. Last, I haven't had that same experience with notepad. @ron-murhammer mentioned as well that he opened files in notepad with DOS line endings stripped and had no problem (now if you have only ^M, it'll look okay in windows, but that file will be completely broken in any other  editor. So the only case I can think of where notepad would render incorrectly is a case that would not redner well on anywhere but notepad. Now if you have \n^M, and then remove the ^M, notepad shoudl still be okay).

**Comment by DanVanAtta** [comment]
With all that said, this I don't think will hurt. To audit for DOS line endings, I think we are creating a lot of work by creating rules where some files can have them. It also doesn't address that some editors will not introduce them, meaning if I edit a line in a file, then we'll have a mix of characters. So only  reasons really for getting rid of DOS line endings, I've yet to know of *any* slightly valid reason for having a DOS line ending in teh year 2015.

**Comment by veqryn** [comment]
This isn't a unix/mac only world.  Yes, I would like it if Windows switched to just LF, but it isn't.
I remember when I first joined the project a decade ago, and couldn't figure out why some files had their entire contents on a single line.
Also, the reason redrum's notepad was fine, was because his local copy had carriage returns (git's fault, which why we have this PR).

**Comment by DanVanAtta** [comment]
This also isn't a windows only world too. Do we prefer for notepad to work, or grep?

**Comment by gaborbernat** [comment]
There is a middle road here, what at release time we convert the required
files to either Windows/UNIX endings depending on the release type. That
way in git it can bee without CR as recommended by git, and in the release
platform dependent. So?

Bernát GÁBOR

**Comment by DanVanAtta** [comment]
I didn't realize the concern was for files that are packaged and then viewed by end-users. Yeah, in that case, in our windows packager we should then convert those files (unix2dos rather than dos2unix).

**Comment by veqryn** [comment]
I haven't ever heard of any potential issues this causes grep.
Since carriage returns are invisible, I think this issue affects windows users more negatively than it affects linux/mac users.
I would prefer to keep carriage returns in the source and distribution for many of those files that are listed, because it makes our source more easily accessible.

**Comment by DanVanAtta** [comment]
The DOS EOL character (^M) can cause the regex "$" to sometimes fail to match end of line properly.

**Comment by ron-murhammer** [comment]
@veqryn So I think the summary here is there are a group of files that are either windows specific (.bat, .ini, etc) or need to display properly in windows (.txt, .xml, etc) that should have windows end lines since they are packaged in the artifacts.

Eventually we could consider adding steps to the build to adjust line endings but until that happens I think this is a good start. The only question I have is line 15 correct:
MacOS_users_read_this_first.txt

Don't you need a specified at the end of it like "text eol=lf"

**Comment by veqryn** [comment]
@ron-murhammer: You would be right.  Fixed.  This can be merged now.

**Comment by DanVanAtta** [comment]
@veqryn The mac user readme file needs to be on a website. Also macs shouldn't have trouble with the CRLF. So I dont' think we need an exception for it.

The reason the mac user readme file belongs on a website is that the file describes how to install on mac. But, the file is not visible until *after* mac installation (oops)

**Comment by veqryn** [comment]
I can give you access to our sourceforge web repo, if you want to put it somewhere.
How good are you at web coding?

**Comment by gaborbernat** [comment]
I can do this I think, it's quite simple :) however I would wait until
we have new installers :)

On 9/2/15, Chris Duncan <notifications@github.com> wrote:
> I can give you access to our sourceforge web repo, if you want to put it
> somewhere.
> How good are you at web coding?
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/triplea-game/triplea/pull/134#issuecomment-137195003


-- 
 Bernát Gábor
Student -  Budapest University of Technology and Economics - Computer
Engineering, M.Sc. - Budapest, Hungary
System Integrator - Gravity R&D | Rock Solid Recommendations - Budapest
office | 5-7 Expo ter | H-1101 | Budapest | Hungary

**Pull request merged**
