### PR TITLE
Remove serialization proxy framework

### PR DESCRIPTION
**Pull request by ssoloff**
As mentioned about a month ago, the serialization proxy framework relied on being able to have circular references between proxies, but the Java serialization framework does not support this requirement.  Several attempts were made to work around this by retrofitting the engine domain model, but I finally ran into a case that couldn't be resolved without breaking changes.

I started working on a second serialization proxy framework that used a two-pass architecture similar to what `GameParser` does (e.g. read/write game data objects first, then read/write the connections between them).  This seemed promising, and, over the past four weeks, I developed it far enough to get to parity with the current state of the first generation serialization proxy framework.

However, I ran into some new issues that are going to be very difficult to resolve while maintaining backwards compatibility.  I don't think it's worth pursuing any further until we make an incompatible release so that the domain model classes can be freely refactored to remove a lot of the cruft that's making this feature difficult to implement.  Therefore, as the current serialization proxy framework is broken anyway, this PR simply removes it.

None of the file deletion changes need to be reviewed.  Reviewers should simply focus on the non-deleted files under _src/main/java_.  That should only encompass a couple hundred lines.

### CODE REVIEW

**Comment by ssoloff** [comment]
Yeah, definitely not going to delete that branch; lots of good stuff in there. :smile:  It should be relatively easy to keep rebasing it to stay up-to-date.

**Comment by DanVanAtta** [comment]
Sad to hear, but interesting and may not that much of a set back. This work was done in a backward compatible way, so it does seem we cannot keep compatibility when we update to this. 

When I added a first few serializaton proxies, I noticed that the `GameData` reference to those classes dropped away. With that there were many simplifications, as well as ad-hoc opportunities for other cleanups.

**Comment by DanVanAtta** [comment]
@ssoloff did this remove every serialization proxy, or just the ones that were on the new framework?

**Comment by ssoloff** [comment]
Only proxies added as part of the new framework were removed.  The existing proxies that pre-date the new framework were not touched.

**Pull request merged**
