### PR TITLE
Remove grid

### PR DESCRIPTION
**Pull request by DanVanAtta**
Remove grid.

While simplifying Tuple and Triple, it turns out the class "Quadruple" is entirely used in Grid. Rather than fix up that code in a few dozen places, just delete it as previously discussed

[Review on Reviewable](https://reviewable.io/reviews/triplea-game/triplea/116)

### CODE REVIEW

**Comment by DanVanAtta** [comment]
Fixed a merge conflict not caused by me! So this code *is* being updated whether we want to or not. Considering it is effectively dead, we are wasting our time with it. Last, since we already removed maps by removing the delegates only, removing grid is not going to make things any worse.

**Comment by ron-murhammer** [comment]
@veqryn - Thoughts on removing grid? I believe we still have kings table in the last release that this would be removing.

**Comment by DanVanAtta** [comment]
@ron-murhammer , we've had the discussion before. @veqryn  is concerned that the work will be incomplete and he'll be left holding the bag for fixes when it comes to next release. Given that we already have removed delegates of games we have suffered the possible consequences of this change already. The tuple change is desirable and requested as another PR requires Grid removal, I didn't want to fix 30+ spots in the Grid code, all of which I know is never executed in real life.

**Comment by veqryn** [comment]
Sorry, but I do not want to remove grid games right now.

**Comment by DanVanAtta** [comment]
Can you explain the risk of keeping them given we have already deleted other maps? How much longer do we have to keep modifying grid code? Ron did in a recent PR, I had to as well in another PR. This removal is not necessarily for convenience but is necessary to implement a code change effectively.

**Pull request closed without merging**
