### PR TITLE
Issue 12447 part2

### PR DESCRIPTION
**Pull request by frigoref**
Undos linked commit and fixes issue described in [PR 12762](https://github.com/triplea-game/triplea/pull/12762)
[8899eb4](https://github.com/triplea-game/triplea/pull/12762/commits/8899eb423ab8117391ec8205fdec7572ed6c9787) Revert "Issues 12447 (Standardized Sorting of UnitCategory) (#12722)" (#12762)

**Changes**
PlayerUnitsPanel.java
- ensure uniqueness in returned list in method getAllUnitCategories
- reduce complexity by use of new method getProducibleUnitTypes

ProductionFrontier.java
- new method getProducibleUnitTypes

### CODE REVIEW

**Comment by frigoref** [comment]
@DanVanAtta This is my first attempt to use the  code review & shipping policy part 'show' here. Please check and guide me in case I am missing anything.

**Comment by TheDog-GH** [comment]
@frigoref 
The Germany Infantry does not appear in the Battle, it has disappeared, also it is not listed as a casualty.

image

**Comment by frigoref** [comment]
@TheDog-GH I have no clue what I should do with your comment. There is nothing for me to reproduce.
Could you please elaborate in more detail what you have found and how I can see that for myself in order to be able to fix it?

**Comment by TheDog-GH** [comment]
@WCSumpton   Please help I am on weak ground and dont want to misdirect @frigoref 

I think the Inf-Trained, flown in on a Air-Transport should be listed for the ground battle, yes?

**Comment by frigoref** [comment]
@TheDog-GH It would already help how you received the screenshot in your comment. For me there is a saved game file or at least a map missing that I would need to start to get closer to the issue you wanted to highlight.

**Comment by TheDog-GH** [comment]
I dont know how best to keep all the comments in one place.  
To get the screen shot.

Game> Show History
At any time you need to see it.
You can step through the history using the down arrow key and it will show the Combat moves.

**Pull request merged**
