### PR TITLE
Reformat rewrap

### PR DESCRIPTION
**Pull request by veqryn**
[Review on Reviewable](https://reviewable.io/reviews/triplea-game/triplea/71)

### CODE REVIEW

**Comment by veqryn** [comment]
@DanVanAtta good to go on this one?

**Comment by DanVanAtta** [comment]
reviewable.io has trouble reviewing something so large. 

I sampled the format changes and overall it looks better. Couple cases where some wrapping is questionable, but on the whole the majority of changes are improvements.

I did notice that you have a second commit with what appear some by-hand changes and some scripted. Reviewing that alone in reviewable was impossible, and adding comments associated with this PR for it is also difficult. I left comments about that change with that commit: https://github.com/triplea-game/triplea/commit/b3142455fffd19f1ca58bb6d1e06e3fa22bf6717

That commit IMO likely would be a good candidate for second PR. That commit I think is also an improvement. I notice that many comments suffer from some of these common problems;
- they do not add value, comments like "why was this done? then next line is commented out". This does not help. It's a mystery for any reader and effectively a complete distraction since the commented out stuff doesn't actually do anything by definition.
- have code in them, code is for code, comments is to explain what can't be explained by code itself
- overly verbose, obvious, restating the code, effectively unnecessary compared to reading the code itself. Often this is a result of poor high level abstractions which result in verbose multi-argument method calls that are not understandable without commentary...

So with all that said, review the comments on the commit, consider them and ship this.

**Comment by veqryn** [comment]
I see all the comments are about StrongAI
I personally could not care less about this particular class (and SUtils), and the sooner it goes away the better.
It is only kept around because it is a decent mid-level AI, and some single player type maps have been tailored to its quirks.
If you would like to strip out all the comments in these two classes that do not add value, be my guest, I will happily accept that PR.

**Comment by DanVanAtta** [comment]
If the class / AI are slated to die anyways, then not much point. Part of my intent was to build a shared understanding. If I get bored one night I may review the comments  and see about cleaning/updating/improving them.

**Pull request merged**
