### PR TITLE
Rework of mapXmlCreator package

### PR DESCRIPTION
**Pull request by frigoref**
Please review carefully as I am not sure whether I have done the fetching and rebasing correctly.

---
This change is [Reviewable](https://reviewable.io/reviews/triplea-game/triplea/571)

### CODE REVIEW

**Comment by DanVanAtta** [comment]
Yes, there were some things that did not go well, see the travis build for compilation errors: 
https://travis-ci.org/triplea-game/triplea/builds/120718147

Looks like packages were moved but not updated everywhere.

**Comment by DanVanAtta** [comment]
If you can, going forward please try to break up PRs so they are small and more easily reviewed. With a rewrite of 5000 lines of code, it's a bit difficult to reivew (and so PRs could get held up for months to finish the review). For this one, successfully getting the branch/PR into a good state is good enough..

**Comment by frigoref** [comment]
I am using eclipse which is doing the commands hopefully in a correct way. So I am trying to interpret the commands you send in clicks on the eclipse menu.Do you need me to do anything now and if so, what exactly?

Gesendet von Yahoo Mail auf Android 
 
  Am Mo., 4. Apr. 2016 um 22:38 hat Dan Van Atta<notifications@github.com> Folgendes geschrieben:   
If you can, going forward please try to break up PRs so they are small and more easily reviewed. With a rewrite of 5000 lines of code, it's a bit difficult to reivew (and so PRs could get held up for months to finish the review). For this one, successfully getting the branch/PR into a good state is good enough..

**Comment by DanVanAtta** [comment]
One thing you can do, view the commits of the master upstream branch: https://github.com/triplea-game/triplea/commits/master

Then if you look at your branch, if it is rebased properly you see that all of your commits are *on top* of the ones in: https://github.com/triplea-game/triplea/commits/master. So for example, the first commit in this branch is: 6adfe9e133b7f1bb02b84ce99732320196906d58, you should see right before that in git history that the previous commit is the final one on the upstream master branch, specifically: 2e174f3d7941e93ae110d095e2ed8b8a07052756


AS is, it does look like you did things well. But, there were some updates to the master code that you did not update for, you still have imports spelling "attatch" as "attach". These need to be corrected since there no longer exists any packages with the name "attatch", and thus the reason why code in the PR fails to compile.

**Pull request closed without merging**
