### PR TITLE
remove unused params  #6578a28

### PR DESCRIPTION
**Pull request by DanVanAtta**
[Review on Reviewable](https://reviewable.io/reviews/triplea-game/triplea/164)

### CODE REVIEW

**Comment by ron-murhammer** [comment]
@DanVanAtta Are you sure this isn't used by reflection anywhere? Its probably pretty unlikely considering it has 3 non-string arguments but not sure if there is an easy way to tell for sure.

**Comment by DanVanAtta** [comment]
Based on the usages, you can actually track down everything that RemoteMethodCall will hit. I hope to open a PR in the next few days that will jump the queue. If anything conflicts with that PR, then we will have an answer to your question. Said in another way, I hope to make a code update soon that makes answering your question much more obvious.

**Comment by DanVanAtta** [comment]
I don't think it will be too too soon before I get to the code update, so I tested this manually.

I launched a lobby with this branch, and connected to it with master and had no issue chatting or launching a game.

Similar, I launched a client with this branch and connected to the existing online lobby and had no issue.

**Comment by DanVanAtta** [comment]
@ron-murhammer , please realize I cannot unassign myself from this PR, nor can I assign it back to you when it is your turn again to do something with it.

**Pull request merged**
