### PR TITLE
Unused params 92a6af

### PR DESCRIPTION
**Pull request by DanVanAtta**
[Review on Reviewable](https://reviewable.io/reviews/triplea-game/triplea/182)

### CODE REVIEW

**Comment by ron-murhammer** [comment]
@DanVanAtta Needs rebased.

**Comment by DanVanAtta** [comment]
rebased and manually tested for serialization issues, found none. Even if there were serialization issues though, I can't see that constituting a defect. Simply that would be something we would prefer to know about rather than as a quality measure.

**Comment by ron-murhammer** [comment]
@DanVanAtta did you test compatibility with the current lobby versions? If so then I'm fine with this change and will merge it.

**Comment by DanVanAtta** [comment]
Yes, the current lobby version was tested as part of "manually tested for serialization issues"

**Pull request merged**
