### PR TITLE
smaller map edge scroll zone, decreasing scroll speed, changelog fix

### PR DESCRIPTION
**Pull request by veqryn**
[Review on Reviewable](https://reviewable.io/reviews/triplea-game/triplea/133)

### CODE REVIEW

**Comment by DanVanAtta** [comment]
It looks like we removed DOS line endings, formatted files, and then blindly reverted some settings without discussion and perhaps without testing. We also have a mysterious addition of `&& chat instanceof Component) `. Regrettably, I fail to see this is a high quality change in its current form.

**Comment by DanVanAtta** [comment]
Why was this assigned to Ron? He was not the most recent to touch this area of code.

**Comment by DanVanAtta** [comment]
Reviewed 2 of 5 files at r1.
Review status: 2 of 5 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

<sup>**[src/games/strategy/engine/framework/startup/ui/MainPanel.java, line 131 \[r1\]](https://reviewable.io:443/reviews/triplea-game/triplea/133#-Jy1dvKN0dRLEW9Lp7tS)** ([raw file](https://github.com/triplea-game/triplea/blob/75db2a359bda757920be1369f1fb78d54466e0a1/src/games/strategy/engine/framework/startup/ui/MainPanel.java#L131)):</sup>
While it is casted to component below, that is the only type possible. If "isHeadless" returns true, but we're not a component, then we will incorrectly evaluate to false  and execute the else block which is intended for when there is no chat or a headless chat. In that case though we have a non-headless chat that is not a component, which should not be executing the else block (really should be executing some third path, but we don't have the use case for it, so by the YAGNI principle I would leave the instanceof check out completely). I'd rather the cast exception than a logic bug.

---

<sup>**[src/games/strategy/triplea/ui/TripleAFrame.java, line 358 \[r1\]](https://reviewable.io:443/reviews/triplea-game/triplea/133#-Jy1dVl5Rpn7iXoUcsyL)** ([raw file](https://github.com/triplea-game/triplea/blob/75db2a359bda757920be1369f1fb78d54466e0a1/src/games/strategy/triplea/ui/TripleAFrame.java#L358)):</sup>
This comment I think might be more maintenance work than the code it is commenting.  This was not a bulk update, so I personally would have opted to fix this since it was touched. To actually fix this comment is not easy though, so I can also understand just fixing the formatting too..

---

<sup>**[src/games/strategy/triplea/ui/TripleAFrame.java, line 1813 \[r1\]](https://reviewable.io:443/reviews/triplea-game/triplea/133#-Jy1cm1QE3NU4wIXTRJ-)** ([raw file](https://github.com/triplea-game/triplea/blob/75db2a359bda757920be1369f1fb78d54466e0a1/src/games/strategy/triplea/ui/TripleAFrame.java#L1813)):</sup>
60 really is slow. Someone originally commented that instead of multiple keys, that we should boost the faster speed. 

100 is not outrageously faster, you can click the arrow keys a bit slower. It's hard to click them even faster. At speed of 60 I was going nuts trying to scroll around maps. The multiplier would help, but 500 was a useful speed. Particularly on a map like cold war where you do need to scroll large distances. So 180 for a max speed is *really* slow of a max. I would want us to then have the control keys.

IMO keep at 100, or put it at 80 so it is faster. Keep the multiplier high, the faster scroll speed needs to be in the 400-600 range at least to traverse a map like NWO or Cold War reasonably.

Eventually this should become a setting so users can set it to what they want. For now better to cater to people that think the map is moving to slow, than those that think it is going to fast (one can fix the problem, the other is SOL)

---

<sup>**[src/games/strategy/ui/ImageScrollerLargeView.java, line 47 \[r1\]](https://reviewable.io:443/reviews/triplea-game/triplea/133#-Jy1ca8R7tY1vKbjtleD)** ([raw file](https://github.com/triplea-game/triplea/blob/75db2a359bda757920be1369f1fb78d54466e0a1/src/games/strategy/ui/ImageScrollerLargeView.java#L47)):</sup>
You still have divided by 4 here for the scroll zone. I think you had mentioned it was divided by 3. 7 pixels wide is tiny. It was kinda hard to hit the faster scroll with 15 pixels.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/triplea-game/triplea/133)

**Comment by DanVanAtta** [comment]
Review status: 2 of 5 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

<sup>**[src/games/strategy/ui/ImageScrollerLargeView.java, line 47 \[r1\]](https://reviewable.io:443/reviews/triplea-game/triplea/133#-Jy1ca8R7tY1vKbjtleD)** ([raw file](https://github.com/triplea-game/triplea/blob/75db2a359bda757920be1369f1fb78d54466e0a1/src/games/strategy/ui/ImageScrollerLargeView.java#L47)):</sup>
Again, with the bigger scroll zone, the real trick I think is to increase the delay before scroll, not to make the scroll zones so small you can't hit them unless you *really* try.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/triplea-game/triplea/133)

**Comment by DanVanAtta** [comment]
> The comment was too long. I do not see any problem with the comment.

You may not see a problem, but you have may have more context than the average reader. I've generally found if something was worth commenting on, there  can be something done to improve clarity. Assuming there may be a nugget of truth somewhere in the reviewers comments often yields better results (so responding in one way by updating the code, letting the code speak for itself). Failing that, some comments are best simply merely noted ;)   Likely like this one! 

Though this particular comment makes little real sense to me, I'd have to look at the definition and perhaps usages to really understand what is going on (in which case the comment did not help, only just now something extra  to update if that line of code needs to change).

**Comment by DanVanAtta** [comment]
I play tested the settings for a small bit. 

Scroll zone did not bother me quite as much as I thought they would, but they are just a bit too hard to hit. Another 10px wider should do it.

Arrow key scroll at 60 on Cold War is not nearly as nice as 100. I played a lot the day before yesterday testing the arrow keys, I was enjoying the map a lot more with the faster navigation. With the reduced speed, you have to hit the arrow keys two or three times as many times to scroll the same distance. I'd stick with 100, that was a good base scroll speed. If you think 500 is too fast, try out 4x or 3.5x as a multiplier.

**Comment by ron-murhammer** [comment]
@veqryn So I'm fine with all the changes here though I think maybe split the difference on the scroll changes. Can we make it say 75 or 80 default with a 3x-4x multiplier so the increase is at least noticeable. Maybe increase the width from 28 to say 40? I personally tend to prefer the increase speed but I'm mixed on the increased width so cautious on that.

**Comment by veqryn** [comment]
@ron-murhammer @DanVanAtta Points taken.  I have increased the multiplier to 4, and the base speed to 70, which is about as high as I want to go for the base speed.  The sidebar zones are now 30 (up from their previous 25), with a 10 width increased speed zone.  I'm still not a particularly big fan of them, especially when playing on a very small screen.

**Comment by DanVanAtta** [comment]
Thank you for the updates - :shipit:  

I'm quite comfortable with 70 and 280 compared to 60 and 180 as arrow scroll speeds. 

I agree the scroll zones are awkward, can cause unintentional scrolling.  With the generously wide scroll zone, the extra fast scroll speed zone made sense. With it more narrow, it still feels pretty usable, but maybe it doesn't make sense to have two scrolls zones now. I won't protest if we go back to one map edge scroll zone instead of two. A forum post would probably be appropriate to ask a wider audience how the feature could be updated, IMO we have a lot of other higher value things to do (I'm happy to call this good enough for some time)

**Comment by veqryn** [comment]
Seems we have acceptance.  Merging.

**Pull request merged**
