### PR TITLE
Improve game loading

### LINKED ISSUE #2038: 5419: Executed associated savegame does not load
### My Operating System:
Windows 7/64

### TripleA version:
1.9.0.0.5419
### Map:
irrelevant
### Can you describe how to trigger the error? (eg: what sequence of actions will recreate it?)
Doubleclick on savegame, that is associated with TripleA
### Do you have the exact error text? Please copy/paste if so
TripleA starts, but savegame is not loaded
aaa
You can see the savegame appearing for a short time on the left side, but then the last map loaded appears.
### Instead of this error, what should have happened?
The dialogue should show and go on with the savegame loaded.
### Any additional information that may help:
./.

### PR DESCRIPTION
**Pull request by RoiEXLab**
FIxes #2038
### What caused this problem:
`GameSelectorModel#loadDefaultGame` was called in a new Thread which lead to the case that the savegame was parsed faster than the default game, which made triplea load the default game instead.
### Why did this problem happen?
I'm not 100% sure, but this is my theory:
Default Game Loading is invoked before savegame loading as some sort of "fallback" if savegame loading fails.
When loading a savegame, the map loading is invoked before "applying" the game history, when the default game is the same game the savegame requires, everything of course works fine, because when the savegame is parsed, the "original map" it needs is already partially loaded and the savegame waits for the loading to end in order to apply its history (which is not the case if it's a completely different base map).
Therefore savegame loading should sometimes work in cases, where the default map takes less time to parse than the basemap for a savegame, but either did I always pic the wrong maps, which does indeed work when trying to load a WAT savegame with a Minimap default game, but not in most cases for whatever reason...

### CODE REVIEW

**Comment by ssoloff** [comment]
The switch to running `loadDefaultGame()` in a background thread was made in 710a83b.  @DanVanAtta is probably in the best position to comment.

**Comment by RoiEXLab** [comment]
@ssoloff I synchronized some methods, which achieves the same result.
Thoughts?

**Comment by ssoloff** [comment]
@RoiEXLab As coded, the synchronization here only guarantees `load()` and `loadDefaultGame()` will not run concurrently.  While you may be observing the side effect that `loadDefaultGame()` completes before `load()` will run, that may not happen in all scenarios because synchronization can't guarantee an order here.

For example, say the JVM or OS takes quite a bit of time to spin up the background thread in which `loadDefaultGame()` will run (i.e. longer than it takes to run between lines 238 and 249 of `GameRunner`).  Then the calling thread can make progress and enter `load()`, at which point the lock will be acquired and prevent `loadDefaultGame()` from running until `load()` completes.  This is a classic race condition.

Also, I'm not sure what you're gaining here.  Even if the race condition resolves in your favor (i.e. `loadDefaultGame()` runs before `load()`), you're still blocking the UI thread because `load()` will block until `loadDefaultGame()` completes.  That kind of defeats the purporse of running `loadDefaultGame()` in a separate thread. :smile:

I would just wait for @DanVanAtta to comment on how important the optimization of running `loadDefaultGame()` in a separate thread actually is.  If it's not a big deal, then I would just stick with your original solution that does guarantee `loadDefaultGame()` runs before `load()`.  Otherwise, you may have to redesign how all this stuff works to guarantee things are run in the correct order while not blocking the UI.

**Comment by RoiEXLab** [comment]
@ssoloff But this synchronization does solve the problem, while not blocking the UI Thread, if all of the load actions are executed in a seperate Thread.
Old behaviour:
```
UI Thread -> new Thread(loadDefaultGame) -> new Thread(loadSavegame)
```
loadDefaultGame may finish after loadSavegame.

With the new behaviour the second Thread has to wait for the first Thread to finish before processing.
This way loadSavegame will always finish after loadDefaultGame

This is the basic idea

**Comment by ssoloff** [comment]
@RoiEXLab First, please define what `loadSavegame()` is.  I see no method with that name.  Based on the changes in this PR, I'm assuming you mean `GameSelectorModel#load(File, Component)`.

Second, I don't see where a second thread is spawned from `loadDefaultGame(Component, boolean)` (the private overload that you marked as `synchronized`).  Can you point this out to me?

I was focusing on the code in `GameRunner#showMainFrame()`, which calls these two  `GameSelectorModel` methods (commented below):

```java
public static void showMainFrame() {
  SwingUtilities.invokeLater(() -> {
    gameSelectorModel.loadDefaultGame(mainFrame); // <-- (1) spawns a new thread that acquires the gameSelectorModel lock

    mainFrame.requestFocus();
    mainFrame.toFront();
    mainFrame.setVisible(true);

    SwingComponents.addWindowCloseListener(mainFrame, GameRunner::exitGameIfFinished);

    final String fileName = System.getProperty(GameRunner.TRIPLEA_GAME_PROPERTY, "");
    if (fileName.length() > 0) {
      final File f = new File(fileName);
      gameSelectorModel.load(f, mainFrame); // <-- (2) acquires the gameSelectorModel lock on this thread
    }
    mainFrame.setVisible(true);
    if (System.getProperty(GameRunner.TRIPLEA_SERVER_PROPERTY, "false").equals("true")) {
      setupPanelModel.showServer(mainFrame);
    } else if (System.getProperty(GameRunner.TRIPLEA_CLIENT_PROPERTY, "false").equals("true")) {
      setupPanelModel.showClient(mainFrame);
    }
  });
}
```

My point in my previous comment was that even though (1) is executed before (2), the thread spawned by (1) may not start running until after (2) is reached and the lock acquired by the UI thread.  Then `loadDefaultGame(Component, boolean)` running in the other thread would be blocked until `load(File, Component)` returns, which is not the order you want.

Is there a different area of the code calling the `GameSelectorModel` methods that you are looking at?

**Comment by RoiEXLab** [comment]
@ssoloff You are correct, I was assuming a second Thread was being spawned somewhere, but the second thread was simply the UI Thread. I fixed this, so the parsing is being executed asynchronously

**Comment by ssoloff** [comment]
@RoiEXLab Great, thanks for clarifying.

Note, however, that you still have a race condition between `loadDefaultGame(Component, boolean)` and `load(File, Component)`.

The following change relative to 3490609 appears to have the effect you're looking for: loading the default and save games off the UI thread, while it ensures loading the default game completes before starting to load the save game.  It composes the two individual operations into a single operation to ensure they are serialized, and then moves the responsibility for running the composed operation asynchronously to the UI thread.

```diff
diff --git a/src/main/java/games/strategy/engine/framework/GameRunner.java b/src/main/java/games/strategy/engine/framework/GameRunner.java
index 1e559ac..fd6a304 100644
--- a/src/main/java/games/strategy/engine/framework/GameRunner.java
+++ b/src/main/java/games/strategy/engine/framework/GameRunner.java
@@ -1,6 +1,7 @@
 package games.strategy.engine.framework;
 
 import java.awt.AWTEvent;
+import java.awt.Component;
 import java.awt.Container;
 import java.awt.EventQueue;
 import java.awt.FileDialog;
@@ -18,6 +19,7 @@ import java.util.Calendar;
 import java.util.Collection;
 import java.util.List;
 import java.util.Optional;
+import java.util.function.Consumer;
 import java.util.prefs.Preferences;
 import javax.swing.JFileChooser;
 import javax.swing.JFrame;
@@ -235,7 +237,7 @@ public class GameRunner {
    */
   public static void showMainFrame() {
     SwingUtilities.invokeLater(() -> {
-      gameSelectorModel.loadDefaultGame(mainFrame);
+      final Consumer<Component> loadDefaultGame = gameSelectorModel::loadDefaultGame;
 
       mainFrame.requestFocus();
       mainFrame.toFront();
@@ -243,10 +245,16 @@ public class GameRunner {
 
       SwingComponents.addWindowCloseListener(mainFrame, GameRunner::exitGameIfFinished);
 
+      final Consumer<Component> loadSavedGame;
       final String fileName = System.getProperty(GameRunner.TRIPLEA_GAME_PROPERTY, "");
       if (fileName.length() > 0) {
-        new Thread(() -> gameSelectorModel.load(new File(fileName), mainFrame)).start();
+        loadSavedGame = ui -> gameSelectorModel.load(new File(fileName), ui);
+      } else {
+        loadSavedGame = ui -> { };
       }
+
+      final Consumer<Component> loadGame = loadDefaultGame.andThen(loadSavedGame);
+      new Thread(() -> loadGame.accept(mainFrame)).start();
       mainFrame.setVisible(true);
       if (System.getProperty(GameRunner.TRIPLEA_SERVER_PROPERTY, "false").equals("true")) {
         setupPanelModel.showServer(mainFrame);
diff --git a/src/main/java/games/strategy/engine/framework/startup/mc/GameSelectorModel.java b/src/main/java/games/strategy/engine/framework/startup/mc/GameSelectorModel.java
index f8cc335..c8e3e86 100644
--- a/src/main/java/games/strategy/engine/framework/startup/mc/GameSelectorModel.java
+++ b/src/main/java/games/strategy/engine/framework/startup/mc/GameSelectorModel.java
@@ -99,7 +99,7 @@ public class GameSelectorModel extends Observable {
     return null;
   }
 
-  public synchronized void load(final File file, final Component ui) {
+  public void load(final File file, final Component ui) {
     if (!file.exists()) {
       if (ui == null) {
         System.out.println("Could not find file:" + file);
@@ -262,7 +262,7 @@ public class GameSelectorModel extends Observable {
     // clear out ai cached properties (this ended up being the best place to put it, as we have definitely left a game
     // at this point)
     ProAI.gameOverClearCache();
-    new Thread(() -> loadDefaultGame(ui, false)).start();
+    loadDefaultGame(ui, false);
   }
 
   /**
@@ -272,7 +272,7 @@ public class GameSelectorModel extends Observable {
    *        we only call with
    *        'true' if loading the user preferred map failed).
    */
-  private synchronized void loadDefaultGame(final Component ui, final boolean forceFactoryDefault) {
+  private void loadDefaultGame(final Component ui, final boolean forceFactoryDefault) {
     // load the previously saved value
     final Preferences prefs = Preferences.userNodeForPackage(this.getClass());
     if (forceFactoryDefault) {
```

It's a little more verbose than necessary because `Runnable` doesn't support composition.  So I had to use an intermediate `Consumer` to get the desired effect.

Note that there may be a thread safety issue here you'd have to look into.  Unfortunately, `ProAI#gameOverClearCache()` is called from `GameSelectorModel#loadDefaultGame(Component)`.  This eventually delegates to `ProLogUI`, which looks like it is intended to only run on the UI thread.  The code above works as written, but probably only because `ProLogUI#clearCachedInstances()` does not assert that it is called on the UI thread as `ProLogUI#initialize()` does.

I looked at the other callers of `GameSelectorModel#loadDefaultGame(Component)` and they all call it off the UI thread, so we'd just be doing what everyone else is already doing.  However, the `ProLogUI` class is not thread safe, and there could be some latent threading issues here.  Might want @ron-murhammer to take a look and comment about that.  Regardless, since all the other callers are not calling it safely, we can probably bump the fix to a separate PR since it seems out-of-scope at this point.

**Comment by RoiEXLab** [comment]
@ssoloff Any objections if this is being merged for now and we or you if you have the time open another PR which enhances the way games are currently loaded?

**Comment by ssoloff** [comment]
@RoiEXLab In its current state, there's still a race condition in this PR.  And the use of synchronization to achieve the effect you're looking for kind of makes me nervous. :smile:  I actually think your original solution (05a9927) is cleaner, even if it does remove a potential optimization.  If we're going to open a separate PR to enhance how games are loaded, I think it would be better to go back to the simpler, non-optimized version, and work forward from there.  That is, "make it correct, and then make it fast." [\[1\]](http://wiki.c2.com/?MakeItWorkMakeItSmallMakeItFast)

@ron-murhammer, @DanVanAtta Can one of you please review and provide direction on how to proceed?

**Comment by RoiEXLab** [comment]
@ssoloff This reverts #2057 again and launches `loadDefaultGame` and `load` in the same Thread.
This ensures `load` is being called _after_ `loadDefaultGame`

**Comment by ssoloff** [comment]
@RoiEXLab Great, that fixes the race condition while loading the game asynchronously.  However, let me ask you the following questions:

1. `ProAI#gameOverClearCache()` is no longer being called.  Is that going to be a problem?  To preserve the existing behavior, you might have to make an explicit call to `ProAI#gameOverClearCache()` from the UI thread in `showMainFrame()`.
1. Are there any consequences of calling `GameSelectorModel#load(File, Component)` off the EDT?  It looks like that method contains transitive calls to `JOptionPane#showMessageDialog()`.  That might be a problem if those code paths get triggered.  If so, I'm not sure what's the best solution here.  Some possibilities are
     1. Pass `null` for the second parameter so it won't invoke `error()`.
     1. Modify `error()` to wrap the existing code in a `SwingUtilities#invokeLater()` call since there's no need to wait for the message dialog to be closed.

**Comment by RoiEXLab** [comment]
@ssoloff 
> 1. `ProAI#gameOverClearCache()` is no longer being called.  Is that going to be a problem?  To preserve the existing behavior, you might have to make an explicit call to `ProAI#gameOverClearCache()` from the UI thread in `showMainFrame()`.

This shouldn't be a problem. According to the comments in `loadDefaultGame(Component)` this method is supposed to be executed after a game has been left (which is not the case since this is being called on startup).
I assume this clears out some variables which are used by the AI.

> 2. Are there any consequences of calling `GameSelectorModel#load(File, Component)` off the EDT?  It looks like that method contains transitive calls to `JOptionPane#showMessageDialog()`.  That might be a problem if those code paths get triggered.  If so, I'm not sure what's the best solution here.

Another Reason why JavaFX is great. JavaFX throws an exception if UI is being modified from a Thread other than the JavaFX Thread.
Probably not. The other way round might be even worse, because it blocks the UI entirely.
I still wrapped the error method inside the invokeLater method

**Comment by ssoloff** [comment]
@RoiEXLab 

> I still wrapped the error method inside the invokeLater method

:+1:

> This shouldn't be a problem. According to the comments in `loadDefaultGame(Component)` this method is supposed to be executed after a game has been left (which is not the case since this is being called on startup).

If you search for calls to `GameRunner#showMainFrame()`, you'll see that it's called in other locations, as well, including what appears to be code paths that are executed when someone disconnects from a network game.  So I'm not sure we can say definitively that this method is only called during startup.

**Comment by ron-murhammer** [comment]
I'll assign this to @DanVanAtta for now since he made some of the changes to this previously.

**Comment by RoiEXLab** [comment]
@ssoloff I added the method call back.

**Comment by ssoloff** [comment]
@RoiEXLab :+1: but, as I mentioned above, if you follow the call chain from `ProAI#gameOverClearCache()`, I think some of descendants (e.g. `ProLogUI`) make the assumption that they are called on the EDT.  I think to be safe, this call should be moved up one line before the thread is started.  That will preserve the semantics prior to this change.

**Comment by RoiEXLab** [comment]
@ssoloff Updated

**Comment by ssoloff** [comment]
Looks good.  I'm going to give @DanVanAtta a bit more time to comment before merging.

**Comment by ssoloff** [comment]
Merging this now.  @DanVanAtta please feel free to open an issue if you see something wrong or that can be improved.

**Pull request merged**
