### PR TITLE
Turn IExecutable mostly to lambdas

### PR DESCRIPTION
**Pull request by RoiEXLab**
Most of this PR turns anonymous classes implementing the IExecutable Interface into lambda expressions.
There are also some other code changes, none of which are functional

### CODE REVIEW

**Comment by ssoloff** [comment]
I was curious how this actually works since `IExecutable` is `Serializable`, and this PR not only changes the serialization UID of each type, but the name of the anonymous type created, as well.  I always assumed `IExecutable`s were serialized between network nodes, but since they are usually stateless, the serialization was simply a way to get the remote node to execute a bit of code by serializing the appropriate type name.

I tested this branch in a network game with a 3635 client and was a bit surprised when everything worked without issue.  I then removed `Serializable` from `IExecutable` and ran another network game between two clients from this branch, and once again there were no issues.

I can only assume that having `IExecutable` implement `Serializable` is some kind of legacy requirement that is no longer applicable.  @ron-murhammer Do you know the history of this type, or if it's safe to drop the serialization requirement?

**Comment by ron-murhammer** [comment]
Uh. I don't think we can do this. I think they do need to be serializable. Most of these are battle window steps and you can save the game halfway through a battle so it needs to be able to save the stack of remaining steps.

**Comment by ssoloff** [comment]
Yup, save games are where they get serialized.  Don't know why I was focused on network games.

I confirmed that saving a game from this branch results in an exception when loading it in a 3635 client.

**Comment by ron-murhammer** [comment]
@ssoloff Yeah. This code is a mess but we'd need to probably move to just refactoring a lot of the IExecutable steps to separate methods/classes to break a lot of this up. But touching any of the code around this is pretty much asking for things to not be backwards compatible.

**Comment by ssoloff** [comment]
> But touching any of the code around this is pretty much asking for things to not be backwards compatible.

Yeah, probably even a simple reorder of methods in a class where these anonymous types are defined might even break compatibility because the anonymous types may get enumerated, and thus named, differently.

**Comment by RoiEXLab** [comment]
@ssoloff @ron-murhammer Let's hold this PR until we create a breaking branch then.
And fix master before that.

**Comment by RoiEXLab** [comment]
Closing this PR, we can always revisit this later, this PR isn't really complicated at all, deleting the branch, the merge conflicts aren't really pretty anyways ^^

**Pull request closed without merging**
