### PR TITLE
Remove .git_attributes

### PR DESCRIPTION
**Pull request by DanVanAtta**
See #577 and 	086055f

---
This change is [Reviewable](https://reviewable.io/reviews/triplea-game/triplea/578)

### CODE REVIEW

**Comment by DanVanAtta** [comment]
@ron-murhammer , @veqryn  - .gitattributes gives hell on linux when you get the wrong characters checked in. I'm going to wind up rebasing everything on this..

**Comment by ron-murhammer** [comment]
@DanVanAtta Umm. If we remove that won't be go back to inconsistent line endings?

**Comment by DanVanAtta** [comment]
We're in that state today. So it does not help. Yet, I've spent the last 30 minutes fighting with this file, a good 30 minutes last night fighting with it..  Any time in the future where I have a rebase that crosses the commit that introduces a CRLF, things break. Big cost for something that does work.

**Comment by DanVanAtta** [comment]
Second important point, it really does not matter so much if we mix up line endings. If someone is using CRLF in source we will hopefully point it out, or do a bulk clean up. At the end of the day it does not cause any errors, so it's not really worth spending time fighting with a file that is overly zeolous about correcting things, which causes a whole lot more trouble than mixing CRLF with LF

**Comment by DanVanAtta** [comment]
Last point I would make on this issue - we have real problems to deal with, a half dozen release blockers for starters...

**Comment by DanVanAtta** [comment]
@ron-murhammer , what are next steps. I'm blocked by this. It's wasted too much time, we don't have the spare resources. I would have had gotten a PR done already to resolve teh merge conflicts in: https://github.com/triplea-game/triplea/pull/569, and time to spare for something else. This is broken, will merge soon when it gets in the way next..

**Comment by ron-murhammer** [comment]
@DanVanAtta Ok I'm fine merging this as honestly I never really cared or had issues with the line endings in the first place.

**Pull request merged**
