### PR TITLE
Make private methods static where possible

### PR DESCRIPTION
**Pull request by ssoloff**
This PR makes private methods `static` where possible.

No call sites required modification, so this should be an easy review even if it is a bit longer than usual.

### CODE REVIEW

**Comment by ron-murhammer** [comment]
@ssoloff So the problem I have with this PR is that while I see the value of making methods static, all the references to these methods will still use object calls rather than class calls.

**Comment by ssoloff** [comment]
@ron-murhammer Can you elaborate?  Because these are private methods, all calls to the modified methods are within the enclosing class, thus the following code in an instance or class method of class `Foo`:

```java
someStaticMethod();
```

is equivalent to

```java
Foo.someStaticMethod();
```

For example, consider this class:

```java
public class Foo {
  public void bar() {
    baz();
  }

  private void baz() {}

  public static void main(final String[] args) {
    final Foo foo = new Foo();
    foo.bar();
  }
}
```

The bytecode for `Foo#bar()` is

```
public void bar();
  Code:
     0: aload_0
     1: invokespecial #15                 // Method baz:()V
     4: return
```

If I make `Foo#baz()` static, **and do not change the call site in `Foo#bar()`**, the bytecode for `Foo#bar()` becomes

```
public void bar();
  Code:
     0: invokestatic  #15                 // Method baz:()V
     3: return
```

So, it appears that the compiler infers the desired behavior.

From a code style perspective, I can understand your concern if the preference is to always invoke static methods **defined in the same class** through a class reference, as in `<class>.<method>`.  However, I have not observed that style in existing code.

One other thing to note...  I did verify that no call site invoked an affected method via an explicit `this` reference, e.g. `this.someStaticMethod()`.  I believe this still generates the same `invokestatic` bytecode as above, but it triggers a warning in the Eclipse static analyzer that static methods should not be invoked via `this`.

**Comment by ron-murhammer** [comment]
@ssoloff Sorry, I'm apparently too tired to be reviewing PRs. I totally missed that all of these were private methods and was thinking of public references to these methods. Merging.

**Comment by ssoloff** [comment]
@ron-murhammer NP.  Go to bed. :smiley:

**Pull request merged**
