### PR TITLE
Update ISSUE_TEMPLATE.md

### PR DESCRIPTION
**Pull request by DanVanAtta**
I did some quick edits to the issue template; meant to be starting point for some discussion; please have at it and nitpick this one  :+1: 

Driving this topic is new forum post point to here for bug tracking: https://forums.triplea-game.org/topic/606/bug-reports-https-github-com-triplea-game-triplea-issues-new

### CODE REVIEW

**Comment by ssoloff** [comment]
LGTM.  Making the comments context-specific is a good improvement.

If there was only a way to force/encourage users to type the information _below_ the headings instead of _after_ them...  That would be a big :+1:  Maybe the trailing colons in the headings are misleading, thus causing users to type on the same line?

**Comment by DanVanAtta** [comment]
I forgot about the trailing colons @ssoloff , those struck me first time I saw the form and then I got used to them.  I removed them in: c8daa4f

**Comment by ssoloff** [comment]
:+1: If that doesn't work, we can always add a `<!-- begin typing here -->` comment under each heading. :smile:

**Comment by ron-murhammer** [comment]
Seems like an improvement to me. I'd say let's merge and we can always keep adjusting it.

**Pull request merged**
