### PR TITLE
Remove commented out / printlns

### PR DESCRIPTION
**Pull request by DanVanAtta**
This change is [Reviewable](https://reviewable.io/reviews/triplea-game/triplea/991)

### CODE REVIEW

**Comment by RoiEXLab** [comment]
@DanVanAtta I don't get why you are not merging when only removing comments...

**Comment by DanVanAtta** [comment]
Some time ago we agreed that when a person submits a PR, they should pretend they do not have write permissions. Perhaps we should revisit that, I do think that has lead a bit to the bad practice of CR as gatekeeping.

**Comment by RoiEXLab** [comment]
@DanVanAtta Yeah, whatever feel free to merge though

**Comment by DanVanAtta** [comment]
Well, we're still at least going to stick to the rule that everything needs review. You may have noticed for the less controversial stuff, I've been treating your review as sufficient. We probably should raise a larger conversation once more about what we are trying to accomplish with the CR process, and if our current process is the best way to accomplish those goals.

**Pull request merged**
