### PR TITLE
Update triplea_maps.yaml

### PR DESCRIPTION
**Pull request by Navalland2**

### CODE REVIEW

**Comment by beelee1** [comment]
@Navalland2 double check that you have "mapName" listed. i don't see it here:

What went wrong:

Execution failed for task ':spotlessAllFilesCheck'.

> The following files had format violations:

      triplea_maps.yaml

          @@ -2185,6 +2185,6 @@

           ··mapCategory:·GOOD

           ··url:·https://github.com/triplea-maps/aggression_1941/archive/master.zip

           ··version:·1

          -··img:·

          +··img:

           ··description:·|

           ···<br>A·WWII·scenario·loosely·based·on·1941,·inspired·from·AA50·Anniversary·and·Big·World

The other one is:

 What went wrong:

Execution failed for task ':validateYamls'.

> /home/travis/build/triplea-game/triplea/triplea_maps.yaml: duplicate key: mapCategory

Idk if thats just the way it comes out but you have:
··mapCategory:·GOOD
maybe try 
··mapCategory:GOOD

Idk. I'm just guessing here :)

**Comment by Navalland2** [comment]
Is it good now?

**Comment by beelee1** [comment]
@Navalland2 yea idk looking at what you had before looked ok to me. I don't why it's throwing those errors. Guess you'll have to wait for one of the smart people.

**Comment by Navalland2** [comment]
I guess its because of lack of image.

**Comment by beelee1** [comment]
@Navalland2 Is it a custom map or just a mod ? If a mod just use the original maps image. If custom you should just need a screenshot. I haven't done it in a long time, but I think you just need a "description" folder and put your image in there. It should be with "map" and the "README" when you first open it up.

**Comment by Navalland2** [comment]
It is a custom map.

**Pull request merged**
