### PR TITLE
Remove uneccessary censoring

### PR DESCRIPTION
**Pull request by RoiEXLab**
@DanVanAtta @ron-murhammer I did some testing: It's absolutely impossible to intentionally leak secret env variables via the buildscript. Travis is censoring the log on its own!

I created an empty travis script just containing `echo $SECRET_TOKEN` and what was printed? `[secret]`

### CODE REVIEW

**Comment by RoiEXLab** [comment]
@DanVanAtta @ron-murhammer Here's the travis build, just i case you are concerned/not convinced:
https://travis-ci.org/RoiEXLab/triplea-game.github.io/builds/240141135

**Comment by RoiEXLab** [comment]
Now that I think about it: It probably is possible to leak the token intentianally, but only by splitting it into multiple string which all get printed seperately.
But not by accident!

**Comment by ssoloff** [comment]
@RoiEXLab I agree with you that since the [Travis security advisory](https://blog.travis-ci.com/2017-05-08-security-advisory) released on 2017-05-08, it appears that all secure environment variables and tokens are scrubbed from the build logs.  However, the [Travis security best practices](https://docs.travis-ci.com/user/best-practices-security/) document (which was created after the security advisory was released) still has a section on self-scrubbing command output (e.g. redirecting to `/dev/null`), and they even use `git push` as an example.

I suspect the section "Recommendations on how to avoid leaking secrets to build logs" is focused on general secrets **other than** Travis secure environment variables and tokens.  That is, those secrets for which Travis has no idea about and thus can't detect and scrub (e.g. say when running a test I receive a response from the network that contains secret data and I log it to stdout).  However, I'm not 100% sure this section doesn't apply to Travis secure environment variables and tokens, especially since they use that phrase in bullet 5 ("git commands like...").

Just to be safe, do you mind contacting `security@travis-ci.com` and asking if the kind of scrubbing we've been doing for Travis secure environment variables and tokens is truly no longer necessary?  Unless, of course, others chime in and state that they believe the Travis docs are unambiguous on this topic. :smile:

**Comment by DanVanAtta** [comment]
I recall seeing the travis update that they had done this, and remember thinking were were doing such scrubbing some time before their patch.

For me the only question is if we want to be explicit about the scrubbing and not rely on travis at all. On the one hand, the fewer dependencies on travis behavior the more we can test locally. On the other hand, travis does hide env variables and secrets, so we could just simplify and not worry about leaking secret env variables.

@RoiEXLab I suspect you're voting for the second option where we just stop worrying about it? : )

**Comment by RoiEXLab** [comment]
> I suspect you're voting for the second option where we just stop worrying about it?
@DanVanAtta Correct ^^

**Comment by DanVanAtta** [comment]
Okay, I'm inclined to go with you on this @RoiEXLab , just one less thing to worry about.

**Comment by RoiEXLab** [comment]
From travis support:
> Hi RoiEX,

> Thanks for your email!

> You're right: at the moment, any encrypted (or "secret") environment variables will be automatically replaced with [secure] in the builds logs. This was a measure we released recently (see our Security advisory [here](https://blog.travis-ci.com/2017-05-08-security-advisory)) since secured environment variables could be accidentally exposed in the build logs, and this was affecting users both in https://travis-ci.com (where build logs remain private to those who have access to the private repo) and https://travis-ci.org (where logs are public).

> With this security measure, if any of the commands of your build tries to print a secret in the log, it would automatically be removed from the log. As you say, you can consider our recommendations on how to avoid leaking secrets general tips on how to handle sensitive data in Travis CI or any other tools or services. Still, we'd recommend following these advices for prevention.
[...]
Have a great day,
Carla

**Comment by ssoloff** [comment]
Thanks for following up, @RoiEXLab.  It sounds like the last sentence in the email from Travis support is simply CYA. :smile:

**Pull request merged**
