### PR TITLE
Update to include WW2 Path to Victory

### PR DESCRIPTION
**Pull request by regularkyd**
Update to include WW2 Path to Victory

## Functional Changes

[] New map or map update
[] New Feature
[] Feature update or enhancement
[] Feature Removal
[] Code Cleanup or refactor
[] Configuration Change
[] Problem fix:  
[] Other:

### CODE REVIEW

**Comment by ron-murhammer** [comment]
@RoiEXLab Looks like there is some issue with the link checker from another open issue? Can you take a look at this to see if it looks ok and merge it so the map maker can test the download?

**Comment by RoiEXLab** [comment]
@ron-murhammer Kind of. There is an issue with the script, but travis isn't able to reach the a&a forum for some reason, which causes the problem. @DanVanAtta suggested to just disable this check for now, but I don't plan to do this before tomorrow (it's currently 2am here)

**Comment by ron-murhammer** [comment]
Ok, can we just merge this PR though? Just wanted a second set of eyes on the yaml changes.

**Comment by RoiEXLab** [comment]
We could but it would cause the master build to fail, so it would be better to just comment in the line in the bash script that does the link checking

**Comment by DanVanAtta** [comment]
Disabled the link check for in-game links, merged latest to this PR. The link check then failed but due to a typo in the YAML. I fixed that just now, should be good to merge once build checks pass.

**Comment by DanVanAtta** [comment]
Congrats @regularkyd , the map should be live for download now from in-game.

**Pull request merged**
