### PR TITLE
Refactor unload transport

### PR DESCRIPTION
**Pull request by ron-murhammer**
Clean up unload transport code to prepare to tackle point 3 on #553

Based on #739

---
This change is [Reviewable](https://reviewable.io/reviews/triplea-game/triplea/740)

### CODE REVIEW

**Comment by DanVanAtta** [comment]
589b9d6 looks good.

**Comment by DanVanAtta** [comment]
When I looked at this, at 589b9d6, only TransportUtils.java was updated. Now there is quite a bit more. I'm a bit curious how that happened. Should this be cherry-picked onto a clean branch to avoid the unintended diff? What would you suggest be done with the extra changes?

**Comment by ron-murhammer** [comment]
@DanVanAtta Honestly not sure why that happened. If you glance at the other 2 classes that show up, there aren't actually any changes... My guess is either a formatting or EOL issue. I'd prefer to avoid creating a 3rd branch and PR for this change but can if you feel its necessary.

**Comment by DanVanAtta** [comment]
The github magic flag for hiding whitespace confirms it's just extra whitespace changes. https://github.com/triplea-game/triplea/pull/740/files?w=1

My guess would be EOL. Since the one commit was just the one file, it means the update was introduced as part of the merge commit (one problem with merge commits, they are a 'change-the-world' commit where anything and everything can be changed in them).

**Comment by ron-murhammer** [comment]
Yeah, probably means one of the new devs doesn't have the same EOL settings. Might start seeing this more often.

**Pull request merged**
