### PR TITLE
Checkstyle: Fix line length violations

### PR DESCRIPTION
**Pull request by ssoloff**
This PR fixes the remaining violations of the Checkstyle LineLength rule.

The fixes aren't pretty and don't really even improve readability.  However, the code at least now fits within the editor window. :smile:

It would be nice if Java supported type aliases, as that would be the preferred way to fix these violations.  However, since it doesn't, I'm open to any alternative suggestions for fixing these violations including simply closing this PR and not fixing them at this time.

### CODE REVIEW

**Comment by ssoloff** [comment]
The latest commit is an alternate fix for the violations.  In this case, I added line breaks to keep a `Map`s key and value types on separate lines, and a `Tuple`s first and second types on separate lines.  Not sure if this is any better than the first fix.  I can revert to the original commit, if necessary.

**Comment by ssoloff** [comment]
@RoiEXLab 

> While it doesn't have a real support for this, you can "workaround" this issue by creating a "dummy nested interface" like this

When I was first fixing line length violations a few months ago, I tried that approach.  Unfortunately, it won't work in any of these three occurrences:

* The types of the two occurrences in `BattleTracker` cannot be changed because the `m_relationshipChangesThisTurn` field is serialized with save games.  Changing types would break save game compatibility.
* The type of the one occurrence in `BattleDelegate` cannot be changed because portions of this type are part of the `ITripleAPlayer#scrambleUnitsQuery()` method, and this method is callable via RMI.  Changing the type would break network game compatibility.

**Comment by ron-murhammer** [comment]
@ssoloff I think I'm gonna agree with @RoiEXLab here. I think the changes actually make readability worse. Probaby better to just leave them alone.

**Comment by ssoloff** [comment]
NP.  Closing.

**Pull request closed without merging**
