### PR TITLE
Code clean ups to AI code and another trace message.

### PR DESCRIPTION
**Pull request by asvitkine**
## Change Summary & Additional Notes
Code clean ups to AI code and another trace message.
No logic changes, some performance improvements by avoiding unnecessary operations.

Tested using a full game (18 rounds) with all-hard-AI round on 1942 global 2nd ed to verify no crashes from removing collection copies.

### CODE REVIEW

**Comment by asvitkine** [comment]
All the codeclimate issues are pre-existing.

**Comment by DanVanAtta** [comment]
> All the codeclimate issues are pre-existing.

These are of course best effort to fix. I think you should be able to 'approve' exceptions and make that check go green now @asvitkine  for these cases where it's best for another PR to fix the warnings. You should be able to click the 'code climate' link and after signing in, there ought to be an 'approve' button that will override the check.

**Comment by asvitkine** [comment]
> > All the codeclimate issues are pre-existing.
> 
> These are of course best effort to fix. I think you should be able to 'approve' exceptions and make that check go green now @asvitkine for these cases where it's best for another PR to fix the warnings. You should be able to click the 'code climate' link and after signing in, there ought to be an 'approve' button that will override the check.

Thanks. I'm not seeing the UI to approve, though. Here's what it looks when I click the link (and I confirmed I'm logged in):
Screen Shot 2022-05-11 at 10 41 59 PM

**Comment by asvitkine** [comment]
Did a careful self review and a bunch more all-AI rounds to test. Going to merge this.

**Comment by DanVanAtta** [comment]
That screenshot is certainly missing an 'approve' button:

Screenshot from 2022-05-11 21-23-33


It is odd, I don't see a way to specify user permissions or anything, presumably they are just from the repository. Though, if you can merge anyways, it does not matter as much as it could..

**Pull request merged**
