### PR TITLE
Update shadowJar configuration

### PR DESCRIPTION
**Pull request by ssoloff**
This PR changes the `shadowJar` task to write the shadow jar directly to its expected location instead of having to copy it after-the-fact.

#### Testing

I ran `./gradlew clean release` locally, and it built all artifacts without issue.

### CODE REVIEW

**Comment by ssoloff** [comment]
@RoiEXLab :+1: Indeed.  The installers are about 3-4 MiB smaller.  I'll investigate where the disconnect is.

**Comment by RoiEXLab** [comment]
@ssoloff Yup, there's a reference: https://github.com/triplea-game/triplea/blob/9152a8a36517d7f175e917e9fd54470f7c4cbf40/build.install4j#L31

**Comment by ssoloff** [comment]
@RoiEXLab Good catch.  This should be fixed in the latest commit.  I verified the Unix installer works as expected.

**Comment by ssoloff** [comment]
Ugh.  On Windows, I'm seeing the following exception when starting a new game:

```
java.lang.reflect.InvocationTargetException
        at java.awt.EventQueue.invokeAndWait(Unknown Source)
        at java.awt.EventQueue.invokeAndWait(Unknown Source)
        at javax.swing.SwingUtilities.invokeAndWait(Unknown Source)
        at games.strategy.triplea.TripleA.startGame(TripleA.java:122)
        at games.strategy.engine.framework.startup.launcher.LocalLauncher.launchInNewThread(LocalLauncher.java:49)
        at games.strategy.engine.framework.startup.launcher.AbstractLauncher.lambda$launch$0(AbstractLauncher.java:51)
        at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException
        at games.strategy.engine.ClientFileSystemHelper.folderContainsGamePropsFile(ClientFileSystemHelper.java:106)
        at games.strategy.engine.ClientFileSystemHelper.getRootRelativeToClassFile(ClientFileSystemHelper.java:94)
        at games.strategy.engine.ClientFileSystemHelper.getRootFolder(ClientFileSystemHelper.java:51)
        at games.strategy.triplea.ResourceLoader.getMapResourceLoader(ResourceLoader.java:47)
        at games.strategy.triplea.ui.HeadedUiContext.internalSetMapDir(HeadedUiContext.java:71)
        at games.strategy.triplea.ui.AbstractUiContext.setDefaultMapDir(AbstractUiContext.java:104)
        at games.strategy.triplea.ui.TripleAFrame.<init>(TripleAFrame.java:229)
        at games.strategy.triplea.TripleA.lambda$startGame$0(TripleA.java:124)
        at java.awt.event.InvocationEvent.dispatch(Unknown Source)
        at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
        at java.awt.EventQueue.access$500(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.awt.EventQueue.dispatchEvent(Unknown Source)
        at games.strategy.engine.framework.GameRunner$1.dispatchEvent(GameRunner.java:351)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.run(Unknown Source)
```

Investigating.

**Comment by ssoloff** [comment]
#2731

**Pull request merged**
