### PR TITLE
Revert "Remove fourth version number"

### PR DESCRIPTION
**Pull request by DanVanAtta**
This reverts commit ca0fb9edb4d353f3b13aeb33ebe3639225e01bba.

### CODE REVIEW

**Comment by DanVanAtta** [comment]
@simon33-2 with regret and FYI, please revert the revert with fixes when ready.

**Comment by simon33-2** [comment]
Unfortunately it appears that this cannot be fixed in one go. Looks like we need to get the bots to stop looking at the fourth number before we can then remove it.

I'm having trouble getting any debugging from a bot. Where does the stdout actually go to? In build 3635 it was sent to a file in the "logs" subdirectory. I don't know if I'm doing something stupidly wrong like putting the jar file in the wrong place or something but this apparently simple change is causing me some headaches.

It's a shame no one thought of testing that, particularly myself.

**Comment by ssoloff** [comment]
> I'm having trouble getting any debugging from a bot. Where does the stdout actually go to? In build 3635 it was sent to a file in the "logs" subdirectory.

Looks like that functionality was removed in 28de187.

When I ran a 7051 bot locally, both stdout and stderr went to the console from which I started the application.  So, I guess, you should be able to redirect stderr and stdout however you wish from the command line.

**Comment by simon33-2** [comment]
For me, it isn't going to the stdout. It's just disappearing.

**Comment by prastle** [comment]
Noob comment but the bots work fine again with .7051 . No problems so far today.  jfyi

**Comment by RoiEXLab** [comment]
@simon33-2 Could it be the case that you are using javaw to run the jar instead of just `java`?

**Comment by simon33-2** [comment]
Ok, here's some more detail. Script used to start the bot is:
simon@probook:~/TripleA_1.9.custom$ more run-headless-game-host.sh 
cd $(dirname $0)
lobby_host=45.79.144.53
lobby_port=3304
triplea_port=3363
java -server -Xmx320m -Djava.awt.headless=true -classpath bin/triplea.jar games.
strategy.engine.framework.headlessGameServer.HeadlessGameServer triplea.game.hos
t.console=true  triplea.server=true triplea.port=$triplea_port triplea.lobby.hos
t=$lobby_host triplea.lobby.port=$lobby_port triplea.name=BotBB99_Simon33 triple
a.lobby.game.hostedBy=BotBB99_Simon33 triplea.lobby.game.supportEmail=yourEmailN
ame@emailProvider.com triplea.lobby.game.comments="automated_host"

<end>

If I add this System.out line to src/main/java/games/strategy/engine/framework/startup/login/ClientLoginValidator.java:
    // check for version
    final Version clientVersion = new Version(versionString);
System.out.format("Client %s Server %s\n", versionString, ClientContext.engineVersion().toStringFull("."));
    if (!ClientContext.engineVersion().equals(clientVersion, true)) {
      return "Client is using " + clientVersion + " but server requires version " + ClientContext.engineVersion().toStringFull(".");
    }

I get nothing in the bot window, nor in the client. I get the message "Client is using"... though. I'm confused as to what is going on.

**Comment by simon33-2** [comment]
> Noob comment but the bots work fine again with .7051 . No problems so far today. jfyi

Yeah, but we want the bots to be upgradeable to a version which allows the 4th number to be removed later at the very least.

**Comment by ssoloff** [comment]
@simon33-2 Just a theory...  What happens if you add a call to `System.out.flush()` after you call `System.out.format()`?

The predefined `System.out` instance is created to auto-flush.  However, our code replaces the predefined stdout stream with one that doesn't auto-flush.  See [`GenericConsole`](https://github.com/triplea-game/triplea/blob/11205903841febbd79a6987c09b881759f63f553/src/main/java/games/strategy/debug/GenericConsole.java#L89-L90).

**Comment by simon33-2** [comment]
It doesn't appear to do anything different. Thanks anyway.

**Comment by simon33-2** [comment]
Although another strange part is the message has "version 1.9" when I've changed the string to be created by toStringFull(".")

**Comment by simon33-2** [comment]
It's as though the .jar file isn't going over to the bot correctly.

**Comment by ssoloff** [comment]
> It's as though the .jar file isn't going over to the bot correctly.

Yup, was just going to say it seems like you're not running the code you think you are.  How are you building `triplea.jar`?  Are you restarting the bot after you replace the existing `triplea.jar`?

**Comment by simon33-2** [comment]
-rw-rw-r-- 1 simon simon 13121609 Oct 10 07:34 ../aaa/build/libs/triplea-1.9.0.08889.dev-all.jar
-rw-rw-r-- 1 simon simon 13121511 Oct  9 21:45 ../aaa/build/libs/triplea-1.9.0.0.dev-all.jar
-rw-rw-r-- 1 simon simon 13167316 Oct  5 19:17 ../aaa/build/libs/triplea-all.jar


Bother. I didn't know the name of the shadowJar was now being mangled with the version number!

**Comment by simon33-2** [comment]
Thanks for your help - at least you helped me to know where the problem wasn't.

**Pull request merged**
