### PR TITLE
Remove Travis Java7 build and fork configuration

### PR DESCRIPTION
**Pull request by DanVanAtta**
[Review on Reviewable](https://reviewable.io/reviews/triplea-game/triplea/212)

### CODE REVIEW

**Comment by DanVanAtta** [comment]
Admins (@ron-murhammer , @veqryn ) , please re-run the build on this to verify it was only a temporary Travis problem that failed the build.
(click details link of the travis CI build and then look for the re-run button below the "details" drop down)

**Comment by DanVanAtta** [comment]
@ron-murhammer , @veqryn , it would be useful if this PR jumped the review queue. Merging this will fix travis builds that fail only for me. The change is pretty trivial since it only removes lines and touches configuration that does not impact the game organization or repository.

**Comment by ron-murhammer** [comment]
Yep looks fine. Merging.

**Comment by ron-murhammer** [comment]
Well guess you can't merge PRs that fail the build from a phone. Will merge tonight when I get to my computer.

**Comment by DanVanAtta** [comment]
Thanks.

@veqryn  , @ron-murhammer  - Apologies I should haved called this out explicitly - this change also removes java7 from the Travis build and leaves only  Java8. That *does* impact the Travis build for the game organization!

Veqryn had requested we remove the Java7 build the next time we update the travis configuration (that request was made I believe the last time we merged updates to the travis file). Removing the Java7 build helps out the Travis people, and it would be pretty trivial to add that one line back if we ever really wanted to.

**Pull request merged**
