### PR TITLE
Update triplea_maps.yaml

### PR DESCRIPTION
**Pull request by CrazyGerman**
Update the version number

### CODE REVIEW

**Comment by ron-murhammer** [comment]
@CrazyGerman There appears to be a missing or incorrect image path with your updates as its showing this error:
https://raw.githubusercontent.com/triplea-maps/house_of_habsburg/master/description/MapThumbnail.jpeg: map resource not available (404)

**Comment by RoiEXLab** [comment]
This issue prevents master from building...

**Comment by ron-murhammer** [comment]
@RoiEXLab Should be fixed now.

**Comment by CrazyGerman** [comment]
Thanks for the help!

Currently I'm traveling and can only check github or my email when I have
VPN access, sorry to be late to respond

**Pull request merged**
