### PR TITLE
Mp3 with JLayer

### PR DESCRIPTION
**Pull request by DanVanAtta**
MP3 playback support using jLayer, based on: http://thiscouldbebetter.wordpress.com/2011/06/14/playing-an-mp3-from-java-using-jlayer/

[Review on Reviewable](https://reviewable.io/reviews/triplea-game/triplea/484)

### CODE REVIEW

**Comment by gaborbernat** [comment]
Reviewed 257 of 257 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/games/strategy/sound/ClipPlayer.java, line 428 \[r1\]](https://reviewable.io:443/reviews/triplea-game/triplea/484#-KBcVd5KskkSdpwSgJlG:-KBcVd5KskkSdpwSgJlH:-1596841488) ([raw file](https://github.com/triplea-game/triplea/blob/86945fc58e3ff4ce9e827840955243da229914b6/src/games/strategy/sound/ClipPlayer.java#L428)):*
Lets' make this a little more verbose, like extracting the suffix check into a isMp3File function and zipElement.getName().indexOf(resourceAndPathURL) != -1 into a a has something.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/triplea-game/triplea/484)*

**Comment by DanVanAtta** [comment]
Review status: 255 of 257 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/games/strategy/sound/ClipPlayer.java, line 428 \[r1\]](https://reviewable.io:443/reviews/triplea-game/triplea/484#-KBcVd5KskkSdpwSgJlG:-KBoo-LmklHTglXPvN4M:298232066) ([raw file](https://github.com/triplea-game/triplea/blob/86945fc58e3ff4ce9e827840955243da229914b6/src/games/strategy/sound/ClipPlayer.java#L428)):*
Added 75b9d0b with that chnage. Second, also cleaned up some unnecessary null checks that were nearby as well.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/triplea-game/triplea/484)*

**Comment by ron-murhammer** [comment]
@DanVanAtta - How are we planning to handle sounds packaged with existing maps? Are you going to go through and update all maps that have .wav files to .mp3 files?

**Comment by DanVanAtta** [comment]
@ron-murhammer  yup :+1: 
In addition to re-encoding to mp3, the `sound.properties` file in each map will also need to be updated  as well to swap the `wav` suffix to `mp3`.

**Comment by ron-murhammer** [comment]
@DanVanAtta I'm good with this PR. After converting all the maps, we'll need to make sure to do some testing to make sure at least the most popular maps sound work properly. Gonna merge this now.

**Pull request merged**
