### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by DanVanAtta**
## Overview
Use GPLv3 license shield instead of auto-detected one. After recent breaking changes were rolled back, the shield is no longer detecting the GPL license.

## Functional Changes

[ ] New map or map update
[ ] New Feature
[ ] Feature update or enhancement
[ ] Code Removal
[ ] Code Cleanup or refactor
[X] Configuration Change
[ ] Bug fix

## Testing

[ ] Covered by existing automated tests
[ ] Covered by newly added automated tests
[X] Manually tested
[ ] No testing done

### CODE REVIEW

**Comment by RoiEXLab** [comment]
Déjà-vu #832

I recall that I used to double check the license using this tool: https://github.com/licensee/licensee
It's the same tool GitHub uses to detect the license. This would display the license name on the "overview bar" already:
License

**Comment by ssoloff** [comment]
I think the auto-detection is broken because of the presence of both _LICENSE_ and _license.md_ files (see [here](https://help.github.com/en/articles/licensing-a-repository#determining-the-location-of-your-license) and [here](https://help.github.com/en/articles/licensing-a-repository#detecting-a-license)).  While this change fixes the badge, GitHub still can't auto-detect the license, resulting in the loss of a few features:

#### No license classification for project (including in searches)

##### Before

triplea-license-auto-detect-before

##### After

triplea-license-auto-detect-after

#### No license term summary

##### Before

triplea-license-term-summary-before

##### After

triplea-license-term-summary-after

---

The easiest way to re-enable the license auto-detection should be to either rename _license.md_ to something else (e.g. _license_terms.md_) or to simply inline the content of _license.md_ into the README.

**Comment by RoiEXLab** [comment]
@ssoloff Your explanation is even better 😄

**Comment by DanVanAtta** [comment]
@RoiEXLab , @ssoloff  - thank you for the feedback; Opened: https://github.com/triplea-game/triplea/pull/5075 which perhaps will resolve the license issue. Good suggestion to rename 'license.md', I went with instead merging that file to README. It'd be nice to see if we can reduce the number of top-level non-source files and directories in the project.

**Pull request closed without merging**
