### PR TITLE
Fix default run configurations for Intellij Idea.

### PR DESCRIPTION
**Pull request by OrdoFlammae**
## Overview
This pull request fixes a slight error in the run configurations for Intellij.

## Manual Testing Performed
- ..

### CODE REVIEW

**Comment by DanVanAtta** [comment]
Great to see the first contribution @OrdoFlammae , welcome

I think we might have been ping-ponging between having this run config vs not

**Comment by DanVanAtta** [comment]
@OrdoFlammae did you import the checked in IDEA settings (in folder: `.ide-intellij/`)? If not, does it change the configs for you?

**Comment by RoiEXLab** [comment]
> I think we might have been ping-ponging between having this run config vs not

@DanVanAtta That's exactly what happened, this PR broke my configuration.

**Comment by OrdoFlammae** [comment]
@DanVanAtta, I did import the IDEA settings. Just in case, I just re-imported them, and nothing has really changed. @RoiEXLab, how does this break your configuration. Sorry, I had no idea that would happen (probably should've guessed, since this hadn't happened yet).

**Comment by RoiEXLab** [comment]
Well my IDEA project expects the "one module per gradle project" layout. Whereas your configuration seemingly uses the "one module per source set" approach.
If your have the project open, you can open a window using the bar on the right where it says "Gradle", then select the wrench 🔧 and somewhere there should be a checkbox that allows you to configure this setting.

**Comment by OrdoFlammae** [comment]
@RoiEXLab, that setting appears to be non-existent in recent versions of IDEA (I'm using 2019.2).

**Comment by RoiEXLab** [comment]
Yeah, I just double checked too:
Screenshot

Interesting

**Pull request merged**
