### PR TITLE
Use Streams instead of Enumeration

### PR DESCRIPTION
**Pull request by RoiEXLab**
I felt like I should code something for TripleA again :)
Haven't tested my changes so far, but will do tomorrow

### CODE REVIEW

**Comment by DanVanAtta** [comment]
Good to see you back @RoiEXLab

**Comment by RoiEXLab** [comment]
@DanVanAtta Ok it refined my changes and finally got to test them, everything seems to work.
Not sure about the integration test though: I don't think the failure is related to my code changes. Any ideas?

**Comment by DanVanAtta** [comment]
Yeah, the integ test has been an ongoing issue. Seems to have broken a week or two ago. It needs fixing. Should be not be related (it's a bad situation, we won't know if we make things worse, so it is kinda pressing to fix it).

**Comment by DanVanAtta** [comment]
Nice update with the FileSystem API, that simplified quite a bit :+1:

**Pull request merged**
