### PR TITLE
[Eclipse GameRunner2 JMX Args Run Config]

### PR DESCRIPTION
**Pull request by DanVanAtta**
Add args for eclipse GameRunner2 to open up the JMX console port.

[Review on Reviewable](https://reviewable.io/reviews/triplea-game/triplea/499)

### CODE REVIEW

**Comment by gaborbernat** [comment]
I feel like this should be a gradle task too, at least.

**Comment by gaborbernat** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/triplea-game/triplea/499)*

**Comment by DanVanAtta** [comment]
I would add it to the run task rather than adding it as a brand new task. I'm not willing to expand the scope of this to update Gradle.

**Comment by DanVanAtta** [comment]
Actually, a second runner task is probably better. With this you cannot run multiple instances since each wants to grab the same JMX port. The eclipse launcher is likely to get forked soon... (or should be once someone starts to do some network game testing)

**Pull request merged**
