### PR TITLE
Allow invisible units

### PR DESCRIPTION
**Pull request by simon33-2**
Builds on #1599 

The major reason for this is to allow a universal scramble relatively easily by putting an airstrip in every territory.

### CODE REVIEW

**Comment by ron-murhammer** [comment]
@simon33-2 I thought invisible units such as factories were already being done in some maps? Do you have any threads or issues to reference on other folks looking for this feature? Have you gotten anyone else to test this?

**Comment by simon33-2** [comment]
I'm not aware of any maps with invisible factories? All this change does is make it possible to suppress the error for missing image. Perhaps they just live with the error in those maps.

**Comment by simon33-2** [comment]
Many people are interested in the universal scramble and the invisible units is a quick (and slightly dirty) way of doing it. Do the invisible factories just give missing image errors?

To be honest, this is a nice to have for me but I thought it was worth a try.

**Comment by DanVanAtta** [comment]
@simon33-2 there are a couple of items introducing some difficulty in accepting the updates as proposed:
- mixture of major elements. We can review the work here, but there are 2 or 3 different functionalities being introduced, and you'll have to work through them all before anything can be merged in.
- testing needs to be more significant and obvious (preferably fully automated). This is not an easy code base, and it's really easy to introduce major errors. Ideally there would be examples of XMLs and screenshots of the new invisible unit feature added. For a new feature it is generally better to discuss it first via an issue, otherwise there is risk of it not being accepted right away or at all sometimes.

**Comment by DanVanAtta** [comment]
Recommendations for moving forward: 
- do some git foo to pull the updates into independent changes
- avoid requiring a major number upgrade
- open an issue to highlight the invisible unit feature and how it will be used. (for context: my concern is that we have many incomplete or fully unused features in the codebase. The complexity of it I view as also a number 1 problem, my inclination then is to verify that the features we do add are at least done correctly and complete.)

**Comment by simon33-2** [comment]
Hi @DanVanAtta 
I have sympathy for your viewpoint today. Re: 1.9.1 version, that change was picked up from the other PR.

I'm going to close this issue off now so we can just talk about the much more important issues in #1599.

**Pull request closed without merging**
