### PR TITLE
Fix flickering issue

### LINKED ISSUE #3520: 10514 screen blanks after each move
### My Operating System
linux
### Map name
global 40 House rules
### Can you describe how to trigger the error? (eg: what sequence of actions will recreate it?)
every time you move a quick flash of a blank spot appears.

### Instead of this error, what should have happened?
it shouldn't happen
### Any additional information that may help
doesn't happen in 506

### PR DESCRIPTION
**Pull request by RoiEXLab**
Fix #3520 
Draw the image each time, not only when it's not dirty

### CODE REVIEW

**Comment by ron-murhammer** [comment]
@RoiEXLab So this change did impact the flickering but its still happening just in a bit different way. Before you could essentially see the whole tile or 2 go gray then be drawn. Now you kind of see just parts of them flicker and a bit faster than before.

**Comment by RoiEXLab** [comment]
@ron-murhammer I'm not observing any kind of flickering.
The only thing I'm seeing is the Tiles being loaded lazily if the area of the map hasn't been displayed before.

**Comment by Cernelius** [comment]
I believe it depends on how heavy the graphic is. I've a map I'm making that has **very** heavy graphic, and I can very clearly see flickering in there, while it is very hard to notice it in any of the repository maps I've tried so far. Sadly, that map I have is not released, so you cannot test with it, but I'll keep it tested for you (if that one would stop flickering, that would be pretty much assure there can be no flickering LOL).

**Comment by Cernelius** [comment]
Try to open "World At War" and move all units from Bohemia to Hungary. I see flickering in that move consistently, but not always. Eventually, keep undoing and redoing the move until you can perceive the flickering.
Sadly, I'm not finding a repository map that is heavy enough for the flickering to be more consistent.

**Comment by RoiEXLab** [comment]
#3528 Could fix this issue.
I'm seeing a small chance that this won't work, in which I have an idea that will most likely work (unless there's weird stuff going on)

**Pull request merged**
