### PR TITLE
Reduce size of PNG image files (optipng lossless compression)

### PR DESCRIPTION
**Pull request by DanVanAtta**
run 'optipng' on all PNG files, a losssless compression utility. In-place replacement of all PNG files with optimized, lossless compressed versions.  This saves about 17M on project size. The majority of that space savings is in the `maps` folder, the other large chunk is in the `docs` folder.

CLI run: `find . -name "*png" -type f | xargs optipng -o6 -strip all -zw 32k 2>&1 | tee ~/opti-output`

Note, the strip argument strips metadata, done intentionally as tripleA PNG files do not need metadata. 

Percentiles of file reduction, largest file reduction was 93.45%, smallest was by 0.02%

100% - 93.45 
 99% - 85.40
 90% - 68.94
 80% - 58.65
 50% - 35.84
 25% -  8.42
  0% -  0.02

Some screen shots showing before and after compression on maps, no difference can be observed (the lossless compression is by removing unused data, as opposed to jpeg or gif which will blur and do other interpolation techniques to reduce data stored)

lotr1
lotr2
pos1
pos2

[Review on Reviewable](https://reviewable.io/reviews/triplea-game/triplea/146)

### CODE REVIEW

**Comment by veqryn** [comment]
can you explain all the arguments you used?
does the compression work by combining closely related colors?

**Comment by DanVanAtta** [comment]
Can you point out exactly the arguments? I stated:
- "in-place replacement of PNG" This is fact and what happened
- "17M saved on project space", Again, this is what happened, disk usage reported 17MB less used space.
- "PNG files with optimized, lossless compressed versions."  I'll provide some background links on optiPng, it is a *loss-less* compression. More detail than that and we would start talking about how PNGs are compressed and how optiPNG functions. But in short, it optimizes the color pallette to not contain unnecessary data. There are various parameters for PNG compression, it needs CPU time to go through all the possibilities. Typically that does not happen. OptPNG with the settings I ran it with essentially finds the *best* PNG compression per PNG to optimize how much information is stored with each PNG file. It took quite a bit of crunching power to produce.
- "The majority of that space savings is in the maps folder, the other large chunk is in the docs folder." That is also just a statement of the results seen after running the operation.

- "Note, the strip argument strips metadata, done intentionally as tripleA PNG files do not need metadata."  yes, tripleA does not need PNG image metadata. We do not need to know when, where, or with which camera a picture was taken. We only want the bits that represent the image data, we don't need the other details that are more appropriate for personal photo catalogs or collections.

- "Percentiles of file reduction, largest file reduction was 93.45%, smallest was by 0.02%"  This was just doing some computations on the results. I sed'ed out the completion row data from the result output and the sorted it to find percentiles.

- "Some screen shots showing before and after compression on maps, no difference can be observed (the lossless compression is by removing unused data, as opposed to jpeg or gif which will blur and do other interpolation techniques to reduce data stored)" A subjective statement since it depends on observation. Though I would challenge anyone to tell me which side of the screen shots is compressed and which one is not compressed. The screenshots are proof in our context the compression does turn out to be lossless.  I did debate including them, typically when compression images with lossy compression you would want the before/after. Mainly I did want proof that the compression was in fact lossless. I also tested that images were compressed well, I did get an error message at "o7" compression that corrupted an image. Mainly that was the reason I went with "o6". 

"does the compression work by combining closely related colors?"
No, see above in this comment for more some more details. Or see the reading links below:


http://www.macworld.com/article/2045127/mac-gems-optipng-makes-png-files-smaller-without-losing-image-quality.html
http://optipng.sourceforge.net/pngtech/optipng.html
https://perishablepress.com/png-image-optimization/  
"...first (and most important) step in our image-optimization process, we want to run our PNG images through a command-line optimizer like OptiPNG or Pngcrush...Either of these powerful programs will remove unnecessary data from your PNG images without reducing image quality."

**Comment by veqryn** [comment]
by arguments, i meant this: `xargs optipng -o6 -strip all -zw 32k 2>&1 | tee ~/opti-output`

**Comment by DanVanAtta** [comment]
Ah, I should have just asked


-o6  :: this is the thoroughness for finding compression. 1 is minimum, 7 is max and slowest. 7 was too slow to be worth it, generally there was no compression saving and a few runs had errors even. 6 runs fast enough that it wasn't too bad waiting a few hours.

-strip all  :: says to strip all metadata


For zw, I tried different values with o2 and found that the largest generally had the most compression. Beyond tha I'll have to refer you to reference material on what that parameter does:

http://linux.die.net/man/1/optipng
```
-zw size
Select the zlib window size (32k,16k,8k,4k,2k,1k,512,256) used in IDAT compression.
The size argument can be specified either in bytes (e.g. 16384) or kilobytes (e.g. 16k). The default size value is set to the lowest window size that yields an IDAT output as big as if yielded by the value 32768.
The effect of this option is defined by the zlib(3) library used by OptiPNG.
```

The `| tee` is piping stdout to tee. Tee will print it's input on standard out and also the file. Thus you can watch the output and also have a file with the same output. The 2>&1 redirects standard error to standard out, optipng is a bit annoying by sending a lot of intermediary output to std err.

**Comment by DanVanAtta** [comment]
Let me know if there is anything more that I can answer. OptiPng is very nice since the only cost for the smaller files PNG files is CPU crunching time (lossless compression, image quality is retained). For one person to pay that cost and many to benefit, makes this a particularly beneficial change.

**Comment by veqryn** [comment]
I need to look into this utility a little more before I merge this, and I won't have time to do that today.
But from a general point of view, it looks good.

**Comment by DanVanAtta** [comment]
Fair enough, roughly zero chance of this having a merge conflict, so it'll sit around comfortably enough. 

Since we will be unavoidably adding 80MB to the repo when this is merged, arguably we should even wait until we are ready to perma-delete the previous object form the git object DB.

**Comment by veqryn** [comment]
Forgot about this PR for a while, sorry about that.
@DanVanAtta: Not sure what the merge conflicts are, but I am ready to merge this once that is fixed.

**Comment by DanVanAtta** [comment]
@veqryn  - merge conflicts were the chess/grid image removals. PR updated. Not sure if you caught it, Cernel successfully did an image comparison in Gimp to make sure optipng was lossless (http://tripleadev.1671093.n2.nabble.com/mp3-sound-files-tp7589462.html).

**Comment by DanVanAtta** [comment]
Alrighty, I believe I found the problem with this PR and how I've been using optipng.


Effectively you need to use optipng with the "-nx" for it to be actually lossless. For example, this kills the blend images on NWO:

```
dan@dan-desk:~/triplea/maps/new_world_order$ find . -name "*png" | parallel optipng  {}
```
While this does not:
```
dan@dan-desk:~/triplea/maps/new_world_order$ find . -name "*png" | parallel optipng -nx {}
```

I tried out the preserve flag, it did not seem to matter. Here is a portion from the optipng man page:

```
  -preserve
              Preserve file attributes (time stamps, file access rights, etc.) where applicable.



     -nb    Do not apply bit depth reduction.

       -nc    Do not apply color type reduction.

       -np    Do not apply palette reduction.

       -nx    Do not apply any lossless image reduction: enable the options -nb, -nc and -np.
```

**Pull request merged**
