### PR TITLE
Update triplea_maps.yaml

### PR DESCRIPTION
**Pull request by beelee1**
screwed up again. Here's hoping 3rd time's a charm

## Manual Testing Performed
- ..

### CODE REVIEW

**Comment by RoiEXLab** [comment]
@beelee1 FYI you can simply update the current branch (by choosing patch-<current revision> as your current branch) so you don't have to create a new pull request when you make a small mistake

**Comment by beelee1** [comment]
Can't figure out where I'm going wrong. Anyone know what this means ?

What went wrong:
610
Execution failed for task ':validateYamls'.
611
> /home/travis/build/triplea-game/triplea/triplea_maps.yaml: mapping values are not allowed here
612
   in 'reader', line 2010, column 13:
613
           mapName: Oztea 1939 Global

**Comment by RoiEXLab** [comment]
There are some typos. I'll fix them real quick

**Comment by RoiEXLab** [comment]
grafik
GitHub makes the issues real obvious, the error message is not really useful here TBH, but probably super accurate if you are into the YAML jargon 🤷‍♂

**Comment by beelee1** [comment]
Thanks Roi. I can stare at the thing over and over and still miss the littlest things. Ok so mapName wasn't lined up right that's what that error was saying in line 2010 and I missed a semicolon.

**Pull request merged**
