### PR TITLE
Refactor, move class LocalBeanCache to PBEMSetupPanel 

### PR DESCRIPTION
**Pull request by DanVanAtta**
PBEMSetupPanel.java is the only class that uses the 'LocalBeanCache.' The benefit here is we are reducing the overall complexity of the code base by isolating the LocalBeanCache with its one usage.

[Review on Reviewable](https://reviewable.io/reviews/triplea-game/triplea/337)

### CODE REVIEW

**Comment by ron-murhammer** [comment]
@DanVanAtta I'm kind of on the fence about this change. PBEMSetupPanel is already a pretty large class so making it even longer by adding LocalBeanCache isn't great. It does help isolate it though.

**Comment by DanVanAtta** [comment]
I'm not on the fence, I think this example is pretty clear cut. A public APIs implies a lot more complexity than a private API. PBEMSetupPanel is already a long awkward class. By adding privately scoped elements to it, we are not adding very much to that problem.

Meanwhile LocalBeanCache potentially used anywhere throughout the entire system is a much more signfiicant level of complexity to understand and deal with.

**Comment by ron-murhammer** [comment]
@DanVanAtta Gonna merge this. I guess my point is just because a class is only currently used in one place doesn't always mean its worth nesting it. I just don't want to end up with class files that have multiple nested classes and are thousands of lines long. Sometimes its just worth dividing up a class file into multiple class files just to make it more manageable even if it then exposes some behavior.

**Comment by DanVanAtta** [comment]
@ron-murhammer , I share some of that concern. I think when a person goes that route, moving the class(es) into their own package is a good way to go. This way public methods can be 'protected' except for where we have a public entry point into that new package.

In this case, I think we're grouping stuff up that needs to be broken down anyways into many smaller pieces. So bit of a case by case basis. Thank you for the review/discussion.

**Pull request merged**
