### PR TITLE
Enable 'units to place' panel by default.

### PR DESCRIPTION
**Pull request by asvitkine**
Enable 'units to place' panel by default.

This panel is no longer behind "beta" features toggle.
No change in functionality otherwise. Cleans up the previous code.

## Functional Changes

[] New map or map update
[X] New Feature
[] Feature update or enhancement
[] Feature Removal
[X] Code Cleanup or refactor
[] Configuration Change
[] Bug fix:  
[] Other:   

## Testing

[] No manual testing done
[X] Manually tested

### CODE REVIEW

**Comment by DanVanAtta** [comment]
I've no objection @asvitkine 

@ron-murhammer, any thoughts to making this feature prime-time?

We probably could use to give it a day or two for any last feedback from the forum thread.

**Comment by ron-murhammer** [comment]
@DanVanAtta I'm good with that especially as we still have a few bugs to fix in the pre-release so have some more testing time.

**Comment by RoiEXLab** [comment]
Hmm, for some reason this seems to have introduced a LGTM warning:
https://lgtm.com/projects/g/triplea-game/triplea/snapshot/7c493d894e4b54ef277ec4c495d5544eb4bbff6d/files/game-core/src/main/java/games/strategy/triplea/ui/PlacePanel.java?sort=name&dir=ASC&mode=heatmap#xefbae6956f69a293:1

**Comment by asvitkine** [comment]
Thanks, I'll take a look. Surprised this didn't get caught by CI during the PRs.

(I think it's a false positive due to the checker not being able to track when postProductionStep is true, but we can workaround that.)

**Pull request merged**
