### PR TITLE
Replaced Buffered Reader with Scanner (Fix #1525)

### LINKED ISSUE #1525: bad file descriptor endless printout - took the server down with full disk
server logs are full of the below repeated over and over again:

```
>>>>java.io.IOException: Bad file descriptor
        at java.io.FileInputStream.readBytes(Native Method)
        at java.io.FileInputStream.read(FileInputStream.java:255)
        at java.io.BufferedInputStream.read1(BufferedInputStream.java:284)
        at java.io.BufferedInputStream.read(BufferedInputStream.java:345)
        at sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:284)
        at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:326)
        at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178)
        at java.io.InputStreamReader.read(InputStreamReader.java:184)
        at java.io.BufferedReader.fill(BufferedReader.java:161)
        at java.io.BufferedReader.readLine(BufferedReader.java:324)
        at java.io.BufferedReader.readLine(BufferedReader.java:389)
        at games.strategy.engine.lobby.server.headless.HeadlessLobbyConsole.printEvalLoop(HeadlessLobbyConsole.java:69)
        at games.strategy.engine.lobby.server.headless.HeadlessLobbyConsole.lambda$start$263(HeadlessLobbyConsole.java:59)
        at java.lang.Thread.run(Thread.java:745)
```

```
danv@tripleawarclub:~$ wc -l nohup.out
431594515 nohup.out
```

### PR DESCRIPTION
**Pull request by RoiEXLab**
This should hopefully fix #1525.
Not sure if it really does though

### CODE REVIEW

**Comment by RoiEXLab** [comment]
Just noticed, that
```
while(true){
  if(condition){
    //stuff
  } else{
    break;
  }
}
```
should be replaced with
```
while(condition){
  //stuff
}
```

**Comment by DanVanAtta** [comment]
@RoiEXLab  i'm planning to rip out this loop entirely before the next lobby deployment.

**Comment by RoiEXLab** [comment]
@DanVanAtta what are your plans about this?
Are you planning a server interface/bus?
I think it would probably be the best, if we had one triplea lobby process, which could be accessed via commands via a localhost network connection and start bots as new threads itself...
This way we had no trouble regarding the accessibility and could even start the lobby server as a Linux service with automatic restarts on crashes

**Comment by RoiEXLab** [comment]
@DanVanAtta I think I have the perfect solution on how to manage the server:
We should let the lobby server listen on a port on localhost. This input stream will be our new way of communicating with the server.
Using `nc` we can send plain strings to our server, which will be the commands we control it with.
Using a custom service file (I did this with the nodebb forum) we can start the lobby server via `sudo service triplea_lobby start`.
If we write a bash script using `nc` we could send requests to the server by something like `./triplea_Server start bot 5`.
Of course this would require us of running the bots in the same process as the lobby server...

**Comment by DanVanAtta** [comment]
The server is already listening on port 3303. Can't we send `nc` commands to it today?

I was thinking of a custom service file. Solves our problem of knowing if server is running, restarting, and start-on-boot. I was also figuring we'd do something similar as well for the bots. We can't tie the bots to the lobby since we run bots on other servers.

**Comment by RoiEXLab** [comment]
We could send commands to 3303, but we'd still need to implement that + this would cause security issues, since port 3303 needs to be open for the Public?

**Comment by RoiEXLab** [comment]
@DanVanAtta also we don't need to exclusively tie the bots to the lobby...
We could just add a functionality to the server, which calls the main method for the bots with the correct params in a new thread which is stored in a thread array.

**Comment by DanVanAtta** [comment]
`new thread`, spawned from where? Are you considering the bot only services?

**Comment by DanVanAtta** [comment]
3303 is already open to public. We're basically sending custom commands, and in other cases we get a bit more sophisticated and do it via object serialization with RMI. At core we need a sane framework for doing object marshalling/unmarshalling, and then transmission. The key trick to this is we will control how the data is copied to and from network, which allows us to have backward-compatible fault tolerance.

**Comment by RoiEXLab** [comment]
A new thread spawned from the lobby process...
If we used 3303 couldn't someone just send a command like `start bot 5` etc. Because we didn't authenticated anyone?

**Comment by DanVanAtta** [comment]
Sorry, I was more referring to replacing RMI.
For bot setup, let's use /etc/init.d scripts? We could start with `service bot01 start`, and check status with `service bot01 status`

**Comment by RoiEXLab** [comment]
Np, yeah we could do that,the problem I see with this, is that using this method the amount of used bots is limited...
Technically We could write a script which creates a new service file, but I don't think thats optimal

**Comment by RoiEXLab** [comment]
@DanVanAtta nevermind, there seems to be a way http://stackoverflow.com/a/30457399

**Comment by RoiEXLab** [comment]
@DanVanAtta There's your working script!
https://github.com/triplea-game/lobby/pull/26

**Pull request closed without merging**
