### PR TITLE
Remove DoubleTextField in favour of JSpinner

### PR DESCRIPTION
**Pull request by RoiEXLab**
There is still a class Left called `IntTextField`, that essentially mirrors the behaviour of JSpinner as well, but it'll be tricky to remove that one, because there's a class `ScrollableTextField`, that depends on it, and is essentially a JSpinner that additonally has a max and min button

### CODE REVIEW

**Comment by ssoloff** [comment]
When I run Map Properties Maker and select **Show All Options**, the width of the **UnitsScale** field is way too big:

map-properties-maker-all-options

Does the same thing happen for you?

**Comment by RoiEXLab** [comment]
@ssoloff Yeah, noticed it as well, but I thought this was unrelated, I should've checked 😅
However a fix for this seems pretty straightforward.
Previously the super constructor was called to set the columns to 10, and I'm pretty sure something similar can be achieved for the JSpinner as well.

**Comment by RoiEXLab** [comment]
@ssoloff Updated, was acutally way more fiddling than I thought it would be...
Swing is weird.

**Comment by ssoloff** [comment]
@RoiEXLab The extreme width is apparently by design because the minimum and maximum values we're using are `Double#MIN_VALUE` and `Double#MAX_VALUE`, respectively, as explained in [this post](https://implementsblog.com/2012/11/26/java-gotcha-jspinner-preferred-size/).  I used the information from that post to restore the width to be based on the original "10 columns," whatever that happens to be for the current L&F:

```diff
diff --git a/src/main/java/games/strategy/engine/data/properties/DoubleProperty.java b/src/main/java/games/strategy/engine/data/properties/DoubleProperty.java
index c5fc773c8..4c8420700 100644
--- a/src/main/java/games/strategy/engine/data/properties/DoubleProperty.java
+++ b/src/main/java/games/strategy/engine/data/properties/DoubleProperty.java
@@ -1,6 +1,5 @@
 package games.strategy.engine.data.properties;
 
-import java.awt.Dimension;
 import java.io.File;
 import java.math.BigDecimal;
 import java.math.RoundingMode;
@@ -58,10 +57,16 @@ public class DoubleProperty extends AEditableProperty {
 
   @Override
   public JComponent getEditorComponent() {
-    final JSpinner field = new JSpinner(new SpinnerNumberModel(m_min, m_min, m_max, 1));
-    field.setValue(m_value);
+    final JSpinner field = new JSpinner(new SpinnerNumberModel(m_value, m_min, m_max, 1.0));
+
+    // NB: Workaround for JSpinner default sizing algorithm when min/max values have very large magnitudes
+    // (see: https://implementsblog.com/2012/11/26/java-gotcha-jspinner-preferred-size/)
+    final JComponent fieldEditor = field.getEditor();
+    if (fieldEditor instanceof JSpinner.DefaultEditor) {
+      ((JSpinner.DefaultEditor) fieldEditor).getTextField().setColumns(10);
+    }
+
     field.addChangeListener(e -> m_value = (double) field.getValue());
-    field.setPreferredSize(new Dimension(50, 20));
     return field;
   }
 
```

I tried the workaround discussed in the above post, and it worked, but it is not deterministic.  It depends on how `DecimalFormat` converts a `double` to a string.  In some locales, there may be thousands separators, while in others there won't be any separators.  So that using `0` for the (temporary) minimum value and `1000000000` for the (temporary) maximum value may yield a column count of 10 or 13.

**Comment by RoiEXLab** [comment]
@ssoloff I believe such a small difference in columns is OK.
Feel free to apply your patch to this branch and merge afterwards.
You should've sufficient rights to do so.

**Comment by ssoloff** [comment]
@RoiEXLab Hmm, for some reason, I'm getting an authentication error when I attempt to push changes to your branch.  I remember this working in the past, so I'm not sure what's different today.  Anyway, I just created a PR against your fork.

It's not so much getting the column count the same as the original code, but to avoid hard-coding a component's size in pixels.  In general, we should let the `LayoutManager` do its job so that a component's size can change as the L&F or system font DPI changes.

**Comment by RoiEXLab** [comment]
@ssoloff No problem. I just merged in the changes

**Pull request merged**
