### PR TITLE
Remove support for MD5Crypt authentication in P2P games

### PR DESCRIPTION
**Pull request by ssoloff**
## Overview

Removes support for MD5Crypt authentication in peer-to-peer network games (i.e. when connecting to a password-protected game server).  All stable releases in the wild for about a year now use HMAC-SHA512 authentication, so one more usage of the deprecated `Md5Crypt#hashPassword()` can be removed.

## Functional Changes

* Removed support for MD5Crypt authentication in peer-to-peer network games.

## Manual Testing Performed

Verified a client can connect to a password-protected server in the following scenarios:

* client: this branch, server: this branch
* client: this branch, server: 12226

:warning: Note that a 12226 client cannot connect to a server from this branch due to an oversight in the `ClientLogin#addAuthenticationResponseProperties()` method (that code should have actually tested to see if the challenge could be processed by the `Md5CryptAuthenticator` instead of simply assuming it could).  Since we've decided to break network compatibility, this shouldn't be a show-stopper, but consider this a heads-up.

### CODE REVIEW

**Comment by ssoloff** [comment]
@RoiEXLab 

> However before proceeding doing incompatible changes we should push a release with an updated dice server domain

Note that we've already broken compatibility with #4123 and #4190.  It sounds like we need to proceed with creating a hotfix branch for 1.9.0.0 and enable releases from there.

**Comment by RoiEXLab** [comment]
@ssoloff I was already aware of that, I was only reminded of this issue today by prastle's post in the forums today and I haven't really gotten around to open an issue for that.
AFAIK The config file can be edited as well, so there'd even be a good workaround

**Comment by ssoloff** [comment]
@RoiEXLab Sorry, I interpreted "before proceeding doing incompatible changes we should push a release" as pushing a new stable 1.9.0.0 release from `master`.  Just wanted to make sure everyone knew that is no longer possible. :smile:

**Comment by RoiEXLab** [comment]
@ssoloff That's why I was saying "proceeding" and not "starting" ^^

But thanks anyways for the heads up

**Pull request merged**
