### PR TITLE
Junit cleanup

### PR DESCRIPTION
**Pull request by RoiEXLab**
Follow up of #2493
This should address your issues @ssoloff

### CODE REVIEW

**Comment by RoiEXLab** [comment]
@ssoloff I found the required setting to scan just a single classpath.
Should I revert the class rename, or just keep it a some sort of non-force convention?

**Comment by RoiEXLab** [comment]
I believe that after this PR is merged the only remaining goal is to have jacoco collect the coverage of the integrationtests as well...

**Comment by ssoloff** [comment]
> I found the required setting to scan just a single classpath.
> Should I revert the class rename, or just keep it a some sort of non-force convention?

:+1:  I think we should just follow the convention that we only use the `IntegrationTest` suffix for actual integration tests to reduce any confusion.  So, let's just keep the renames submitted in this PR as they are.

**Comment by ssoloff** [comment]
> I believe that after this PR is merged the only remaining goal is to have jacoco collect the coverage of the integrationtests as well...

Just for clarification, we only want the integration test coverage reported as part of the `jacocoRootReport` task; we do not want it reported as part of the `jacocoJunit5TestReport` task.  This was a decision @DanVanAtta made a few months ago so that we don't rely on integration tests to boost our code coverage metrics.

With that being said, I see the problem you're talking about in that the JaCoCo agent is not attached to the integration tests.  That's again probably because we are running these tests outside of Gradle.  There's a way to [manually collect coverage](http://www.jacoco.org/jacoco/trunk/doc/agent.html) using JaCoCo.  You might be able to modify the `integTest` task to get the JaCoCo agent on the classpath when you run the JUnit `ConsoleLauncher`.  You just need to determine the path to the JaCoCo agent JAR from the installed Gradle dependency.

Note that once that's fixed, the `jacocoRootReport` task should not have to be modified.  It scans for all _*.exec_ files, so as long as one is created for the integration tests, it should Just Work.

**Pull request merged**
