### PR TITLE
PlayerID Get attachment + PurchasePanel cleanup

### PR DESCRIPTION
**Pull request by DanVanAtta**
First two commits are cherry-picked from other in-flight PRs.

[Review on Reviewable](https://reviewable.io/reviews/triplea-game/triplea/503)

### CODE REVIEW

**Comment by gaborbernat** [comment]
Reviewed 14 of 14 files at r1.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[src/games/strategy/common/swing/SwingComponents.java, line 92 \[r1\]](https://reviewable.io:443/reviews/triplea-game/triplea/503#-KBvLArykPw-maSGU1fT:-KBvLArykPw-maSGU1fU:1416534914) ([raw file](https://github.com/triplea-game/triplea/blob/dd3ca1e014cd90541747c66040d2e6fc084147ab/src/games/strategy/common/swing/SwingComponents.java#L92)):*
what's this, why is here, why is in comment?

---

*[src/games/strategy/common/swing/SwingComponents.java, line 95 \[r1\]](https://reviewable.io:443/reviews/triplea-game/triplea/503#-KBvLIuX4yoJM3r7QA7C:-KBvLIuX4yoJM3r7QA7D:206080879) ([raw file](https://github.com/triplea-game/triplea/blob/dd3ca1e014cd90541747c66040d2e6fc084147ab/src/games/strategy/common/swing/SwingComponents.java#L95)):*
a isYes name is more appropriate I think here

---

*[src/games/strategy/common/swing/SwingComponents.java, line 164 \[r1\]](https://reviewable.io:443/reviews/triplea-game/triplea/503#-KBvLdUxNQM6WEOxntic:-KBvLdUxNQM6WEOxntid:149299618) ([raw file](https://github.com/triplea-game/triplea/blob/dd3ca1e014cd90541747c66040d2e6fc084147ab/src/games/strategy/common/swing/SwingComponents.java#L164)):*
there should be spaces here between the variables

---

*[src/games/strategy/common/swing/SwingComponents.java, line 172 \[r1\]](https://reviewable.io:443/reviews/triplea-game/triplea/503#-KBvLlRaABIClAM34Dxx:-KBvLlRaABIClAM34Dxy:-1098485375) ([raw file](https://github.com/triplea-game/triplea/blob/dd3ca1e014cd90541747c66040d2e6fc084147ab/src/games/strategy/common/swing/SwingComponents.java#L172)):*
shouldn't this key be a static final class field? What are other keys possible, maybe make it part of enum?

---

*[src/games/strategy/triplea/printgenerator/SetupFrame.java, line 91 \[r1\]](https://reviewable.io:443/reviews/triplea-game/triplea/503#-KBvMAXfzRskMgLmK5Qw:-KBvMAXfzRskMgLmK5Qx:993007008) ([raw file](https://github.com/triplea-game/triplea/blob/dd3ca1e014cd90541747c66040d2e6fc084147ab/src/games/strategy/triplea/printgenerator/SetupFrame.java#L91)):*
xagain the spaces after comma 

---

*[src/games/strategy/triplea/ui/BattlePanel.java, line 129 \[r1\]](https://reviewable.io:443/reviews/triplea-game/triplea/503#-KBvMHmPB06jOzYGGNDD:-KBvMHmQF-1uSMXIYkj0:-470517520) ([raw file](https://github.com/triplea-game/triplea/blob/dd3ca1e014cd90541747c66040d2e6fc084147ab/src/games/strategy/triplea/ui/BattlePanel.java#L129)):*
comma

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/triplea-game/triplea/503)*

**Comment by DanVanAtta** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[src/games/strategy/common/swing/SwingComponents.java, line 92 \[r1\]](https://reviewable.io:443/reviews/triplea-game/triplea/503#-KBvLArykPw-maSGU1fT:-KBvPh1betGrAMZCE_dW:-1182335571) ([raw file](https://github.com/triplea-game/triplea/blob/dd3ca1e014cd90541747c66040d2e6fc084147ab/src/games/strategy/common/swing/SwingComponents.java#L92)):*
This is extracted code, it's left over from that. SwingComponents has gotten pretty rough and needs some cleanup. At the same time it's under heavy development. I'd like to continue work and then come back and see what still needs to be fixed. I've cut a tracking ticket for this task: https://github.com/triplea-game/triplea/issues/506

---

*[src/games/strategy/common/swing/SwingComponents.java, line 95 \[r1\]](https://reviewable.io:443/reviews/triplea-game/triplea/503#-KBvLIuX4yoJM3r7QA7C:-KBvPdd2DbFuSRxvSl9S:-807114145) ([raw file](https://github.com/triplea-game/triplea/blob/dd3ca1e014cd90541747c66040d2e6fc084147ab/src/games/strategy/common/swing/SwingComponents.java#L95)):*
No disagreement, though I would like to revisit later. This class is going to see a lot more work before things are over.

---

*[src/games/strategy/common/swing/SwingComponents.java, line 164 \[r1\]](https://reviewable.io:443/reviews/triplea-game/triplea/503#-KBvLdUxNQM6WEOxntic:-KBvOpyf5lpQ8joTfdrn:378693729) ([raw file](https://github.com/triplea-game/triplea/blob/dd3ca1e014cd90541747c66040d2e6fc084147ab/src/games/strategy/common/swing/SwingComponents.java#L164)):*
The whole class needs formatting.

---

*[src/games/strategy/common/swing/SwingComponents.java, line 172 \[r1\]](https://reviewable.io:443/reviews/triplea-game/triplea/503#-KBvLlRaABIClAM34Dxx:-KBvOf_UKB4X1WDYSqiA:-2044798246) ([raw file](https://github.com/triplea-game/triplea/blob/dd3ca1e014cd90541747c66040d2e6fc084147ab/src/games/strategy/common/swing/SwingComponents.java#L172)):*
The action map is local to the dialog. We would not expect any other keys, so really we just need any key value that is not in the default actionMap already.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/triplea-game/triplea/503)*

**Comment by DanVanAtta** [comment]
Rebased, @gaborbernat , anything outstanding?

**Comment by gaborbernat** [comment]
Reviewed 5 of 6 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/triplea-game/triplea/503)*

**Comment by gaborbernat** [comment]
:lgtm: 

---

Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/triplea-game/triplea/503#-:-KCoPKfj2rUStrpogPU0:980077423)*

**Comment by gaborbernat** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/games/strategy/triplea/printgenerator/SetupFrame.java, line 91 \[r1\]](https://reviewable.io:443/reviews/triplea-game/triplea/503#-KBvMAXfzRskMgLmK5Qw:-KCoPSK8yBQdgePZDR0k:285293411) ([raw file](https://github.com/triplea-game/triplea/blob/dd3ca1e014cd90541747c66040d2e6fc084147ab/src/games/strategy/triplea/printgenerator/SetupFrame.java#L91)):*
:ok_hand: 

---

*[src/games/strategy/triplea/ui/BattlePanel.java, line 129 \[r1\]](https://reviewable.io:443/reviews/triplea-game/triplea/503#-KBvMHmPB06jOzYGGNDD:-KCoPUZrtafBlSLa47zx:285293411) ([raw file](https://github.com/triplea-game/triplea/blob/dd3ca1e014cd90541747c66040d2e6fc084147ab/src/games/strategy/triplea/ui/BattlePanel.java#L129)):*
:ok_hand: 

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/triplea-game/triplea/503)*

**Pull request merged**
