### PR TITLE
add the shogun

### PR DESCRIPTION
**Pull request by TheDog-GH**

### CODE REVIEW

**Comment by beelee1** [comment]
try removing line 2766

**Comment by TheDog-GH** [comment]
@beelee1 
Thanks you saw I was struggling, I tried that, but it still fails.

I managed to make the arena_of_death map work, but not the_shogun, it will be something simple, just got to find it :-(

**Comment by beelee1** [comment]
hmm ... well ... sorry but idk. :) maybe ask roger

**Comment by beelee1** [comment]
@TheDog-GH this is what I get when I try to edit the yaml

Screenshot from 2022-09-03 01-18-54

This shows a line 2767 as well. Do you have the same ?

**Comment by TheDog-GH** [comment]
@beelee1  Thanks for trying to help.
I eventually got the 5 tests to work
I did nothing different but I can confirm that I put an extra blank line in, backspaced 3 times to remove tab/extra spaces.
I shall be polite and say this part of loading a map is very unsatisfactory  ;-)

Now I cannot write the changes/commits, and so it continues ...
https://github.com/triplea-game/triplea/pull/11040
https://github.com/triplea-game/triplea/pull/11041

**Comment by beelee1** [comment]
@TheDog-GH yes it is quite frustrating. Sometimes i have to go out to the backyard and punch some paper. Then I feel better : )

**Pull request closed without merging**
