### PR TITLE
Update triplea_maps.yaml

### PR DESCRIPTION
**Pull request by Navalland2**

### CODE REVIEW

**Comment by DanVanAtta** [comment]
@Navalland2 , the preview image is 10MB large, that'll be a really heavy preview image! Any chance you can shrink it down and reduce the file size?

**Comment by Navalland2** [comment]
I've just replaced it with the shrinked version but "LGTM analysis: Java" seems failing.

**Comment by DanVanAtta** [comment]
Could you check on the upload @Navalland2 ?
I don't see where the preview image is in: https://github.com/triplea-maps/aggression_1941

**Comment by Navalland2** [comment]
https://raw.githubusercontent.com/triplea-maps/aggression_1941/master/description/picture.png

**Comment by DanVanAtta** [comment]
You're on way here @Navalland2 
It looks like when the merge resolution was done the image link was removed. Please add it back in if you would, the link you provided in your last comment looks good.

**Comment by Navalland2** [comment]
LGTM doesn't approve whatever I do including not attaching an image.

**Pull request merged**
