### PR TITLE
Update triplea_maps.yaml...

### PR DESCRIPTION
**Pull request by panther2**
... to reflect https://github.com/triplea-maps/world_war_ii_global/pull/25
(wwII_global)

### CODE REVIEW

**Comment by RoiEXLab** [comment]
@panther2 I don't want to clutter the diff with all of your merge commits (try using "Rebase and merge" instead), could you edit this file in the online editor and push the change to a new branch?

**Comment by panther2** [comment]
@RoiEXLab 
Sorry, I fail to see how to use "Rebase and merge" as I do not use the Github client, but the web interface exclusively. 
With "push to a new branch" you mean a branch not in my fork, but a branch of the master of triplea-game/triplea?

**Comment by RoiEXLab** [comment]
@panther2
I assume you use Pull Request to bring your master branch up to date. When merging the PR, just press this little arrow next to the merge button to select "Rebase and merge" instead of "Create a merge commit", this will 1:1 copy master to your fork, instead of copying it and adding a commit indicating that it has been copied. 

If you use the webinterface, you can edit the file here on triplea-game/triplea
Of course you can't push the changes on your own, but you'll notice, that one of the options (not even sure if there are multiple ones) is creating a new branch on your fork and commit the changes there.
Then you just need to open a new PR and close this one.

**Comment by panther2** [comment]
@RoiEXLab 

I found out how to "Rebase and Merge" using another repo. I am very happy to finally be able to do it.
Thanks a lot for your guidance!  :smile:

**Pull request closed without merging**
