### PR TITLE
Fix get movable units comparator exception

### PR DESCRIPTION
**Pull request by ron-murhammer**
The issue appears to have been a potential integer overflow when subtracting hashcodes.

---
This change is [Reviewable](https://reviewable.io/reviews/triplea-game/triplea/630)

### CODE REVIEW

**Comment by DanVanAtta** [comment]
Glad to see we arrived at something of a fix. It does seem like we should be able to test this. I ran into trouble though, it looks like the map saves were corrupted on upload. Launching old map saves with new maps should work, we have the map name conversion logic in place to support that. I've been doing PBEM where my opponent has an old WaW while I have the new. I'm quite sure it should work. But, you perhaps will have no better luck if the files are corrupted..


Second question/item: There are a number of other similar blocks in this same file that look like:
```
         if (noTies) {
           return t1.hashCode() - t2.hashCode();
         } else {
           return 0;
         }
```
They would be buggy as well?

**Comment by ron-murhammer** [comment]
@DanVanAtta Yeah I couldn't get any of the uploaded saves to work. I'm about 98% sure this does fix it though. Good catch on potentially other similar errors. I search the code base for hashcode subtraction and found a few more that I fixed now.

This is actually not easy to unit test. The reason is you can't mock `hashcode()` with mockito. I actually spent a good chunk of time setting up unit tests then realized they wouldn't run. You essentially need some way to return/set the hashcode on a few units with one close to max integer value and one close to min integer value. Any ideas?

**Comment by gaborbernat** [comment]
the changes on their own seem good, so no reason not to merge them. Testing if #320 is actually fixed is harder on the other end.

**Comment by DanVanAtta** [comment]
@ron-murhammer  - thanks for taking a stab at the unit tests. If  you still have any, please send me a Gist of them if you would. I'm thinking a partial mock could maybe do the job, so we would only mock out the `hashcode()` method.

**Pull request merged**
