### PR TITLE
New installer (cross platform builder and Gradle powered entirely) - Release Candidate

### PR DESCRIPTION
**Pull request by gaborbernat**
Hello, 

I've managed to finalize the installer. It should work just fine. All that is needed to a release is to run the ./gradlew release task. 

Tested on UNIX the latest fix for now (however due to the nature of the fix should work just fine on Windows/Mac as tested earlier). If anyone has a Windows/Mac please run a quick test with the installers from: https://drive.google.com/folderview?id=0B42XvjSlpDCtZkhWejhScV9XaTg&usp=sharing. 

Do we have a place where we store private files? I'm referring now to the install4j license :+1: 

If you have any other questions please let me know. A quick how to:

- Add a Gradle task to make runnable the Linux Installer.
- a relase generation may be performed with the gradle task release
- install4j must be installed on the target system, and in the
  ~/.gradle/gradle.properties specify the installed dir by setting
  install4jHomeDir property
- after the task completes, installers are inside build/releases and
  zips are inside build/distributions

Note the version is no longer stored in Gradle file, so for this too work you'll need to set the current version inside the TRAVIS_TAG environment variable, before running the release task.

[Review on Reviewable](https://reviewable.io/reviews/triplea-game/triplea/218)

### CODE REVIEW

**Comment by DanVanAtta** [comment]
Build failed with compilation errors for test.
  symbol:   variable Matchers
  location: class DownloadFileParserTest
/home/travis/build/triplea-game/triplea/test/games/strategy/engine/framework/mapDownload/DownloadFileParserTest.java:30: error: cannot find symbol
    assertThat(desc.getMapName(), is("mySecondGame"));

Seems like the build.gradle file does not have the latest dependencies included.

**Comment by gaborbernat** [comment]
could be I missed something around the merge commits, will fix it later on.

**Comment by DanVanAtta** [comment]
Tried to test on win10 and got stuck. Gradle first error'ed and asked for install4jhome to be specified in ~/.gradle/gradle.properties. I did so, now I get a cannot normalize path error. Tried a couple of different syntax but no joy yet. This is where I am..

could_not_noramlize_error

**Comment by gaborbernat** [comment]
from the error I would say you need to specify relative path or try using a file object and get its absolute path :+1: the normalization error is because after the first C: there is a second error and according to the Windows file rules only one : can be present in a path :+1:

**Comment by gaborbernat** [comment]
pushed a fix for the failing tests :) now should be okay

**Comment by gaborbernat** [comment]
Any updates on this?

**Comment by DanVanAtta** [comment]
From my side, will hope to test the linux side of this tomorrow, and give the win10 test another try tomorrow as well.

**Comment by gaborbernat** [comment]
okay, note you'll need the license file to actually do the install4j build on your machine, still haven't decided how to share this privately inner team.

As test I recommend using my builds at https://drive.google.com/folderview?id=0B42XvjSlpDCtZkhWejhScV9XaTg&usp=sharing Thanks.

**Comment by gaborbernat** [comment]
any updates? :)

**Comment by DanVanAtta** [comment]
> "Actually the licence file is just a key, but you got my point. Maybe create a triplea gmail user and put it in it's driver, share the file for each developer after authentication and trust?"

If it's just a key, we can set it as a secret environment variable in travis. If we need to have it checked in  we can encrypt it with travis  and  have the encrypted version be checked-in as plain text.

**Comment by ron-murhammer** [comment]
@gaborbernat Just tried this today and end up with the same error as @DanVanAtta posted above:
"Tried to test on win10 and got stuck. Gradle first error'ed and asked for install4jhome to be specified in ~/.gradle/gradle.properties. I did so, now I get a cannot normalize path error. Tried a couple of different syntax but no joy yet. This is where I am.."

**Comment by gaborbernat** [comment]
guys, even if the path normalization is fixed, you'll still need the key. I'm still waiting for you to porpose a way to store/share the key between trusted users.

**Comment by DanVanAtta** [comment]
The most important is that travis is able to get access to the secret key. How is the key found by install4j? Is it a file it finds at a specific location, is it a file whose location is passed in as an arg, or is the key value passed in as a parameter?

If the key is passed in as a file, this should hopefully do: http://docs.travis-ci.com/user/encrypting-files/

If the key is passed in as an arg, then we can take the same approach as we do for the secret personal access token that is used to push tags. Namely put the secret value in a travis environment variable that we can then use. For example: `$ install4j --secret-key=$TRAVIS_SECRET_KEY`, this way the key is never actually shown to anyone but can still be used by travis.

Otherwise to pass around the key for testing purposes, or one-off builds, probably email or IM.

**Comment by gaborbernat** [comment]
You guys both tried locally, which is a non-travis enviroment, please
propose a solution for that too.

**Comment by DanVanAtta** [comment]
GPG encryption/decryption will do the trick, the only difference between local and travis would be how the GPG passphrase is provided as an environment variable.

**For both local and travis the gpg decryption command will be:**
`echo $gpg_key | gpg license.txt.gpg`

For extra simplicity, dev's will store the GPG key in a file: `~/.github/triplea_gpg_key`, then instead of using an echo command it then becomes a `cat` command:  `cat ~/.github/triplea_gpg_key | gpg license.txt.gpg`  (note, the decrypted value never appears on the command line or in the command history, someone would have to read the file to get the key)


**To do the file encryption:**
```
$ vi ~/.github/triplea_gpg_key  ## create something 1024 characters+ with lots of randomness, then copy it to your clipboard
$ gpg -c license.txt ## you'll be prompted for the encryption password twice, paste it
$ git commit license.txt.gpg -m "Add encrypted install4j license file"
```

** Then the last steps will be to update .travis.yml:**
You'll need to add the encrypted environment variable and second add the command to decrypt the license file using that environment variable.

```
$ sudo gem install travis
$ travis encrpyt gpg_key=$(cat ~/.github/triplea_gpg_key) --add
```

Now notice that the .travis.yml file has been modified. When travis decrypts the secret chunk of text it'll read the environment variable "gpg_key" along with the encrypted value. 


Fix the formatting error travis introduces when it wraps "--pull" to a new line, then finally add the decryption command:
```
before_install:
  - echo $gpg_key | gpg super_secret.txt.gpg
```

In total, .travis.yml should have some new lines at the end of the file only, should look something like this:
```
env:
  global:
    secure: ... encoded secret ...
before_install:
  - echo $gpg_key | gpg license.txt.gpg
```


** Caution, it's possible for travis output to display the value of environment variables in error messages. So be a bit careful about that otherwise a secret value might get stored in the travis build history output. Sometimes this can be fixed by re-running the build, sometimes not though.

**Comment by gaborbernat** [comment]
Wouldn't this make the installer generation not run on Windows?

Bernát GÁBOR

**Comment by DanVanAtta** [comment]
Windows can decrypt GPG files, but it looks like an encrypted file is unnecessary and we can simply pass in the license key on the command line. The install4j command can look something like this: `install4j [args] -L  $INSTALL4J_LICENSE_KEY`, where `$INSTALL4J_LICENSE_KEY` is a secret environment variable set in the travis UI (I can take care of this once the license key has been shared).

To share the license key with the team, one way would be to copy it to a "secret" github Gist and (privately) share the link with us. Then delete the Gist after 24 or 48 hours.

**Comment by veqryn** [comment]
fyi: please email me the key instead of using a pastebin/gist (same goes for any other critical account stuff)

**Comment by DanVanAtta** [comment]
#### On security of emails/pastebin (for the record)
Please never send anything that is supposed to be secure via email or via pastebin (and yeah, the bot password will need changing accordingly).

Pastebin is scraped very quickly by many people and then stored in searchable databases. Gist doesn't suffer from that yet, it has more namespaces as well so it may never suffer from that problem.

Email is kept around forever and is not encrypted. If your email account were ever compromised then this secret would be given up too. Tying things together like that could then lead to more of your account and information being compromised. Also though we've been entrusted with a secret key from install4j. As an org I think we have something of a responsibility to follow some basic and real security practices to protect that secret.

But with all that said, I'm more concerned that we get this done rather than worrying so much about email a gist link vs emailing an actual value.

**Comment by gaborbernat** [comment]
Managed to specify the install4j path on Windows:

install4jHomeDir=C://data/install4j6

note no quotes required.

**Comment by gaborbernat** [comment]
So I've managed to get this working on Windows. There are still a couple of hurdles that make it hard to implement the automated Travis release process. Here's how to get this working: 

1. Install install4j latest
2. Set into the gradle.properties the path to the install directory, no quotes: install4jHomeDir=C://data/install4j6
3. Specify the license key (at the moment the Gradle API does not support this, probably due security reasons). So the only option is to either start up the graphical interface and enter it; or write it inside the ~/.install4j/config.xml 
4. Download the JRE for Mac (1.8.0.66 MAC x64) and Windows (1.8.0.66 Windows X86). For this did not found a command line option yet. 
5. open up a terminal set the travis tag to the version as enviroment variable; run the generateInstallers commnad.

**Comment by gaborbernat** [comment]
I think the current state completes this ticket. Travis integration should be a different one, as its scope it's different.

**Comment by DanVanAtta** [comment]
The trick for the license file is to run `install4jc -L $license` once after installing it. Then gradle can just run.

I tested the build process and got it to work in travis even with a few changes. The linux and windows installer also looked good for the most part (https://github.com/DanVanAtta/triplea/releases). #260 filed for the cannot find root folder warning message that has cropped up again.

**Comment by DanVanAtta** [comment]
Note, merged since this is adding stuff and won't hurt the java code. Meanwhile it does look like things work, and we need to merge in the end to really see if the release stuff will work. Opene #261 to add in some last changes to make the installer work with travis.

**Comment by veqryn** [comment]
@DanVanAtta @gaborbernat 
The changes to GameRunner2 break old jar compatibility.  Is this intended?

**Comment by gaborbernat** [comment]
It is, as part of fixing the warning message pointed out in #260. However,
from what I saw that part of code was never called when using the all
platforms zip.

Bernát GÁBOR

**Comment by veqryn** [comment]
`getTripleaJarWithEngineVersionStringPath` is called in two places, not sure how you came to that conclusion...

**Comment by gaborbernat** [comment]
I was not saying it's not called anytime. I said it's not called during the all platforms zip. I think this is related to #260 , now that we added a new number into the version, maybe we should continue this talk there.

**Comment by DanVanAtta** [comment]
Added a testing task to verify old engine jar compatibility to #262

**Comment by veqryn** [comment]
@gaborbernat @DanVanAtta actually it is not related to 260 at all.
it shouldn't matter what the directory is called, and it never has.
if you look at where getTripleaJarWithEngineVersionStringPath is being called, it is only related to finding the root folder IF we are an old engine jar, or determining if we are an old engine jar.

the change you guys made to GameRunner2 needs to be undone.  please undo it.

**Comment by gaborbernat** [comment]
Sorry for being stubborn but why do we care for old engine jar? Old engine
jar should still have the old game runner, does not?

**Comment by veqryn** [comment]
1 We won't be able to find the old engine jars if we change the naming schema in one place but not in another.
2 Inconsistent naming schema
3 Why is this being changed anyway? It is not related to the build process, and it doesn't fix the bug in 260 anyway?

I don't care if you guys want to change it, but put it in a different PR and change it in all places (including renaming the existing old engine jars).  I would also want to know why it is being changed...

**Comment by veqryn** [comment]
@DanVanAtta I think you merged this pr too early without proper review, considering it touched more than just the build scripts.  Should we revert it, undo the changes to GameRunner2, and then re-merge?  Or should we just make a new PR to undo the changes?

**Comment by veqryn** [comment]
@gaborbernat:
I am getting the following errors trying to do gradle release.
I have put in the license info already.

```01:19:31.640 [INFO] [org.gradle.process.internal.DefaultExecHandle] Successfully started process 'command 'C:\Users
\cduncan\programs\install4j6\bin\install4jc.exe''
01:19:32.265 [ERROR] [system.err] install4j: missing config file argument
01:19:32.272 [ERROR] [system.err] Usage: install4jc [OPTIONS] [config file]
01:19:32.278 [ERROR] [system.err] Try 'install4jc --help for more information'
01:19:32.374 [DEBUG] [org.gradle.process.internal.DefaultExecHandle] Changing state to: FAILED
01:19:32.381 [DEBUG] [org.gradle.process.internal.DefaultExecHandle] Process 'command 'C:\Users\cduncan\programs\install4j6\bin\install4jc.exe'' finished with exit value 1 (state: FAILED)
01:19:32.389 [DEBUG] [org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter] Finished executing task ':generateInstallers'
01:19:32.397 [LIFECYCLE] [class org.gradle.TaskExecutionLogger] :generateInstallers FAILED
01:19:32.426 [ERROR] [org.gradle.BuildExceptionReporter]
01:19:32.434 [ERROR] [org.gradle.BuildExceptionReporter] FAILURE: Build failed with an exception.```

It appears we are not specifying a config file for install4j

**Comment by gaborbernat** [comment]
Actually the issue you see is that you have not set in the environment the
version number (TRAVIS_TAG, or what other Dan renamed it to in the
meantime).

Bernát GÁBOR

**Comment by gaborbernat** [comment]
It's just that the format used is:

install4jc -v ${version_number} ${config_file}

if you fail to set the version number then the config file is taken as version number, hence your error :)

**Comment by veqryn** [comment]
Ok, where/how does that get set?  Is it in a file? Is it an env variable?

**Comment by gaborbernat** [comment]
It's an environment variable as usually with Travis. In build.gradle look for the version setting:

 version = System.getenv("TRAVIS_TAG") ?: ""

For the actual parameter name. This here is for this pull request, @DanVanAtta renamed that variable in the meantime for some reason.

**Comment by veqryn** [comment]
Ok. Is it reasonable to expect people to be setting this?  We should have a default or something if it is not available

**Comment by gaborbernat** [comment]
We can change the empty to something like "not_set", but that would not obey our version scheme. 

Originally the version number was set explicitly in file, as in case of Ant, however @DanVanAtta removed that and changed to the upper format, probably for Travis interoperability. But I've already wrote upper about this requirement... strange that this just came up :)

**Comment by veqryn** [comment]
We could use 0.0.0.0 as a default.

Anyway, i am still have issues even after doing `export TAGGED_VERSION=1.1.1.1`:
```
Loading config file C:\Users\cduncan\workspace\eclipse\triplea\build.install4j
Creating media file 'Windows':
  Collecting files:
  Compiling launchers:
    Compiling launcher 'TripleA':
      Generating VM options file TripleA.vmoptions.
    Compiling launcher 'triplea-headless':
      Generating VM options file triplea-headless.vmoptions.
  Creating media file:
    Generating custom installer icon
    Zipping custom code & resources JAR file
    Identifying components
    [WARNING] The version of the bundled JRE is too low. It should be at least 1.6!
    Adding JRE (jre-8u66-windows-x86)
install4j: compilation failed. Reason: java.io.FileNotFoundException: Could not find JRE bundle. Neither C:\Users\cduncan\programs\install4j6\jres\jre-8u66-windows-x86.tar.gz nor C:\Users\cduncan\.install4j6\jres\jre-8u66-windows-x86.tar.gz nor C:\Users\cduncan\workspace\eclipse\triplea\jre-8u66-windows-x86.tar.gz exist.:generateInstallers FAILED```

**Comment by DanVanAtta** [comment]
@veqryn , yes apologies i got tunnel vision testing the install4j stuff and getting it to work. Spent 5 hours on that today and forgot there were any java changes in here at all.  As far as the updates, we have to solve the problem anyways before the next release. We've an issue to keep tabs on it. We can revert the java changes, but we are still just trading one problem for another.

**Comment by gaborbernat** [comment]
@veqryn 

Sigh, please read my upper post:

So I've managed to get this working on Windows. There are still a couple of hurdles that make it hard to implement the automated Travis release process. Here's how to get this working:

1. Install install4j latest
2. Set into the gradle.properties the path to the install directory, no quotes: install4jHomeDir=C://data/install4j6
3. Specify the license key (at the moment the Gradle API does not support this, probably due security reasons). So the only option is to either start up the graphical interface and enter it; or write it inside the ~/.install4j/config.xml
4. Download the JRE for Mac (1.8.0.66 MAC x64) and Windows (1.8.0.66 Windows X86). For this did not found a command line option yet.
5. open up a terminal set the travis tag to the version as enviroment variable; run the generateInstallers commnad.

As the error message tells you, you've failed to download the JRE.

**Comment by DanVanAtta** [comment]
@veqryn  You need to download the two JRE's mentioned in the error message and deploy them to the install4j home, jre's folder. The two JRE's are here: https://github.com/triplea-game/assets/tree/master/install4j

**Comment by DanVanAtta** [comment]
With respect to old engine code, it should use an old algorithm to find any needed jar dependencies. It doesn't make much sense for an old engine jar to need the new engine jar code. By this token we might be okay actually in terms of version compatibility. Specifically @gaborbernat  the test would be to launch an old game engine save using a new game engine and verify that it finds the root folder without problem.

**Comment by veqryn** [comment]
@gaborbernat: yes, i read that, but did not understand what you meant.  i thought i already had the windows jre because it is on my system.  the directions could have been a little more explicit, i did not realize you had to do this through install4j's UI.

@DanVanAtta: once the old engine jar is running, it doesn't need/care/know-about the new engine jar.  But if you try to load an old savegame with either jar file active, it will not be able to find the version matching it if we have changed the filename format.  Does this make sense?

**Comment by DanVanAtta** [comment]
@veqryn That does make sense.  I'd like to work with @gaborbernat to look at the problem in detail so we can come up with a complete solution. It won't be immediate, but we'll get it done well before the next release.

@veqryn w.r.t JREs - the name of the JRE file needs to match what is in the build.install4j file as well. I'm not sure where install4j gets the JREs.

@gaborbernat The JRE in the asset repo is from oracle, not install4j. Any insight if there is much differences? (new issue if there is much to discuss there) IE: see the changes I made in #261 to the build.install4j file.

**Comment by veqryn** [comment]
It seems even after downloading the JRE bundles, you have to go in and change their names to match what the script wants.  They get downloaded (if you use install4j's UI [i did not see Dan's reply about them being in the assets repo until after i started downloading them]), they come as `windows-x86-1.8.0_66.tar.gz` but need to be `jre-8u66-windows-x86.tar.gz`

**Comment by veqryn** [comment]
Question: for windows users with x64 computers, will the released windows version force them to use the bundled jre or will it choose the system jre first if it exists?

**Comment by DanVanAtta** [comment]
pretty sure bundled. Looked that way on the win10 virt I was testing with.

This explains then where the JREs were coming from (install4j has gui to download them, I was working with it purely on command line). The JREs checked in are from oracle.

**Comment by gaborbernat** [comment]
I would oppose using the Oracle. I think we should stick with the install4j download. Maybe it has some extra required meta embedded, or could be in the long run. I see that change you made, and I do not like it. :| 

There is an option in install4j for using system/bundled. I prefer bundled because that way we can control the users Java version.

**Comment by veqryn** [comment]
Some of our users set their max memory quite high, and x86 only allows 4g max.  We should bundle both x86 and x64 for windows and linux users.

I finally got gradlew release to work, but the all platforms zip does not have any executables or scripts in it. is this desired?

**Comment by DanVanAtta** [comment]
About the version number. Pretty clearly we want it to be in one place and not many. We had it I think in 3 places. It now is in 2. Sorry if this wasn't clear to everyone, I thought it had been well communicated (but perhaps not).

So those 2 places that store the: 1.8.0.10 version number are:
- travis build environment variable (which is just a shell environment variable, nothing special)
- java code

For java code, maybe instead of hardcoding we could read it from a file. The build process could also probably be driven by the same file rather than it being driven by an environment variable.

**Comment by veqryn** [comment]
Previous to this it was only in 2 places as well, the .ant.properties and the java code.  If we do switch to using a file, it needs to not be editable by the end user.  Not sure how we would do that, maybe put it into the data directory and have it get packed into the jar file, and sign the jar.

**Comment by DanVanAtta** [comment]
The user can simply edit the file directly, no? The Java reads it with standard IO. Then the build process instead of having the variable hardcoded is updated like this:
`TAGGED_VERSION=$(cat version_file)`

So then whatever is in the file is the version number.

**Comment by veqryn** [comment]
I mean that if the java code is reading the version number from a file, that file should not be editable by our end users (the people who play the game), otherwise that would cause hell in the lobby.

**Comment by DanVanAtta** [comment]
It's not much different if someone compiles the code with a different version number. Having it in plain text would make it more tempting though. Maybe we encode the number in hex, or some other simple obfuscation.

**Comment by veqryn** [comment]
Well, right now someone can change it in the java code in plain text.  But it does mean they need to recompile and run it.  I just want to stop average users from going in and editing a text file.  
This could be accomplished by packing the text file into the jar (just like with do with some other simple resources, like the game.dtd) and signing the jar, i think...

**Comment by DanVanAtta** [comment]
@gaborbernat I'd like to know more about the JRE you would like bundled. As a linux user, I use the Oracle JRE not because I love oracle, but because I have to. The open source implementation lags and is buggy.

Travis builds and tests with the oracle JDK. It's less liability that we use that JRE. I think we need to have more reason than philosophical dislike of proprietary software and oracle. There is are two practical reasons for going with an oracle JRE that I've mentioned.   Let's pls  discuss more in #263

**Comment by veqryn** [comment]
@gaborbernat & @DanVanAtta: Good job on this.  I haven't tested any of the installers yet, but this is great progress.

Also, please merge https://github.com/triplea-game/triplea/pull/264 (and we won't have to revert this pr)

**Comment by DanVanAtta** [comment]
Version number - I recall now the practical reason for pulling it out of the build file is so a code commit was not required each time we update it for non-major releases.

For local builds, getting 0.0.0.0 for the version number instead of empty string when the environment variable is missing is reasonable. Version number doesn't make too much sense anyway when talking about local builds (which are probably going to be forks)

**Comment by veqryn** [comment]
Ok, new issues: I just tried the windows installer and it errors out by saying "you do not have permission to install in that directory".
Why doesn't it ask for permission?

**Comment by veqryn** [comment]
Problem number 2, we install directly into the directory they specify, instead of into a sub directory with our version number.
Are we not allowing people to install multiple versions anymore?

**Comment by DanVanAtta** [comment]
Win8? Also, are you overwriting or creating a new folder in terms of install location?


About problem 2, that is something I noticed. @gaborbernat , looks like the install behavior changed slightly.

**Comment by veqryn** [comment]
Problem number 3, and the reason why #260 has an error: the installed jar file in the bin directory is called `triplea-1.1.1.1-all.jar` instead of `triplea.jar` (like it is with all previous releases, and with the current all platforms zip).  
Fix this and you will fix #260

@DanVanAtta: I am Win7, and i get this permission issue regardless of whether or not the folder exists (i tried both ways).

**Comment by DanVanAtta** [comment]
Created #265 to talk about problem 2 in more detail.

For permissions, is there a run as administrator option or something? It did work on win10, I would think it  should also on win7 without too much additional effort. Would be good to rule out local problems, particularly at least so we can document them and give people a heads up.

**Pull request merged**
