### PR TITLE
Change installer name

### PR DESCRIPTION
**Pull request by RoiEXLab**
Based on #2031
Notable Changes:
Installation entry on windows no longer looks like this: 
Screenshot
And looks more like this: 
Screenshot
The new installer gives the possibility to autoremove any old TripleA versions if the user wants to. We can still have multiple TripleA versions in parallel.
@ssoloff Can you confirm protocol handlers are still working on linux systems?
I fear that the desktop files no longer are always named `TripleA-0.desktop`, but `TripleA-1.desktop` etc. instead for example...

### CODE REVIEW

**Comment by ssoloff** [comment]
@RoiEXLab Sure, I will test on Linux, but I probably will not get to it until tomorrow.

**Comment by ssoloff** [comment]
@RoiEXLab Removing the version number from the generated installer files breaks the `setRunnableLinux` Gradle task (which is only useful for local installer builds).  The following change should fix it:

```diff
diff --git a/build.gradle b/build.gradle
index 950118f..2e0b08b 100644
--- a/build.gradle
+++ b/build.gradle
@@ -209,8 +209,7 @@ task generateInstallers(type: Install4jTask, dependsOn: [renameShadowJar, copyJR
 
 task setRunnableLinux(dependsOn: [generateInstallers]) {
     doLast {
-        def linuxFile = "TripleA_${version}_unix.sh"
-        ant.chmod(dir: "$buildDir/releases", perm: '+x', includes: linuxFile)
+        ant.chmod(dir: "$buildDir/releases", perm: '+x', includes: 'TripleA_unix.sh')
     }
 }
```

**Comment by ssoloff** [comment]
@RoiEXLab Here's the results of my tests on Linux...

#### Protocol handlers

The `triplea:` protocol handler appears to no longer work.  Typing `triplea:<something>` into Firefox simply triggers a search for the entered string.

The name of the desktop file created by the installer is `TripleA-<version>-0.desktop`.

I also noticed there's now a `TripleA-<version>.desktop` file (note no trailing `-0`) in the install directory.  I don't remember if that file was there before.

#### Installation over existing install

The default install path is now `~/TripleA` instead of `~/TripleA_<version>`.  I don't think this is a problem because most users will want to install over the previous version anyway.  For those of us who install versions side-by-side, it's not a big deal to change the install path to include the version.

I created two different versions of the installer with different versions (1.9.0.0.7777 and 1.9.0.0.8888).  I installed 7777 first to `~/TripleA` and then attempted to install 8888 to the same folder.  Everything appeared to work with one exception: I was prompted to overwrite the `.vmoptions` file.  Apparently, this file was not removed during the automatic uninstall (I didn't modify it after the previous install).  You might want to check the changes from the previous PR that modified this file to see if there's a way to avoid this prompt.  (Note that if I manually run the uninstaller, the `.vmoptions` file is removed without any prompt.)

#### Installer file names

Now that you are not including the version number in the name of the file output by the installer, those files need to be manually renamed when building the installer from Gradle (you already updated the Travis build script to do this).  It might be better to do the renames as part of the Gradle build so that the local and Travis builds have the same effect.

My recommendation would be to transform the existing `setRunnableLinux` task into something like `prepareInstallers` that does the renames, in addition to setting the executable bit for the Linux installer (in which case, my previous comment about `setRunnableLinux` being broken can be ignored).  Then all the rename logic can be removed from `.travis/build_installers`.

**Comment by RoiEXLab** [comment]
> I was prompted to overwrite the .vmoptions file.

@ssoloff This is intended, but I see this can get annoying pretty fast.
I changed this setting to "Overwrite if newer, otherwhise ask", which should be a better option.

**Comment by RoiEXLab** [comment]
> My recommendation would be to transform the existing `setRunnableLinux` task into something like `prepareInstallers` that does the renames, in addition to setting the executable bit for the Linux installer (in which case, my previous comment about `setRunnableLinux` being broken can be ignored).  Then all the rename logic can be removed from `.travis/build_installers`.
@ssoloff I believe this is out-of-scope for this PR, but definitely a good change, which could get rid of the `build_installers` file entirely

**Comment by RoiEXLab** [comment]
Ok @ssoloff I fixed the protocols, and I'd appriciate if you could double-check if everything is working.
The trailing `-0` is for the special case in which the exact same version is installed twice (e.g. the same installer is executed twice and the installation directory is changed). In this case the installation directory is not being updated, because I have no idea how to detect which "additional version" we are. Also this shouldn't change anything, because it's still the same version right?
The desktop file in the installation directory was there before. Nothing changed there.

**Comment by ssoloff** [comment]
@RoiEXLab 

> I fixed the protocols, and I'd appriciate if you could double-check if everything is working.

I confirmed the protocol handler is working again on Linux.  Good job!

> In this case the installation directory is not being updated, because I have no idea how to detect which "additional version" we are. Also this shouldn't change anything, because it's still the same version right?

That sounds right, but I'm not 100% sure without testing that scenario.

> The desktop file in the installation directory was there before. Nothing changed there.

Thanks for pointing that out.  I confirmed that file is present when installing from `master`.  I think I never noticed it before because I still typically disable the **Create symlinks** checkbox.

@ron-murhammer, @DanVanAtta Any further comment on this PR?

**Comment by RoiEXLab** [comment]
@ssoloff I reverted some changes...
Install4j now renames the files correctly without any additional script. Therefore the other changes were no longer needed.
I also enabled pack200 compression, which reduced the file size of the installer even more, but makes the installer a couple seconds slower ^^ (took about 5 seconds zu decompress the packed jar file on my powerful machine instead of being instantly)

**Comment by ssoloff** [comment]
> Also md5sums are no longer generated.
> 
> 1. We don't use them

Yup, we should probably be uploading a file that contains checksums for **all** files (not just the installers) we publish to GitHub releases.  And that file itself should probably be signed.  This [project](https://github.com/syncthing/syncthing/releases/) seems to do something like that.

> 2. MD5 is broken

Agreed, we should be using a different hash function.

**Comment by RoiEXLab** [comment]
Bumping @ron-murhammer @DanVanAtta

**Comment by ron-murhammer** [comment]
Seems fine to me. Merging.

**Pull request merged**
