### PR TITLE
Encoded value fix for empty string

### PR DESCRIPTION
**Pull request by DanVanAtta**
## Overview
After setting test value for lobby server port and then unsetting, this code can throw an integer parse exception trying to parse an empty string. This simple fix checks for an empty string and returns null skipping the integer parsing.

## Manual Testing Performed
-I'm not 100% sure of the repro case, though when I hit this error, this update fixed the situation. Otherwise, the error occurs on game launch and prevents the main window from loading.

### CODE REVIEW

**Comment by DanVanAtta** [comment]
I don't know if it matters 100% how the empty string gets in there. Defending against any possible empty string to be set seems to be brittle compared to interpreting empty string to be the same as null.

On master, whenever I load the settings window I get an error message and stack trace:
```
WARNING: Failed to decode encoded value: '' in client setting 'TEST_LOBBY_PORT'
games.strategy.triplea.settings.ClientSetting$ValueEncodingException: java.lang.NumberFormatException: For input string: ""
	at games.strategy.triplea.settings.IntegerClientSetting.decodeValue(IntegerClientSetting.java:22)
	at games.strategy.triplea.settings.IntegerClientSetting.decodeValue(IntegerClientSetting.java:3)
	at games.strategy.triplea.settings.ClientSetting.decodeValueOrElseDefault(ClientSetting.java:297)
	at java.util.Optional.map(Optional.java:215)
	at games.strategy.triplea.settings.ClientSetting.getValue(ClientSetting.java:291)
	at games.strategy.triplea.settings.ClientSetting.isSet(ClientSetting.java:227)
	at games.strategy.engine.lobby.client.login.LobbyServerPropertiesFetcher.getTestOverrideProperties(LobbyServerPropertiesFetcher.java:84)
	at games.strategy.engine.lobby.client.login.LobbyServerPropertiesFetcher.getTestOverrideProperties(LobbyServerPropertiesFetcher.java:73)
	at games.strategy.engine.lobby.client.login.LobbyServerPropertiesFetcher.fetchProperties(LobbyServerPropertiesFetcher.java:60)
	at games.strategy.engine.lobby.client.login.LobbyServerPropertiesFetcher.fetchLobbyServerProperties(LobbyServerPropertiesFetcher.java:53)
	at games.strategy.debug.ErrorMessage.serviceClient(ErrorMessage.java:138)
	at games.strategy.debug.ErrorMessage.setUploadRecord(ErrorMessage.java:117)
	at games.strategy.debug.ErrorMessage.show(ErrorMessage.java:104)
	at games.strategy.debug.ErrorMessageHandler.publish(ErrorMessageHandler.java:44)
	at games.strategy.debug.ErrorMessageHandler.publish(ErrorMessageHandler.java:38)
	at java.util.logging.Logger.log(Logger.java:738)
	at java.util.logging.Logger.doLog(Logger.java:765)
	at java.util.logging.Logger.log(Logger.java:876)
	at games.strategy.triplea.settings.ClientSetting.decodeValueOrElseDefault(ClientSetting.java:299)
	at java.util.Optional.map(Optional.java:215)
	at games.strategy.triplea.settings.ClientSetting.getValue(ClientSetting.java:291)
	at games.strategy.triplea.settings.SelectionComponentFactory$2.<init>(SelectionComponentFactory.java:206)
	at games.strategy.triplea.settings.SelectionComponentFactory.intValueRange(SelectionComponentFactory.java:204)
	at games.strategy.triplea.settings.ClientSettingSwingUiBinding$18.newSelectionComponent(ClientSettingSwingUiBinding.java:229)
	at java.util.Map.computeIfAbsent(Map.java:957)
	at games.strategy.triplea.settings.SettingsWindow.buildTabPanel(SettingsWindow.java:125)
	at games.strategy.triplea.settings.SettingsWindow.lambda$newContentPane$0(SettingsWindow.java:94)
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
	at games.strategy.triplea.settings.SettingsWindow.newContentPane(SettingsWindow.java:94)
	at games.strategy.triplea.settings.SettingsWindow.open(SettingsWindow.java:78)
	at games.strategy.triplea.settings.ClientSetting.showSettingsWindow(ClientSetting.java:195)
	at games.strategy.engine.framework.startup.ui.MetaSetupPanel.lambda$setupListeners$5(MetaSetupPanel.java:120)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
	at org.pushingpixels.substance.internal.utils.RolloverButtonListener.mouseReleased(RolloverButtonListener.java:108)
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289)
	at java.awt.Component.processMouseEvent(Component.java:6539)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6304)
	at java.awt.Container.processEvent(Container.java:2239)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2297)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4904)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4535)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4476)
	at java.awt.Container.dispatchEventImpl(Container.java:2283)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:760)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:84)
	at java.awt.EventQueue$4.run(EventQueue.java:733)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:730)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.lang.NumberFormatException: For input string: ""
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:592)
	at java.lang.Integer.valueOf(Integer.java:766)
	at games.strategy.triplea.settings.IntegerClientSetting.decodeValue(IntegerClientSetting.java:20)
	... 70 more
```

I've also seen this error on startup when the settings have been applied and that is a severe problem as the game will not load properly in that case. I'm not sure how to repro that situation, the error I'm seeing whenever loading settings window is current though.

**Comment by DanVanAtta** [comment]
Screenshot from 2019-03-31 09-47-18


PS: if any user hits the case where they see this error on start-up, it's an extremely bad error as the game is un-launchable. A player would have to get a code patch or a hack their registry.

**Comment by RoiEXLab** [comment]
@DanVanAtta Fair point, but what about a general error handling for this case?
If we catch all exceptions in format and decode and just clear the the individual setting in this case, that would be a cleaner approach IMO. Thoughts?

**Comment by DanVanAtta** [comment]
Treating empty string as a null does not seem to be a big leap. We should try to force only valid numbers to be added, though if a user enters nothing for a port number then it is an empty string. We had a previous comment for a user to enter '0' to null out a value, which is a hack IMO and we did not enforce a value to be set in the port override field. Worse yet, the revert to defaults seems to introduce this problem without any kind of explicit user input. 

On the other hand catching any kind of exception seems like control-flow by exception handling. We also do not expect to see alpha characters and that indicates we've failed to constraint user input or some other problem.

**Comment by DanVanAtta** [comment]
> @DanVanAtta Fair point, but what about a general error handling for this case?
If we catch all exceptions in format encode and decode and just clear the the individual setting in this case, that would be a cleaner approach IMO. Thoughts?

Let's say somehow we do allow a user to add an alpha character. If we clear the value, then it's a silent failure. We would be override a user value to something else without notifying the user.

This violates the UX principle of "respect user choices and selections". If a user makes a choice or selection, it should never be cleared out by the software, that choice should be respected. It's like clicking 'back' in a browser and having all form fields revert back. When a user specifies something, either that should happen, or there should be an error at that time. Failing later is a bug.

**Comment by DanVanAtta** [comment]
merging this to get it out of the way, sorry to not have the time to take the comment suggestion @RoiEXLab

**Pull request merged**
