### PR TITLE
Remove commented out code from 121 files

### PR DESCRIPTION
**Pull request by DanVanAtta**
There's no easy way I know of to remove commented out code. I did some searches in eclipse and deleted a whole lot of it, over 5000 lines. It's very clear none of it needs to stick around. There were maybe about 30 or 40 lines I left in, and 10 or 20 that were borderline and deleted.

FYI #58 merged into this PR, so merging this one would merge them both. Or you can merge #58 first and the merged commits between the two PRs would fall away from this one.

[Review on Reviewable](https://reviewable.io/reviews/triplea-game/triplea/54)

### CODE REVIEW

**Comment by veqryn** [comment]
Reviewed 113 of 170 files at r1.
Review status: 113 of 170 files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

<sup>**[src/games/strategy/common/ui/BasicGameMenuBar.java, line 233 \[r1\]](https://reviewable.io:443/reviews/triplea-game/triplea/54#-JwSiJsq0xOrEOptgXcz)** ([raw file](https://github.com/triplea-game/triplea/blob/5e934bad4029b4a33769230d48afcf997a138391/src/games/strategy/common/ui/BasicGameMenuBar.java#L233)):</sup>
We should either delete this method instead, OR keep the comments telling why we are not implementing it.

---

<sup>**[src/games/strategy/common/ui/BasicGameMenuBar.java, line 562 \[r1\]](https://reviewable.io:443/reviews/triplea-game/triplea/54#-JwSinuXZCQAfp_f34LE)** ([raw file](https://github.com/triplea-game/triplea/blob/5e934bad4029b4a33769230d48afcf997a138391/src/games/strategy/common/ui/BasicGameMenuBar.java#L562)):</sup>
Why delete comments? I thought you were just deleting dead code...

---

<sup>**[src/games/strategy/triplea/ai/proAI/ProPurchaseAI.java, line 706 \[r1\]](https://reviewable.io:443/reviews/triplea-game/triplea/54#-JwSqFD6mzl6vTFqIOEF)** ([raw file](https://github.com/triplea-game/triplea/blob/5e934bad4029b4a33769230d48afcf997a138391/src/games/strategy/triplea/ai/proAI/ProPurchaseAI.java#L706)):</sup>
I think redrum wants to keep this

---

<sup>**[src/games/strategy/triplea/delegate/AirMovementValidator.java, line 236 \[r1\]](https://reviewable.io:443/reviews/triplea-game/triplea/54#-JwSrDPspzHtnGzgckG4)** ([raw file](https://github.com/triplea-game/triplea/blob/5e934bad4029b4a33769230d48afcf997a138391/src/games/strategy/triplea/delegate/AirMovementValidator.java#L236)):</sup>
Can you instead combine the comment lines and put them on a new line?

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/triplea-game/triplea/54)

**Comment by veqryn** [comment]
@DanVanAtta can you fix, then i'll merge

**Comment by DanVanAtta** [comment]
Don't quite follow regards to what I need to fix. I see the conflicts for commit b33085b that were already resolved.  Those conflicts are from the first round of formatting. So I already integrated once there. The second round of formatting that is in-flight, I already tried merging and the merge conflict is almost 100 files. So I abandoned that until I have to.

---

Review status: 113 of 170 files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

<sup>**[src/games/strategy/common/ui/BasicGameMenuBar.java, line 233 \[r1\]](https://reviewable.io:443/reviews/triplea-game/triplea/54#-JwSiJsq0xOrEOptgXcz)** ([raw file](https://github.com/triplea-game/triplea/blob/5e934bad4029b4a33769230d48afcf997a138391/src/games/strategy/common/ui/BasicGameMenuBar.java#L233)):</sup>
Let's remove the method as a second PR?

---

<sup>**[src/games/strategy/common/ui/BasicGameMenuBar.java, line 562 \[r1\]](https://reviewable.io:443/reviews/triplea-game/triplea/54#-JwSinuXZCQAfp_f34LE)** ([raw file](https://github.com/triplea-game/triplea/blob/5e934bad4029b4a33769230d48afcf997a138391/src/games/strategy/common/ui/BasicGameMenuBar.java#L562)):</sup>
The comments comment the dead code. The comments have nothing useful to the existing code. 

---

<sup>**[src/games/strategy/triplea/ai/proAI/ProPurchaseAI.java, line 706 \[r1\]](https://reviewable.io:443/reviews/triplea-game/triplea/54#-JwSqFD6mzl6vTFqIOEF)** ([raw file](https://github.com/triplea-game/triplea/blob/5e934bad4029b4a33769230d48afcf997a138391/src/games/strategy/triplea/ai/proAI/ProPurchaseAI.java#L706)):</sup>
In code is not the right place to keep it. How much of this code still compiles? Will this implementation be correct when it is uncommented and the day comes we want to implement it? Will this implementation be complete, why not also code in other stuff? I notice there are about a half dozen places for NPE as well. 

It could be appropriate to save it in a ticket.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/triplea-game/triplea/54)

**Comment by veqryn** [comment]
Review status: 113 of 170 files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

<sup>**[src/games/strategy/common/ui/BasicGameMenuBar.java, line 233 \[r1\]](https://reviewable.io:443/reviews/triplea-game/triplea/54#-JwSiJsq0xOrEOptgXcz)** ([raw file](https://github.com/triplea-game/triplea/blob/5e934bad4029b4a33769230d48afcf997a138391/src/games/strategy/common/ui/BasicGameMenuBar.java#L233)):</sup>
Ok, as long as you remember to do it.

---

<sup>**[src/games/strategy/common/ui/BasicGameMenuBar.java, line 562 \[r1\]](https://reviewable.io:443/reviews/triplea-game/triplea/54#-JwSinuXZCQAfp_f34LE)** ([raw file](https://github.com/triplea-game/triplea/blob/5e934bad4029b4a33769230d48afcf997a138391/src/games/strategy/common/ui/BasicGameMenuBar.java#L562)):</sup>
They seem related to the method and how it applies to Mac OS, and whether we need to do something about it or not...

---

<sup>**[src/games/strategy/triplea/ai/proAI/ProPurchaseAI.java, line 706 \[r1\]](https://reviewable.io:443/reviews/triplea-game/triplea/54#-JwSqFD6mzl6vTFqIOEF)** ([raw file](https://github.com/triplea-game/triplea/blob/5e934bad4029b4a33769230d48afcf997a138391/src/games/strategy/triplea/ai/proAI/ProPurchaseAI.java#L706)):</sup>
Then remove the code part and change it to do a TODO comment reminding of what is missing / what needs to be done here.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/triplea-game/triplea/54)

**Comment by DanVanAtta** [comment]
Review status: 113 of 170 files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

<sup>**[src/games/strategy/triplea/ai/proAI/ProPurchaseAI.java, line 0 \[r1\]](https://reviewable.io:443/reviews/triplea-game/triplea/54#-JwSqFD6mzl6vTFqIOEF)** ([raw file](https://github.com/triplea-game/triplea/blob/5e934bad4029b4a33769230d48afcf997a138391/src/games/strategy/triplea/ai/proAI/ProPurchaseAI.java#L0)):</sup>
Done.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/triplea-game/triplea/54)

**Comment by DanVanAtta** [comment]
Review status: 113 of 170 files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

<sup>**[src/games/strategy/common/ui/BasicGameMenuBar.java, line 233 \[r1\]](https://reviewable.io:443/reviews/triplea-game/triplea/54#-JwSiJsq0xOrEOptgXcz)** ([raw file](https://github.com/triplea-game/triplea/blob/5e934bad4029b4a33769230d48afcf997a138391/src/games/strategy/common/ui/BasicGameMenuBar.java#L233)):</sup>
Done.

---

<sup>**[src/games/strategy/common/ui/BasicGameMenuBar.java, line 562 \[r1\]](https://reviewable.io:443/reviews/triplea-game/triplea/54#-JwSinuXZCQAfp_f34LE)** ([raw file](https://github.com/triplea-game/triplea/blob/5e934bad4029b4a33769230d48afcf997a138391/src/games/strategy/common/ui/BasicGameMenuBar.java#L562)):</sup>
The code block is copy paste from below, it blows up on Mac, so that is probably the reason it was commented out. The comment below it is to explain why the top half of the method, likely cloned from the bottom half, is different. I added the core of that comment back in, that AWT components prompt for overwrite. I also found a couple of other quick easy fixes while scanning to this spot, some other small things that need to be removed (empty javadoc, another block of commented out code, some e.printStackTrace lines - newest revision has the updates.)

---

<sup>**[src/games/strategy/triplea/delegate/AirMovementValidator.java, line 0 \[r1\]](https://reviewable.io:443/reviews/triplea-game/triplea/54#-JwSrDPspzHtnGzgckG4)** ([raw file](https://github.com/triplea-game/triplea/blob/5e934bad4029b4a33769230d48afcf997a138391/src/games/strategy/triplea/delegate/AirMovementValidator.java#L0)):</sup>
Done.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/triplea-game/triplea/54)

**Comment by DanVanAtta** [comment]
Review status: 113 of 170 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

<sup>**[src/games/strategy/triplea/ai/proAI/ProPurchaseAI.java, line 706 \[r1\]](https://reviewable.io:443/reviews/triplea-game/triplea/54#-JwSqFD6mzl6vTFqIOEF)** ([raw file](https://github.com/triplea-game/triplea/blob/5e934bad4029b4a33769230d48afcf997a138391/src/games/strategy/triplea/ai/proAI/ProPurchaseAI.java#L706)):</sup>
Created issue: https://github.com/triplea-game/triplea/issues/69 to track the code sample and desire to allow AI to place in allied territories.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/triplea-game/triplea/54)

**Comment by veqryn** [comment]
Review status: 113 of 170 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

<sup>**[src/games/strategy/triplea/ai/proAI/ProPurchaseAI.java, line 706 \[r1\]](https://reviewable.io:443/reviews/triplea-game/triplea/54#-JwSqFD6mzl6vTFqIOEF)** ([raw file](https://github.com/triplea-game/triplea/blob/5e934bad4029b4a33769230d48afcf997a138391/src/games/strategy/triplea/ai/proAI/ProPurchaseAI.java#L706)):</sup>
This is not done.  I asked this to be added back as a TODO comment, not another git issue.  Redrum is presently working on these files, and if he wants to make some notes in them, then he can.  This is clearly notes, not dead code.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/triplea-game/triplea/54)

**Comment by veqryn** [comment]
Reviewed 55 of 170 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/triplea-game/triplea/54)

**Pull request merged**
