### PR TITLE
Make Comparator be Serializable

### PR DESCRIPTION
**Pull request by DanVanAtta**
Only one example found where we had a non-serializable comparator.

Identified by this automatic code report: Reports on subclasses of java.lang.Comparator which are not also Serializable. Objects of java.util.TreeMap or java.util.TreeSet will become non-Serializable if instantiated with such Comparators. This can result in unexpected and difficult-to-diagnose bugs. Since subclasses of java.lang.Comparator are often stateless, simply marking them Serializable is a small cost to avoid such issues.

### CODE REVIEW

**Comment by ssoloff** [comment]
This appears to be the right thing to do (all comparators returning by the `Comparators` factory methods are `Serializable`). However, it seems there's several other `Comparator` subtypes in our code that are not `Serializable` (e.g. `RandomStartDelegate$UnitCostComparator`, `UnitBattleComparator`, etc.).

What heuristics are your code analyzer using that it thinks `AlphanumComparator` is the only non-`Serializable` comparator in the code?  Is it only looking for stateless comparators?

**Comment by DanVanAtta** [comment]
@ssoloff just pushed a couple more changes, some of the comparators can be simplified to built-in, and a little bit of scope creep to fix up RandomStartDelegate warnings

**Comment by DanVanAtta** [comment]
Let's merge if all looks good and build passes, no more changes intended for this branch  : )

**Comment by ssoloff** [comment]
@DanVanAtta Heh, I hit the merge button just as you pushed and was rejected.

I reviewed the latest commit, and all looks good. :+1:

**Comment by ssoloff** [comment]
Build failed due to a network error.  I restarted the failing job,

**Pull request merged**
