### PR TITLE
Remove nodraw

### PR DESCRIPTION
**Pull request by RoiEXLab**
This doesn't seem to be used (There is no such system property on my system)
This seems to be some sort of "workaround" for a legacy version of java (I assume Java 6): http://www.oracle.com/technetwork/java/javase/java2d-props-142956.html
This change only affects windows if it affects anything at all

### CODE REVIEW

**Comment by ssoloff** [comment]
This code was added in 76c57e9.  Probably safe to remove as it was added specifically to fix an issue on Windows 98.

It would be interesting to look up the original bug report, but I don't know what bug tracker the ID `1742775` refers to.  That bug ID doesn't exist on the old SF project.  But, if IIRC, SF used to allow you to run custom apps (e.g. Trac, Bugzilla, etc.), so those old issues may have been lost when SF discontinued support for those apps.

**Comment by RoiEXLab** [comment]
@ssoloff Conflicts have been resolved

**Comment by ssoloff** [comment]
@ron-murhammer This looks ok to merge, but do you have any history here beyond what I added above?  Just in case this property is more important than it appears...

**Comment by ron-murhammer** [comment]
Yeah, no history with this. I agree that it appears to be unnecessary at this point. Merging.

**Comment by ssoloff** [comment]
Thanks, @DanVanAtta!  Can you elaborate on how you got from 1742775 to SF bug #372?  I tried searching the SF bug database with 1742775 but came up empty.  That's why I assumed it referred to a different bug tracker.

**Comment by DanVanAtta** [comment]
@ssoloff  I got a bit lucky finding it. From the bug tracker I looked at the URL and saw an ID at the end, so I  tried directly: https://sourceforge.net/p/triplea/bugs/1742775. It then redirected to bug 372.

**Comment by ssoloff** [comment]
@DanVanAtta Thanks.  Good to know that trick the next time I need to go back in time. :smile:

**Pull request merged**
