### PR TITLE
Remove deprecated method only used in debug logging

### PR DESCRIPTION
**Pull request by DanVanAtta**

### CODE REVIEW

**Comment by ssoloff** [comment]
@ron-murhammer Could you make the call on removing this method, please?  I remember you adding some debug-related engine logging recently (not in this class, but somewhere).  I'm not sure if this is useful information we're willing to take the performance hit on.

**Comment by ron-murhammer** [comment]
Could we instead make the method private? That way we don't need to worry about it being used outside of this class.

**Comment by DanVanAtta** [comment]
We need to think about this a bit differently. 

Benefit:
- almost none. Knowing which territory a unit is in helps pinpoint the unit, but if we have 100 units in the territory it still does not even help. Even if we do the know the unit, it still brings us no closer to knowing what the problem is. The debugging does not really tell us much

Cost:
- big scary comment, took 5 minutes to realize this was debug only code. Maintaining it seems the wrong investment
- the debug only is really questionable, this is pretty clearly temp logging that was added in to try and help fix a problem, it's been some time, it has not been of help. 
- YAGNI, it's just yet more code to maintain.

**Comment by ron-murhammer** [comment]
@DanVanAtta Knowing the territory can help track down the issue. This issue usually has to do with something got messed up with game data through units being changed or added in properly. I would say just remove the comment or minimize it.

**Comment by DanVanAtta** [comment]
@ron-murhammer I don't think it does actually. It's a feel good thing. If we were debugging this problem, let's say you find out it's one of the infantry in Moscow, then what? Either way we'd need a save and probably step through with a debugger.

**Comment by ron-murhammer** [comment]
Might be. If you really feel strongly about removing it then I'm ok with that. Just worried we end up seeing this error again in the future then add it back in :)

**Comment by DanVanAtta** [comment]
@ron-murhammer thanks, yeah, YAGNI. If we do run into this problem, the territory of the unit is not the information we would be seeking, I'm not concerned that we'd re-add this code for serialization debugging.

**Pull request merged**
