### PR TITLE
Consolidate TestData to utility classes

### PR DESCRIPTION
**Pull request by DanVanAtta**
- Reduces redundancy
- Extracts data setup from unit tests
- Allows for future data changes to be done in one place

 

## Functional Changes

[] New map or map update
[] New Feature
[] Feature update or enhancement
[] Feature Removal
[x] Code Cleanup or refactor
[] Configuration Change
[] Bug fix:  
[] Other:   

## Testing

[x] No manual testing done
[] Manually tested

### CODE REVIEW

**Comment by DanVanAtta** [comment]
> Hmm, not sure if I like that there are 3 classes with the same name and almost the same content, this might cause some confusion in the future.

How would you envision that confusion manifesting? I'm thinking that given they all serve the same purpose, the scoping of the different objects available will prevent any errors/issues.

**Comment by RoiEXLab** [comment]
I always think of the most common scenario how I navigate through code:
Let's say I create a PR with some refactoring changes and forget fixing the tests. The build fails and in the logs I see the class name with the issue.
I go back to the code, change the data and for some reason the test still fails.
Until I realise that I was simply looking at the wrong class at least 5 minutes will have passed.

I don't think this is an absolute blocker, I'm just saying that this might potentially be a think too look out for

**Comment by DanVanAtta** [comment]
Compilation errors should be highlighted in-file, the path is fully qualified in logs, and searching for a class and seeing multiple results I hope is all enough where it'll never take 5 minutes: 
Screenshot from 2019-10-11 18-23-04

**Comment by DanVanAtta** [comment]
Agree there could be confusion perhaps, but I think it's a bigger problem if the classes served different purposes and weren't standardized in form/purpose. I don't think artificially naming them otherwise at this juncture quite makes sense either.

**Pull request merged**
