### PR TITLE
Flaky coverage

### PR DESCRIPTION
**Pull request by RoiEXLab**
Another iteration that tries to get rid of flaky coverage

**I'd recommend reviewing with whitespace changes off**

## Functional Changes

[ ] New map or map update
[ ] New Feature
[ ] Feature update or enhancement
[ ] Feature Removal
[x] Code Cleanup or refactor
[ ] Configuration Change
[ ] Bug fix:  
[ ] Other:   

## Testing

[x] No manual testing done
[ ] Manually tested

### CODE REVIEW

**Comment by RoiEXLab** [comment]
Of course Decoder wants attention now as well

**Comment by DanVanAtta** [comment]
Looks fine :+1: 
 Kinda curious where/what the inconsistent coverage was, I did not spot it.

**Comment by RoiEXLab** [comment]
Well I'm really relying on codecov here to see what kind of coverage changes all of the time.
I assume that the flaky coverage is caused by non-deterministic behaviour of tests that test battles: Sometimes dice roll differently, so specific code paths may never be triggered

**Comment by DanVanAtta** [comment]
I think I realized late, after you mention it, one way to fix that is to test the code-path that is sometimes tested explicitly, in which case it is always tested. Not a bad strategy  :+1:

**Pull request merged**
