### PR TITLE
Display logo on launch screen

### PR DESCRIPTION
**Pull request by DanVanAtta**
### Before
Screenshot from 2020-09-14 19-46-48

### After
Screenshot from 2020-09-14 19-27-00

Screenshot from 2020-09-14 19-47-45

### CODE REVIEW

**Comment by DanVanAtta** [comment]
Fixed up the colspan of the logo, looks a bit better now:

Screenshot from 2020-09-14 20-29-49

**Comment by DanVanAtta** [comment]
Row indexing was off, that is fixed now:
Screenshot from 2020-09-14 21-34-38

**Review by RoiEXLab — APPROVED** [review]
👍

**Comment by RoiEXLab** [comment]
@DanVanAtta Just realizing this now, but where did the "Download Maps" button go?

**Comment by tvleavitt** [comment]
> @DanVanAtta Just realizing this now, but where did the "Download Maps" button go?

I can confirm that I'm seeing this as well. Was it intentional? If not, then we should open a new issue, I think.

**Comment by tvleavitt** [comment]
triplea-lefhand-2 3 21550

**Comment by DanVanAtta** [comment]
Fixed the missing download button in: https://github.com/triplea-game/triplea/pull/7675

**Comment by FrostionAAA** [comment]
May I present an alternative logo design for use in 2.3?
I think the current 2.3 logo seems a bit different than what we are used to on the website and forum. Also the current 2.3 design has a strange shadow cut at the bottom. So I made this one if we would want to use it. Maybe this should be brightened light 5-10% to look better, but this is easily fixed:
TripleA-Logo-30pct

TripleA-Icon-128

[TripleA-New-Logo.zip](https://github.com/triplea-game/triplea/files/5380746/TripleA-New-Logo.zip)

23Logo

**Comment by FrostionAAA** [comment]
Do you guys, @DanVanAtta @tvleavitt @RoiEXLab , actually get informed about a new post here in this conversation after it is closed or merged? I am just speculating if anyone actually read my post ;-)

**Comment by prastle** [comment]
Hi Frosti yes we get them.  If you are subscribed to github

**Comment by FrostionAAA** [comment]
OK. Well, I still think that the TripleA logo in the launcher looks strange and out of place, as the style, look and red color of the logo does not fit the logo displayed at triplea-game.org, on the Forum or during game install. These logos are all of a better quality. Also there are graphical shadow issues with this current launcher logo image.
MapOrGame

**Comment by DanVanAtta** [comment]
@FrostionAAA there is a forum thread around this, submissions of an alternative logo are welcome.=

**Comment by FrostionAAA** [comment]
OK thx.

**Pull request merged**
