### PR TITLE
Revert "fix_mac_icon.sh - Fix DOS end of line character used in script."

### PR DESCRIPTION
**Pull request by DanVanAtta**
This reverts commit f1b80152cf29f07c1f3336ffebcd934ce15e956a.

[Review on Reviewable](https://reviewable.io/reviews/triplea-game/triplea/89)

### CODE REVIEW

**Comment by ron-murhammer** [comment]
Looks like @veqryn already merged a pull request to fix this. Can we close this?

**Comment by DanVanAtta** [comment]
One PR was to update the release branch, this PR is to update master with the same change.

**Comment by DanVanAtta** [comment]
Note, #87 and #88 are similar, one is for the release branch, the other is for master.

**Comment by ron-murhammer** [comment]
Yeah I merged the one for the release branch and then noticed that the fix had already been made to master so I think this is redundant now.

**Pull request closed without merging**
