### PR TITLE
Extract get lobby node method and fix parallel lists

### PR DESCRIPTION
**Pull request by DanVanAtta**
Extract redundant code block in LobbyGamePanel. Sits on top of common work in commit 3669b1d, which will be in another pull request.

[Review on Reviewable](https://reviewable.io/reviews/triplea-game/triplea/110)

### CODE REVIEW

**Comment by ron-murhammer** [comment]
@DanVanAtta Looks good. Nice refactoring.

**Comment by veqryn** [comment]
@ron-murhammer @DanVanAtta:
Hold up here guys, there are some very major problems with this PR, and I think it wasn't tested, otherwise they would have been caught.
You are putting GameDescription into a Tuple, and then using .equals() on this tuple, but GameDescription does not override .equals or hashcode.
This means that when the tuple gets sent over the network, two tuples with the same effective GUID + GameDescription will not be equal, because they will be different == instances.
This is why the previous code used only GUID for the comparison.

**Comment by ron-murhammer** [comment]
@veqryn All the places I saw were using the tuple.getFirst() which is the GUID when doing .equals() checks. Can you reference the line number where you see the issue?

**Comment by veqryn** [comment]
Line 87 is at least one place.

**Comment by veqryn** [comment]
I think instead of a Tuple, you should use a Map

**Comment by ron-murhammer** [comment]
Oh I gotcha. You mean implicitly through indexOf and remove. I believe you are correct then that this shouldn't work.

**Comment by ron-murhammer** [comment]
Yeah, map should work since you only really want to compare the GUID not both fields when checking equality.

**Comment by veqryn** [comment]
@DanVanAtta: can you issue a new PR that switches this to a Map instead of a tuple, please?

**Comment by DanVanAtta** [comment]
GameDescription does not need to implement equals for purposes of  the indexOf call.  Note that in the prior statements we get the exact Tuple we need to remove, so the instances are guaranteed to be equal ("=="):

```
+        Tuple<GUID, GameDescription> gameToRemove = findGame( gameId );
+        if( gameToRemove != null ) {
+          int index = gameList.indexOf(gameToRemove);
```

Tthe findGame(gameId) function iterates over the List<Tuple> and uses the GUID to locate the game, so we do not rely on GameDescription equality.


The serialization problems with GameDescription not implementing equals I think probably already existed with the List<GameDescription>
```
-  private final List<GUID> m_gameIDs = new ArrayList<GUID>();
-  private final List<GameDescription> m_games = new ArrayList<GameDescription>();
+  private final List<Tuple<GUID,GameDescription>> gameList;
```

The `List<GameDescription>` should suffer from that problem as much does `List<Tuple<GUID,GameDescription>>`

`LobbyGamePanel` , a swing component, is the only thing that owns this object (LobbyGameTableModel). So from that context we would have unequal LobbyGameTableModel instances on serialization/deserialization the swing UI. Not a component that is saved to disk or sent over the wire, I don't know of good examples where we exercise serialization of swing components.


In general though, unless we need a strict ordering on tuples, it does seem a map is always a better choice than a `List<Tuple<GUID,GameDescription>>`. The list of tuples may as well be the maps entry set.  By that, I'll be happy then to clean up the data structure.

On the other hand, the serialization consideration was an excellent consideration, I was pretty sure you had spotted a bug for a good while. Unless I missed something (not the first time nor last), I don't think any new bugs were introduced.

**Comment by veqryn** [comment]
@DanVanAtta: I think you may have misunderstood our comments.
The following code is error prone, you are doing a `remove` on a list of tuples, where one of the objects in the tuples does not override `equals`.
```
Tuple<GUID, GameDescription> gameToRemove = findGame( gameId );
if( gameToRemove != null ) {
  int index = gameList.indexOf(gameToRemove);
  gameList.remove(gameToRemove);
  fireTableRowsDeleted(index, index);
}
```

The previous code did not have this issue because it relied entirely on insertion order.

**Comment by veqryn** [comment]
A map probably won't work since we need the index.
I recommend reverting this change and then a new PR that only does the method duplication extraction.

**Comment by DanVanAtta** [comment]
The implementation of the `findGame( gameId)` method guarantees that the `indexof` and `remove` will work because the instances will be the same.

**Comment by DanVanAtta** [comment]
To elaborate a bit, `findGame` returns a Tuple instance that is picked from the List of tuples, so we know the exact elements will be in that same list. 

When the `indexOf` and `remove` calls `equals` on the `Tuple`, eventually this code in `Tuple` `equals` method will be called `!m_second.equals(other.m_second)) `

The "m_second" is a GameDescription instance in this case, which does not override equal so this equals method will perform a "==" check by default. The two GameDescription objects will be the same instance since no serialization and deserializaton occurred between the `findGame` call and the `indexOf` and `remove` calls.

**Comment by veqryn** [comment]
Ah, you are indeed correct.
I still wonder if this is a good change through.
It may be easy for someone to come along in the future and think what I just did on first pass, that you are doing a remove, so it must be safe/fine to compare those tuples.

**Comment by DanVanAtta** [comment]
I think you were right to suggest the map @veqryn , that would have been a better change.

**Comment by veqryn** [comment]
So, how about instead of a list of tuples, or two lists, how about a list and a map.
You can get the index from the list, and you can get the description from the map?
Would you say that is the 'best' way to do it?

**Comment by DanVanAtta** [comment]
I think the key problem is we couple the table index with the index in the data structure. Solving that should lend to a good solution (but one should stop and  ask if it is overkill though)

List+map is better than two lists, but a single data structure should be all that is needed. Generally converting a nested data structure into a first class object is a way to fix that up. 

So in this case:
```
Tuple<GUID, GameDescription> gameToRemove = findGame( gameId );
if( gameToRemove != null ) {
  int index = gameList.indexOf(gameToRemove);
  gameList.remove(gameToRemove);
  fireTableRowsDeleted(index, index)
```
Becomes:

```
gameData.removeGame(gameId);
```

But then you need to handle "fireTableRowsDeleted", with some sort of callback mechanism (either pass in a reference of the parent object to the new `gameData` object, or have an event listener where the parent class listens for gameData events). Still more problems though, and doesn't really improve things yet either. 

So I'm not particularly sure what would be a "best" way to do it. Simplifying other parts of this same class might help make it more obvious what could be done. Bit of an interesting puzzle...

**Comment by veqryn** [comment]
Ya, moving up to a first class object feels like overkill.
Lets do list+map.

**Pull request merged**
