### PR TITLE
Don't abort early

### PR DESCRIPTION
**Pull request by RoiEXLab**
This should fix the issue where tiles are not correctly loaded under certain conditions.
Concurrency is weird sometimes

### CODE REVIEW

**Comment by Cernelius** [comment]
This didn't apparently fix anything (1.9.0.0.10535, on a 7th generation i5, with Windows 10), on my end. When I open World At War at zoom 100, most tiles outside the ones displayed on the screen at start are not loading. Scrolling around might make some tiles loading, but it happens very rarely and it doesn't seem that the whole issue gets fixed, that way. If, instead of scrolling around, I put the zoom at 10% (so to have all maps on screen), and wait, the section without loaded tiles flashes white intermittently, and more tiles are very slowly loaded, until, eventually, after several minutes, all the map is suddenly loaded successfully.

**Comment by Cernelius** [comment]
The prerelease is unplayable for me live for any games any bigger than 270BC. Even Pact Of Steel is borderline, since huge swats of the map are not draw, and I have to wait more than 1 minute wondering if / hoping they will be eventually drawn. I'll have to go back using the stable.

**Comment by ron-murhammer** [comment]
@Cernelius Can you open a new issue to track the problem you are seeing?

**Comment by RoiEXLab** [comment]
@Cernelius Could you try recording a video showing the behaviour you observed?
Also are you using an SSD or HDD in your PC?
Please put all of the details into a dedicated issue.

**Comment by Cernelius** [comment]
I tried and I succeded!
You should be able to download it in less than 2 hours...
https://github.com/triplea-game/triplea/issues/3539

**Pull request merged**
