### PR TITLE
Revert "Fix map position"

### PR DESCRIPTION
**Pull request by ron-murhammer**
Reverts triplea-game/triplea#5180

### CODE REVIEW

**Comment by ron-murhammer** [comment]
@RoiEXLab This fix causes a really bad side effect where you can't vertically scroll maps anymore. Reverting.

**Comment by RoiEXLab** [comment]
Hmm I was pretty sure I checked that.
Basically we need to set x and y = 0 on small maps, maybe you are able to come up with better criteria?

**Comment by RoiEXLab** [comment]
@ron-murhammer I just double checked using Hexglobe. I can vertical-scroll just fine.
Not that scrolling is only disabled when the map is too small for the screen, so chances are your screen is simply too "high" so the map can't wrap around correctly (every part is is only displayed once, but I don't quite see how reverting this change fixes this).

So I'd highly appreciate if you could go into more detail here please, and if this takes longer to resolve, revert the revert because this bug makes small maps literally unplayable (Release Blocker-level).

**Comment by ron-murhammer** [comment]
@RoiEXLab I tested revised and game of thrones. I tried all the various ways of vertically scrolling the map down and none of them did anything. I was essentially stuck on the top edge of the map. I'll retest later today to double check if you can't reproduce it.

**Comment by RoiEXLab** [comment]
@ron-murhammer Thanks for clarifying I'm able to reproduce it. I'll try to come up with another condition

**Comment by RoiEXLab** [comment]
Created #5186

**Pull request merged**
