### PR TITLE
Checkstyle: Fix incomplete Javadoc sentences

### PR DESCRIPTION
**Pull request by ssoloff**
This PR fixes violations of the Checkstyle SummaryJavadoc rule.  Specifically, the subrule "First sentence of Javadoc is incomplete (period is missing) or not present."  These violations were nearly pure noise that account for almost 9% of the remaining Checkstyle violations.

This is a huge PR, but **all changes are to Javadocs; there are no changes to actual code.**  I don't expect that a careful review is required.  A few spot checks should be all that's necessary.

More than 95% of the changes simply add a period to the end of a sentence.  However, there were a few exceptions in which I did one of the following instead:

* Removed a useless Javadoc comment on a private method or an override.  By useless, I mean, for example, all it had were empty `@param` tags with no descriptions.
* Converted a Javadoc comment to a normal block comment if it was in a location that is not applicable to Javadoc.  For example, a Javadoc comment on a local variable or on some arbitrary statement within a method.

If I modified a line for one of the above reasons, and I happened to notice an obvious error on that line, I fixed it.  Such errors include:

* Misspelled words
* Wrong class name was used in the Javadocs for a constructor

### CODE REVIEW

**Comment by ron-murhammer** [comment]
@ssoloff Needs rebased.

**Comment by ssoloff** [comment]
@ron-murhammer As the only conflict is in `gradle.properties`, I'm going to wait until you merge #1625 because it will just be in conflict again after that. 😃

**Comment by ron-murhammer** [comment]
@ssoloff Merged #1625.

**Comment by ssoloff** [comment]
@ron-murhammer Rebased against `master` at 5e0db29 (1.9.0.0.4011).

**Comment by ron-murhammer** [comment]
That's a lot of periods... Merging this.

**Comment by RoiEXLab** [comment]
Wooo 1000 merged prs 🎉

**Pull request merged**
