### PR TITLE
reverting changes to GameRunner2's getTripleaJarWithEngineVersionStringPath

### PR DESCRIPTION
**Pull request by veqryn**
[Review on Reviewable](https://reviewable.io/reviews/triplea-game/triplea/264)

### CODE REVIEW

**Comment by veqryn** [comment]
@gaborbernat & @DanVanAtta, I do not get the error described in https://github.com/triplea-game/triplea/issues/260 regardless of what `getTripleaJarWithEngineVersionStringPath` does. 
please let me know if and how you do get errors?

**Comment by veqryn** [comment]
@DanVanAtta please have a look at the travis log.  It seems i need something special these days to make branches?

**Comment by DanVanAtta** [comment]
A misconfiguration. I made a change just now as you may have noticed in your emails to set the build to just be for master only. Travis should not have attempted do get as far as it did for a pull request.

But also notice in the log the bot token was revealed. I created an issue to track a permanent fix to ensure we don't reveal the token no matter what. With the fix just merged, we should be good, but I want a full proof solution so we don't worry about  it.

**Comment by DanVanAtta** [comment]
@veqryn  - you added "temp" to .gitignore, otherwise I agree this is a straight undo of this change:

```
   private static String getTripleaJarWithEngineVersionStringPath() {
-    return "triplea_" + EngineVersion.VERSION.toStringFull("_") + ".jar!";
+    return "triplea-" + EngineVersion.VERSION.toStringFull(".") + "-all.jar!";
   }

```

**Comment by DanVanAtta** [comment]
Now travis should build and do a full release. @veqryn, if you submit another branch for pull request, travis should do "gradle test" but it should not do anything for deployment like it tried for this PR.

**Comment by DanVanAtta** [comment]
To be clear and a bit redundant - the change in #266 should prevent Travis from kicking off a deployment as it attempted for this PR (#264 - installer code change revert)

**Pull request merged**
