### PR TITLE
Checkstyle: Fix AI package name violations

### PR DESCRIPTION
**Pull request by ssoloff**
This PR fixes violations of the Checkstyle PackageName rule in packages under `g.s.triplea.ai`.

There are two issues of note:

* I did not move the `ProLogSettings` class because it is serialized to the preference store between  runs of the application.  I did this to avoid losing a user's settings when they upgrade to an engine version containing this change.
    * :question: @ron-murhammer Would it be that big of a deal to move this class such that a user's pro AI log settings get reset to the defaults upon an upgrade?  Is this feature used outside of the dev team and map makers?  Note that moving it will not cause any kind of error upon upgrade; the settings will simply be silently replaced with the defaults.
* While the `AggregateEstimate` class is serializable, @DanVanAtta's analysis in #3046 demonstrated that its superclass (`AggregateResults`) can be modified without breaking serialization compatibility.  (It looks like instances of `AggregateResults` are never actually serialized, and `Serializable` can be removed, but I'll investigate that in a follow-up PR.)

#### Testing

* Verified that pro AI log settings are still saved/loaded to/from the original location.
* Ran a network game with a 3635 client using human, Hard AI, and Fast AI players.
* Ran battle calculator in both 3635 and this branch during a network game.

### CODE REVIEW

**Comment by DanVanAtta** [comment]
no objection here, leaving for @ron-murhammer to review.

**Comment by ron-murhammer** [comment]
@ssoloff AI log settings aren't used by very many people so its fine if they reset. Everything looks fine to me.

**Comment by ssoloff** [comment]
@ron-murhammer Thanks.  I'll submit a new commit later that moves `ProLogSettings` to the new package structure.

**Comment by ssoloff** [comment]
Going to merge this now since it affects so many files in a somewhat-active area of the code and was previously approved.

**Pull request merged**
