### PR TITLE
Map panel npe fix

### PR DESCRIPTION
**Pull request by DanVanAtta**
[Review on Reviewable](https://reviewable.io/reviews/triplea-game/triplea/363)

### CODE REVIEW

**Comment by ron-murhammer** [comment]
@DanVanAtta Is there a way to reproduce the error?

**Comment by DanVanAtta** [comment]
@ron-murhammer  not easily that I know of.

**Comment by ron-murhammer** [comment]
@DanVanAtta Are you sure that start and end can even be null? Just wondering if you ran into an error which is why you added this check and how you got to that error.

**Comment by DanVanAtta** [comment]
The commit comment has those details. We do have cases where the constructor for RouteDescription gets a null start and end, but a valid route[] array. In this code path, it's assumed another usage of  the constructor which is not always the case, hence the NPE.

**Pull request merged**
