### PR TITLE
2 file refactor: GameDataManager.java - Add method signature: public GameData loadGame(final ObjectInputStream input)

### PR DESCRIPTION
**Pull request by DanVanAtta**
GameDataManager.java - Add method signature: public GameData loadGame(final ObjectInputStream input). Allows clients to avoid calls with null parameters, for example: loadGame(input,null)

GameSelectorModel.java - Call gameDataManager.loadGame(input) instead of loadGame(input,null)

[Review on Reviewable](https://reviewable.io/reviews/triplea-game/triplea/32)

### CODE REVIEW

**Comment by gaborbernat** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

<sup>**[src/games/strategy/engine/framework/GameDataManager.java, line 64 \[r1\]](https://reviewable.io:443/reviews/triplea-game/triplea/32#-Jvns8_Bpo2iw_KgPePm)** ([raw file](https://github.com/triplea-game/triplea/blob/4627f6bde4d05b72145797c046936a075f431870/src/games/strategy/engine/framework/GameDataManager.java#L64)):</sup>
here the formatting is off, there should be a space between the coma 

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/triplea-game/triplea/32)

**Comment by DanVanAtta** [comment]
Review status: 0 of 2 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---

<sup>**[src/games/strategy/engine/framework/GameDataManager.java, line 64 \[r1\]](https://reviewable.io:443/reviews/triplea-game/triplea/32#-Jvns8_Bpo2iw_KgPePm)** ([raw file](https://github.com/triplea-game/triplea/blob/4627f6bde4d05b72145797c046936a075f431870/src/games/strategy/engine/framework/GameDataManager.java#L64)):</sup>
Fixed in r2

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/triplea-game/triplea/32)

**Comment by gaborbernat** [comment]
Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/triplea-game/triplea/32)

**Comment by veqryn** [comment]
You should probably add one for InputStream as well.

**Comment by DanVanAtta** [comment]
Updated to be an InputStream instead of ObjectInputStream. ObjectInputStream is an inputStream, so it'll have the same effect as having the second one.

**Comment by veqryn** [comment]
Would this possibly cause the object input stream to get re-wrapped?
I think you actually might need both method signatures.

**Comment by veqryn** [comment]
@DanVanAtta see above comment

**Comment by ron-murhammer** [comment]
@veqryn I just merged #46 which removes the load method that uses ObjectInputStream as it extends InputStream and has the same method implementation. If that method is actually needed let me know so I can undo that merge. That change appears to have conflicted with this PR since this is editing a method that now doesn't exist.

**Comment by DanVanAtta** [comment]
The conflict went away on rebase, but now the branch is being rebuilt against latest master and will be broken. So will now rebase this as well on top of #103.

**Comment by DanVanAtta** [comment]
These changes are no longer valid. In fact, if we merge this, all our tests would probably break. Another branch fixed up the logic of loading a game and removed the extra method and created a new one for test. With *this* branch, old calls will go to the prod method, and all of them would do so. So auto-merging this would cause *logical* errors, and sorting those out is not worth it. Reviewing all that was done for this PR, it is a good example of why small changes really want to be merged quickly. If not, lump changes into larger PR's that are merged less often. Everything we did for this PR at this point is now being thrown away, I see all 4 of us have touched this.

**Pull request closed without merging**
