### PR TITLE
converting line endings as per .gitattributes

### PR DESCRIPTION
**Pull request by veqryn**
[Review on Reviewable](https://reviewable.io/reviews/triplea-game/triplea/142)

### CODE REVIEW

**Comment by veqryn** [comment]
.gitattributes seems to think these two files need to change, so here we go.
As agreed, this is a completely trivial pull request, so I will merge it in the morning unless there objections.

**Comment by gaborbernat** [comment]
Excuse me, but I still fail to really understand the underlying issue here. With auto set inside the gittattribute on checkout git should check out with lf on UNIX/MAC and crlf on Windows. So the platform default, which makes everyone happy. (see https://help.github.com/articles/dealing-with-line-endings/)

For releases I think setting the correct ending should be part of the build process, make the transformation in the build, package the correct line ending file. Am I missing here something?

**Comment by DanVanAtta** [comment]
We have this line in the git attributes:
`*.txt text eol=crlf`

That forces the issue.

@veqryn , please merge this now rather than morning if you would. The constantly changed file is a bit ackward to work around.


And FYI, the dos line ending needs to be specified when grepping, so if you wanted to find out how many changes redrum had, you would have to remember to update your regex:

```
dan@dan-desk:~/work/triplea$ grep -c "(redrum)$" changelog.txt 
0
dan@dan-desk:~/work/triplea$ grep -c "(redrum)^M$" changelog.txt 
29
```

If you are not expecting DOS line endings, then sometimes a person might incorrectly go with the "0" count instead of the correct one - this bit me once before.

**Comment by DanVanAtta** [comment]
#141 looks to be the same. Also in that one the XML file change is not required. Could you double check that you really need to change the XML file?

**Comment by DanVanAtta** [comment]
@veqryn and @gaborbernat , could you guys give the following steps a try: http://stackoverflow.com/questions/1510798/trying-to-fix-line-endings-with-git-filter-branch-but-having-no-luck/1511273#1511273

**Comment by DanVanAtta** [comment]
- Is there a way to audit for correct line endings? The link above might do it. If so, it looks like there are  125 files that do not have correct line endings that match what they should have per the .gitattributes file.

Mixing CRLF with LF in repro, and deploying files with CRLF to Mac and Linux systems seems a bit risky.

**Comment by veqryn** [comment]
@DanVanAtta: The link you gave gives the WRONG instructions.  "input" = commit with LF only, but checkout with whatever it currently has.  This is why it is telling you that you have 125 files wrong...
You need to use this:
`git config core.autocrlf false`

As far as grepping with regex patterns go, I do not think you need a line end char at the end of that, but if you really did, you could always just add [\s]* to the end of your regexes, and they will work with both linux and windows:
`grep -c "(redrum)[\s]*$" changelog.txt`

@gaborbernat: We are not doing it at build time because I want people to be able to check out the source and then view the files with the specified extension on either Windows or Linux/Mac.  In any case, the map files (.txt, .properties, and .xml) should not change between windows and linux, they should be universally the same (so that you can do a checksum on zip file, and get the same result, for example).

**Comment by veqryn** [comment]
I will merge this.  If we still have trouble after this, we can always just delete .gitattributes and go back to the old way (which wasn't causing issues).

**Pull request merged**
