### PR TITLE
Remove 404 links

### PR DESCRIPTION
**Pull request by RoiEXLab**
@ssoloff We should consider "upgrading" the validation script to check if the links are actually available...

### CODE REVIEW

**Comment by ssoloff** [comment]
Good idea, @RoiEXLab.  Can you create an issue to add image URL validation for `triplea_maps.yaml` to the `validateYamls` Gradle task?  I can look into it sometime this week.

**Comment by RoiEXLab** [comment]
@ssoloff I will create an issue with a less specific topic 👍

**Comment by RoiEXLab** [comment]
@ssoloff #1818

**Comment by RoiEXLab** [comment]
@DanVanAtta @ron-murhammer Bumping... This is a pretty minor change and probably the last thing from creating a PR to add my buildscripts to the website repo

**Pull request merged**
