### PR TITLE
Update README + LICENSE file

### PR DESCRIPTION
**Pull request by RoiEXLab**
I was noticing, that the current shield badges are somewhat broken. This should fix the issue...
If the "license change" isn't working as expected, I'd kindly ask you, @ron-murhammer or @DanVanAtta to edit the license file in the online editor and to choose the GNU GPL 2 license as template and push directly to master.

### CODE REVIEW

**Comment by RoiEXLab** [comment]
Hmmm for whatever reason travis didn't even start...

**Comment by ron-murhammer** [comment]
@veqryn Can you take a look at this?

**Comment by RoiEXLab** [comment]
It's still the same gpl license... 
It's just the github template. 
My hopes are, that github will the display it correctly...

**Comment by veqryn** [comment]
This should be good, but please replace: 
`{description}` with `TripleA is a turn based strategy game and board game engine, similar to Axis & Allies or Risk.`
`{year}` with `2002`
`{fullname}` with `triplea-game`
After that, we can merge this.

**Comment by RoiEXLab** [comment]
@veqryn Done!

**Comment by veqryn** [comment]
@RoiEXLab it looks like your change got rid of a lot more than intended.

**Comment by RoiEXLab** [comment]
@veqryn I just removed the "How to apply this license to your project part"
Those are just instructions on how to add copyright notices etc.
I double checked if this license is recognized by github by using the same tool. (and wasted 2 hours getting it to work on windows (failed) and getting it to work on my virtual ubuntu machine in 10 mins)
100% match

**Comment by veqryn** [comment]
Cool, just wanted to make sure removing that didn't stop the shield icon from matching (the point of your PR).
:+1:

**Comment by RoiEXLab** [comment]
No problem!

**Comment by RoiEXLab** [comment]
Yay it worked!

**Pull request merged**
