### PR TITLE
Prevent isSuicide units to first strike on defense if option is on

### LINKED ISSUE #6861: Domination 1914 "bunkers" technology broken
The Domination 1914 map has a technology known as "bunkers" that raises the defense of the trench unit from 0 to 1. The bug is that this defense value is now acting as a first strike when it should not.

### If playing a prerelease, which version are you using?

Game Version:

### If playing a prerelease, does this happen on the latest release?

- [ ] yes
- [ ] no

### PR DESCRIPTION
**Pull request by trevan**
Fixes #6861

In 1.9, defending suicide units didn't have the quasi "first strike" ability if `DEFENDING_SUICIDE_AND_MUNITION_UNITS_DO_NOT_FIRE` was true.  When the suicide attributes were enhanced in #5871, all suicide units (both attacker and defender) were given `isFirstStrike`.

This adds a new matcher for defending first strikes.  If a map is using the deprecated `isSuicide` option, then the units will get `isFirstStrike` and `isSuicideOnAttack`.  But if `DEFENDING_SUICIDE_AND_MUNITION_UNITS_DO_NOT_FIRE` is false, they also get `isSuicideOnDefense`.  Since normal `isFirstStrike` units will not have `isSuicideOnAttack` or `isSuicideOnAttack`, I can't do a `isSuicideOnDefense.negate()` because that will exclude normal `isFirstStrike` units.

## Functional Changes

[] New map or map update
[] New Feature
[] Feature update or enhancement
[] Feature Removal
[] Code Cleanup or refactor
[] Configuration Change
[x] Problem fix
[] Other:   

## Testing
Loaded a game in Domination 1914 that has trenches with the bunker ability and checked that the units fired correctly.

## Additional Notes to Reviewer
I think it would be a good idea to split out `isFirstStrike` into `isFirstStrikeOnAttack` and `isFirstStrikeOnDefense` at some point.  I didn't do that here but I did create the `isFirstStrikeOnDefense` matcher.

This is also a draft PR because there needs to be a small change once #6885 is merged in.

## Release Note

FIX|Suicide units on defense have first strike abilities only if they have isSuicideOnDefense or the deprecated option "Defending Suicide and Munition Units Do Not Fire" is false.

### CODE REVIEW

**Comment by trevan** [comment]
@ron-murhammer You did the suicide enhancement.  Can you check this change?

**Comment by DanVanAtta** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- game-core/src/test/java/games/strategy/triplea/delegate/battle/steps/BattleStepsTest.java  7
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/triplea-game/triplea/pullRequest?prid=5767403&bid=18875787)

**Comment by DanVanAtta** [comment]
@trevan the release not perhaps could use a first sentence that gives a more lay explanation. For example "bunkers getting an incorrect first strike against attackers on dom 1914 fixed", or something like that. A description in term of map properties is useful to us, but the common player is not aware of map properties.

**Comment by DanVanAtta** [comment]
:+1: Thanks for jumping in with a fix for this @trevan

**Comment by trevan** [comment]
I changed the release note.  Is it ok now?

**Comment by DanVanAtta** [comment]
Perfect, thanks @trevan

**Pull request merged**
