### PR TITLE
Add Find Territory command

### PR DESCRIPTION
**Pull request by ssoloff**
## Overview

Addresses https://forums.triplea-game.org/topic/1026/find-province-command.

This is the first of two or more PRs that will fully implement this feature.  This PR implements the basic functionality of prompting the user to choose from a list of territories, and then center the map on the selected territory.  Follow-up PRs will explore optimizing the territory selection process via free-form text entry.

## Functional Changes

* Added the new **View > Find Territory...** command to the menu bar.
    * This command is also available via the mnemonic <kbd>Alt</kbd>+<kbd>V</kbd>, <kbd>F</kbd>.
    * This command is also available via the hotkey <kbd>Ctrl</kbd>+<kbd>F</kbd>.
    * Selecting this command displays a dialog with a combo box that contains all map territories in lexicographical order.
    * The initial focus is on the combo box.
    * In addition to the mouse, the user can use the following keys to navigate the combo box:
        * Up/down arrow
        * Page up/down
        * Alpha keys to change the selection to the first item matching the pressed letter.
    * Closing the dialog by pressing <kbd>Enter</kbd> or clicking the **OK** button will center the map on the selected territory.
    * Closing the dialog by pressing <kbd>Esc</kbd>, clicking the **Cancel** button, or clicking the system close menu will do nothing.

## Manual Testing Performed

* Verified the map view is centered on the selected territory.
* Verified the map view is not changed if no territory is selected.
* Verified all "OK" close actions work as expected.
* Verified all "Cancel" close actions work as expected.

## Screen Shots

find-territory-menu-new

find-territory-dialog

## Additional Reviewer Notes

* ~I dithered between adding the **Find Territory...** command to the **View** and **Game** menus.  Please advise if **View** would have been a better choice.~ **EDIT:** Moved to **View** menu based on forum feedback.
* I added the **Find Territory...** command to the end of the **View** menu.  Please advise if it would be better positioned at the beginning of, or some other location within, this menu.

### CODE REVIEW

**Comment by Cernelius** [comment]
In "Help"?

**Comment by ssoloff** [comment]
@Cernelius Hmm, not sure about that. I see this more as a "navigation" command rather than a "help" command.  Traditionally, "find" commands are found on an **Edit** menu.  But, as TripleA doesn't have one, that kind of rules it out.  I'm not sure we should add a new top-level menu for a single command.

So the question becomes, under what existing menu would a user expect to find a "navigation" command?  In fact, **View** may be more appropriate simply because this command affects the state of the map view by changing its position.

**Comment by Cernelius** [comment]
When something is so dubious, I say better not hiding it somewhere, obliging you to search most places to find it, as none is clearly the one. Just, then, make a new "Search" main menu, now having only "Territory" as function.

**Comment by ssoloff** [comment]
> I'd appreciate if a simple test using a "spy-mock" could be written for `SelectTerritoryDialog#open` if possible

@RoiEXLab Are you talking about a test for `FindTerritoryAction#actionPerformed()` that asserts it calls `SelectTerritoryDialog#open()`?  Or a test for `SelectTerritoryDialog#open()` that asserts it returns the correct value based on `SelectTerritoryDialog#result`?

**Comment by ssoloff** [comment]
@Cernelius I will post on the forum asking for opinions where most users would expect to find this command.  If I don't get enough responses by the time this PR is merged, I will submit a separate PR after-the-fact to accommodate the majority opinion.

**Comment by RoiEXLab** [comment]
@ssoloff 
The latter case

**Comment by ssoloff** [comment]
@RoiEXLab 956e1015b

**Comment by RoiEXLab** [comment]
👍

**Comment by ssoloff** [comment]
4ab57dd moves the new command to the **View** menu based on forum feedback. We can still shuffle this around, as there will be at least one more PR coming related to this feature.

**Pull request merged**
