### PR TITLE
Replace while loops with foreach loops

### PR DESCRIPTION
**Pull request by DanVanAtta**
Re-opening from: 
https://github.com/triplea-game/triplea/pull/699

git was being wonky and was not seeing the updates to the branch.

---
This change is [Reviewable](https://reviewable.io/reviews/triplea-game/triplea/733)

### CODE REVIEW

**Comment by ron-murhammer** [comment]
@DanVanAtta Looks like this needs rebased.

**Comment by ron-murhammer** [comment]
@DanVanAtta Looks like the build failed here.

**Comment by DanVanAtta** [comment]
Note, travis did two builds, it was confused about the branch. The build of the existing branch did succeed.

**Comment by ron-murhammer** [comment]
@DanVanAtta Can we re-run the build or will it still try to build the wrong branch?

**Comment by DanVanAtta** [comment]
Depends which build you re-run. One fails, one succeeds. One build is something from a travis bug, the other one is legit.

**Comment by ron-murhammer** [comment]
@DanVanAtta Not really sure where the issue is with this one. Is it the PR, the branch, or the build that has a problem? Do we need to create an issue for this? Should we rename the branch and see if that resolves it?

**Pull request closed without merging**
