### PR TITLE
Update triplea_maps.yaml

### PR DESCRIPTION
**Pull request by SwampyAcres**
Not sure I updated this correctly specifically around the line 1691

img: https://raw.githubusercontent.com/triplea-maps/steampunk_advanced/master/description/TripleA_Steampunk_mini.png

## Functional Changes

[] New map or map update
[] New Feature
[] Feature update or enhancement
[] Feature Removal
[] Code Cleanup or refactor
[] Configuration Change
[] Problem fix:  
[] Other:

### CODE REVIEW

**Comment by RoiEXLab** [comment]
@SwampyAcres I fixed the yaml format for you but there are a couple of other Problems:

1. The link you provided (as you mentioned already) is invalid. It has to point to a valid image file on the internet.
2. Your map is not hosted on triplea-maps (yet?), which is a requirement AFAIK. @DanVanAtta or @ron-murhammer Should be able to give you more details on the exact procedure for map makers

**Comment by ron-murhammer** [comment]
@SwampyAcres You'll need to follow this process to create the map repo and then transfer it to tripleA maps so that your map is then available for download in TripleA: https://docs.google.com/document/d/1FfF7N0srp9QG0_if5D-c1d1Aa1QTttdhxgm1GBh3pI4

**Comment by Cernelius** [comment]
> The link you provided (as you mentioned already) is invalid. It has to point to a valid image file on the internet.

Hasn't been decided that all minimaps shown in the repository must be kept inside the "description" folder of the map and have the file name exactly as "TripleA_mapName_mini.png". Isn't this documented somewhere (sorry don't recall)?

**Comment by RoiEXLab** [comment]
@Cernelius I'm just saying that the link is currently a 404 link and doesn't actually point to an image file

**Comment by DanVanAtta** [comment]
Looks like we just need `mapName` property to be updated and would be good to go: https://github.com/triplea-game/triplea/issues/6417

**Comment by SwampyAcres** [comment]
I believe I have corrected this mapname properties issue as Dan indicated (row 8470). Please review and advise.

**Pull request merged**
