### PR TITLE
Added 270BC Variants

### PR DESCRIPTION
**Pull request by RogerCooper**

### CODE REVIEW

**Comment by RogerCooper** [comment]
I left a blank line at the end. It still did not work.

**Comment by Cernelius** [comment]
I actually had a map called "270bc_variants" deleted from the repository some time ago. The map had only two games, both made by me. If I recall correctly, I made that request and @DanVanAtta accepted it. I've not changed my mind.

**Comment by RogerCooper** [comment]
The Tertiered scenario looked interesting. However, my main concern here is the formatting error I received. I don't see what is wrong the way I entered the data.

**Comment by Cernelius** [comment]
> The Tertiered scenario looked interesting. However, my main concern here is the formatting error I received. I don't see what is wrong the way I entered the data.

That is substantially the old (and more aggressively scaled down) version of "270BC 40%", which went through a series of versions too.

I have preferred removing from the repository all my variants of "270BC" but "270BC Wars" in order to let any interested player focus on that.

**Comment by RogerCooper** [comment]
I will remove those files.

**Comment by DanVanAtta** [comment]
Merge conflict needs to be resolved now before this can move forward @RogerCooper 
Let me know if you need help doing so

**Pull request closed without merging**
