### PR TITLE
Added Britannia - Roman Invasion

### PR DESCRIPTION
**Pull request by RogerCooper**

### CODE REVIEW

**Comment by TheDog-GH** [comment]
@RogerCooper 
Check the yaml file, as your commit has not been actioned/updated
https://github.com/triplea-game/triplea/blob/master/triplea_maps.yaml

I have the same problem for 2 of my commits.

**Comment by beelee1** [comment]
@RogerCooper looks as if you'll need to redo this. I just added Dog's Shogun and it has the same lines in the yaml being used is my guess as to what's up. 

Idk how to avoid that in the future. Seems as if there should be a way ?

**Comment by beelee1** [comment]
@TheDog-GH Roger's was fine it's just that multiple ones were done at the same time using the same lines in the yaml. Idk how to avoid that in the future.

You'll probably need to redo your Arena one now too. I'll check

**Comment by TheDog-GH** [comment]
@beelee1 
THANKS
Arena of Death was just v1 to v2 change, so a one line change.
The Shogun now appears in downloads :-)

Beelee you have the power.

**Comment by beelee1** [comment]
@TheDog-GH ut oh conflicts just noticed. Too fried to look closer at the moment. Maybe the yaml thing again ? Too many on same thingy ? idk

**Comment by RogerCooper** [comment]
> @TheDog-GH ut oh conflicts just noticed. Too fried to look closer at the moment. Maybe the yaml thing again ? Too many on same thingy ? idk

This mod was already on Github but wasn't in triplea_maps.yaml. Either I missed it or there was some pre-existing problem here.

**Comment by beelee1** [comment]
@RogerCooper I'm not sure what needs to be done here. This is what I get when I hit resolve conflicts:

Screenshot from 2022-09-04 13-15-14

It looks as if maybe the patch didn't work right ? Idk

**Comment by DanVanAtta** [comment]
A merge conflict is when incoming changes conflict. Git is quite decent at resolving these automatically, but in some cases it needs to "phone-a-human" to resolve them.

When clicking 'resolve conflicts', you are being shown the changes that were integrated into the modified file by some other merged PR, and the incoming changes from this PR. In that UI, just edit the file to make it look how it should look in a final state.

To try and explain a merge conflict, it's as if there is an in-flight order to "reverse the last transaction". If that order is queued and the last transaction changes, then it's not clear if you really want to reverse the last transaction, or some other one. Merge conflicts happen when the same content is modified by multiple sources.

**Comment by beelee1** [comment]
we'll see if this works :)

**Pull request merged**
