### PR TITLE
Move 'doc' folders to asset repo

### PR DESCRIPTION
**Pull request by DanVanAtta**
Move 'dice_servers' and' doc' folders to asset repo: https://github.com/triplea-game/assets

Corresponding PR in the asset repo: https://github.com/triplea-game/assets/pull/1

[Review on Reviewable](https://reviewable.io/reviews/triplea-game/triplea/340)

### CODE REVIEW

**Comment by ron-murhammer** [comment]
@DanVanAtta Why move /dice_servers to assets? Its just property files? I can see the value of moving images/sounds/docs/etc to assets but usually keeping property files with the code is worth it.

**Comment by DanVanAtta** [comment]
Let's be clear that moving dice_servers does *not* at all reduce the size of the repo.

The overall motivation is to try and start reducing the number of files and folders that have piled on at the top level of the project.

Keeping configuration of dice servers, the lobby, with the source code of the client application is not terribly appropriate. Perhaps we need a "server_config" repo to store that, for now moving anything out of the source code that does not relate to building the game installers, is a win. Said in another way, we have so many different things piled in with the client game, we have very little hope of organizing it if we keep it all in-place.

**Comment by ron-murhammer** [comment]
@DanVanAtta Understood. But I think the property files fit better with the main project then an assets project so would prefer to keep them here for now.

**Comment by DanVanAtta** [comment]
I think there is a point of view difference. I think of this is as the client application project, and we have the lobby and dice server shoe-horned in. Moving the dice server configs at the same time as when we deal with the larger problem I think is reasonable enough.

Devils advocate, since these files are hand-deployed, I don't think there is any practical difference. I'm also concerned that we don't even use all three of them anymore.

Assigning to myself, will remove the dice_servers folder from this PR..

**Comment by DanVanAtta** [comment]
Updated, just moving the 'doc' folder now.

**Pull request merged**
