### PR TITLE
whenHitPointsDamagedChangesInto for units with no hitpoints left

### PR DESCRIPTION
**Pull request by alkexr**
Units that would be removed are damaged first and are kept track of in a list, then they are checked for WHPDCI.

Units created newly this way won't prevent the battle from ending.

### CODE REVIEW

**Comment by alkexr** [comment]
Due to an unrelated bug, the process shows up in a weird way in the game history. Namely, the game tries to display the _hit version of unit images (even though they take damage after they are removed). See https://github.com/triplea-game/triplea/issues/4717

**Comment by ron-murhammer** [comment]
@alkexr Did you test out this change? I did a quick test by changing TWW BBs to transform when at max damage and seems to have some issues after the unit transforms including that unit not firing any more and it not being considered as a casualty.

I think your implementation is close but the code needs a few adjustments. Just wanted to check before I change anything.

**Comment by ron-murhammer** [comment]
@alkexr I used some of your ideas from this and re-implemented this change into this PR #4720. Please let me know if that addresses what you are looking for.

**Comment by alkexr** [comment]
Well I did not truly expect my first messing with the code to be free of mistakes.

**Pull request closed without merging**
