### PR TITLE
Try to fix concurrency issue 1.10

### PR DESCRIPTION
**Pull request by RoiEXLab**
## Overview
Attempt to resolve the issue reported in #4731
If this PR turns out to be a fix (after deployment, the code cleanup doesn't hurt anyways) we can merge this change into 1.9 (#4736), and deploy a new stable.
Can't produce the error myself, so no guarantees.

## Functional Changes
Atomic checks of boolean values.

## Manual Testing Performed
None.

### CODE REVIEW

**Comment by DanVanAtta** [comment]
Reading the related issues, looks like there is a NPE after this fix. This is perhaps not a fix. Adding testing label as we need to test more.

Fixes in the dark are generally very difficult. A repro case will be very valuable if we can get one.

**Comment by RoiEXLab** [comment]
@DanVanAtta Perhaps I should've clarified why I think this change is a fix:
In case of the NullPointerException the only place where the variable is ever set to null (apart from declaration with null) is after the point where the NullPointerException is thrown which suggests that the snippet is called twice.
However in a single threaded environment this would be impossible because before the actual invocation there's an if check to a boolean that is set to the opposite value afterwards, indicating there might be a race condition somewhere.
This would also explain why I'm not able to reproduce the issue.
Of course there's no guarantee, but the refactoring alone should (at least that's the intention) already be reason enough to merge this PR.

**Comment by RoiEXLab** [comment]
And by refactoring I mainly mean the removal of the CountDownLatch that is used to wait for the EDT to invoke it's action.

**Comment by RoiEXLab** [comment]
@DanVanAtta Could we treat this as refactoring PR that preemptively tries to eliminate potential race conditions?
When we merge this, we get a binary for testing if the issue has actually been fixed.

**Pull request merged**
