### PR TITLE
Checkstyle: Suppress remaining naming violations

### LINKED ISSUE #4137: Checkstyle rule reconciliation - variable naming
It's kinda painful to find checkstyle violations after committing code. Largely this is because we have so many, finding new ones is a needle in haystack.

Beyond the practical impact, it's not good we have violations that we just cannot fix. Grant it, I very much like that we have went to some great lengths to ensure we do not make violations worse. This I think has set a strong working precedent. At the same time, I don't think the incentive of doing a non-compatible release just so we can fix naming violations is a good one to have. So I think there is a larger picture impact here, that we are more focused on the violations potentially rather than doing the right thing and adding project value. 

### Proposal

Given that we:
  - have set a strong standard on variable names (done)
  - are actively working towards  removing 'm_' variables (done)
Proposal:
 - update  checkstyle to allow 'm_' variables, names with the understanding this is something we wish to remove.

Expected benefits:
- drastic reduction in checkstyle violations, this has a number of follow-up benefits:
  - easier to find new ones
  - i'm guessing given this group, if we can get the violation count under 300 by removing the naming violations and have things we can actually fix, that we'll get it down to zero in pretty short order  :grin: 
- correction of incentives. Channeling @ simon33-2 and @Deltium here : )
  - doing an incompatible release just so we can fix variable naming is IMHO a bad incentive to even have.

### PR DESCRIPTION
**Pull request by ssoloff**
## Overview

Resolves #4137.

Suppresses the remaining Checkstyle naming violations until they can be fixed in the upcoming incompatible release.  Just in case that takes longer than expected, the noise from these 700+ violations will no longer be present in the build logs.

## Functional Changes

None.

## Manual Testing Performed

None.

## Additional Review Notes

This PR should probably be merged after #4140.  The conflicts will be easier to resolve here.

### CODE REVIEW

**Comment by ron-murhammer** [comment]
@ssoloff I'm not really convinced this is worth doing. I'd like to just fix all these after we handle the anonymous username length issue. Rather just close this unless you feel strongly otherwise.

**Comment by DanVanAtta** [comment]
@ron-murhammer the mass checkstyle violations is impactful, this issue was opened in response:
https://github.com/triplea-game/triplea/issues/4137

**Comment by ssoloff** [comment]
@ron-murhammer In a sense, I agree.  It would have been more useful six months ago.  I submitted it just in case fixing these issues doesn't actually happen "soon." :smile:

How about we close this for now, and, if we still haven't fixed the issues in 30 days, I re-submit it?

**Comment by DanVanAtta** [comment]
I'd prefer the benefit from this now rather than later.
I also like that this actively reduces the checkstyle violations, just letting them sit is not very acceptable at the end of the day, and saying we'll fix these eventually means we should turn the check off until we have it fixed IMO.

**Comment by DanVanAtta** [comment]
My last 2 cents, I see favorable cost / benefit:
- benefits:
 - can find the naming violations easily with `grep -A1`, can help us verify we remove these well too when looking at diffs (perhaps a bit far fetched, but it sure won't hurt)
 - reduces violation counts that we are otherwise sitting on. This improves the culture of not ignoring things.

Costs:
  - the work was already done here, so review time, time to fix merge conflict
  - removing the annotation. It's a one-line sed command though: `find . -name "*java" -type f | xargs sed -i '/<regex>/d'`

Seems favorable to me : )

**Comment by DanVanAtta** [comment]
@ssoloff i think it's up to you if you think it's worthwhile to push this forward or to spend your time to focus on the longer term fix instead. I don't necessarily feel that married to this update, I would like to see it, but we've been dealing with violation noise for quite some time, the end is in sight :clinking_glasses:

**Comment by RoiEXLab** [comment]
I'm neutral on this I don't think it'd be really useful to suppress all the errors now when we're going to rename all the variables soon anyways.
On the other side this change doesn't really hurt either so...

**Comment by ssoloff** [comment]
Closing as there isn't a clear positive majority here.  As I said above, I'll re-evaluate submitting this PR at the end of the month if we're not making progress on the Checkstyle naming fixes.  Thanks for all the input!

**Comment by DanVanAtta** [comment]
screenshot from 2018-10-06 14-54-19

I have the above output, and it does not repro when running `./gradlew check`. Digging through the noise to find the one violation is a lot of wasted time/effort. We are not winning here; It was not long to find examples where the checkstyle noise cost time/effort and frustration @ssoloff @ron-murhammer.

**Pull request closed without merging**
