### PR TITLE
Eliminate loading stutter

### PR DESCRIPTION
**Pull request by RoiEXLab**
This PR refactors the game-loading code to keep non-swing code off the EDT, in order to eliminate short freezes when loading a game.

### CODE REVIEW

**Comment by ron-murhammer** [comment]
@RoiEXLab Code looks alright. What/how did you test? Just concern with playing around with what is loaded in which threads causing weird behavior or errors. Probably want to make sure you load up some large maps potentially locally and in the lobby to make sure this works as expected.

**Comment by RoiEXLab** [comment]
@ron-murhammer I added lots of printlns to measure time in order to spot operations taking longer than 100 ms.
So I added comments loaded a game, moved the comments, loaded a game until I could figure out what part of the code took so long.

**Comment by ron-murhammer** [comment]
Alright, merging this so we can get it in the hands of folks to test and see if there are any issues.

**Comment by DanVanAtta** [comment]
@RoiEXLab FYI and FWIW, `PerfTimer.java` should help with that, outputs to the performance console available under the debug menu: https://github.com/triplea-game/triplea/blob/master/game-core/src/main/java/games/strategy/performance/PerfTimer.java (note the slightly out of date class javadoc that has a usage example)

**Pull request merged**
