### PR TITLE
Add failure comment

### PR DESCRIPTION
**Pull request by RoiEXLab**
This Pr adds an error message if the file association could not be created. (Currently it is not for whatever reason)
This is probably an install4j bug.
Self-merging to trigger the release build

### CODE REVIEW

**Comment by RoiEXLab** [comment]
@ssoloff It seems something is not working correctly wih this version of install4j, but the [changelog](https://www.ej-technologies.com/download/install4j/changelog.html) mentions file associations and my hopes are the latest version contains a fix...
Would you mind creating a PR to update install4j again?

**Comment by ssoloff** [comment]
@RoiEXLab IIRC, you have an install4j license.  Can you not verify install4j 6.1.6 fixes the issue with a locally-built installer?

Upgrading install4j is at least a 3 PR process because it requires touching multiple repos.  Not to mention the regression testing involved... :smile:

**Comment by RoiEXLab** [comment]
@ssoloff I forgot that local testing was so easy compared to the build process ^^
The problem is being fixed in #2031, but updating would be nice because the new update allows file associations even if the user doesn't have admin rights

**Comment by ssoloff** [comment]
@RoiEXLab Ok, I'll get the ball rolling on the installer upgrade, but I'll probably ask you to test the Windows version. :smile:

**Pull request merged**
