### PR TITLE
Remove rulebooks

### PR DESCRIPTION
**Pull request by DanVanAtta**
[Review on Reviewable](https://reviewable.io/reviews/triplea-game/triplea/459)

### CODE REVIEW

**Comment by ron-murhammer** [comment]
@DanVanAtta - Looks like this needs rebased.

Looks like you added the PDF to the assets repo. I don't see the docx though?

**Comment by DanVanAtta** [comment]
The PDF in the assets repo is needed, the in-game URL is updated to that location. The docx would be otherwise unused. The assets repo is all used AFAIK, so I'd rather not break precedent.

If we really want a copy, I would suggest an "archive" repo. But, that's a good bit of duplication of bits, and what would really be the purpose? I suggest we deal with the archive or not to archive question when we actually get rid of the docx file. In the meantime we can recover it if we find we want it again.

**Comment by DanVanAtta** [comment]
When do a history rewrite, we'll know which assets we are removing. Thus, I'm sure it'll come up then, as well as other binary assets where we will be asking the same question.

**Comment by DanVanAtta** [comment]
@ron-murhammer , this is assigned to you to indicate where/why we need the docx at all. It's only checked in to the game, not included with the game installer (i'm looking at 1.8.0.9, and only the PDF is included). We also only link to the PDF version, not the docx - thus the docx asset is both redundant and orphaned.

**Comment by DanVanAtta** [comment]
Rephrasing, is there any good reason to keep the docx game manual around in the source code as yet one more file? I'd also like to point out we are only marking it as deleted. Unless we know of some immediate plans for this file, IMO we should move on. When we do a mass history rewrite some months down the road, we'll have more insight about whether we needed the file in the first place or not. Until then, if we need it, we can find it without much trouble at all.

**Comment by ron-murhammer** [comment]
@DanVanAtta I think we are maybe looking at this from 2 different perspectives. In general, I prefer to keep all 'source code' in the repos and use it to build 'artifacts'. In this case, the docx is actually the 'source code' and the pdf is an 'artifact'. I would actually argue we should remove the pdf from the repos and it could be built during a build.

That being said we don't currently have the tool that was used to create the pdf with the high quality images. I'd still prefer not to remove the docx from the master of the code since its then not clear where the pdf came from.

**Comment by DanVanAtta** [comment]
If we were making the original decision, I would suggest the game manual does not even belong with the source code at all. Sure it should be in some repository of some type, but not necessarily Git with the Java files.

That is beyond the point though. What's very interesting to me is that there is actually a relationship between the two files. Until you mentioned it, I had no clue and would not even have guessed that the docx was the source for the PDF. There are many ways to generate a PDF, I would have guessed we created multiple formats from the same original document that was perhaps discarded some time ago.


"I'd still prefer not to remove the docx from the master of the code since its then not clear where the pdf came from."

I hate to disagree, but as I mentioned above, this relationship is already not clear. Having the two files around does not help make it clear there is a relationship.  If we cannot re-run the tool to generate the PDF, it really does not seem that we have any further use for the docx.

**Comment by ron-murhammer** [comment]
@DanVanAtta - Can we add the docx to the assets repo and then delete it so its at least in the history?

**Comment by DanVanAtta** [comment]
If we add the docx file to the assets repo, it'll be in two different git histories. I'm a bit confused @ron-murhammer about which history you are referring to.

I'm hesitant to add an unused file to the asset repo. One day I expect we may want to clean out the binary files from the game engine history. When we do that, we'll have more information about what we can permanently delete vs what should be archived. I would prefer for us to delay the "archive or not" decision till then. 

Despite my 'hoarding' concerns, I've added the file to a new "cold-storage" repository: https://github.com/triplea-game/cold-storage. The cold-storage repository addresses my concerns that we won't be able to tell what is used vs not used in the assets repository.

**Comment by ron-murhammer** [comment]
@DanVanAtta That works.

Good to merge after its rebased.

**Pull request merged**
