### PR TITLE
prerelease Lobby automated deploy

### PR DESCRIPTION
**Pull request by DanVanAtta**
Add travis config and install script to deploy the lobby to the lobby server on each update of master. The second lobby is running on port 33333, rather than port 3303, and will be installed to: /home/triplea/triplea_prerelease_lobby

The install script also drops a pid file into the same folder, which it uses to identify and kill any previous running instances.

[Review on Reviewable](https://reviewable.io/reviews/triplea-game/triplea/458)

### CODE REVIEW

**Comment by ron-murhammer** [comment]
@DanVanAtta - Looks like this needs rebased.

@gaborbernat - I'm going to assign this one to you since its focused on the build process which you are pretty much the owner of and you now have merge permissions :)

**Comment by gaborbernat** [comment]
Yeah sure will review it.

Bernát GÁBOR

**Comment by gaborbernat** [comment]
Resolve the merge conflict, and my one note, otherwise good for merging.

---

Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[.travis/prerelease_lobby_install, line 13 \[r1\]](https://reviewable.io:443/reviews/triplea-game/triplea/458#-KBcJ7z8xD6R7Lz-naUV:-KBcJ7z8xD6R7Lz-naUW:260802902) ([raw file](https://github.com/triplea-game/triplea/blob/a1fca5e3fe73ae6a823baff2fb3ecbc94fa07cfd/.travis/prerelease_lobby_install#L13)):*
this seems like a potential bug down the line, maybe at this point just to make sure it's not running also do a kill -9, and another sleep if process is running? that is if the process for some reason failed to stop kill it forcefully

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/triplea-game/triplea/458#-:-KBcJPJvJ6E0rBqXsMum:-1105320686)*

**Comment by gaborbernat** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/triplea-game/triplea/458)*

**Comment by DanVanAtta** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[.travis/prerelease_lobby_install, line 13 \[r1\]](https://reviewable.io:443/reviews/triplea-game/triplea/458#-KBcJ7z8xD6R7Lz-naUV:-KBedKmUmMbR0JGu5ejB:1333746129) ([raw file](https://github.com/triplea-game/triplea/blob/a1fca5e3fe73ae6a823baff2fb3ecbc94fa07cfd/.travis/prerelease_lobby_install#L13)):*
Good point. Though if we did that then we would be burying the problem. Seems like the thing to do would be instead:
- check that the previous $PID dies after we kill it. If not exit -1 and print an error message.
- Check that the lobby pic is running a few seconds after we start it, exit -1 and print an error message if it is not.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/triplea-game/triplea/458)*

**Comment by DanVanAtta** [comment]
Script improved, please take another look @gaborbernat

**Comment by gaborbernat** [comment]
Reviewed 1 of 1 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/triplea-game/triplea/458)*

**Comment by gaborbernat** [comment]
@DanVanAtta this errored on Travis, can you check please :)

**Comment by DanVanAtta** [comment]
Found a typo in the .travis file #505 to fix.

**Pull request merged**
