### PR TITLE
Move version on for v4 & Global

### PR DESCRIPTION
**Pull request by simon33-2**
I think this needs to be merged. Was waiting for v3, v6, pacific and europe versions of ww2 to be merged but it's been too long and is causing confusion among players.

### CODE REVIEW

**Comment by panther2** [comment]
Agreed! Just referenced them.

**Comment by simon33-2** [comment]
BTW, this change doesn't include v3, Europe, Pacific or v6. Only Global and v4. There will need to be another PR to move on the version for those other maps when or if the fixes are merged. Big world has already been fixed.

**Comment by panther2** [comment]
Yes I understand that, I just thought that it could be added once those are merged. Don't know why they have not been, yet.

**Comment by simon33-2** [comment]
There needs to be more people with write access I think.

**Pull request merged**
