### PR TITLE
Eclipse launchers

### PR DESCRIPTION
**Pull request by DanVanAtta**
Add eclipse folder, move the formatter and cleanup files to it and add launchers: start game (GameRunner2), start local lobby, start headless (bot) server connecting to local lobby

[Review on Reviewable](https://reviewable.io/reviews/triplea-game/triplea/155)

### CODE REVIEW

**Comment by DanVanAtta** [comment]
@veqryn  @ron-murhammer  - this is a relatively easy pull request. There is pain by not having it, at the moment I'm having to recreate these launchers (again) and am considering basing another branch on this one just for the sake of having launchers. Please take a couple of moments to review and merge.

**Comment by ron-murhammer** [comment]
@DanVanAtta I'm fine with this. My only question is:

This is starting to lead us to adding IDE specific files into version control. Are we getting to a point that it just makes more sense to add the eclipse project/configuration files to the version control (.project, .classpath, .settings)?

**Comment by DanVanAtta** [comment]
I can see a pretty convincing case for launchers being checked in, particularly compared to other IDE files. The cost of launchers is quite low, they play quite well between eclipse versions and platforms. I do not know if that will be the case for other eclipse files. I'm also not yet convinced we'll save that much time by having those project files checked in. On the other hand, I won't be opposed to giving those files a try if we agree to "fail fast" on the effort.

So fundamentally I've no particular objection to having more IDE files checked in if it is convenient and does not cause anyone problems.

**Comment by ron-murhammer** [comment]
Alright. We can just add the launchers for now. Just wanted to bring up the point to see what your thoughts were.

**Comment by veqryn** [comment]
@DanVanAtta: What do these do?

**Comment by DanVanAtta** [comment]
Adds run configurations that are checked in. Eclipse will see them on file system refreshes and pick them up automatically. A fresh clone would not not to recreate them. Below is a screenshot. Note the four java application launchers, those are now checked in (there is another one as well to run tests). One other thing to note is the "common" tab has a field "shared file". The shared file location is the difference between local and something that you can check in and share with the project.

After you run the launcher from this menu first, it'll be available in the "quick run" menu - the green run arrow on the 'main' screen, center top.


run_config

**Pull request merged**
