### PR TITLE
Simplify Tuple usage

### PR DESCRIPTION
**Pull request by DanVanAtta**
Replace usages of "new Tuple< >(a,b)" or "new Triple< >(a,b,c)" with factory creation methods "Tuple.of(a,b)" or "Triple.of(a,b,c)"

The factory methods can automatically infer generic types, this simplifies code. So for example instead of writing:
   `Tuple<String,String> myTuple = new Tuple<String,String>("Value1", "Value2");`
We can instead write:
  `Tuple<String,String> myTuple = Tuple.of("Value1", "Value2");`

Also add a test for Tuple.java. One was not included for Triple.java, would be preferable to have that class be replaced by Guava @autovalue or something, it is not very clean to use. IE: getFirst(), getSecond(), getThird() can get really meaningless very quickly. Tuple falls in the same bucket, but for the moment it is useful enough to not be worth replacing just yet. In the meantime reducing the syntax around Tuple and making it a bit cleaner is a useful increment.

Class, Quadruple, was only used in Grid code, hence why this branch is based on top of grid removal, avoids updating 'legacy' code.

NOTE: breaks lobby chat compatibility, reminder to bump the version number before/after this is merged

Based on top of: #116, #117

[Review on Reviewable](https://reviewable.io/reviews/triplea-game/triplea/118)

### CODE REVIEW

**Comment by veqryn** [comment]
We could try using http://www.javatuples.org/index.html instead.
Also, why all these other commits that have nothing to do with tuples?  If I do want to accept your tuple patch, but don't want the rest (or the rest *yet*), then what to do?

**Comment by DanVanAtta** [comment]
I looked into libraries and found this: https://code.google.com/p/guava-libraries/wiki/IdeaGraveyard

IMO anything beyond triple is completely unusable, and triple is questionable. Quadruple I find much easier as "tuple<tuple,tuple>" rather than as "quadruble", or "{{a,b},{c,d}}  {a,b,c,d}

So, I'd rather not continue the existence of the library even, but I do still find Tuple useful at the same time. So in the meantime this is an update to make Tuple better, keeps triple around, and Quaduple was only used in grid code and so could be removed.

The other commits are all needed for one reason or another. First one fixes the build, from there I could ensure no regressions with respect to the build. The test libraries are needed since tests were added for the tuple class that require them. Guava is needed since the tuple was updated to use libraries for the equals, to string and hashcode functions. The next commit is the original change to add the static method. The next change is to remove grid code, this was done after the fact and after it was observed that quadruple was entired used in grid code and that an additional dozen updates would be needed in gride code to support the next change. Finally, the last change takes benefit of having the Tuple.of method.

Other branches really wanting Tuple.of might be built on top of this one, but in that case you'll see hte same commit stack and I'll also have to do re-basing work as things get committed. Not the worst work flow, but also not the most efficient (the overhead is reduced when the branch on branch is not needed and PR's are merged/updated/rejected quickly). 

So to answer your question directly, you can cherry pick to get the commits you want, but this was not structured in a way to allow that, and was made to be a minimal PR. So while you can, you shouldn't. In fact, this PR was structured to have minimal other branches, compilation errors were resolved by pulling in other branches one at a time, a few branches were recreated even in order to extract common ones.

**Comment by DanVanAtta** [comment]
So bottom line:
- this is an improvement, let's merge this, then add the library if needed. I've objection to the library, so this is the extent of hte work I want to do on this area for now. If you want to take it further, I don't know if that would be the most effective thing to do, but I wouldn't object too much.
- The mention of chat compatibility is more a callout we need to bump version numbers. Please explain why chat incompability is such a bad thing? Also, I noticed after this release that people were not playing 1805 games with the 1807 engines, so we effectively may as well have had a 1901 release as far the as the user behavior was concerned. Given that this doesn't break save games, and that we upgrade the lobby and force users to upgrade anyways, I'm curious where the problem would be exactly.

**Comment by ron-murhammer** [comment]
@DanVanAtta looks like one of the other merges conflicts with this.

**Comment by DanVanAtta** [comment]
Thanks, i'm not terribly surprised about that. I think it might be the same grid code merge conflict I resolved once for another branch already. To another extent, this is a good example of a flaw in a process. This could have N more merge conflicts and I'll resolved them that many more times. Eventually it may never get reviewed or die from too-nasty-to-fix merge conflict, in which case we will have just wasted time. So my point is, I'd almost rather someone let me know that they're ready to review, and that if i can get the merge conflicts fixed that they would then merge it. At the same time, merge conflicts do not block it from being reviewed.

**Comment by veqryn** [comment]
we are not removing grid code yet, so please do not depend on its removal.

**Comment by veqryn** [comment]
So, chat and lobby code can be changes, so long as no public api has changed.
The reason we do not want to change the public api, is because it breaks backwards compatibility with previous versions of TripleA.
So, to give an example:
Currently, the following versions of TripleA can join the online lobby in order to play older savegames:
1.5.2.1, 1.6.1.4, 1.7.0.3, 1.8.0.5, and 1.8.0.7
If you changed the API, then it would break the ability for those versions to join the lobby as part of playing an older savegame (you can explore this functionality by getting a savegame made by 1703, and trying to host it on the lobby).

Now, we CAN still break the api if it is necessary and a large enough feature to be worth it.  But it would mean doing a couple of things:
1. We need to do at least a minor version bump (ie: we would need to go to 1.9.x.x)
2. Going and finding the old branches we want to maintain compatibility with (say, we drop 1.5.x.x and 1.6.x.x but still want to keep 1.7.x.x and 1.8.x.x compatible, so we grab those last two branches).  Then we would need to patch these two branches to be able to join the new lobby (ie: fix their API's to match), and then rebuild their jar's and update the jars in the /old/ directory.

We don't be doing this over just an update to tuples...

**Comment by DanVanAtta** [comment]
The backwards compatibility with RMI is more brittle than I think you suspect. 1.8.0.7 games cannot joins games hosted by 1.8.0.9


If I don't depend on Grid being removed, then I have to maintain and fix Grid. We've agreed this is dead code, maintaining and fixing dead code is as close to a definition of waste of time as I can think.

**Comment by veqryn** [comment]
1807 and 1809 users should not be able to join each other's games, and currently can not due to checks on the host and client versions.
However, they can be in the lobby and talk in the lobby together.

Yes, RMI is more brittle than just the API, since you have to account for all serialized objects that get transfered.  I was simplifying things just a little.

I do like having grid games in there for now.  I can think about this some more.

**Comment by DanVanAtta** [comment]
I hosted a game, that had all of the 1809 code but not version,  and played
with people on 1807. This is a great way to test too, we should open that
up more and we can get beta users to really test new releases.

Then after trying out an auto-installer, I get an error message instead. So
at one point the RMI compatibility looks to have been broken. That is my
point, we break RMI compatibility very easily and often without realizing
it. I think we did so somewhere along the way that made the RMI calls no
longer compatible. Though that is unexpected given the changes in 1807 and
1809 were theoretically RMI backwards compatible.

**Comment by DanVanAtta** [comment]
This PR is in trouble, there are about 30 places that would need to be updated in grid code. @veqryn, do you really want that code updated for this PR?

**Comment by veqryn** [comment]
I'll talk with redrum and some of my lobby admins, and will come back to this soon.

**Comment by DanVanAtta** [comment]
@veqryn  Any follow up?

**Comment by veqryn** [comment]
@DanVanAtta: heavy heart and all, i guess removing grid stuff is better for the future
you will need to rebase after https://github.com/triplea-game/triplea/pull/203 is merged
After that we can evaluate what potential conflicts this PR has with the lobby api, if any.

**Comment by DanVanAtta** [comment]
PR updated with merge conflicts fixed.

IIRC you cannot connect to the existing lobby after this update. If that is the case then we simply need to update the lobby. We will do that anyways on the next release AFAIK. In retrospect, perhaps that is not a concern after all.

**Comment by veqryn** [comment]
@DanVanAtta: can you please do the following:
While on this branch, update the EngineVersion to 2.0.0.0, then launch a local lobby.
Create a lobby.properties file in the root dir that specifies localhost as the domain for the lobby server.
Join this local lobby using this branch, and test a game.  This should work just fine.

Now, to test for backwards compatibility, leave this 2.0.0.0 lobby running (and you can even leave your 2.0.0.0 game running).
Go find the installed copy of TripleA 1.8.0.9 and try to join the lobby.
If this fails, we've broken compatibility, and will need to update this PR to not break compatibility.

**Comment by veqryn** [comment]
Also, why did you make the constructor private?
I prefer using parameters to casting, and I should have the option to use the constructor when the factory method is forcing me to cast.

Secondly, why did you rename the fields from m_stuff to stuff?  Keep them the same and you probably won't break compatibility.

Can you please update this by making the constructor public again, and changing the fields back to what they were.

**Comment by DanVanAtta** [comment]
"Also, why did you make the constructor private?"

There is no longer a good reason to use it. The heart of this change is that we no longer use "new" and use the factory method, this gets rid of diamond notation. Can you give an example where the factory method forces you to cast but a constructor would not?

"Secondly, why did you rename the fields from m_stuff to stuff? Keep them the same and you probably won't break compatibility."
 
In the triplea-test repo we had an issue where every developer except you agreed that we should get rid of the "s_" and "m_" prefix naming conventions. It's been mentioned a few times since. Do you really want to keep that prefix naming convention around? Ultimately getting rid of the prefix helps understandability, scope is *way* less important than function and meaning. Polluting the name of variables does not help.

We also agreed on Google Java formatting. It spells out in gory detail how to create variable names. It leaves no room for variable prefixing.


Then the last point - what does it matter if compatibility was broken? We will upgrade the lobby on the next release just as we did in the prior releases. The prior releases we may have also broken the same compatibility but I don't think ever checked. Why are we now moving the goal posts for this PR?

**Comment by ron-murhammer** [comment]
@DanVanAtta Actually we haven't upgraded or broken lobby compatibility in a long time. I believe if we do that then we either have to host multiple lobbies or force everyone to immediately upgrade to the latest TripleA version when we release. An example is that all 1.8.0.x versions can connect to the same lobby but if we break compatibility then we need everyone to upgrade to the latest release and we have to upgrade the lobby.

**Comment by veqryn** [comment]
@DanVanAtta 
"Any examples of casting?"
`return Tuple.of((Territory) null, (Set<Unit>) new HashSet<Unit>());`

"Google Code format/style"
True, and I will try to follow it within reason, but I am not going to hold it as dogma.  Practical considerations always have a veto over ideology.  And this is one right here.

"Lobby Compatibility"
Actually, like @ron-murhammer says, we don't break compatibility with the lobby for new releases, or even releases that break savegame compatibility.
The Lobby != The Gamesave
And an important point to make here, is that not only can 1.8.0.5 and other 1.8.0.x join the current 1.8.0.9 lobby, but so can 1.7.x.x, 1.6.x.x, and 1.5.x.x.  They can join the current lobby, host an old gamesave, and even join a lobby game (provided that lobby game is running the exact same version of triplea as they are).
This functionality was an important part of making transitions between incompatible versions of triplea livable for our users.  When we upgraded from 1.7.x.x to 1.8.0.1, that was a savegame breaking move, meaning that 1.8.0.1 could not natively open 1.7.x.x gamesaves.  But, those users with old 1.7.x.x gamesaves could, from inside of 1.8.0.1, load up that gamesave using the 'old jars' functionality, and could also host those gamesaves on the lobby.  From the users perspective, it looked like 1.8.0.1 was able to play and host their old gamesaves, but it was really just some magic behind the scenes.

Now, that said, this doesn't mean we can never break the lobby API.  It just means that we should only do it when it is truly worth it, and accumulate more than a few changes as well.
So, when it comes time to break the API, how do we still maintain backwards compatibility?
After the new lobby api has solidified, but before any release, you will:
1. Determine how many versions backwards to make backwards compatible (at a minimum the previous release).
2. Checkout the release tag / git commit point where that release was finished, and make a new branch off of there. 
3. Update the code to make it compatible with the new API.
4. Package it as a jar and add it to the "/old" directory using the existing naming scheme.
5. Repeat for all other versions you want to have compatible.
6. Delete all other "old" versions that are no longer compatible.
7. Profit.

**Comment by DanVanAtta** [comment]
The casting is the same either way, if you use the factory method or constructor. The only difference is one needs diamond notation, the other uses java static type inference which is much better at figuring out typing and does not need diamond notation at all. In your example, the Tuple.of vs new constructor compile both in the same cases (and also the cast to Territory is unnecessary - and explicity, you need the cast from hashSet to Set no matter if you use the factory method or constructor)
```
    Tuple<Territory,Set<Unit>> demo;
    demo = Tuple.of((Territory) null, (Set<Unit>) new HashSet<Unit>());
    demo = new Tuple<>((Territory) null, (Set<Unit>) new HashSet<Unit>());

    demo = Tuple.of(null, (Set<Unit>) new HashSet<Unit>());
    demo = new Tuple<>(null, (Set<Unit>) new HashSet<Unit>());


    // demo = Tuple.of(null, new HashSet<Unit>()); // compilation error
    // demo = new Tuple<>(null, new HashSet<Unit>());  // compilation error
```

"Practical considerations always have a veto over ideology. And this is one right here."

I don't think that is the right way to look at it. The convention says that the right variable name contains no prefix. So the convention does what it is supposed to and clearly indicates that these variable names are wrong. But, I agree, practical considerations mean that is specifically not a good thing to do right now.  It will be a fine day one day when there are no runtime dependencies on the *name* of *private* variables.

**Comment by DanVanAtta** [comment]
Pushed an "undo" of the variable rename.

If/when there are necessary usages of a constructor, we can elevate the visibility when it is needed. In terms of casting of parameters, factory method vs constructor is the same - the difference is in the diamond notation.

**Comment by veqryn** [comment]
Actually, previous to the change, the snippet I chose looked like this (you can see there is no casting):
`return new Tuple<Territory, Set<Unit>>(null, new HashSet<Unit>());`

**Comment by DanVanAtta** [comment]
Indeed:
```
    example = new Tuple<Territory, Set<Unit>>(null, new HashSet<Unit>());
    example = new Tuple<>(null, (Set<Unit>) new HashSet<Unit>());
```

But in both cases, there is an explicit cast that is going on. So at some point, somewhere, you are going to have to do class casting, you will need the text `"Set<Unit>"` somewhere. The difference now is whether you force someone to specify the types of every parameter, or just the types of only the parameters that are being casted.

For example, you can always do the same 'up-casting' in two lines pretty cleanly:

```
    Set<Unit> units = new HashSet<Unit>();
    example = new Tuple<>(null, units );
```
So notice there how there is no need to specify "Territory". This represents a slightly lower degree of coupling compared to the constructor case.  But again, in all cases you're going to need the text "Set<Unit>" somewhere to accomplish the cast anyways.  So the question is, do we use the diamond notation to do the casting, or do we use explicit type casting to do it (parentheses)? In one case we need to specify the type of every parameter, in the other we do not.

**Comment by DanVanAtta** [comment]
@veqryn Variable renamed, constructor is still private. Is your preference to make it public now, or wait until we have a need to do so?

**Comment by veqryn** [comment]
I'd be curious if java 8's improved type inference removes the need to cast.  That would be great if it did.
I'll think about the constructor for another day or two, but in the mean time, can you test this and see if it still breaks compatibility or not?

**Comment by DanVanAtta** [comment]
I'll check the compatibility and will let you know what I find.

**Comment by ron-murhammer** [comment]
@DanVanAtta Any update on this?

**Comment by DanVanAtta** [comment]
Using this branch, a 1.8.0.9 game was able to to connect to a 2.8.0.9 lobby:
game_hosting_snap

**Comment by veqryn** [comment]
@DanVanAtta: did you also test the other way around, that this branch (2809 or w/e) could connect to a 1809 release snapshot lobby?

I am going to merge this, but I would like you to do that check and confirm back to me on it please.

**Comment by veqryn** [comment]
@DanVanAtta: just was reviewing the changes before committing.  While the merge check passes just fine, it looks like this PR undoes some of your good work on fixing comments (example: TriggerAttachment.java).
Do you want to fix this first before we merge, or after?

**Comment by DanVanAtta** [comment]
@veqryn , I'd prefer merging now so we can all have one less thing on our plate.

**Comment by veqryn** [comment]
Merged, thank you.
FYI this PR undoes some of your good work on fixing comments (example: TriggerAttachment.java).

**Pull request merged**
