### PR TITLE
Move panel cleanup

### PR DESCRIPTION
**Pull request by DanVanAtta**
[Review on Reviewable](https://reviewable.io/reviews/triplea-game/triplea/396)

### CODE REVIEW

**Comment by DanVanAtta** [comment]
How do you mean 'cases for lambdas'? The code compiles and works, so I think it is "a" case for lambda.

The for-each/lambda construct are similar. I'm very surprised that question is still active, not flagged as not helpful since it's opinion based the way it is asked. There is a pretty lengthy argument against, and another for.

The construct favors immutability, so that's good. Secondly, similar to simplified diamond notation, it's one less extra Class type reference hanging around. Simpler code to refactor, and less cruft getting in the way.


The for argument states the immutable aspect well:
"Not being able to access non final variables of the outer scope is not a deficit of functions/lambdas, it is a feature that distinguishes the semantics of Iterable#forEach from the semantics of a traditional for-each loop. Once one gets used to the syntax of Iterable#forEach, it makes the code more readable, because you immediately get this additional information about the code. "

Note, we like immutability so much these days that we have "final" explicitly called out everywhere, for args on simple methods I think that is more overkill than lambda on a simple foreach. The reason I bring that up, if you want to get rid of lambda, I would suggest it's the same reasoning as getting rid of the unnecessary 'finals'

**Comment by ron-murhammer** [comment]
@DanVanAtta I'd really prefer not to just change code to change it.

What does this even mean?
"The code compiles and works, so I think it is "a" case for lambda."

So use lambda anywhere that it can compile... I can write terrible code that compiles that's not a good reason to do it. All I want to discuss is 'why' change that foreach loop to use lambda. If you don't like that reference please feel free to link a better one though I think the discussion in the thread is pretty good. It also seems to support that foreach would be better in this instance which I tend to agree with (again limited knowledge of lambdas which is why I want to understand why lambda would be better).

**Comment by DanVanAtta** [comment]
> So I haven't used lambdas much yet so I'm interested in why this is better? 

It's a construct that favors immutability and reduces type coupling with simplified syntax that uses automatic type inference. This latter point is both a simplification and and helps refactor. The first point is the compelling one.

 > This is a pretty good discussion on foreach loops vs lambda 

This is an intereseting example, but wrong forum. Please create an issue if you want to talk about the merits or lack of merits. But in the meantime realize that there are actually 3 changes in this PR. It's being effectively all held up over just one item. That one item is not even about whether the change is correct or not. Meanwhile, I actually want this PR for basis on more work (which may or may not happen, but I got a start on it and this locks in some of that progress). By delaying the PR you add potentially merge conflict work, extra branch management, process delay, and overhead for conversation, editing it, and generally writing. Last, there is an inefficiency with the PR itself since multiple, including myself will keep having to re-review it, wastefully. It's most efficient time wise to take care of things once, rather than repeatedly returning to the same half-done task. So the cost of wanting to chat up about whether it's a good use of the syntax or not, is much more than just pure interest, but actually means I'll be spending extra hours. Hours that could be spent with my family or working on more important features. 


> This is a pretty good discussion .. http://stackoverflow.com/questions/16635398/java-8-iterable-foreach-vs-foreach-loop

It is interesting. The second answer is a compelling anit-case, the third is a compelling for case. Both are very subjective, and personally the first one reads a bit as if someone just doesn't like the syntax and doesn't like change.

>  I'm not sure that this code fits any of the cases for lambdas:

Please define what you mean by "fits any of the cases for lambdas". My point was, certainly this is a case. Is this a good case? Given my leading points, immutability and simplification, it is actually good to use lambda  for each for those reasons, so generally I would favor it other the foreach all things being equal.

Last, the burden of proof is really on you here to define what are the "cases" for lambda, and then how this doesn't fit.  We gain syntax simplification, easier refactor, a construct that favors immutability - which are relatively compelling reasons to simplify things this way. Thus it is not a change for the sake of a change.

**Comment by DanVanAtta** [comment]
@ron-murhammer , when reviewing a PR, the code review should be specific to the actual changes. A code review is not a high level discussion of the merits of various language features and syntaxes. 

If you think the changes for this specific code causes problems, please state what those are explicitly, with line numbers.

**Comment by ron-murhammer** [comment]
@DanVanAtta Comments:
1. How in this case is the code any more immutable then before?
2. Removing the type (Territory) from the variable I would say is a drawback in this case since you then need to go up 10 lines where the list was defined to figure out what type your are iterating over and because Java is a strongly typed language this is important in general. This is very different than <> notation which removes the need to define the type twice on the same line.
3. So I'm fine discussing lambdas in an issue but my point is I don't want us to start putting lambdas all over the place and have them being used in ways they aren't really meant to be used which I believe is the case here. Would be fine reverting that change and opening an issue to discuss. Merging stuff that we don't have agreement on though is not a good way forward.
4. I didn't choose what you bundled together and believe the first 2 changes should have been in a separate PR than the last change. This goes along with exactly what I stated about high level organizational changes vs low level code changes. When you bundled them together you make it all or nothing so that was your choice. If there is any 1 change that I don't think should be committed then I have to reject the PR til that is resolved even if there are 1000 other changes that are great.
5. This shouldn't block any further development since you can just base your next branch on this work. If this PR gets updates then you can rebase to pull them in.
6. Not following the 'inefficiency with the PR itself'... The point of PRs is to have others review the code so that you aren't just making lots of changes without someone else reviewing them. It would be much more efficient for us all to just merge all our own work but that would most likely lead to poor code and lots of misunderstandings. In general, in the past we have agreed that merging your own PRs shouldn't be done yet for some reason you chose to do it here...
7. That discussion does touch on both points though the overall it definitely is against using lambda's to replace simple foreach loops in general. Here is the tutorial link from Oracle that describes that basics of lambda usage/purpose which I don't think fits well in this change: https://docs.oracle.com/javase/tutorial/java/javaOO/lambdaexpressions.html
8. I guess I was trying to be too diplomatic about my code review. *I disagree with the replace of the foreach with the lambda* period. I thought maybe I was missing some benefit so I was giving you a chance to explain the change. You don't appear to have really given any good explanations.
9. I would argue the change is more complex and hard to understand for multiple reasons NOT simpler. Foreach is the general accepted syntax for these types of loops and has been around much longer. Many developers would now read through that code and not understand what is going on. Probably ask themselves why is someone using a lambda there. Its hard to tell what type you are looping over since its not explicitly defined. 
10. Are you indicated you want to replace all foreach loops in the code base with lambdas? Do you have any references to support this? I provided I link that you appear to disagree with but tends to favor foreach. I'm glad to find more if that's what you are looking for:
http://blog.jooq.org/2015/12/08/3-reasons-why-you-shouldnt-replace-your-for-loops-by-stream-foreach/
11. In general, code should just be changed for no reason. The burden of proof on why you made a change is on the committer which is what I asked for. I thought maybe I was missing some benefit but it appears not. I apologize for not being more direct about my comments about disagreeing with this change.

Summary:
- I don't agree with replacing foreach with lambdas so disagree with that change in this PR
- Please don't merge your own PRs as we discussed this in the past already
- When a committer creates a branch and a PR, they are choosing what to include. All of the changes must be reviewed and agreed to before the PR is merged. Having smaller PRs can make it so other changes aren't held up by more controversial changes. This is up to the committer to do.
- The burden of proof of why a change was made is on the committer. If the reviewer doesn't understand or agree then the reasons need to be explained.

**Comment by DanVanAtta** [comment]
1. How in this case is the code any more immutable then before?

The final references are now enforced, if that is dropped, we get a compiler error now. Effectively we are formalizing our usage of the Consumer pattern with the lambda foreach.


> 2. Removing the type (Territory) from the variable I would say is a drawback in this case since you then need to go up 10 lines where the list was defined to figure out what type your are iterating over and because Java is a strongly typed language this is important in general. 

I don't quite agree, I think the Territory type is relatively obvious.

> This is very different than <> notation which removes the need to define the type twice on the same line.

`<>` notation can be used on any line, it's not just on the same line. So it actually is similar..

For example:
```
List<Unit> myUnit;
:
: // 10 lines
myUnit = new ArrayList<>();
```


> 3.  "I don't want us to start putting lambdas all over the place and have them being used in ways they aren't really meant to be used which I believe is the case here."

Why would the 'foreach' method have been added to such a core library as Collections, if it was not meant to be used in this manner? I really disagree on your point here, I think your notion of 'proper' usage is limited.


> 4. I didn't choose what you bundled together and believe the first 2 changes should have been in a separate PR than the last change. This goes along with exactly what I stated about high level organizational changes vs low level code changes. When you bundled them together you make it all or nothing so that was your choice. If there is any 1 change that I don't think should be committed then I have to reject the PR til that is resolved even if there are 1000 other changes that are great.

No, you can revert the 1 commit, pick the SHA1 for that commit in the revert command. You do not need to pick the SHA1 of the merge commit that would revert the merge of the branch.

> 5. This shouldn't block any further development since you can just base your next branch on this work. If this PR gets updates then you can rebase to pull them in.

What happens to those branches when a revert commit is added to a base branch and then they are rebased? It's quite messy.


> 6. Not following the 'inefficiency with the PR itself'... The point of PRs is to have others review the code so that you aren't just making lots of changes without someone else reviewing them. It would be much more efficient for us all to just merge all our own work but that would most likely lead to poor code and lots of misunderstandings. In general, in the past we have agreed that merging your own PRs shouldn't be done yet for some reason you chose to do it here...

Leaving issues hanging/open, causes inefficiencies, overhead. 

I chose to do so since this entire debate is subjective at this point, and there no technical issues with the PR. So it was in fact reviewed.

I don't think you will win the battle of "never use a J8 lambda expression instead of a foreach loop", "always use the classic 'foreach' loop", and frankly "avoid lambda". We moved to J8 in part so we could take advantage of such features that both simplify the code and help allow for cleaner code (less buggy, easier to build on). Perhaps for this one project, but the resistance I sense is religious..

7. That discussion does touch on both points though the overall it definitely is against using lambda's to replace simple foreach loops in general. Here is the tutorial link from Oracle that describes that basics of lambda usage/purpose which I don't think fits well in this change: https://docs.oracle.com/javase/tutorial/java/javaOO/lambdaexpressions.html

The anonymous class here is the "Consumer" class: https://docs.oracle.com/javase/8/docs/api/java/util/function/Consumer.html

We are explictly casting this for each loop in this example to use the Consumer pattern.  If you have objections with lambda foreach, that is a simplified syntax for the Consumer pattern. Since the two are equivalent, you can also show why the Consumer pattern is not appropriate here to prove your point.

I am saying the Consumer pattern here is appropriate, and is a good thing. Hence the lambda expression to use it with less syntax than you even need for a foreach loop.


> 8. I guess I was trying to be too diplomatic about my code review. I disagree with the replace of the foreach with the lambda period. I thought maybe I was missing some benefit so I was giving you a chance to explain the change. You don't appear to have really given any good explanations.

See above answer.


> 9. I would argue the change is more complex and hard to understand for multiple reasons NOT simpler. Foreach is the general accepted syntax for these types of loops and has been around much longer. Many developers would now read through that code and not understand what is going on. Probably ask themselves why is someone using a lambda there. Its hard to tell what type you are looping over since its not explicitly defined. 

Developers had ask themselves the same questions when 'foreach' was introduced in Java. I would suggest this is purely a familiarity problem.


> 10. Are you indicated you want to replace all foreach loops in the code base with lambdas? Do you have any references to support this? I provided I link that you appear to disagree with but tends to favor foreach. I'm glad to find more if that's what you are looking for:
http://blog.jooq.org/2015/12/08/3-reasons-why-you-shouldnt-replace-your-for-loops-by-stream-foreach/

The fact you ask this question leads me to believe you really do not understand a lambda for each. You cannot just go and replace every foreach with a lambda foreach. The premise of the question is incorrect.

A Consumer pattern can always be unwound and implemented the hard way without the wrapper objects. But you can't always take a for loop and fit it into the Consumer pattern.


> 11. In general, code should just be changed for no reason. The burden of proof on why you made a change is on the committer which is what I asked for. I thought maybe I was missing some benefit but it appears not. I apologize for not being more direct about my comments about disagreeing with this change.

I'm in process of simplifying this code to extract functionality that is tightly coupled inside of it. Even if I don't get to the end of it, the simplification will be useful.

**Comment by DanVanAtta** [comment]
@ron-murhammer , if you can convincingly demonstrate why the Consumer pattern is not appropriate here, you will have shown why lambda is not appropriate.  The misunderstandings you have leads me to feel the opposite. You've given me two references, one is purely subjective and goes all over the place (though interesting and well written), and the second, the Oracle reference, actually supports this usage.

**Comment by ron-murhammer** [comment]
@DanVanAtta Comments:
1. Why do we need to 'enforce' final? Final already indicates that a variable is immutable, end of story.
2. If what is dropped we get a compiler error? The code compiled before your refactoring.
3. Your example of <> notation is one that I don't like to use for that exact reason.
4. Foreach() has many good uses especially when using other aggregate operations. Example: https://docs.oracle.com/javase/tutorial/collections/streams/
5. I'm not breaking up your PRs for you. If you bundle them together then you need to either break them apart or resolve the issues. Not just merge the PR yourself.
6. If its subjective then why are you correct and I'm wrong? Given that, then since I say prefer classic foreach instead of foreach with lambdas then I can go make PRs to do the exact opposite of what you did here? You SHOULD NOT MERGE YOUR OWN PRs, period. That shouldn't even be up for debate and you should be ashamed you did it, not be defending it.
7. I never said "I don't think you will win the battle of "never use a J8 lambda expression instead of a foreach loop", "always use the classic 'foreach' loop", and frankly "avoid lambda". We moved to J8 in part so we could take advantage of such features that both simplify the code and help allow for cleaner code (less buggy, easier to build on). Perhaps for this one project, but the resistance I sense is religious.." Honestly that is just offensive and argumentative. We are discussing this particular change and I'm not against using foreach() and lambdas. Both traditional foreach loops and foreach()/lambdas are tools that we need to determine when its best to use. 
8. Consumer pattern here is overkill. We have a simple 3 line foreach loop. KISS. There is no need to use a design pattern just because it exists. Again they are all tools that should be used in the proper situation.
9. Many libraries have been introduced in Java and just because they are added doesn't mean you use it everywhere because its the new/cool/sexy thing. You use it where its appropriate.
10. Again you appear to disregard the link I provide for no real reason and provide none of your own. For some reason, you believe you are correct with no justification and anything that doesn't agree with your point is subjective and someone's opinion. 
11. You did not simplify the code with that commit. You essentially made a replacement of foreach with lambda which adds complexity. 
12. I've given you 3 references (you still haven't provided any...):
http://stackoverflow.com/questions/16635398/java-8-iterable-foreach-vs-foreach-loop
http://blog.jooq.org/2015/12/08/3-reasons-why-you-shouldnt-replace-your-for-loops-by-stream-foreach/
https://docs.oracle.com/javase/tutorial/java/javaOO/lambdaexpressions.html
These all explain lambda usage and the first 2 explain 'why' you shouldn't replace all the traditional foreach loops with lambdas. Not sure what more you want... I can provide more links if that's it. I can copy the points from those references into here directly. Please let me know what more you need to be convinced.

At this point, I think we need a third party since you don't seem to be open to admitting you made an unnecessary subjective change with that commit. Everything that I've laid out you seem to either ignore or suggest that its subjective/opinion yet what you have to say is fact. This is really becoming a large waste of time that I could be spending doing much more productive work. Bottom line is don't merge your own PRs.

@veqryn @gaborbernat Can you guys please review this PR and provide thoughts around replacing  the traditional foreach with foreach()/lambda in this case?

**Pull request merged**
