### PR TITLE
Added CTF2

### PR DESCRIPTION
**Pull request by RogerCooper**

### CODE REVIEW

**Comment by beelee1** [comment]
@RogerCooper I don't see anything wrong but it doesn't like the yaml again.

* What went wrong:
Execution failed for task ':spotlessAllFilesCheck'.
> The following files had format violations:
      triplea_maps.yaml
          @@ -2493,4 +2493,3 @@
           ···<br>CTF·Good·Versus·Evil:·Fantasy·themed·units
           ···<br>CTF·Medieval:·Medieval·themed·units
           ···<br>CTF·WW2:·World·War·2·themed·units
          -···
  Run './gradlew :spotlessApply' to fix these violations.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

**Comment by RogerCooper** [comment]
I am having problem downloading maps with recent versions of TripleA [https://forums.triplea-game.org/topic/3109/unable-to-download-maps-in-2-6-535/6](url). Do you know what is the URL for downloading maps.

**Comment by beelee1** [comment]
Sorry no. i can't get 2.6 to work at all. It totally whacks out on downloaded maps

**Comment by RogerCooper** [comment]
I have been trying to all that maps I have to work for 2.6. Now it does not seem to be working at all.

**Comment by beelee1** [comment]
yea idk what to say. Sounds like Dan not around anymore, so idk what that means for 2.6

**Comment by RogerCooper** [comment]
I was not happy with the some of the changes that Dan was making in 2.6, so I would not be disappointed to go back to 2.5 and restart from there. Who is the lead programmer on this project now?

**Comment by beelee1** [comment]
idk. My guess, by seniority that is still somewhat active, would be Roiex. I guess Dan just taking an extended break, but historically people haven't come back from that. Not saying that'll be the case here but yea don't really know.

Unfortunately, I haven't been able to try out 2.6. i thought there was supposed to be a couple new features with it. As far as the way maps and stuff are all handled, I guess it's something I'll have to learn. I'm sure I'll struggle with it as with most things that are new

**Comment by RogerCooper** [comment]
Be careful when installing. When I first tried 2.6, it deleted many of my maps.

2.6 unzips all the mod folders. It deprecates the notes in the xml, instead storing them in a separate file. It also deprecates the map name, instead assuming that all the map files are in the folder.

Getting rid of the map name is a big problem. If I want to create mod using an existing map, I need to copy all the files over, resulting in a much bigger download. It also means that all scenarios in a mod must reference the same map.

**Comment by beelee1** [comment]
yea i made an issue a few months ago when it first happened. Dan is aware of it. Tried it a few weeks ago and got same behavior. I guess i should dig up the old issue and comment there. 

Not confident in a response though

**Pull request closed without merging**
