### PR TITLE
HeadlessGameServerConsole - Add test, break off controller functionality, Loop Delay Performance Improvement

### PR DESCRIPTION
**Pull request by DanVanAtta**
[Review on Reviewable](https://reviewable.io/reviews/triplea-game/triplea/53)

### CODE REVIEW

**Comment by DanVanAtta** [comment]
PR depends on this branch to be merged first (so we can get dependent test libs):  new_mockito_hamcrest_test_libs   (likely a PR with that branch will happen this if not that branch itself, so probably not an issue).

---

Review status: 0 of 3 files reviewed at latest revision, 6 unresolved discussions, all commit checks successful.

---

<sup>**[src/games/strategy/engine/framework/headlessGameServer/HeadlessConsoleController.java, line 1 \[r1\]](https://reviewable.io:443/reviews/triplea-game/triplea/53#-Jvwt0wPIMjdwLvO4t3Y)** ([raw file](https://github.com/triplea-game/triplea/blob/023ff540f7c85115e6f323b7d6681ee6e9fc304f/src/games/strategy/engine/framework/headlessGameServer/HeadlessConsoleController.java#L1)):</sup>
Contents of this class is largely the tail of the HeadlessGameServerConsole class. Since most functionality in HeadlessGameServerConsole is static, the move was pretty straight forward. The benefit/purpose of this is it leaves the scope and responsibility of HeadlessGameServerConsole to be much more limited. Specifically, that responsibility is: spin up infinite listener loop, get input, send input to be handled. The handling logic is now here. From here we can do further refactoring and testing.

The entry point into this class from HeadlessGameServerConsole is "process(String command)", which previously was a method implemented in the Console but is now in the controller.

---

<sup>**[src/games/strategy/engine/framework/headlessGameServer/HeadlessGameServerConsole.java, line 27 \[r1\]](https://reviewable.io:443/reviews/triplea-game/triplea/53#-JvwtqjFWGF_uJkd47SP)** ([raw file](https://github.com/triplea-game/triplea/blob/023ff540f7c85115e6f323b7d6681ee6e9fc304f/src/games/strategy/engine/framework/headlessGameServer/HeadlessGameServerConsole.java#L27)):</sup>
This constructor signature needed so we can inject mock objects.

---

<sup>**[src/games/strategy/engine/framework/headlessGameServer/HeadlessGameServerConsole.java, line 33 \[r1\]](https://reviewable.io:443/reviews/triplea-game/triplea/53#-Jvwti_Y3S9Hg7oJ2sDG)** ([raw file](https://github.com/triplea-game/triplea/blob/c3d49d3d3fec0a96af3803e45f41eacb6c3e830f/src/games/strategy/engine/framework/headlessGameServer/HeadlessGameServerConsole.java#L33)):</sup>
It turns out when we get the quit command we do a System.exit(0), so this (m_shutDown) is never changed to true

---

<sup>**[src/games/strategy/engine/framework/headlessGameServer/HeadlessGameServerConsole.java, line 60 \[r1\]](https://reviewable.io:443/reviews/triplea-game/triplea/53#-Jvwtw7Z1RLudYyQUVMn)** ([raw file](https://github.com/triplea-game/triplea/blob/023ff540f7c85115e6f323b7d6681ee6e9fc304f/src/games/strategy/engine/framework/headlessGameServer/HeadlessGameServerConsole.java#L60)):</sup>
And this is where we broke off the bottom of the class and now schill out to the controller to act on the command.

---

<sup>**[src/games/strategy/engine/framework/headlessGameServer/HeadlessGameServerConsole.java, line 68 \[r1\]](https://reviewable.io:443/reviews/triplea-game/triplea/53#-Jvwu0ZMy5HumNXQ_0uD)** ([raw file](https://github.com/triplea-game/triplea/blob/023ff540f7c85115e6f323b7d6681ee6e9fc304f/src/games/strategy/engine/framework/headlessGameServer/HeadlessGameServerConsole.java#L68)):</sup>
Way down here is a small loop delay. This delay gives input time to buffer up. We may see some improvement in CPU usage of bots, they won't be so busy aggressively trying to read input.

---

<sup>**[src/games/strategy/engine/framework/headlessGameServer/HeadlessGameServerConsole.java, line 79 \[r1\]](https://reviewable.io:443/reviews/triplea-game/triplea/53#-JvwuH8VRV1BBRSytWpv)** ([raw file](https://github.com/triplea-game/triplea/blob/c3d49d3d3fec0a96af3803e45f41eacb6c3e830f/src/games/strategy/engine/framework/headlessGameServer/HeadlessGameServerConsole.java#L79)):</sup>
And now starting from here below, the stuff was moved to the controller.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/triplea-game/triplea/53)

**Comment by veqryn** [comment]
I hate it how git and diffs can't see that stuff is being moved, not changed...

**Comment by veqryn** [comment]
rebase pls

**Comment by DanVanAtta** [comment]
@veqryn  Now rebased

**Comment by ron-murhammer** [comment]
Looks good. Pretty straightforward refactoring which makes this much cleaner. Also nice that a basic unit test was added.

@veqryn All yours!

**Comment by veqryn** [comment]
The console class was mostly just composed of what you moved to the controller class.  What is the point of breaking it apart like this?
Also, because it is moved to another file, I am finding it hard to tell what you have changed in the actual content.  I've always hated moving methods and code around for this reason, so do you have any recommended way for me to quickly and easily review what changed to the code?  If not, my plan is to copy the code side by side into notepad++ and try diffing it, but I am curious if anyone knows of something easier.

**Comment by gaborbernat** [comment]
Meld? :)

**Comment by DanVanAtta** [comment]
Another change needed a test on HeadlessGameServerConsole. As is, the class was not testable and has many design problems that make it time consuming to work with. Breaking it up helps, lessens the SRP violation, and allows for a start to testing.

I would recommend eyeballing about 5 lines at a time and comparing. It took me about 3 minutes to be pretty convinced that nothing had changed. There are only about 4 or 5 complicated methods, it's not too much to eyeball. Or if you insist on being really really accurate, open up the same review in two different windows and scroll side by side.

**Comment by DanVanAtta** [comment]
@veqryn, here is a diff of the stuff that moved: http://pastebin.com/L5AfSkBxa
Formatting and old style end of line comments are the only differences

Diff was generated with:
```
$ cd triplea/src/games/strategy/engine/framework/headlessGameServer
$ git checkout master
$ cp  HeadlessGameServerConsole.java  HeadlessGameServerConsole.java.orig
$ git checkout  HeadlessGameServerConsole
$ diff HeadlessGameServerConsole.java.orig HeadlessConsoleController.java
```

**Comment by DanVanAtta** [comment]
@veqryn, any chance you'll get to this PR in the next couple weeks? If not, can @ron-murhammer review it again and merge it instead? At the risk of complaining, this PR is almost 4 months old. It's not efficient for anyone for something to sit this long. I would like to get this moving forward so we can kindly forget about it and move on.

**Comment by veqryn** [comment]
@DanVanAtta: the diff helps a lot, thanks!
why remove the shutdown boolean?

**Comment by DanVanAtta** [comment]
I can't remember why the shutdown boolean was removed. I'll refactor something back in to restore it. Please skip this PR for a few days or a week while I work on that..

**Comment by DanVanAtta** [comment]
Updated:
- Restored the shutdown logic. I think maybe I was leaving that for another day and forgot about restoring it, and then when looking for branches that were hanging out ready to be pushed I might have included this one..
- The 'server' constructor arg is not used in the 'HeadlessServerConsole' class. Fixed that by removing it.
- Added "checkNotNull" around the constructor args in the 'HeadlessServerController', this then allows for needless null checks to drop away. Since the controller is created in only one place, judging from that location it does not look like the controller should ever receive null parameter inputs.

**Comment by veqryn** [comment]
looks good now

**Pull request merged**
