### PR TITLE
Prune lobby welcome message

### PR DESCRIPTION
**Pull request by DanVanAtta**
- Remvoe upgrade text, if users have not upgraded by now, the continued lobby message is not going to make a difference.

- Remove help mention, there is a 'help' menu that users should be able to find without too much trouble

 

## Functional Changes

[ ] New map or map update
[ ] New Feature
[ ] Feature update or enhancement
[ ] Feature Removal
[ ] Code Cleanup or refactor
[ ] Configuration Change
[ ] Bug fix:  
[x] Other:   Lobby welcome text changed

### CODE REVIEW

**Comment by Cernelius** [comment]
I'd change "Welcome to TripleA, we are pleased you are here" to only "Welcome to the TripleA lobby".

**Comment by DanVanAtta** [comment]
It is a bit saccharine, but I don't think it hurts @Cernelius and avoids "welcome to..." from being a bit overly dry IMO. We could think to maybe remove the message. Long term I think we probably need to create a 'terms and rules of lobby' pop-up for first-time logins where a person has to agree once. Then we could remove most of the welcome message, I think it'll be most effective if it changes every few weeks and also is not more than a sentence or two.

**Comment by DanVanAtta** [comment]
Merging for now, we can continue following-up and discussing changes.

**Comment by Cernelius** [comment]
The other item that I was pointing out is that should welcome the user to the lobby, rather than to TripleA in general.

At most I would add something like "enjoy your stay".

**Comment by DanVanAtta** [comment]
I missed that, good suggestion. I'm personally tempted to axe the welcome message line, not sure if it is really needed.

**Pull request merged**
