### PR TITLE
Parens

### PR DESCRIPTION
**Pull request by DanVanAtta**
### Overview

Ran IDE static analysis to add parens in compound conditionals

### Scope

I'll happily fix any egregious formatting or checkstyle errors. 

### Review

The hand formatting, second commit is perhaps worth a more detailed look. The first commit is all IDE.

### CODE REVIEW

**Comment by ron-murhammer** [comment]
@DanVanAtta This is potentially going to conflict with other PRs in progress. I think we need to be a bit more careful around mass refactoring changes that's touching 100s of files.

**Comment by DanVanAtta** [comment]
> @DanVanAtta This is potentially going to conflict with other PRs in progress. I think we need to be a bit more careful around mass refactoring changes that's touching 100s of files.

The conflicts should be pretty easy to resolve. I'm not sure how much more careful we can always be, there will always be in-flight work. 

I spent some pretty solid time cleaning this up post-update. I'm not going to be happy to have lost a few hours, the other way round, conflicts are going to be bad for this PR. I don't think anyone is going to lose more than a few minutes updating, hard to justify that against a few hours getting this ready.

**Comment by DanVanAtta** [comment]
>  I only spot-checked the first commit; 

More than fair,  it's machine done; some engineers do not review machine work at all;

I don't think it's worth spending too much time reviewing. Either we have missing parens everywhere in the project, or we get it fixed. I don't want to see onesy-twosy fixes and last PR was nitted over missing parens; we should get it fixed.

**Comment by DanVanAtta** [comment]
@ron-murhammer do you have any branches you're particularly concerned about? I can send de-confliction PRs post-merge your way if concerned..

**Comment by DanVanAtta** [comment]
> This is potentially going to conflict with other PRs in progress.
@ron-murhammer sorry, this bothers me, it's not a good reason for holding up a PR. If you've any branches that are about ready that you specifically want to go first, we can coordinate. If you've something in-flight and are worried about conflicts, let me know and I can help.

**Comment by DanVanAtta** [comment]
@ron-murhammer thinking about this:
- yes, changing many files is likely to have conflicts, but they are not necessarily going to be bad ones.
- changes in other branches are likely to conflict badly with this branch. The merge conflict concern is really for this branch, not the other way round. Merging changes into this branch are likely to be bad resolutions, while the other way round they are likely to be automatic, or very simple to fix.

We've an active problem where so many conditionals are hard to read, and adding parens was requested in another PR. There is no good reason to fix that by hand, I also don't want to see a commit attached to each PR "fix parens in this file", which would hurt those diffs. Generally if there is a problem found in a PR that is across the board, fixing it across the board in a follow-up seems effective so we aren't consistently tripping up over it.

**Comment by DanVanAtta** [comment]
I'll follow up with an issue on some mass changes. If we do not review them, then it will work well.

This one has been frustrating:
- I updated this branch so it merges cleanly with your PR @ron-murhammer , that was easy.
- Creating a PR to merge cleanly with the other open PR was a bit more work, but done in 5 minutes.

Meanwhile:
- there were hand fixes to this
- I spent 20 minutes doing difficult merge conflicts today
- did merge conflicts yesterday
- the merge conflict concern was for *this* branch, not the other way round. Same line, single character updates that can be ignored are easy to resolve.  :|

So this is dead, and the work that went into it, which is annoying as the concern for it were misguided; the merge conflict concern was the other way round; and this was ready to be merged at one point.

Going forward @ron-murhammer , if there is a concern over conflicts, I'd ask that specific branches be mentioned and at that time an ordering be determined. I would have been happy to help deconflict those branches, but I was not happy to have more of my own changes get merged out of order conflicting this branch to death.

**Pull request closed without merging**
