### PR TITLE
Update triplea_maps.yaml

### PR DESCRIPTION
**Pull request by beelee1**
New Map Upload

G 40 Expansion

## Testing

Have tested locally and map runs correctly.

### CODE REVIEW

**Comment by beelee1** [comment]
Well I'm out of ideas @DanVanAtta  When you get a chance would you look at this ?

Thanks

**Comment by RoiEXLab** [comment]
@beelee1 The formatting is correct now, however the repository https://github.com/triplea-maps/g_40_expansion does not exist which is why the build fails

**Comment by beelee1** [comment]
@RoiEXLab  thanks for the reply. I didn't realize the "I" was needed. I don't have it in the other map yamls. 

At any rate I just noticed it says "private" next to the repo in triplea-maps. i tried to transfer to triplea-maps and then tried pasting the url as well but the transfer button doesn't light up.

Do you know who i need to transfer it too ?

Thanks

**Comment by beelee1** [comment]
Ok I'm closing this and starting over

**Comment by RoiEXLab** [comment]
@beelee1 Ah if it says "private" this means the repo is only visible to members of triplea-maps, that's why I can't see the repo and the build script can't see it either.
You need to make sure the repository is public

**Pull request closed without merging**
