### PR TITLE
Cache gradle dependencies in travis

### PR DESCRIPTION
**Pull request by RoiEXLab**
See https://docs.travis-ci.com/user/languages/java/#Caching for more information

### CODE REVIEW

**Comment by ssoloff** [comment]
From the [Travis docs](https://docs.travis-ci.com/user/caching/#How-does-the-caching-work%3F):

> Note that this makes our cache not network-local, it’s still bound to network bandwidth and DNS resolutions for S3. That impacts what you can and should store in the cache. If you store archives larger than a few hundred megabytes in the cache, it’s unlikely that you’ll see a big speed improvement.

I checked the [cache settings](https://travis-ci.org/triplea-game/triplea/caches) for this branch, and it's currently 214 MiB.  So, given the disclaimer above, I'm just curious how much the build time will improve with caching enabled.  Did you do a test in your fork?  If not, can you just amend your latest commit in this branch (without any changes) and force push to trigger a new build (please do not just restart the build on Travis so we can compare logs before and after the cache is in place)?

**Comment by RoiEXLab** [comment]
The difference it not that great (looks like 6 seconds), but at least this avoids the long "Downloading dependency xyz" logs.
So whatever

**Comment by ssoloff** [comment]
@RoiEXLab I just looked at my local copies of the folders that will be cached and noticed they contain different folders for different versions of Gradle I've built with in the past:

```
$ ll ~/.gradle/caches
total 40
drwxrwxr-x. 6 ssoloff ssoloff 4096 Aug  9 23:54 3.3
drwxrwxr-x. 9 ssoloff ssoloff 4096 May 31  2017 3.5
drwxrwxr-x. 9 ssoloff ssoloff 4096 Jul  1 19:05 4.0
drwxrwxr-x. 9 ssoloff ssoloff 4096 Aug 24 15:28 4.1
drwxrwxr-x. 9 ssoloff ssoloff 4096 Sep 27 12:50 4.2
drwxrwxr-x. 7 ssoloff ssoloff 4096 Dec 20 22:55 4.4.1
drwxrwxr-x. 2 ssoloff ssoloff 4096 Aug  9 23:54 jars-2
drwxrwxr-x. 6 ssoloff ssoloff 4096 Oct 23 23:18 jars-3
drwxrwxr-x. 6 ssoloff ssoloff 4096 Dec 20 22:55 modules-2
drwxrwxr-x. 2 ssoloff ssoloff 4096 May 31  2017 transforms-1
```

```
$ ll ~/.gradle/wrapper/dists/
total 48
drwxrwxr-x. 3 ssoloff ssoloff 4096 Dec 22  2015 gradle-2.10-bin
drwxrwxr-x. 3 ssoloff ssoloff 4096 Feb  8  2016 gradle-2.11-bin
drwxrwxr-x. 3 ssoloff ssoloff 4096 Aug  9 23:52 gradle-3.3-all
drwxrwxr-x. 3 ssoloff ssoloff 4096 Jan 30  2017 gradle-3.3-bin
drwxrwxr-x. 3 ssoloff ssoloff 4096 Mar 21  2017 gradle-3.4.1-all
drwxrwxr-x. 3 ssoloff ssoloff 4096 Apr 29  2017 gradle-3.5-all
drwxrwxr-x. 3 ssoloff ssoloff 4096 Apr 29  2017 gradle-3.5-bin
drwxrwxr-x. 3 ssoloff ssoloff 4096 Jul  1 18:57 gradle-4.0-all
drwxrwxr-x. 3 ssoloff ssoloff 4096 Aug 24 15:25 gradle-4.1-all
drwxrwxr-x. 3 ssoloff ssoloff 4096 Sep 27 12:47 gradle-4.2-all
drwxrwxr-x. 3 ssoloff ssoloff 4096 Dec 20 22:53 gradle-4.4.1-all
drwxrwxr-x. 3 ssoloff ssoloff 4096 Dec 23 12:11 gradle-4.4.1-bin
```

Presumably, as we upgrade Gradle, we'll be caching data that is no longer required, and the builds may actually get slower.  We should probably manually [clear the cache](https://docs.travis-ci.com/user/caching/#Clearing-Caches) every time Gradle is upgraded to avoid slowing down the build as time progresses.

**Comment by RoiEXLab** [comment]
@ssoloff Good Point.
Leaving it up to you how to proceed from here.

**Comment by ssoloff** [comment]
@RoiEXLab I guess it comes down to asking if a six second improvement is worth the extra process?  Noting that if the extra process isn't followed, build time performance will ultimately decrease.  My personal opinion is that a 2% improvement is probably not worth it.

However, if you want to merge this change, I would suggest adding some brief documentation under _docs/dev/_ that describes what's involved in upgrading Gradle.  That's probably just two items:

1. The syntax of the `wrapper` task we run to perform the upgrade.
1. How to clear the Travis cache after the Gradle upgrade PR is merged.

That way, if a few months goes by between Gradle upgrades, it's less likely that we will forget to clear the Travis cache.

**Comment by RoiEXLab** [comment]
I haven't done any testing in advance, so it was an experiment for me as well.
There wasn't even a lot of effort put in this PR, so closing, experiment showed to little improvement

**Comment by ssoloff** [comment]
Well, it was a good idea nonetheless.  And I learned that Travis offers a caching facility, which I didn't know before. :smile:

**Comment by RoiEXLab** [comment]
@ssoloff Didn't know about that either until yesterday when I wanted to check what jdks are available in travis ^^
That's why I wanted to check.
I'm pretty sure this feature is one of the newer features though

**Pull request closed without merging**
