### PR TITLE
Allow dice image of 0

### PR DESCRIPTION
**Pull request by ron-murhammer**
Update check that didn't allow dice images with 0 value

### CODE REVIEW

**Comment by ron-murhammer** [comment]
Merging as just a 2 line UI change.

**Comment by RoiEXLab** [comment]
Because I'm currently working on the new dice server software:
Do dice servers need to be able to return "0" as dice?

**Comment by prastle** [comment]
I believe the "0" needed to be shown for when a negative is applied due to triggers and effects.  (Example a bomber can miss now).  But the dice still cant roll a Zero it only becomes a Zero from effects.  Hope that helps @RoiEXLab

**Comment by RoiEXLab** [comment]
@prastle Does help indeed, thanks!

**Comment by prastle** [comment]
Also I asked you a ? on gitter when ya have a second @RoiEXLab

**Comment by ron-murhammer** [comment]
@RoiEXLab Pras is correct that dice still start at 1 but bonuses/etc can make it 0 (or miss for bombing).

**Pull request merged**
