### PR TITLE
Add LGTM code quality badges

### PR DESCRIPTION
**Pull request by xcorail**
Hi there!

I thought you might be interested in adding these [code quality badges](https://lgtm.com/projects/g/triplea-game/triplea/ci/#badges) to your project. They will indicate a very high code quality to potential users and contributors.
To get an idea of the analyses reflected by these grades, check the [alerts discovered by LGTM](https://lgtm.com/projects/g/triplea-game/triplea).

N.B.: I am on the team behind LGTM.com, I'd appreciate your feedback on this initiative, whether you're interested or not, if you find time to drop me a line. Thanks.

### CODE REVIEW

**Comment by RoiEXLab** [comment]
@DanVanAtta @ron-murhammer @ssoloff 
I don't have any strong opinion on this, thoughts?

**Comment by ssoloff** [comment]
We decided not to use Codacy, a similar tool, in #2498 for various reasons.  (One big issue with Codacy is that it didn't support a custom location for _checkstyle.xml_, and their support team indicated such a customization was not on their roadmap.)

Looking at the LGTM alert report, there are some good issues identified that are worthy of fixes.

However, I'm not sure how useful something like Codacy/LGTM is going forward unless triggering new alerts would fail a build.  Otherwise, no one's going to look at it, and alerts will tend to just increase over time.  One of the suggestions mentioned in #2498 was to integrate this type of static analysis (which should be possible with FindBugs and/or PMD) into the Gradle build so it is actually enforced.

So I'm a firm neutral here, as well.  If we can get it to fail a PR build upon a net increase of alerts, I would change my vote to :+1:.

**Comment by xcorail** [comment]
Hello @ssoloff 

Thanks a lot for the feedback!

> Looking at the LGTM alert report, there are some good issues identified that are worthy of fixes.

Happy you found it useful. Note that whatever your decision or using or not this service, these alerts will be always there for you guys, to check at any time. Commits are polled once a day.

> However, I'm not sure how useful something like Codacy/LGTM is going forward unless triggering new alerts would fail a build

I couldn't agree more. There is one thing you can already do, it's activate PR integration. LGTM will report any new problem (but also the fixes) directly within the PR. It's a [one-click operation](https://lgtm.com/projects/g/triplea-game/triplea/ci/), and it's free for open source projects. You can configure the integration to block or not the PR. Here the analysis is done immediately, not polled once a day.
You can easily give it a try and deactivate if it's not ok. (And I'll appreciate your feedback on it of course)

A second thing we are working on is to provide you with APIs so that you can integrate our analysis within your ecosystem. They should be available this quarter.

**Comment by ssoloff** [comment]
> these alerts will be always there for you guys, to check at any time

@xcorail  Thank you, that's good to know.  I've already got it bookmarked to address some of the identified issues. :smile:

> There is one thing you can already do, it's activate PR integration.

@ron-murhammer @DanVanAtta Assigning to you both for the final :+1: :-1: decision since it will probably require an admin to configure the PR integration.  Sounds like we can evaluate LGTM without it blocking merges, and then remove it if we don't find it useful.

**Comment by ron-murhammer** [comment]
We'll give it a try. Merging this and activating PR integration.

**Pull request merged**
