### PR TITLE
Added Russian Civil War

### PR DESCRIPTION
**Pull request by RogerCooper**

### CODE REVIEW

**Comment by beelee1** [comment]
@RogerCooper I think you need to remove line 2738 ?

**Comment by beelee1** [comment]
@RogerCooper you wanna go ahead and close these two

**Comment by RogerCooper** [comment]
I tried removing the blank line and it worked, even though I needed the blank line before. I hate YAML format.

**Comment by RogerCooper** [comment]
Then I got an error.

**Pull request closed without merging**
