### PR TITLE
trying to fix this line endings mess

### PR DESCRIPTION
**Pull request by veqryn**
[Review on Reviewable](https://reviewable.io/reviews/triplea-game/triplea/148)

### CODE REVIEW

**Comment by veqryn** [comment]
@DanVanAtta: do you knows up with ww2v6_1941_test.xml?  git thinks it is binary, and my text editor shows everything in chinese or japanese....

**Comment by DanVanAtta** [comment]
This change doesn't fix the problem, still see a lot of changed line endings. I think this probably a particularly difficult task to do on Windows, Windows is very eager to quietly change line endings for you.

The line endings were inconsistent in SVN, SVN simply didn't provide the same level of management 
as git does. In the SVN world the rule of thumb was everything was LF unless you were a 100% windows shop, in which case you have 100% CRLF. Alternatively you silently dealt with CRLF + LF mixture, and likely did not realize it and occasionally had breaks/errors because of "^M" characters . Chances are good that was the case with few Mac/Unix developers who would be the ones to break the CRLF consistency. 

What autocrlf=true does is allows windows users to get CRLF automatically so you can view files, but they don't get checked in.  This is so you can have your CRLF's, and you don't force them on Unix/Mac developers. 

Also, deploying CRLF files to Unix and Mac systems is DANGEROUS. I debugged once an XML parsing error because a "^M" made it into a DTD file. This is why I think it is a very bad idea to have any CRLF files in repo, we have to fix them at packaging time, and in the meantime it was one more variable that makes our tests drift from production.

IMO We should follow git best practices here. Windows users use autocrlf = true, LInux use  autocrlf =input.  We commit only LF into source code (since windows users get CRLF everywhere with the autocrlf, this is not a problem). Yeah, LF in source code only is not required, but the reason to have LF only is because CRLF *breaks* things. It is an annoyance to have a file appear as one line in notepad, it is more than an annoyance to have the game crash or fail because of CRLF (and we had an example recently where CRLF broke unix). 

Having CRLF also means there is that extra level we have to test on Unix and Mac. Like we *really* do have to test that. CRLF plays well on windows always. So LF in source code, and CRLF in windows only packages minimizes our test burden and risk.

**Comment by DanVanAtta** [comment]
With all that said:
.gitattributes is  useful for forcing good end of line consistency, which is difficult on windows machines.

Since linux is seeing the problem readily, how about this:
- I'll do a fresh clone and let git fix any line endings per the git attribute file
- I'll submit a PR,
- Then do what I did and check out the branch, see if git tries to change any files. If not, we'll then be good to go.

I have stated though a preferred solution for me is CRLF only when on windows, otherwise all LF. At this point let's go with the above plan, LF vs CRLF is not a good thing for us to spending so much time on.

**Comment by veqryn** [comment]
You are missing a large point.  Windows users using autocrlf=true is how we got problems with the initial 1807 release.  
This is a so-called git best practice that isn't a best practice anymore.  From what I am reading these days, using .gitattributes is the new best practice.

Instead of doing your plan, why not check out this branch, fresh, seeing as how it should solve the issue?

**Comment by DanVanAtta** [comment]
My original comment 2 hours ago of this not fixing the problem was based on a fresh clone and checkout of this branch.

I'm not clear how how `autocrlf=true` could have caused this problem. It is precisely there to convert CRLF back to LF on commit, to avoid committing CRLF into repo.

```
core.autocrlf = true

This means that Git will process all text files and make sure that CRLF is replaced with LF when writing that file to the object database and turn all LF back into CRLF when writing out into the working directory. This is the recommended setting on Windows because it ensures that your repository can be used on other platforms while retaining CRLF in your working directory.
```
http://stackoverflow.com/questions/3206843/how-line-ending-conversions-work-with-git-core-autocrlf-between-different-operat

Deploying CRLF to unix and mac machines is certainly not a good practice, and is risky. CRLF all for the benefit of just notepad I have trouble seeing as being worthwhile.

How should we move forward on this?

**Comment by DanVanAtta** [comment]
If you find any interesting or compelling reads on .gitattributes, please do link them, I would be interested in the reads.

My suggestion for next steps is to go back to the plan I pitched a few hours ago. I think if I commit all files that are modified on a fresh linux checkout, I'm guessing windows will be happy with the modifications too. If that is the case, we will have "correct" line endings and nobody gets auto-modified files  anymore.

**Comment by veqryn** [comment]
I did this branch on linux btw, not windows.

**Comment by veqryn** [comment]
So, the find commands I ran to generate this branch, all look good, as do the results.
I plan on merging this, unless there are any actual objections.

**Comment by DanVanAtta** [comment]
"actual objections."

Please avoid unnecessary disrespect as it motivates nobody and does not generally help.

If you say this fixes things, then let's merge it since it'll hardly make anything worse. I don't really care about the line endings, I want files to not be modified on checkout and I would like to go back to other tasks.

I'd recommend testing carefully around MAC/LINUX XML and DTD functionality as CRLF can cause problems there.

**Comment by DanVanAtta** [comment]
PS: did you figure out what went wrong with the character set?

As a data point - I can apply the work around to get linux to think I'm in a clean state. So in any case I don't think we'll know for certain until after this has been merged if it fixes everything. Yeah, running dos2unix or unix2dos corresponding to the gitattributes file *should* really fix it. So again, IMO let's merge and see what happens.

**Comment by gaborbernat** [comment]
Ok, here are my ***actual objections***:

1. It may be nice that this works on your Linux system @veqryn, however even this solution does not  work on my machine (Arch Linux latest, lastest 2.5.1 Git - and tried for at least one other person). Did you actually tried to do a clean pull after making this commit, and see how it goes? Yeah, I tried, and suprise for me it's the same old. :-1: 
 
2. I literally spent like 3 hours researching and trying to really fix this issue yesterady. And yes I did ran over the URL you link in. Plus at least 10 others. And all points to the same conclusion: this should work but it does not. Hence, why I connected guys in the git IRC channel, they said the same they are not 100% sure, but together we came up with an actual solution.

3. I refuse to change my global autoctrl settings. Why? Because I work on 10 other projects for which my current setttings are the good. That was the old way, which forced the user to set it's own resolution for line endings, gitattributes is the new way of doing things, which makes this settings be part of the git repo itself. http://adaptivepatchwork.com/2012/03/01/mind-the-end-of-your-line/

4. I fail to see why not go ahead with my proposed solution? It was a good solution from my current understanding, that while true modified the git objects, the working directory always contained the right line endings. And that's whay you were looking for. I'm just wondering, you do understand the difference between the working directory and the object database?

**Comment by veqryn** [comment]
@gaborbernat: will your proposed solution result in CRLF on *.txt files on linux and mac computers?

**Comment by gaborbernat** [comment]
Absolutely yes, that's why it's a solution.

**Comment by veqryn** [comment]
So why then, does my current checkout from master, on a linux machine, not have CRLF on files like changelog right now?

**Comment by gaborbernat** [comment]
Hmm, not sure, however I also applied the changes on my clone (and there seems to work). See https://github.com/gaborbernat/triplea/commits/master. There may be some other issues to here.

**Comment by gaborbernat** [comment]
I'm also in progress of testing this on MAC, however the clone speed of the repository is slow :)

**Comment by gaborbernat** [comment]
Tested it works on MAC too.

**Comment by gaborbernat** [comment]
So what will we do, will you accept my version as a pull request? (Maybe you should also test that it works beforehand). My problem with this one is that for me it does not seem to work :worried:

**Comment by veqryn** [comment]
Ok, could you make a pr?
I am in LA til Wednesday and will have a look on Wednesday

**Comment by ron-murhammer** [comment]
@gaborbernat @veqryn So it appears #151 now actually fixes the issues? Can this be closed?

**Comment by gaborbernat** [comment]
I think yes.

Bernát GÁBOR

**Comment by veqryn** [comment]
What I ran to create this PR:
```
dos2unix MacOS_users_read_this_first.txt
find ./ -type f -name "*.bat" -exec unix2dos {} \;
find ./ -type f -name "*.txt" -exec unix2dos {} \;
find ./ -type f -name "*.ini" -exec unix2dos {} \;
find ./ -type f -name "*.prop" -exec unix2dos {} \;
find ./ -type f -name "*.properties" -exec unix2dos {} \;
find ./ -type f -name "*.xml" -exec unix2dos {} \;
find ./ -type f -name "*.html" -exec unix2dos {} \;
find ./ -type f -name "*.css" -exec unix2dos {} \;
find ./ -type f -name "*.dtd" -exec unix2dos {} \;
find ./ -type f -name "*.java" -exec dos2unix {} \;
find ./ -type f -name "*.sh" -exec dos2unix {} \;
```

**Pull request closed without merging**
