### PR TITLE
Cleaned Up Libraries

### PR DESCRIPTION
**Pull request by RoiEXLab**
This gets rid of all unused Libraries and commons-io.
Commons-io was used for a total of 2 lines of code.
Both lines were used in methods, which technically did the same...
I removed 1 method ~ the complete class and replaced this one line of code with a standard java solution of 4 lines of code

---
This change is [Reviewable](https://reviewable.io/reviews/triplea-game/triplea/805)

### CODE REVIEW

**Comment by RoiEXLab** [comment]
This PR will cause merge conflicts with my RouteDrawer PR... Please merge this one first

**Comment by RoiEXLab** [comment]
One thing I noticed...
There are no compile-Time checks if `com.github.insubstantial:substance:7.3` and `org.apache.derby:derby:10.12.1.1` is present...

**Comment by DanVanAtta** [comment]
LGTM, but merge conflict ..

**Comment by RoiEXLab** [comment]
@DanVanAtta Ready for merge

**Pull request merged**
