### PR TITLE
Optimize pngs lossily, to keep the installer size small

### PR DESCRIPTION
**Pull request by RoiEXLab**
The installer size grew to 20MB because of the images we use in the new UI.
I applied a lossy compression to the PNGs to keep the installer size under 40MBs in the long run

### CODE REVIEW

**Comment by ron-murhammer** [comment]
@RoiEXLab Yeah, let's obviously do what we can to keep the installer small but given how much better the screens look already I think its definitely worth it.

**Comment by DanVanAtta** [comment]
I see the latest release is at 20MB, when previously it was 10MB. That seems a pretty painful of a jump.

2nd, our repo is 927M, we are 70MB worth of content away from not being to change anything : (

We really need to avoid checking in images.

**Comment by ron-murhammer** [comment]
@DanVanAtta Any idea how much of that is old images? Might be worth doing a permanent delete on any large files that aren't current.

**Comment by ssoloff** [comment]
For images added in the future...  It looks like Git LFS does not yet support filtering files by size (see [here](https://github.com/git-lfs/git-lfs/issues/282)).  It might be painful to LFS-enable _every_ PNG file, which would pick up even those that are less than 1 KiB.

One of the suggested workarounds at the above issue is to have a dedicated folder for files to be stored via LFS.  We could simply create a new resource folder and configure everything in that folder to be LFS-enabled.  Then we store "small" (whatever we define that to be) images under _src/main/resources_ and "large" ones under, for example, _src/main/resources-large_.

**Comment by DanVanAtta** [comment]
@ron-murhammer  I don't recall exact image size, I think around 80MB or so. 
Lions share are older audio files, `wav`, something around 250MB+ there.

@ssoloff A folder to store those resources would make sense. The install4j configuration should not be too difficult to update so it moves that content to the old location.

**Comment by ssoloff** [comment]
@DanVanAtta I don't think install4j would be affected by that change; it should be purely a Gradle concern.  AFAIK, install4j only cares about the following files/folders in the workspace:

* _assets/_
* _build/libs/_
* _build/rootFiles/game_engine.properties_
* _dice_servers/_

The new resource folder will be packaged up in the shadow jar under _build/libs/_ with install4j none the wiser. :smile:

**Comment by RoiEXLab** [comment]
@DanVanAtta According to the [github api we still have about 250MB available](https://api.github.com/repos/triplea-game/triplea) + there doesn't seem to be a strict enforcement of the 1GB rule, we'll just get a friendly reminder to delete some files, or break the repository up into pieces.
So I'm more concerned about the installer size than over the capacity of github. 
I believe up to 50 MB are perfectly fine for a 2D game like TripleA, however as long as the new UI is far from being finished the additional size is not desirable. 
As you already brought up the modularisation issue: Of course those images are not needed for headless bots nor for the lobby, so our goal should really be to exclude resources for headless binaries.

**Comment by DanVanAtta** [comment]
For headless/lobby binaries, splitting project into sub-projects (https://github.com/triplea-game/triplea/issues/2848)  will solve that and then some : )

**Comment by DanVanAtta** [comment]
DL size, generally the smaller the better, my feeling is that under 25MB is a good place to be. Regardless, 10MB for background images is not too outrageous.

Good to know we can go over 1GB. It would still be great if we could prune our repo size as it takes a long time to clone and git operations are not as efficient. It'll be a bit tough as it requires a history re-write.

**Comment by RoiEXLab** [comment]
@DanVanAtta Yup, git takes a really long time for this repo :/

**Pull request merged**
