### PR TITLE
Restore images to Git from LFS

### LINKED ISSUE #2921: Travis broken due to exceeding GitHub LFS quota
I'm not sure how, but we've either exceeded the 1 GiB storage quota or 1 GiB bandwidth quota imposed by GitHub LFS.  Travis builds are failing with this error:

```
Error downloading object: src/main/resources/org/triplea/client/ui/javafx/images/background.png (fc82f76): Smudge error: Error downloading src/main/resources/org/triplea/client/ui/javafx/images/background.png (fc82f760ee88fbd0ee86ebbe58c7bf263601ab882c12d6cc1806d554fafe354d): batch response: This repository is over its data quota. Purchase more data packs to restore access.
```

I'm going to guess we're exceeding the bandwidth quota due to the frequency of our Travis builds.

Relevant link: https://help.github.com/articles/about-storage-and-bandwidth-usage/

### PR DESCRIPTION
**Pull request by ssoloff**
Fixes #2921.

This PR effectively disables LFS in this repo.  We need to better understand the limits LFS imposes on our workflow before re-enabling it.

### CODE REVIEW

**Comment by ssoloff** [comment]
The build appears to fail here and not in my fork because PR builds clone and then checkout the PR branch, whereas the build in my fork clones and checks out the PR branch in one step (so it never hits the LFS pointers on `master`).  I was hoping it would work in this repo so this PR could be merged by anyone, but now it's going to be up to someone with admin rights. 😞 

You can see the build pass in my fork [here](https://travis-ci.org/ssoloff/triplea-game-triplea/builds/334439712).

**Comment by RoiEXLab** [comment]
@ron-murhammer To make this clear: we need you as the only active developer with admin rights to merge this PR.
Alternatively @ssoloff Could just push the changes directly to master I guess.

**Comment by ssoloff** [comment]
@ron-murhammer @veqryn Bumping to see if one of you could please merge this PR.  Travis has been broken for two days, which is effectively stopping any further work in this repo.

@RoiEXLab If none of the admins are available, I'll go ahead and merge into `master` on my fork and push from there.  I'm assuming branch protection won't kick in as long as I create a merge commit?  Although, it looks like this branch can be fast-forwarded, and that shouldn't require a forced push, but I'll just play it safe with a merge commit. :smile:

**Comment by ssoloff** [comment]
Thanks, @ron-murhammer!  Travis is green again, and I confirmed the JFX UI images are present in pre-release 8540.

**Pull request merged**
