### PR TITLE
Use diamond notation everywhere possible

### PR DESCRIPTION
**Pull request by DanVanAtta**
- Done using an IDE 
- Since generic type information is discarded at compile time, we know this will be safe with respect to any possible reflection/serialization.

---
This change is [Reviewable](https://reviewable.io/reviews/triplea-game/triplea/696)

### CODE REVIEW

**Comment by DanVanAtta** [comment]
@gaborbernat  @ron-murhammer -  There are a lot of changes here, it is hard to make much further progress on any part of the project without running into merge conflict. Simply merging the current queue will likely create some conflicts. So there is a pressing need to integrate this change with all forks/branches.

Second, there is nothing to really review. We have made a similar bulk change by hand in large sections of the code before hand, so we are clearly on-board with diamond notation. Second, this was auto-done by an IDE, it compiles well, is 'safe' (since we are dealing with just syntactic sugar) and scanning through the diff locally, it looked fine. The point of a review would be to verify correctness, and second to verify that the change is reasonable and there is some consensus around it. In this case we have both to a reasonable extent.  So moving forward on this now to keep the team unblocked.

**Comment by gaborbernat** [comment]
For me this looks fine, and I could not detect any problems with it. I found it reasonable, so from my side this can be merged.

**Comment by DanVanAtta** [comment]
Thanks for the second set of eyes

**Comment by ron-murhammer** [comment]
@DanVanAtta There appears to be errors in master due to this merge. Can you please take a look.

**Comment by DanVanAtta** [comment]
@ron-murhammer , does the gradle build fail for you? 
I'll have some time tomorrow night to look at in detail. I'm curious what the drift is in our build system as well, it does appear the travis branch build passed.

**Comment by ron-murhammer** [comment]
@DanVanAtta Yeah, the gradle build works and I can start the game with gradlew run. But I have lots of errors in eclipse and can't launch it from there. I opened an issue to track this #741

**Pull request merged**
