### PR TITLE
Test util java

### PR DESCRIPTION
**Pull request by DanVanAtta**
Start a branch for test utilities. Contains so for a method to wait for AWT event queue thread events to complete and a second utility for checking component state.

Branch based on top of  #43 and #103

[Review on Reviewable](https://reviewable.io/reviews/triplea-game/triplea/119)

### CODE REVIEW

**Comment by ron-murhammer** [comment]
Looks good. Anything that makes unit testing easier and cleaner I'm all for.

**Comment by veqryn** [comment]
@DanVanAtta @ron-murhammer: Right now all tests can be run in a headless environment.  By adding swing to the test package, you break the ability for me to run the tests in a pure terminal environment, that does not have swing or a desktop, etc.

**Comment by ron-murhammer** [comment]
@veqryn So that means we essentially have 0 GUI unit tests? Is it worth breaking the ability to run the tests in a pure terminal environment to allow us to have GUI unit tests?

**Comment by veqryn** [comment]
I assume there is a way with gradle or something to `run all tests` and `run all non-gui tests`.
If so, then I am fine with adding gui tests, but anything using swing/gui should probably be segregated so that we can still run non-gui tests separately if/when we want to.
So in other words, this new utility probably needs to be in a new class (like GuiTestUtils).

**Comment by DanVanAtta** [comment]
The Travis build fails when Swing components are instantiated (AWT headless exception). So it will ensure that we do not add swing component dependencies into the normal unit test work flow.

`gradlew assemble` is what Travis runs, compiles and runs tests. It then runs packaging commands we define if there is a tag present (and any other conditions specified in .travis.yml, branch conditions can apply, and many others)

No fundamental disagreement with splitting Utility code like that. The wait for swing threads method IIRC can be needed in headless instances.

I don't think it is quite worth going back for that now, but as a general future direction, next time this code is touched, (like closeFrame I think needs an instance with UI), I'll look to move the utility functions over.

**Pull request merged**
