### PR TITLE
Added Lord of the Rings - War of the Ring

### PR DESCRIPTION
**Pull request by RogerCooper**

### CODE REVIEW

**Comment by RogerCooper** [comment]
I don't see the problem here.

**Comment by beelee1** [comment]
I don't see anything wrong either. Says it's the formatting in the yaml but that all looks good to me

**Comment by TheDog-GH** [comment]
There is a mod with a very similar name/same name here.
https://forums.triplea-game.org/topic/2919/lord-of-the-rings-war-of-the-ring-official-thread/47

The above points here
https://github.com/triplea-game/triplea/pull/10193

https://github.com/triplea-maps/middle_earth/pull/5

Could this the problem?

**Comment by beelee1** [comment]
@TheDog-GH so you're saying the repos are named different but the map name inside them are the same ?

**Comment by TheDog-GH** [comment]
Yes, the xml and map name are the same, so this might be the problem?

**Comment by beelee1** [comment]
Right on. Thanks Dog. @RogerCooper you wanna try and just add a "2' to the name and see if it works ?

**Comment by RogerCooper** [comment]
I will try changing the XML file name.

**Comment by DanVanAtta** [comment]
@RogerCooper there is a formatting/checkstyle error that is killing the build here:

> > The following files had format violations:
      triplea_maps.yaml
          @@ -2792,4 +2792,4 @@
           ··version:·1
           ··img:·https://raw.githubusercontent.com/triplea-maps/lord_of_the_rings_war_of_the_ring/master/preview.png
           ··description:·|
          -···<br>The·War·of·the·Ring·from·Tolkien's·Lord·of·the·Rings·Trilogy···
          +···<br>The·War·of·the·Ring·from·Tolkien's·Lord·of·the·Rings·Trilogy

(check the details button next to the failing build check)

The above is indicating there are trailing spaces that need to be removed.

**Comment by DanVanAtta** [comment]
@RogerCooper  is this patch still valid? Looks like it is just now some updates to copy - are they good to go?

**Comment by RogerCooper** [comment]
I was just cleaning up the names. They should be good.

**Pull request merged**
