### PR TITLE
Another try: Rework of mapXmlCreator package

### PR DESCRIPTION
**Pull request by frigoref**
This change is [Reviewable](https://reviewable.io/reviews/triplea-game/triplea/575)

### CODE REVIEW

**Comment by DanVanAtta** [comment]
@frigoref  - same error, import statements need to be updated:
`import games.strategy.triplea.attatchments.UnitAttachment;`

Note, this is not a rebase issue, you did that well. You need to hand correct those errors, convert:
`import games.strategy.triplea.attatchments.UnitAttachment;`
to:
`import games.strategy.triplea.attachments.UnitAttachment;` (note the attachments spelling)

**Comment by frigoref** [comment]
Sorry, but I do need further help here. I have deleted my fork on github, then took a new one and rebased my local copy on the fork master branch and pushed my local branch to the fork master.
To me it does not make sense that there are 6 commits and pushing my local branch to the fork master has worked, but the pull request (from my fork to the main project, with the only difference being my last push of the local branch) is failing on the last commit (Rework).

**Comment by frigoref** [comment]
What happened to the jar-files in the lib folder? I am getting errors
all over the place

Am 05.04.2016 um 19:11 schrieb Dan Van Atta:

**Comment by DanVanAtta** [comment]
Simply put, hand correct the import statements and you should be good to go.

To explain, let's say each commit is represented by a letter. Let's consider only two branches as well, the upstream master (the thing you are merging into), and the 'master' branch of your fork (which could be called anything really).

Let's also say that the upstream master has three commits; A, B, C

Then let's say you build a branch and add commits, D, E, F. This branch for the moment is local to your machine. You then push the branch to your fork, we now have three branches - upstream master, your fork's master, and the copy of your forks' master that is on your local machine. These are three *different* branches, but they all 'track' each other.

So, to recap, we have an upstream master with: A, B, C
We have a fork master with: A, B, C, D, E, F
And we have the local copy of master from your fork on your machine that has: A, B, C, D, E, F

Now let's say you add two new commits locally, now your local branch will look like this:
A, B, C, D, E, F, G, H

Now, let's say your forks' master is merged into upstream. At that point upstream master will look like:
A, B, C, D, E, F

Your forks master will match master, and it will be the same: A, B, C, D, E, F

Your local copy will also be the same too:
A, B, C, D, E, F


But, when you rebase your local fork on to master, then Git will see these two branches side by side:
```
A, B, C, D, E, F
A, B, C, D, E, F, G, H
```
Git will then see that A-F are the same, and it'll consolidate them. Your local fork master branch will then only contain two commits after the rebase: G, H.

So, in this situation your branch had a lot of commits, let's say it had 20. Then locally you added 6 more for a total of 26 commits in your local branch. But note, your forks branch which was merged, only had 20, was never updated with those last 6. Then after you rebase, Git subtracts those 20 commits that were merged from your branch, leaving you with just 6. I hope that helps.

**Comment by DanVanAtta** [comment]
Jar files were removed, see the project README, you need to do a gradle import of the libs.

**Comment by DanVanAtta** [comment]
eclipse gradle plugin is key for that, the import can be done from eclipse, you will likely need to re-import the project as a gradle project.

**Comment by frigoref** [comment]
Any more surprises I should be informed about? It is really annoying
that this is happening while we are trying to merge my last changes. WTF?

Am 05.04.2016 um 19:21 schrieb Dan Van Atta:
> an be done from eclipse,

**Comment by DanVanAtta** [comment]
It seems you have not updated to the latest master for some time. It being painful to integrate is somewhat expected. As far as major dev environment changes, the removal of libs in favor of gradle imported libs is probably the biggest/last thing.

Rules of thumb:
- branches should not live long. Ideally they are created and submitted for PR hours later.
- branches and changes are kept small, isolated, and independent. The 100s of changes in one PR is not desired. The last giant PRs I had submitted took Ron and Veqryn a couple of months to review. To some extent you are lucking out there was as much review capacity as there was. In the meantime when a branch is hanging out, more changes happen to master, which is more work for you to integrate those changes.. Thus, keeping branches short lived is very good.

**Comment by frigoref** [comment]
I have done so and I still get a lot of errors due to some missing jars
- even in files I did not touch like
triplea <https://github.com/triplea-game/triplea>/src
<https://github.com/triplea-game/triplea/tree/master/src>/games
<https://github.com/triplea-game/triplea/tree/master/src/games>/strategy
<https://github.com/triplea-game/triplea/tree/master/src/games/strategy>/engine
<https://github.com/triplea-game/triplea/tree/master/src/games/strategy/engine>/framework
<https://github.com/triplea-game/triplea/tree/master/src/games/strategy/engine/framework>/map
<https://github.com/triplea-game/triplea/tree/master/src/games/strategy/engine/framework/map>/download
<https://github.com/triplea-game/triplea/tree/master/src/games/strategy/engine/framework/map/download>/*DownloadRunnable.java
*for importcom.google.common.collect.Maps;

Any suggestions?

Am 05.04.2016 um 19:21 schrieb Dan Van Atta:

**Comment by frigoref** [comment]
@DanVanAtta:
Any suggestions?
Do I have to run specific Gradle tasks?

**Comment by DanVanAtta** [comment]
- make sure you have an eclipse gradle plugin installed, I think there are two different ones out there.
- delete the project, but do not delete contents from disk
- import a project from source, as a gradle project (plugin should add this option)
- once all is done, there should be a right click menu available from the project to import gradle dependencies. In the import project screen, look for options to import dependencies.

When all else fails, google: "gradle eclipse project setup", "gradle eclipse import dependencies"

**Pull request closed without merging**
