### PR TITLE
Build fix - Backwards compatible fix and update of how test map game data is found.

### PR DESCRIPTION
**Pull request by DanVanAtta**
Secondly, make a copy paste of the big world map data in "maps" and move it to "test_data", then update the two tests that used the "maps" version rather than a test version.

The code for finding maps can take a lot of branches, depends on if you run from IDE, ant, gradle, or which packaged version of the game. In addition the test and prod search paths for map data are mixed together. In the test case we find we are running from a class file and assume we are running from ant. In that case all we need to do is ascend up enough directories to get out of the packages and then plus a fixed amount. For gradle this is not enough, the compiled classes are nested a bit deeper.

To fix this, instead of having GameRunner2 tell us what the root folder is, and then from there try to find parent folders with a map file in it, we instead ask GameRunner2 to find us a file and give it a list of potential parent folders. The method that looks at both test and prod paths has been deprecated so we can migrate away from it (so eventually the list woudl perhaps become a scalar). Secondly, GameRunner2 now has different behavior in the finding files in the case of finding relative to a class file (as opposed to relative to a jar). Instead of going up enough directories to match the packages plus one, instead we are given a folder and file, and we keep ascending directories until we find that folder containing the file. This works in both the ant and gradle cases.

Lastly:
-  some extract method was done on GameRunner2, so there is some additional refactoring that was done to clean up the methods so that this change would be clear and make sense. So one can expect some extracted methods in the diff.
- Remove test restriction that chooser model needs to find at least one file. In unit test case maps from a users home folder will get picked up, for travis this is not the case.

[Review on Reviewable](https://reviewable.io/reviews/triplea-game/triplea/103)

### CODE REVIEW

**Comment by veqryn** [comment]
We can look into this after we finish the current release.
Also, why are you changing so many files besides just the getRootFolder method?

**Comment by DanVanAtta** [comment]
1 new file for test data, 2 tests updated to use that. Main fix in 2 other classes plus 3rd for supporting utility method. Already 6 classes, then a final 7th fix for Travis due to travis env not having maps in home folder that otherwise get picked up during test.

**Comment by gaborbernat** [comment]
Can confirm, when I made the initial changes, me too had to change in
multiple classes; this part could use some refactoring on long term to have
a better separation of responsibilities.

Bernát GÁBOR

**Comment by DanVanAtta** [comment]
@ron-murhammer , @veqryn  please merge this next, since it fixes the build, everything is built on top of it.

**Comment by veqryn** [comment]
Things like adding the libraries do not need to be built on top of this.
This PR will need to undergo a lot more QA than simple patches that do not strictly need this PR.
So why make them require it?

**Comment by DanVanAtta** [comment]
This fixes the build. I generally do not submit or maintain pull requests on top of broken builds. Fixing the build is for all intensive purposes number one, everything requires a working build.

**Comment by DanVanAtta** [comment]
I've submitted other PR's that have put this through more QA, namely building artifacts on top of this and then deploying them (all the artifacts except mac DMG). Breaking the build is a critical event, once that happenened, all outstanding work was retro-fitted with the build fix to ensure that they did not break the build. Without that working base, no work could be considered tested.

Given this is also backwards compatible, and the artifacts testing that has happened since, I think that is sufficient testing for the moment until we can work more on the release pipeline.

**Comment by DanVanAtta** [comment]
So to be clear, I'm waiting. Testing has been done on this one, so QA bar has been met. If not, please elaborate. Also, why does it that this change seems to have extra QA requirements while others not? If it is because the changes are in GameRunner, if we then copy/paste other code into GameRunner that GameRunner, calls, does that elevate the testing requirement of those changes? Namely, I think we are being overly sensitive, particularly at the risk of making things move too slowly.

**Comment by ron-murhammer** [comment]
@DanVanAtta I think the reason for extra QA is because its touching things such as file system references which are difficult to test especially related to all the various releases (window, linux, mac) not that its specifically GameRunner or a related class though these are where lots of this is done. 

We got burned on the previous release that we just did on pretty much exactly this as everything appeared work locally running the code and the windows release but there were issues with the Mac release. We don't currently have a good way of testing Mac releases and therefore file system changes.

**Comment by DanVanAtta** [comment]
- extra QA has been done on this, more so than normal considering this was used for testing artifact building. 
- it is backwards compatible, whatever the DMG used to do it will continue to do. That functionality has been no more modified in this PR than in others (other than we are modify surrounding code that is in closer proximity, but we don't change any of the release artifact search paths for releases). Recall the change that where we were burned was completely removed, this is no attempt to restore that but only to fix the tests in a backwards compatible manner.
- the core of this change is that we add a new special search path when we are in a gradle context and not just when we are in an ant or release context. The current search path that is modified is only triggered during ant builds. Only during an ant build will we see a .class file, in which case we assume a certain directly location that is incorrect. This change updates how we search for paths in a way that works for both ant and gradle. I can test the ant build so I know the ant build still works. Please see the details of the PR for how exactly it was updated.

**Comment by ron-murhammer** [comment]
So I reviewed the PR.

Comments:
- Really think the test changes should have been separated from the GameRunner2 changes
- It would be preferable to have functional changes separate from refactoring in commits (GameRunner2 is difficult to review since both happen in the same commit)
- Anyways, tested the changes locally with IDE, triple.jar, generating releases, testing all platforms release, and testing windows release. All those seem to work.

Things I didn't test:
- Mac release
- Running all platforms release on Linux distro

@veqryn please review this as this seems to be the PR blocking lots of other PR's. I'm alright with merging the changes though have the comments above. It would be preferable to see releases tested on mac and linux but not sure that's easily doable at this point so might have to live with that risk.

**Comment by DanVanAtta** [comment]
The refactoring and functional changes are a bit coupled in this PR. To some extent I do not disagree, to another, until the code was re-worked ab it, the needed change was not obvious, and also I don't think the correctness of the change would be nearly as obvious. Since another PR may or may not be accepted, and would have to deal with merge conflicts, it was not worth a second PR, particularly when the light refactor made this change clean.

FYI I use linux primarily and can also test windows. Occasionally depending on the day of the week I can test on a mac as well.

**Comment by ron-murhammer** [comment]
@DanVanAtta I think a single having the functional and refactoring changes in the same PR is fine here. My point was it would have been nice if it was in separate commits. So refactoring methods to clean it up in 1 commit then making functional changes in a separate commit (or vice versa). That makes it so the refactoring changes can just be glanced over while we can inspect the functional changes in a diff easier.

**Comment by DanVanAtta** [comment]
Understood now you guys were not asking for 2 PR. 2 commits, okay - but even with what the changes were, many tiny commits would have driven me insane to do, and part of the fix was refactoring the logic into something that was more generic and still correct. So yeah, you guys are not wrong, but also at the same time, code is not always going to be perfect, and taking the time to really get things to be 100% clean and always fully polished is not always going to happen. Regardless, the loving crap has been tested out of this at this point though. Please let me know next steps to merge it..

**Comment by veqryn** [comment]
So, how can I tell if this PR is based on any other PR's?

**Comment by DanVanAtta** [comment]
Look at the branching history or the number of commits.

**Comment by veqryn** [comment]
Where do I see the branch history?
This one only has 1 commit, so does that mean it is not based on other PR's?
Also, is this the PR to fix the getRootFolder, or is that a different PR?

**Comment by DanVanAtta** [comment]
The getRootFolder bogus error message has no fix yet to the best of my knowledge. There are various tools for viewing git history. Generally any one that shows you branches, like the github network graph will show it to you sometimes. Generally though various git log incantations, here is one example:
`git log --graph --all --decorate`

The 1 commit is pretty much a dead give-away it is not based on other branches.

**Comment by veqryn** [comment]
@DanVanAtta:
Not sure what you mean by bogus error message.
This looks like the PR to fix the Gradle/Travis builds, right?
Can you explain what it is that Gradle needs done to the getRootFolder method?
Why are we changing this method, which appears to work perfectly fine.  What it is that gradle needs done?

**Comment by DanVanAtta** [comment]
The bogus error message is a more recent issue seen during testing of the Mac DMG installer file and new unix installer based on the 1809 code base. I wasn't sure if you were referencing that problem.

So this is the fix for Gradle/Travis.

The current method, getRootFolder guesses the root folder based upon the location and type of GameRunner2. Are we a class file, or a jar file? In the case it is a class file, then the prior code assumed Ant was building the project. In that case all files are in a "build" folder, and so we go one folder up to get to the root. In all other cases, namely releases, we'll see a JAR file and previous logic will be maintained.

The problem is that in the gralde context, the compiles GameRunner2 file is actually 2 or 3 folders below the root, so the logic to go one up does not go far enough. Thus the root folder is incorrect and so we of course don't find artifacts.

So, the method did *not* work perfectly fine, it has incorrect assumptions. The change is to make the search of the root folder a bit more robust. In general we search for root folder so we can then find another folder and then files in that folder. So the algorithm was switched to instead of getting root folder and then descending to an expected location, we instead ascend directories looking for a specific folder that we expect to be at the root. This is more robust since it works for both Ant and Gradle cases with the same code path.

**Comment by gaborbernat** [comment]
@ron-murhammer @veqryn I support this, it's must for the Gradle system, please accept it. (see #128  for details)

**Comment by veqryn** [comment]
@gaborbernat: Yes, I know it needs to be done, I just need some background on why we are doing this and what we hope to accomplish (in more specific terms than just 'getting gradle to work').

@DanVanAtta: Ok, that all makes sense.  What is gradle doing that makes it put the jar or class file too many directories up/nested?

**Comment by gaborbernat** [comment]
Gradle tries to avoid root folder clutter. So instead creating in the root a release, a bin, etcetera folders it creates a build folder and put everything inside folders in that (at some arbitrary depth required - usually just 1 nested folder).

**Comment by DanVanAtta** [comment]
Gradle is in a sense a wrapper to maven. Maven produces a very standard folder output. The ant one was ad-hoc, the code to rely on that behavior was very specific.

**Comment by veqryn** [comment]
Ok, so this looks fine and I will merge it, but there is one outstanding issue: It doesn't really solve the root of the problem (no pun intended).
For example, if you run `gradlew run`, you will find your choose games list to be completely empty, and no assets or otherwise are loaded.  If you have a map in your user directory, you will have them in the choose games list, but not the default ones.  If you try to play one that requires any resources (assets) that come with triplea, it will not work properly.

So, it might be best to actually remove the new `getFile` method and instead have getRootFolder try to figure out where the real root is.

**Comment by DanVanAtta** [comment]
Thanks.  I'll  rebase the in-flight PRs now on to current master, should simplify the diffs that were built on this.

I didn't realize `./gradlew run` had issues. (I gameplay test using eclipse plus extra path elements, or using Jar after ant building). So gradle and ant run and test executes a path of code logic users should never execute. Users will always run using a Jar file, not class file. The two code paths are different depending on that variable.    The true fix I think is unifying the behavior, so we don't have development only code paths. To do that would require quite a few changes, not sure how to do that in the best manner. TBH my immediate goal was to fix the build.

**Comment by gaborbernat** [comment]
I already done this change on my reverted commit :-? and tested it to
work with both ant and gradle. The only break was the Mac icon. I'll
try to use that commit, now that we no longer use that script anyways,
or amend that to work with the Mac icon.

On 8/31/15, Dan Van Atta <notifications@github.com> wrote:
> Thanks.  I'll  rebase the in-flight PRs now on to current master, should
> simplify the diffs that were built on this.
>
> I didn't realize `./gradlew run` had issues. (I gameplay test using eclipse
> plus extra path elements, or using Jar after ant building). So gradle and
> ant run and test executes a path of code logic users should never execute.
> Users will always run using a Jar file, not class file. The two code paths
> are different depending on that variable.    The true fix I think is
> unifying the behavior, so we don't have development only code paths. To do
> that would require quite a few changes, not sure how to do that in the best
> manner. TBH my immediate goal was to fix the build.
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/triplea-game/triplea/pull/103#issuecomment-136281674


-- 
 Bernát Gábor
Student -  Budapest University of Technology and Economics - Computer
Engineering, M.Sc. - Budapest, Hungary
System Integrator - Gravity R&D | Rock Solid Recommendations - Budapest
office | 5-7 Expo ter | H-1101 | Budapest | Hungary

**Comment by DanVanAtta** [comment]
@gaborbernat , IMO getting the install4j stuff out first would be sweet. It's no secret CI is high on my wish list. If you can find the energy, resurrecting the code to unify that logic would be really nice. Plus you have a working build to work off of now too ;)

**Comment by veqryn** [comment]
@gaborbernat: It was not only the 'mac icon' but also the fact that on the mac, the user could not find the assets and games that came with triplea.

**Comment by gaborbernat** [comment]
either way will look into this, this week :)

On 8/31/15, Chris Duncan <notifications@github.com> wrote:
> @gaborbernat: It was not only the 'mac icon' but also the fact that on the
> mac, the user could not find the assets and games that came with triplea.
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/triplea-game/triplea/pull/103#issuecomment-136305021


-- 
 Bernát Gábor
Student -  Budapest University of Technology and Economics - Computer
Engineering, M.Sc. - Budapest, Hungary
System Integrator - Gravity R&D | Rock Solid Recommendations - Budapest
office | 5-7 Expo ter | H-1101 | Budapest | Hungary

**Pull request merged**
