### PR TITLE
Separate out non retreatable units in the casualty selector

### PR DESCRIPTION
**Pull request by trevan**
The UI needs to be worked on but this will separate out units that can retreat from units that can't retreat.

### CODE REVIEW

**Comment by trevan** [comment]
The UnitChooser is the code that builds the UI.  It is used in several places, not just the casualty selection.  It already handles separating out units by their dependents (such as transports), by their transport cost, and by their left over movement.  I added a new case to handle the non-retreat state but it shows the image.

**Comment by Cernelius** [comment]
Is this more likely to be a long term project or more likely to be featured in TripleA 2.6 (asking because it is relevant to a map of mine which I'm going to update soon)?

**Comment by Cernelius** [comment]
So, is it safe to say that TripleA 2.6 will not allow picking between retreatable and non?

**Comment by RaiNova** [comment]
@trevan my pull request #9509 depends on this one. Do you already have a plan when to finalize your pull request?

**Comment by trevan** [comment]
@RaiNova , this was a draft PR because there was still discussion about the UI and I don't have much Java UI experience.  So I committed the logic part and then expected someone else to try and work on the UI.  You can see the discussion in the forum at https://forums.triplea-game.org/topic/2677/allow-user-to-specifically-choose-amphibious-offloaded-units-in-battle-chooser/29?_=1631472565173&lang=en-US.

**Comment by RaiNova** [comment]
> @RaiNova , this was a draft PR because there was still discussion about the UI and I don't have much Java UI experience. So I committed the logic part and then expected someone else to try and work on the UI. You can see the discussion in the forum at https://forums.triplea-game.org/topic/2677/allow-user-to-specifically-choose-amphibious-offloaded-units-in-battle-chooser/29?_=1631472565173&lang=en-US.

@trevan As you mentioned in the forum, I should now build on your pull request. What is the easiest way? Lacking much experience with github, it looks to me the easiest way would be you finalize your pull request, I reveive it by an update of the head and the integrate the UI. The code I am working on includes my pull reuqest #9509. I‘d like to keep me work consolidate in that pull request.

Would that work?

**Comment by trevan** [comment]
@RaiNova , I don't think we want to merge this until the UI is done because this will change the behavior of the game.  I'd recommend you cherry-pick the commit into your branch and then we close this PR.

**Comment by DanVanAtta** [comment]
@RaiNova this was waiting for me to finish the UI components. I haven't been able to manage the time/effort despite my better wishes. If you're willing to, would you want to finish this PR? Judging by the screenshots in the forums, it looks like you are far along the way.

Cherry-picking commits into a new branch could be a good way to go.

@trevan , which changes to behavior are you referring to (more specifically)? Is that referring to how the non-retreat units will be split out in UI, or are there further changes you were thinking of?

**Comment by trevan** [comment]
@DanVanAtta , the changes I'm referring to is how the non-retreat units will be split out in the UI.  But there won't be any indication on why they are split.  So users wouldn't be able to know which of the rows is the non-retreat units and which are the retreat units.  Nor would they be able to tell why there are two rows of the same unit.

**Comment by DanVanAtta** [comment]
@RaiNova could you confirm if you are taking over this effort / PR? If so, do you have a plan or expectation for which changes would land when?

**Comment by RaiNova** [comment]
> @RaiNova could you confirm if you are taking over this effort / PR? If so, do you have a plan or expectation for which changes would land when?

Confirmed. I'll try to complete this by the end of November. It's functionally complete already, but I need to do more testing

**Comment by RaiNova** [comment]
This PR is now included in #9509 and can be closed. But I can't close it - the close button doesn't show left to the comment button.

**Comment by DanVanAtta** [comment]
Closing in favor #9509

**Pull request closed without merging**
