### PR TITLE
Rename user maps folder from "maps" to "downloadedMaps" so new maps

### PR DESCRIPTION
**Pull request by ron-murhammer**
downloaded from git don't conflict with old maps.

---
This change is [Reviewable](https://reviewable.io/reviews/triplea-game/triplea/566)

### CODE REVIEW

**Comment by ron-murhammer** [comment]
@DanVanAtta Need to pretty much do this ASAP now that the 'attatch' fix was merged. I'm open to other names for the 'new' maps folder.

**Comment by DanVanAtta** [comment]
Underscores and lowercase for file names? ie: 'downloaded_maps'
Looks good otherwise, good to merge.

**Comment by ron-murhammer** [comment]
@DanVanAtta I prefer underscores and lowercase but seems like the existing standard is camelcase as the other folders in user folder are 'optionCache' and 'savedGames'. Prefer consistency or want to move towards a new standard?

**Comment by DanVanAtta** [comment]
I do think we should set that as a new standard for file system entities. Would help with the image casing problem. Whether we do the conversion from camel case to lower case plus underscores all at once, or if we do it piecemeal and anything new is updated, does not matter too much to me.

**Pull request merged**
