### PR TITLE
Rollback junitPlatformLauncherVersion

### PR DESCRIPTION
**Pull request by DanVanAtta**
With latest version unable to run tests from within IDEA:

> org.junit.platform.commons.JUnitException: TestEngine with ID 'junit-vintage' failed to discover tests
	at org.junit.platform.launcher.core.DefaultLauncher.discoverEngineRoot(DefaultLauncher.java:189)
	at org.junit.platform.launcher.core.DefaultLauncher.discoverRoot(DefaultLauncher.java:168)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:132)
	at com.intellij.junit5.JUnit5IdeaTestRunner.startRunnerWithArgs(JUnit5IdeaTestRunner.java:69)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:230)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:58)
Caused by: org.junit.platform.commons.JUnitException: Failed to parse version of junit:junit: 3.8.2

 

## Functional Changes

[] New map or map update
[] New Feature
[] Feature update or enhancement
[] Feature Removal
[] Code Cleanup or refactor
[] Configuration Change
[x] Problem fix:  
[] Other:   

## Testing

[] Manual testing done

## Additional Review Notes

Version was recently updated, problem was introduced fairly recently.

### CODE REVIEW

**Comment by RoiEXLab** [comment]
I'm slightly confused:
Why are there any tests that are still running junit 3?

**Comment by DanVanAtta** [comment]
@RoiEXLab not sure if it's the case that there are tests trying to run juni3, perhaps that would have been the same independent of this version change. Considering the error is hit when trying to run any unit test, it's not for sure that is the issue.

All I know is that I can't run *any* unit tests from IntelliJ with the latest version junitPlatformLauncherVersion without seeing the error in the OP.

**Comment by RoiEXLab** [comment]
I don't think we have some junit 3 tests either, but the error message mentiones it.
That's why I'm concerned that we have some sort of configuration issue where IntelliJ tries to run some tests from an outdated dependency or something

**Comment by DanVanAtta** [comment]
It's more likely the latest version of junit launcher is the thing that is trying to run tests as Junit3. Any problems we would have had there, with our configuraton and junit3, we likely should have seen already.

**Pull request merged**
