### PR TITLE
Fix resource not found errors in release build (#1547)

### PR DESCRIPTION
**Pull request by ssoloff**
This PR addresses one type of error reported in issue #1547.  Namely, a class of "resource not found" errors, an example of which was reported in that issue:

```
ta_icon.png not loaded
java.lang.NullPointerException
	at sun.awt.SunToolkit.getImageFromHash(Unknown Source)
	at sun.awt.SunToolkit.getImage(Unknown Source)
	at games.strategy.engine.framework.GameRunner.getGameIcon(GameRunner.java:521)
	at games.strategy.engine.framework.startup.ui.MainFrame.<init>(MainFrame.java:55)
	at games.strategy.engine.framework.GameRunner.lambda$showMainFrame$79(GameRunner.java:185)
	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at games.strategy.engine.framework.GameRunner$1.dispatchEvent(GameRunner.java:349)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)
```

(This PR does **not** address the DTD validation issue reported in the same issue and triaged [here](https://github.com/triplea-game/triplea/issues/1547#issuecomment-281606608).)

The resource not found errors only occur in a release build; they do not occur when running TripleA from Eclipse.  The root cause of the problem is due to the resources being located in the `src/main/resources/data` folder instead of the `src/main/resources` folder.  This causes the resources to be located in a different package on the classpath from where they are expected to be present.

The errors do not occur when running TripleA from Eclipse because the various Eclipse launch configurations explicitly include the `src/main/resources/data` folder at the root of the classpath.

#### Functional changes
None.

#### Refactoring changes
* Moved the contents of the `src/main/resources/data` folder to `src/main/resources`.
* Updated all Eclipse launch configurations to no longer include `src/main/resources/data` on the classpath.  All launch configurations now simply use the default classpath defined by Gradle.

#### Refactoring issues for review
* ⚠️  [This comment](https://github.com/triplea-game/triplea/pull/1492#issuecomment-279278087) in PR #1492 scares me because I have no clue to what it's referring.  Could someone please explain how installer updates are affected by the existence or nonexistence of the `data` folder?  I tried searching the repo for any clue but came up empty.

#### Testing
(**NB:** Because of the DTD validation issue, in order to perform the tests below, I had to locally modify `GameParser#getDocument()` to call `DocumentBuilderFactory#setValidating(false)`.)

I manually verified that the various resource not found errors no longer occur when running TripleA from a locally-built `triplea-all_platforms.zip`.  I verified that at least one resource in each of the following packages was loaded successfully using various aspects of the UI:

* `g.s.engine.chat`
* `g.s.engine.framework`
* `g.s.triplea.help`
* `g.s.ui.images`

In addition, I ran `tools.image.XmlUpdater` from the same release archive to ensure the resources in the `tools.image` package were loaded successfully.

Finally, I verified that I can run TripleA as I've come to expect using `GameRunner_run_game.launch`, and that resource not found errors do not occur.  I also did a basic smoke test of the other three launch configurations, simply to ensure the application started.

### CODE REVIEW

**Comment by ron-murhammer** [comment]
@ssoloff Yeah this is where I wanted to move resources originally and I'm not aware of any issue this would cause.

@DanVanAtta Can you take a look at this in regards to https://github.com/triplea-game/triplea/pull/1492#issuecomment-279278087

**Comment by DanVanAtta** [comment]
@ssoloff  would you mind cutting a PR for `DocumentBuilderFactory#setValidating(false)`
I believe that was the setting I was looking for to fix the DTD validation issue.

Re: comment, the data folder is potentially used in the install4j build process: https://github.com/triplea-game/triplea/blob/master/build.install4j. I don't see that I updated it in that PR: https://github.com/triplea-game/triplea/pull/1492/files#diff-dbb5c25d5c0c7a1b56707fcf8f00b85bL1, either I missed the update or the 'data' folder is not packaged with the installer (implying it is only for testing, in which case we should probably try to get rid of it).

**Comment by ssoloff** [comment]
@DanVanAtta

> would you mind cutting a PR for `DocumentBuilderFactory#setValidating(false)`

Will do.

> either I missed the update or the 'data' folder is not packaged with the installer

Yeah, I don't see any references to "data"-anything in that file.  That's the first install4j build script I've ever looked at, so if there's any other files involved in the installer creation process, I may be missing an actual reference.

> (implying it is only for testing, in which case we should probably try to get rid of it)

Sorry, I should have typed out the full path in my previous comment...  Just to be clear, when I referred to "the `data` folder", I meant `/src/main/resources/data`, which was `/data` prior to #1492.  The content of today's `/src/main/resources/data` is most definitely used in production, so I don't think there's any additional folders to get rid of.

**Comment by ron-murhammer** [comment]
Merging this now.

**Comment by ssoloff** [comment]
@DanVanAtta

> would you mind cutting a PR for `DocumentBuilderFactory#setValidating(false)`

FYI...  I derped this.  `setValidating(false)` is not sufficient to stop the XML parser from actually _loading_ the DTD.  I originally was testing TripleA from the release zip by running it from the folder to which I unzipped the archive (i.e. `cd build/distributions/<something-something>; java -jar bin/triplea.jar`).  Then, for some reason, I switched to running it from the root of the TripleA repo (i.e. `java -jar build/distributions/<something-something>/bin/triplea.jar`).  The fact that _game.dtd_ exists in the CWD allowed the parser to locate it and load it, which gave me the false sense that I had successfully bypassed the `FileNotFoundException` for _game.dtd_.

There appear to be several ways to bypass DTD loading.  I'll pick one that works, and we can discuss the alternatives in the PR.

**Pull request merged**
