### PR TITLE
Fix reflective access in test classes

### PR DESCRIPTION
**Pull request by RoiEXLab**
This seems to fix the remaining reflective access issues (that are our fault) as reported in #2796

### CODE REVIEW

**Comment by ssoloff** [comment]
> that are our fault

@RoiEXLab Did you happen to find a reference that suggests Mockito no longer supports spying on JDK types (or simply types in a different module) in Java 9?  [This issue](https://github.com/mockito/mockito/issues/1325) seems related, and it's been marked as a bug.  I added an MCVE to see if the Mockito maintainers acknowledge whether what we're doing is supported or not.

**Comment by RoiEXLab** [comment]
@ssoloff I found this issue as well, but it has a slightly different error message.
If you look at [The AccessibilityChanger class](https://github.com/mockito/mockito/blob/e51a0515ac8440572cf1af80f7aa620d51e8075e/src/main/java/org/mockito/internal/util/reflection/AccessibilityChanger.java#L25-L31) you will notice, that it's just a helper class that will make all available fields of an object public (or at least that's my theory).
In any case in order to spy on an object mockito needs to be able to access its fields and therefore it would make sense mockito iterates over all fields making them accessible, resulting in the warning for specific fields that have gotten a more restricted access in Java 9.
The issue got labeled as a bug, but I suppose this is just because nobody bothered to dig deeper into this there. _Maybe_ they will check if spied objects have restricted reflective access in the future when Java 11 is released (the next LTS release), but I don't think this will be a priority, and my "workaround" worksfor now 🤷‍♂️

**Comment by ssoloff** [comment]
> I found this issue as well, but it has a slightly different error message.

@RoiEXLab Are you talking about the field it refers to at the end of the message?  That is,

```
to field java.util.logging.LogManager.props
```

vs.

```
 to field java.util.Properties.defaults
```

I believe that difference is simply because two different types are being spied upon, and thus Mockito encounters a different field on which it attempts to reflectively access.

> The issue got labeled as a bug, but I suppose this is just because nobody bothered to dig deeper into this there.

I suspect this issue will affect any attempt to spy on a type in a different module, which means, when TripleA is modularized, you may run into the same issue again (there are currently 17 spies of TripleA types).

Regardless, two of the five changes from spies to mocks in this PR are perfectly fine and a good clean up because those instances (currently) do not rely on any behavior of the concrete implementation.

**Comment by RoiEXLab** [comment]
> I believe that difference is simply because two different types are being spied upon, and thus Mockito encounters a different field on which it attempts to reflectively access.

Yes, that's what I'm thinking as well.

> I suspect this issue will affect any attempt to spy on a type in a different module, which means, when TripleA is modularized, you may run into the same issue again (there are currently 17 spies of TripleA types).

Possible, but if we actually do this would indicate a serious design issue. Tests are technically in the same package (the same module as well if we'd introduce them) as their test subjects.
So we'll be probably fine.

**Pull request merged**
