### PR TITLE
removing author, version, empty return, param tags, anything before package

### PR DESCRIPTION
**Pull request by veqryn**
[Review on Reviewable](https://reviewable.io/reviews/triplea-game/triplea/57)

### CODE REVIEW

**Comment by veqryn** [comment]
please do not merge this yet, i need to manually review the diff

**Comment by DanVanAtta** [comment]
I looked at the changes, via the bash-fu it does look like only comment lines were changed.

The changes to PolygonTerritory.java will create a relatively easy to resolve conflict with: #47.  I recommend deleting PolygonTerritory.java as part of this PR and we close 47.

**Comment by veqryn** [comment]
Reviewed 815 of 815 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/triplea-game/triplea/57)

**Comment by veqryn** [comment]
Reviewed 815 of 815 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/triplea-game/triplea/57)

**Pull request merged**
