### PR TITLE
Make the gameChooser use DefaultGameChooserEntry instead of String

### LINKED ISSUE #8076: 2.5.22294: GameParser#parseResults:642 - games.strategy.engine.data.gameparser.GameParseException
## User Description
Battle for Arda map not working since update to Engine Version 2.5.22294.  It appears twice in the Select Map list and an error message arises when trying to open either.

## Log Message
Could not parse:jar:file:/C:/Users/mattb/triplea/downloadedMaps/battle_for_arda-master.zip!/battle_for_arda-master/TAGX.xml, Could not find resource or unitdunlending_wildman

## TripleA Version
2.5.22294

## Java Version
11.0.6

## Operating System
Windows 10

## Memory
Heap utilization statistics [MB]
Used Memory: 32
Free memory: 1947
Total memory: 1979
Max memory: 1979

## Stack Trace
```
Exception: games.strategy.engine.data.gameparser.GameParseExceptionCould not find resource or unitdunlending_wildman
java.lang.Exception
	at games.strategy.engine.data.gameparser.GameParser.parseResults(GameParser.java:642)
	at games.strategy.engine.data.gameparser.GameParser.parseProductionRules(GameParser.java:587)
	at games.strategy.engine.data.gameparser.GameParser.parse(GameParser.java:164)
	at games.strategy.engine.data.gameparser.GameParser.lambda$parse$0(GameParser.java:110)
	at org.triplea.java.UrlStreams.openStream(UrlStreams.java:73)
	at games.strategy.engine.data.gameparser.GameParser.parse(GameParser.java:105)
	at games.strategy.engine.framework.startup.ui.panels.main.game.selector.GameSelectorModel.lambda$new$0(GameSelectorModel.java:59)
	at games.strategy.engine.framework.startup.ui.panels.main.game.selector.GameSelectorModel.parseAndValidate(GameSelectorModel.java:126)
	at games.strategy.engine.framework.startup.ui.panels.main.game.selector.GameSelectorModel.load(GameSelectorModel.java:99)
	at games.strategy.engine.framework.startup.ui.panels.main.game.selector.GameSelectorPanel.lambda$selectGameFile$8(GameSelectorPanel.java:399)
	at games.strategy.engine.framework.ui.background.BackgroundTaskRunner.lambda$runInBackground$0(BackgroundTaskRunner.java:45)
	at games.strategy.engine.framework.ui.background.BackgroundTaskRunner$1.doInBackground(BackgroundTaskRunner.java:108)
	at java.desktop/javax.swing.SwingWorker$1.call(SwingWorker.java:304)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.desktop/javax.swing.SwingWorker.run(SwingWorker.java:343)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)


```

### PR DESCRIPTION
**Pull request by trevan**
Fixes #8076

In Battle for Arda, there appears to be an old game map in the root directory.  The engine is able to find a game name in it and it has the same game name as the real map.  This causes it to show up in the selector twice.  But the selector finds the game by name in the list and so if the bad game xml is first in the list, it will pull it out first.

This changes the UI selector to use the DefaultGameChooserEntry instead of a String so that it can properly choose the entry.

## Testing

Install Battle for Arda.  Select both of the entries in the UI.  One should throw an error because it is an invalid map.  The other should load without issue.  Without this PR, both entries might load without issue or throw an error (depending on how it is sorted internally).  I generally get an error thrown.

## Additional Notes to Reviewer

We should modify the map and remove the bad XML from it.

## Release Note

Fix|Battle for Arda will have a map that can be selected in the UI and it won't throw an error.

### CODE REVIEW

**Review by DanVanAtta — APPROVED** [review]

**Comment by DanVanAtta** [comment]
We should perhaps fix the map in the meantime and remove the extraneous XML. Doing that will have the release note making less sense.

In the meantime, the change looks good, thank you for fixing this @trevan

**Comment by DanVanAtta** [comment]
@trevan , unit test failure:

> games.strategy.engine.framework.ui.GameChooserModelTest > testOrdering() FAILED
    org.opentest4j.AssertionFailedError: expected: <a> but was: <Mock for DefaultGameChooserEntry, hashCode: 1836567136>

**Comment by trevan** [comment]
@DanVanAtta , I think I fixed that test.

**Comment by alkexr** [comment]
I'm the map creator, just a note here: the game xml is generated by a script, which takes the other xml as input. The only function of the other xml is to make the game xml more conveniently editable. The script more or less just implemented `variableList`, before the functionality was added to TA.

**Comment by trevan** [comment]
@alkexr can you change the extension of the template file?  If it doesn't end in .xml, it won't be seen by the engine.

**Comment by alkexr** [comment]
@trevan just delete it. It's only useful if someone wants to modify the map significantly; for players it's irrelevant. The script is obsolete anyway, I will use variables in the next version.

**Comment by trevan** [comment]
> @trevan just delete it. It's only useful if someone wants to modify the map significantly; for players it's irrelevant. The script is obsolete anyway, I will use variables in the next version.

@alkexr, Can you do that?

**Comment by Cernelius** [comment]
> @trevan just delete it. It's only useful if someone wants to modify the map significantly; for players it's irrelevant. The script is obsolete anyway, I will use variables in the next version.

I strongly advise against using variables. In my tests, they slow down the game loading a lot. Of course, it can be an insignificant delay if the amount of code that they create is not too big.

**Pull request merged**
