### PR TITLE
Updating description of Large Middle Earth

### PR DESCRIPTION
**Pull request by alkexr**
For Large Middle Earth version 1.2

Note: version 1.2 is not released yet, there is a pending pull request. (Also, I'm unsure what exactly happens if I just merge version 1.2 into the master branch.)

### CODE REVIEW

**Comment by ron-murhammer** [comment]
@alkexr I think for now we want to keep all map images in sourceforge. I want to avoid referencing people's personal dropboxes in case they would remove them in the future.

**Comment by alkexr** [comment]
Yes, map image on sourceforge would be cool. So, how do I do that?

BTW can you help me releasing my map? (Sorry, but the documentation for map makers sucks. Links are broken, content out of date etc.) I have uploaded the would-be new version into a new branch of triplea-maps/large_middle_earth. The link in the triplea_maps.yaml references the master branch. Does this mean that as soon as I merge the new version into master, the new version is released?

**Comment by DanVanAtta** [comment]
I would personally avoid source forge (slow and requires SVN). Github provides image hosting  - create a new issue, attach an image, copy/paste the URL somewhere, close the issue without ever even creating it.

**Comment by ron-murhammer** [comment]
@DanVanAtta Agree but we need to move all the existing images over and then update the image links.

**Comment by DanVanAtta** [comment]
Yes, though that can be tackled peace-meal, and for now we can simply avoid adding new SF links.

**Comment by DanVanAtta** [comment]
@alkexr please update the dropbox url to a github one.

> " Github provides image hosting - create a new issue, attach an image, copy/paste the URL somewhere, close the issue without ever even creating it."

Beyond that, I have no objections here.

**Comment by ron-murhammer** [comment]
@DanVanAtta It might be better to put all the images in a repo. Just so they are manageable somewhere. Otherwise it might be difficult if we had to track them down to move or something later on.

**Comment by DanVanAtta** [comment]
@alkexr , I would suggest going with the github issue URL for now (certainly not dropbox). 
Let's discuss and design map thumbnail image handling here: https://github.com/triplea-game/triplea/issues/1468

**Comment by alkexr** [comment]
Everything should be good to go now.

**Pull request merged**
