### PR TITLE
Remove fix mac icon script

### PR DESCRIPTION
**Pull request by DanVanAtta**
script file is not used. This PR branch is based on #101

[Review on Reviewable](https://reviewable.io/reviews/triplea-game/triplea/107)

### CODE REVIEW

**Comment by DanVanAtta** [comment]
@ron-murhammer , (or @veqryn) , why take the time to assign this to yourself but not also merge it? What more do we plan to do?

**Comment by ron-murhammer** [comment]
Because it can't be merged until #103 is.

**Comment by veqryn** [comment]
This kind of a PR shouldn't have been based on any other branches.  There is no reason why deleting this file should require PR 103.

Rebase please.

**Comment by DanVanAtta** [comment]
I follow the rule you never knowingly submit anything that will cause a build to break. A second rule to that is any PR that caused a build break must either be fixed or closed. 

The build succeeding is proof that this file is not need as part of the build. We've done other work already to prove this file is not needed, so the extra proof of the build succeeding I'll agree was not strictly needed. 

Okay, with that said, it'll be my pleasure to rebase. Working on that now....

**Comment by DanVanAtta** [comment]
Now rebased

**Pull request merged**
