### PR TITLE
Yaml update.  Don't merge until these PRs have been merged into their map

### PR DESCRIPTION
**Pull request by CharlieAtlas**
Yaml update.  Don't merge until these PRs have been merged into their map.  

https://github.com/triplea-maps/new_world_order1915lebowski/pulls

### CODE REVIEW

**Comment by DanVanAtta** [comment]
@CharlieAtlas this is good to merge? All dependent PRs are in?

**Comment by CharlieAtlas** [comment]
I think so.  I just didn't want to have the YAML update before the actual PRs were done.  The only question i have is why did that check fail?

**Comment by DanVanAtta** [comment]
@CharlieAtlas merge the latest into this branch. You'll pick up the github build-check actions. We've hit the limit on travis, it can't be re-run.

**Comment by CharlieAtlas** [comment]
I am not quite sure what you mean.  
Rebase my YAML branch?  Does that do anything to my PR?  
Rebase and then do another PR on top of this?

**Comment by CharlieAtlas** [comment]
Okay, so I definitely did something wrong with this.  I am guessing i did my rebase/merge wrong.

**Comment by DanVanAtta** [comment]
@CharlieAtlas 

```
git checkout master
git pull --rebase upstream master
git checkout YAML
git pull --rebase upstream master
git push -f origin YAML
```

**Pull request merged**
