### PR TITLE
AI without capital shouldn't do politics

### PR DESCRIPTION
**Pull request by asvitkine**
AI without capital shouldn't do politics. Otherwise, it's confusing when eliminated players declare war and other random actions when they clearly are in no position to do so.

## Functional Changes

[ ] New map or map update
[ ] New Feature
[ ] Feature update or enhancement
[ ] Feature Removal
[ ] Code Cleanup or refactor
[ ] Configuration Change
[ X] Bug fix:  
[ ] Other:   

## Testing

[ ] Covered by existing automated tests
[ ] Covered by newly added automated tests
[ ] Manually tested
[ X] No testing done

### CODE REVIEW

**Comment by Cernelius** [comment]
I'm personally more bothered by the fact that completely eliminated players cannot receive political actions (so I'm stuck eventually liberating their capitals, in case I was allied with them), but the defaults here I believe are supposed to be what happens in WWII Global...

**Comment by asvitkine** [comment]
Is WWII Global an official board game or just a community map?

Can you link to the rules for it?

In terms of this patch, this is not actually changing the rule set. It's just changing the behavior of the AI. So human players can continue to do what they can do right now.

In theory, this could instead be made more sophisticated instead - for example players who've lost their capital to have logic to not declare wars since that's generally detrimental. But I thought this would be the simplest fix.

(There's a separate argument of whether this should be codified in the rules instead - i.e. you lose the ability to do politics after capital is lost - but that seems like a bigger can of worms, hence why I've opted for this version currently.)

Happy to listen to what you think!

**Comment by ron-murhammer** [comment]
@asvitkine I'm not sure this change would work across all maps as I believe there are some with no capitals. I think my question is what maps have you played where the AI was declaring war after they had lost their capital?

**Comment by asvitkine** [comment]
Ah right, it should be "capital == null || controls capital". I can change it to that.

For the map, its napoleonic wars ffa.

**Comment by asvitkine** [comment]
Apologies for the delay. I updated the logic per the above.

I think the better long-term solution is to make the Politics AI actually do reasonable things - e.g. declare war on enemies that it can attack reasonably and sue for peace when it's in trouble. And make consistent decision when replying to politics actions vs. initiating them.

Right now, it's mostly random.

Still, I think this is a reasonable improvement in the meantime, before we can get some reasonable Politics AI logic in place.

**Pull request merged**
