### PR TITLE
Fix infinite loop in NewGameChooserModel.java when map download is corrupt

### PR DESCRIPTION
**Pull request by DanVanAtta**
In the current code there is a while loop "while(entry != null)". Notice at the bottom of the loop before finally catch blocks we have the line that increments the entry: "entry = zis.getNextEntry()"

But, before this, we use the entry to get a url. If the download file is corrupt or truncated, this can come back null. We then have the following statement "if(url == null) { continue; }". In this case we miss the "zis.getNextEntry()", and we proceed to read the same zip file and get the same null url continuing in an infinite loop.

[Review on Reviewable](https://reviewable.io/reviews/triplea-game/triplea/76)

### CODE REVIEW

**Comment by DanVanAtta** [comment]
The impact of this is you cannot start or select a game while the corrupt file is in the map search path. It can be triggered by terminating a download early. One insidious aspect is that there is no error message for the user or indication of which map file is bad. NewGameChooser goes into an infinite loop with a lock, we then try to access that lock the Swing AWT event thread and will never get it. With the event thread locked up, the UI is unresponsive and the game just sits. Only way to fix the problem for now would be to locate and remove the broken zip file. With this patch the broken zip file *could* be around and would be skipped over, but better to get it removed (hence the extra code to prompt the user to delete the corrupt file)

**Comment by ron-murhammer** [comment]
@DanVanAtta Agree that the continue can cause an infinite loop so needs to be fixed. Were you able to reproduce the infinite loop with a corrupted map zip? If so it would seem to be an excellent test case to add. I would like to test it myself though wasn't sure how to create a corrupt map to test it

**Comment by DanVanAtta** [comment]
I do have a zip that reproduced it. Adding the zip file, megabytes, to the source code is not worth it. We can test it in other ways. Given the state of the code, I would suggest we focus on other stuff to test. We have a *lot* of bad error handling, and this was just one example. 

We have users that are hitting this bug, and there is actually another I have run into due to corrupt zip that I am working on. While I appreciate and to some extent agree with sentiment to add a test case, respectfully in this circumstance I reject that action item.

**Comment by DanVanAtta** [comment]
One other comment, "reproduce" is not quite the right word. I was more "victim" to this problem. I hit it without trying and all of a sudden the game was unplayable with no error message. It was very bad.  A new player, if they try to DL maps and hit that, probably would walk away and be annoyed they downloaded 300MB for nothing.

**Comment by ron-murhammer** [comment]
@DanVanAtta Fair enough though I'm guessing there is a way to create a very small corrupt zip to test it but that's fine if you consider it out of scope for this. I would still like to personally test it just so I see the new functionality you added and understand what the corrupt zip looks like. Can you upload it somewhere or email it to me?

**Comment by DanVanAtta** [comment]
With apologies, I was incorrect to say I still had the zip. In the last month I set up a new ubuntu system, a week ago I switched to a new fast hard disk and thought I had migrated everything important. Likely that file was the one thing I did not get : /    So, sorry, no repro case to provide even if i wanted to now.

**Comment by veqryn** [comment]
Why are you breaking out of the loop instead of continuing like it was previously?

**Comment by DanVanAtta** [comment]
The continue causes an infinite loop. The commit message details the the iterator increment happens at the end of the loop. We continue in the middle, so the iterator is never incremented, and retry the exact same file with the same error.

**Comment by veqryn** [comment]
Ah, I see now.
How about changing it to increment at the start?

**Comment by DanVanAtta** [comment]
Then we would skip over the very first element.

**Comment by veqryn** [comment]
I think there is probably a better way to do this.
Also, I am not sure you should be deleting the while while we have inputstreams and zip entries of it open.

**Comment by DanVanAtta** [comment]
A resource leak is far better than infinite loop. I'm interested to know what a better change would be. Personally I'd rather refactor the whole method. I've tried to keep the change minimal and focused for now for ease of review and priority (you guys don't want a lot of changes to review, and refactoring this code is probably not worht it compared to others, and refactor and fix at same time has drawn criticism befo0re).

We also have had a recent report of htis problem: http://tripleadev.1671093.n2.nabble.com/TripleA-doesn-t-work-at-all-td7589123.html

Given there is no error message once this situation is triggered, and then from then on the game is not playable, this any fix is really better than no fix here. I'm almost surprised we didn't rush this fix into 1809 after we got a report from a user having hit it.

**Comment by DanVanAtta** [comment]
There is no resource leak though, the streams are closed in a finally block. Deleting with streams open a bit suspect yes, but the code does work (been tested). Since the streams are closed anyways, really changing this code to have the same effect I don't see as valuable or as a simplification.

**Comment by veqryn** [comment]
Can you move the deletion of it to outside of the open streams?

**Comment by DanVanAtta** [comment]
I don't think that is necessary, but still mostly reasonable at the same time. I'll have a look. Ball is in my court still.

**Comment by DanVanAtta** [comment]
@veqryn , do you know which permissions issues could cause it? IE: could you describe that repro case to me so I can test with it.

**Comment by DanVanAtta** [comment]
Ball is back with you @veqryn . 

Two updates:
1. set a flag if bad zip file encountered and break. Then after streams are closed, if flag is set, then prompt user if they want to delete the zip file.
2. updated the message displayed to user, gave some more description of what happens if the file is kept (the same error message may pop up again).

A 2.0 feature would be a "do not show this again" property. But then it would be good to have a way to clear that if you click wrong, and all in all, we're better off probably solving this problem at least much and maybe moving on to something else.

**Comment by veqryn** [comment]
Looks good to me. I wish I had a zip to test this on, since I can not test this right now.
@ron-murhammer can you confirm the code looks good, then merge pls?

**Comment by DanVanAtta** [comment]
The test failure is a one-off, not a very good test (or a slightly buggy thread pool implementation). #109 is open to start addressing that test problem.

I updated this PR to remove the leaked .gitignore file update.

Thanks for the review. 

I also wish I still had the repo file as well. Learned the hard way to attach all necessary repro to the ticket, google cloud drive links and all. Actually brings me to a comment about this feature. That particular file that caused this problem had multiple files inside the zip that are parsed by this while loop. Rather than duplicating the increment code and then continuing to see if we could read any other files in the zip, we instead break. The particular zip with the problem, since it was truncated, the problem would happen on the last file and there was nothing to continue to. At that point the maps that were parsed from the zip were in bad state, missing a lot of stuff. Hence the decision to clean it up based on user input.

**Comment by veqryn** [comment]
repro?
Also, we already have an eclipse build .gitignore line: 'temp_eclipse', you prefer telling eclipse to use that instead.

**Comment by veqryn** [comment]
I would still like to test this sometime, so if you ever find another zip that does this, pls save it and add it to the test data or something.  Merging.

**Pull request merged**
