### PR TITLE
Revert "ClientLogger change"

### PR DESCRIPTION
**Pull request by DanVanAtta**
Reverts triplea-game/triplea#1002

---
This change is [Reviewable](https://reviewable.io/reviews/triplea-game/triplea/1008)

### CODE REVIEW

**Comment by DanVanAtta** [comment]
if `e.getMessage()` is null, then we should check for that and not print it.

Otherwise we can lose information that is not printed with the stack trace.

**Comment by RoiEXLab** [comment]
@DanVanAtta that's not the case! e.printStackTrace prints out the message if not null anyways

**Comment by DanVanAtta** [comment]
I recall seeing that the printstack trace and message were needed for some swing back ground events that could die. I do not recall exactly where. 

Please cite some code examples that shows that printStackTrace will always not be needed. 

From the doc: https://docs.oracle.com/javase/8/docs/api/java/lang/Throwable.html#printStackTrace-java.io.PrintStream-

It seems like we are depending on exceptions to print their message. The Swing/legacy exceptions likely do not, in which case we need the message printed.

The test is not if a standard NPE is redundant, but instead be on a AWT thread, fire off a new thread, and have it throw an exception where 'toString()' does not print the error message. If we still get the error message in that esoteric, but real case, then the code is truly not needed.

**Comment by DanVanAtta** [comment]
From here:
- simple NPE check and not print would ensure we have the message
- if we want to get rid of the if branch, which would be sweet, we need confirmation that various swing exceptions and/or exceptions in the background will behave well and will also always print an exception message

**Comment by RoiEXLab** [comment]
@DanVanAtta I'll do some research on this tomorrow...

**Pull request merged**
