### PR TITLE
Added Anglo-American_Nazi_War

### PR DESCRIPTION
**Pull request by RogerCooper**

### CODE REVIEW

**Comment by beelee1** [comment]
@RogerCooper you might want to double check about having "nazi" in the name. I know the swastika is a no go. Some don't like "SS" either. Idk where the line is.

**Comment by RogerCooper** [comment]
The swastika is not used. I have not seen any policy that use of the term 'Nazi' or 'SS' is prohibited.

In any event, they get beat pretty quickly in this poorly balanced scenario.

**Comment by DanVanAtta** [comment]
SS is ahistoric as a major unit type and must be changed.

**Comment by DanVanAtta** [comment]
@RogerCooper the name of this map is odd though. Why 'anglo-american'?

I'd like for this to go a bit slower and get better consideration of the map title. I think there are potentially stronger map titles, perhaps something like "Pact of Molotov-Ribbrentrop"  or "Iron Molotov-Ribbrentrop"

**Comment by DanVanAtta** [comment]
Did a quick revert pending further discussion  (we can roll forward by reverting the revert: https://github.com/triplea-game/triplea/pull/9567)

**Comment by RogerCooper** [comment]
There is no 'SS' unit in this mod. 

I didn't create this scenario, I don't know why the designer used that awkward name. Perhaps "Anglo-American Alliance War" instead.

**Comment by DanVanAtta** [comment]
Funny enough I'm more concerned by the 'Anglo-American' part of the title.

**Comment by beelee1** [comment]
Yea it should say "Anglo Saxon" and it would be fine

**Pull request merged**
