### PR TITLE
Remove Md5Crypt authentication support from lobby client

### PR DESCRIPTION
**Pull request by ssoloff**
## Overview

Removes support for the deprecated Md5Crypt authentication protocol from the lobby client.  The lobby server continues to support Md5Crypt authentication for the sake of older clients.

## Functional Changes

* Lobby client no longer responds to Md5Crypt challenge.  It will only generate a response to a bcrypt challenge.
* Lobby client no longer updates Md5Crypted password during a password change.  Only bcrypted password is updated.

## Manual Testing Performed

Tested the following scenarios using a lobby server from this branch and from 1.9.0.0.11996:

* Login using an existing account that has both Md5Crypted and bcrypted passwords.
* Change password for an existing account that has both Md5Crypted and bcrypted passwords and verified a subsequent login using the new password.
* Create a new account.
    * Verified no Md5Crypted password is created in the database.
    * Verified user could still login using a 1.9.0.0.12226 lobby client.

## Additional Review Notes

Some consequences of this change:

* If a user changes their password using a 1.10 client, they will no longer be able to login using 1.9.0.0.3635.  All stable releases after 1.9.0.0.3635 should work fine, as they all support bcrypt authentication.
* If a user creates a new account using a 1.10 client, they will not be able to login using 1.9.0.0.3635.  Logging in using any stable release after 1.9.0.0.3635 should succeed, as they all support bcrypt authentication.

### CODE REVIEW

**Comment by ssoloff** [comment]
> Looks good, however the database scheme should be updated along with this.

@RoiEXLab I purposefully avoided changing anything on the server side (which would include the database schema) to avoid breaking lobby compatibility with older 1.9 clients.  I don't know that we've made a decision that the 1.10 lobby server must no longer be compatible with 1.9 lobby clients.

**Comment by ssoloff** [comment]
> Regardless it would still be interesting to know how many user accounts there are that don't support bycrypt.

@RoiEXLab It's been a while since I've thought about that.  Would it just be counting the records that have a non-`NULL` value for the `password` column and a `NULL` value for the `bcrypt_password` column?

**Comment by RoiEXLab** [comment]
@ssoloff Yes, actually simply checking for NULL in the bcrypt_password column is sufficient because there's a constraint ensuring at least one of both password fields must be non NULL

**Comment by ssoloff** [comment]
```text
ta_users=# select count(*) from ta_users where bcrypt_password is null;
 count 
-------
  1176
(1 row)
```

**Comment by ssoloff** [comment]
And the most recent login of such a legacy (3635?) user is today:

```text
ta_users=# select max(lastlogin) from ta_users where bcrypt_password is null;
            max             
----------------------------
 2018-10-29 12:24:50.479-04
(1 row)
```

**Comment by RoiEXLab** [comment]
@ssoloff That's not good, I was hoping that the only accounts left were abandoned accounts.
Too bad we had that small gap between database reset and bcrypt on the server side.
Any ideas on how to notify those users that they should update if they want to keep their account?

**Comment by ssoloff** [comment]
@RoiEXLab Extract their emails from the database and mass mail them?

I suppose we could also add another message to _lobby_server.yaml_ that strongly encourages users still using 3635 to upgrade or they will lose access to the lobby in the future.

**Comment by RoiEXLab** [comment]
@ssoloff 
Probably the best option we have

**Comment by RoiEXLab** [comment]
@ssoloff Not really I was kinda waiting for someone else to post their opinion on this, as long as there are so many users with "legacy clients".
On could of course argue that for now, in order to fix this a user could upgrade in smaller steps and install the latest 1.9 version before installing the latest 1.10 version.

**Comment by ssoloff** [comment]
@RoiEXLab No problem.  I'm okay waiting for further input.  Just wanted to make sure I didn't miss a request to do something. :smile:

Tagging @DanVanAtta and @ron-murhammer if they have opinions on the 1.9 to 1.10 upgrade.  To summarize the consequences of this PR:

* Any lobby user currently running 1.9.0.0.3635 (1.5-year-old release) would not be able to upgrade directly to 1.10; they'd have to first upgrade to any later stable 1.9 release and then upgrade to 1.10.
* If they failed to do this, they simply wouldn't be able to login.  This would not be a permanent condition.  They could always go back and install the latest 1.9 and login to the lobby.  Then they'd be able to login using 1.10.

**Comment by beelee1** [comment]
> @RoiEXLab Extract their emails from the database and mass mail them?
> 
> I suppose we could also add another message to _lobby_server.yaml_ that strongly encourages users still using 3635 to upgrade or they will lose access to the lobby in the future.

If you go this route you may want to highlight the message in red or at least bold it. The start of the lobby just kinda all blends in. I would think a lot of people may miss it.

Just a thought.

**Comment by ssoloff** [comment]
@beelee1 That's a good idea.  Unfortunately, I don't think there's a way to change the font and/or color of individual portions of the lobby message at this time.  But maybe that would be a good feature for the reasons you point out.

**Comment by RoiEXLab** [comment]
@ssoloff Are you sure about that.
I don't think there's any escaping going on, so wrapping stuff in html, might do the trick already.

**Comment by ssoloff** [comment]
@RoiEXLab That's what I thought, too, but when I tried it, the tags were rendered as-is.  I looked at the code, and it's simply inserting this string into a `Document` using a fixed `AttributeSet`.  I don't see where the chat subsystem specifies a specific `Document` instance, so presumably it's using `DefaultStyledDocument`, which I believe has no special support for HTML tags.

**Comment by RoiEXLab** [comment]
@ssoloff Too bad then, we should keep that in mind for the next lobby system ^^

**Comment by ron-murhammer** [comment]
@ssoloff Given how easy it is to create a new username or login anonymously, I don't think its a major issue. It might be a good idea to get a feel for how many of those 1176 users have logged in within say the last month. My guess is the vast majority of those are dead usernames. Gonna merge this.

**Comment by ssoloff** [comment]
> It might be a good idea to get a feel for how many of those 1176 users have logged in within say the last month.

@ron-murhammer About 9% of the active lobby users appear to be using 1.9.0.0.3635:

```
ta_users=# select count(*) from ta_users where lastlogin > current_date - interval '1' month;
 count 
-------
   977
(1 row)

ta_users=# select count(*) from ta_users where lastlogin > current_date - interval '1' month and bcrypt_password is null;
 count 
-------
    84
(1 row)
```

**Pull request merged**
