### PR TITLE
Update checkstyle to require javadocs on public classes, interfaces and enums

### PR DESCRIPTION
**Pull request by DanVanAtta**
Submitting first without updating thresholds. The gradle.properties would probably get merge conflicted almost right away. So please approve, once approved I'll fix the threshold to pass the build and merge. (I've found gradle.properties is really a very not nice filed to have in a branch updated, so many conflicts..)

### CODE REVIEW

**Comment by DanVanAtta** [comment]
Hmm. Is there a reasonable javadoc we would want a test class? It could be useful for asking that a test plan/things that are covered be summarized there. Either that or we ignore the test warning count... I don't think we should require nonsense test class javadocs.

**Comment by ssoloff** [comment]
It looks like Checkstyle supports a separate configuration file (commonly called `suppressions.xml`) in which you can turn off specific rules by file name pattern.  So that should allow us to turn off this rule for all files that match `*Test.java`.

Unfortunately, use of a `suppressions.xml` file is not supported in the Gradle 3.5 version of the Checkstyle plugin, but _appears_ to be supported in the Gradle 4.0 plugin.

My suggestion would be to go ahead with this change and do not disable Checkstyle for test code.  We probably will upgrade to Gradle 4 in the next few weeks or months anyway, so there is a path forward.  In the meantime, allow devs to bump the violation count when they add new test classes, if necessary.

**Comment by ssoloff** [comment]
Actually, I see that the Gradle team has been using such a `suppressions.xml` file in their build since 2009.  So there must be a way to configure it in Gradle versions less than 4.  Let me dig around some more.

**Comment by DanVanAtta** [comment]
Impressive follow-up @ssoloff, happy to watch you run with this as far as you're willing.

**Comment by ssoloff** [comment]
@DanVanAtta This seems to do it.  The only thing I'm not happy about is hard-coding the (relative) path to `suppressions.xml`.  There should be a way to specify the path using a Gradle property, but I can't get it to work.  But once we upgrade to Gradle 4, hopefully the `SuppressionFilter` module can be removed or re-configured to have the path injected.

```diff
diff --git a/config/checkstyle/checkstyle.xml b/config/checkstyle/checkstyle.xml
index 0885b58..a87ee6d 100644
--- a/config/checkstyle/checkstyle.xml
+++ b/config/checkstyle/checkstyle.xml
@@ -21,6 +21,11 @@
     <property name="severity" value="warning"/>
 
     <property name="fileExtensions" value="java, properties, xml"/>
+
+    <module name="SuppressionFilter">
+        <property name="file" value="config/checkstyle/suppressions.xml"/>
+    </module>
+
     <!-- Checks for whitespace                               -->
     <!-- See http://checkstyle.sf.net/config_whitespace.html -->
         <module name="FileTabCharacter">
diff --git a/config/checkstyle/suppressions.xml b/config/checkstyle/suppressions.xml
new file mode 100644
index 0000000..9a3882f
--- /dev/null
+++ b/config/checkstyle/suppressions.xml
@@ -0,0 +1,9 @@
+<?xml version="1.0"?>
+
+<!DOCTYPE suppressions PUBLIC
+    "-//Puppy Crawl//DTD Suppressions 1.1//EN"
+    "http://checkstyle.sourceforge.net/dtds/suppressions_1_1.dtd">
+
+<suppressions>
+    <suppress checks="JavadocType" files=".*Test\.java"/>
+</suppressions>
```

**Comment by ssoloff** [comment]
For future reference, [this](https://docs.gradle.org/current/userguide/checkstyle_plugin.html#sec:checkstyle_built_in_variables) is how the hard-coded path can be fixed in Gradle 4+:

**config/checkstyle/checkstyle.xml**
```xml
<module name="SuppressionFilter">
    <property name="file" value="${config_loc}/suppressions.xml"/>
</module>
```

**Comment by ssoloff** [comment]
I also confirmed the suppressions work correctly within Eclipse (albeit after a restart, which seems to be the only way to get the Checkstyle plugin to re-read the configuration).

The IDE test made me think about the `suppressions.xml` path...  The `${config_loc}` variable I mentioned above is injected by Gradle.  During an IDE build, that variable won't be available, so the path resolution will fail.  Bottom line, I think we're stuck with the hard-coded relative path as it is in the above patch.

**Comment by ron-murhammer** [comment]
@ssoloff Works for me. Do you want to update this PR, create a new PR, or merge this then have a follow on PR?

**Comment by ssoloff** [comment]
@ron-murhammer Merging this PR as-is is off the table because it will fail the build due to the thresholds being off.

If @DanVanAtta doesn't apply the above patch to this PR before I am ready to go offline, I'll submit a new PR because I'm not sure I have write permission to @DanVanAtta's fork (I believe only "maintainers"  have write access if the fork owner checks that box when opening a PR).

**Comment by ssoloff** [comment]
@ron-murhammer I'm pretty much done for the night, so I submitted #2035.  It captures the changes in this PR, as well as the test class suppression documented above.  If @DanVanAtta updates this PR in the meantime, please prefer this PR over #2035.

**Pull request closed without merging**
