### PR TITLE
Update logic for units can be in battle to include AA on attack

### LINKED ISSUE #1966: Allow isInfrastructure unit to attacking with only AA attack to last for multiple rounds
**Description:**
There seems to be a problem if a land unit uses only AA attack (no matter what the unit or AA attack is named), has isInfrastructure true, and can attack move into combat. The unit seems to only fire once even though it is set to infinite rounds. If the same unit is defending, everything works, but just not when attacking.

Here is a test xml with a setup that can be tested (mod of xml in world_war_ii_classic-master.zip):
[text-XML-for-world_war_ii_classic-master.zip](https://github.com/triplea-game/triplea/files/1098462/text-XML-for-world_war_ii_classic-master.zip)

Here is the AA unit used in the XML testing:
```
        <attachment name="unitAttachment" attachTo="aaGun" javaClass="games.strategy.triplea.attachments.UnitAttachment" type="unitType">
            <option name="isInfrastructure" value="true"/>
                <option name="attackAA" value="1"/>
                <option name="offensiveAttackAA" value="1"/>
                <option name="maxAAattacks" value="1"/>
                <option name="maxRoundsAA" value="-1"/>
                <option name="isAAforCombatOnly" value="true"/>
                <option name="isAAforBombingThisUnitOnly" value="false"/>
                <option name="isAAforFlyOverOnly" value="true"/>
                <option name="mayOverStackAA" value="true"/>
            <option name="transportCost" value="1"/>
            <option name="movement" value="1"/>
        </attachment>
```
 
**Example 1 (Works):**
Russia attacks with Infantry and fighter. The German aaGun shoots its 1 every round, as long as enemy fighter lives and as long as USSR units are also alive.
unavngivet
unavngivet2

**Example 2 (Bug):**
Russia attacks with Infantry and aaGun. The Russian aaGun should be attacking in infinite rounds, as long as there is a German fighter. But the Russian aaGun only shoots once and is not displayed either. In second battle round there is no more “Russians AA fire”.

unavngivet3
unavngivet4

Forum diskussion here:
https://forums.triplea-game.org/topic/154/aa-gun-only-attacking-once-on-offence-help

### PR DESCRIPTION
**Pull request by ron-murhammer**
Fixes #1966. Would appreciate any additional testing on a variety of maps to ensure no adverse affects. I tested it on a few popular maps and didn't see any issues as well as the test map from the issue. 

Functional Changes
- Update logic that filters which units can be in battle to allow AA on attack just like defense

### CODE REVIEW

**Comment by ssoloff** [comment]
@ron-murhammer Can you list which additional maps you'd like to see tested?

**Comment by ron-murhammer** [comment]
@ssoloff No specific maps. Anything that has infra units that can attack would be particularly useful but just a variety to ensure no strange behavior.

**Comment by ssoloff** [comment]
@ron-murhammer I tested Feudal Japan Warlords (4 player).  I didn't see any difference in behavior between this branch and `master` with respect to the Ninja (infrastructure) unit in combat.

**Comment by ron-murhammer** [comment]
Resolved merge conflicts. For some reason, I had to merge master twice...

**Comment by ron-murhammer** [comment]
@ssoloff @DanVanAtta @RoiEXLab Thoughts on this PR?

**Comment by ssoloff** [comment]
@ron-murhammer  As I mentioned above, testing with Feudal Japan Warlords displayed no issues.

The first time I went through the code, the match logic had my brain spinning, and I didn't feel comfortable commenting on it.  I went through it again just now, and it seemed remarkably simpler on the second pass. :smile:

Here's what I think is happening:

The core of the change was moving the component match previously named `defenseMatchAnyBuilder ` outside of the if-attack-else-defense block so it now applies to both cases and renaming it `supportOrNotInfrastructureOrAa`.  Then the rest of the change was just clean-up:

* You merged `attackMatchAllBuilder` and `defenseMatchAllBuilder` into a single variable `canBeInBattle`.
* Now that there aren't two separate match builders for attack and defense, you got rid of the intermediate `combat` variable and use `canBeInBattle.all()` directly in the return statement.

Please confirm if I got all that right.  If I did, then I think this PR is good to merge.

**Comment by ron-murhammer** [comment]
@ssoloff Exactly. So logically it ends up just allowing AA to also be in battle on attack just like defense which ends up making the method much simpler. Going to merge so this can get more user testing to ensure no unintended side effects.

**Pull request merged**
