### PR TITLE
Installer beta release

### PR DESCRIPTION
**Pull request by gaborbernat**
@DanVanAtta @ron-murhammer @veqryn I tested it on Windows, and Linux. I found no issues. Someone should test the mac installer though. 

- remove old installer build files
- Add mp3 player as compile dependency, remove libs that can be downloaded with the builder 
- Create a shadowJar, without the version number name, use this for both the releases and the installer  
- JREs are now downloaded on-demand from github at installation time
- add 32 bit Windows installer (to 64 bit Windows, plus MAC/UNIX - 64 bit only)
- fix bad icons for installer, uninstaller
- at install time by selecting the same directory the user can choose to upgrade its tripleA version; if this is choosen first we uninstall the old version (non install files, such as save games are kept)
- add version number into created application shortcut (for easier multi
      version install use case)

[Review on Reviewable](https://reviewable.io/reviews/triplea-game/triplea/372)

### CODE REVIEW

**Comment by DanVanAtta** [comment]
@gaborbernat  - I don't think this is complete without an update to .travis.yml with the new installer file names, so that they may be deployed to github releases.

**Comment by DanVanAtta** [comment]
@gaborbernat , this overall looks good, but please address:
-  .travis.yml needing new installer file names, wraps up the loose end
-  Drop commit: e3b391d, and/or update documentation somewhere to address the concerns

**Comment by gaborbernat** [comment]
Fixed all that was reported.

**Comment by DanVanAtta** [comment]
#374 opened to ask the other admins to see about configuring their dev environments to be ready for the lib deletion.

**Comment by ron-murhammer** [comment]
@gaborbernat @DanVanAtta My preference would be to wait until we do an official release with the new build before removing all the ant build files. I think it would be better to split anything that we need for the new gradle build to work and removing the old ant files into 2 separate PRs. We can merge the gradle updates now then have the ant clean up later on.

Either way I think making the ant clean up into a separate PR is a must since if for some reason we need to roll back it will be much easier to see what needs to be restored.

**Comment by DanVanAtta** [comment]
@ron-murhammer we are really well far beyond needing the ant builds. In no case should anyone still be using them. With the decision to freeze the code in SVN, we are only going to roll forward with fixes in the build process, not back, past the point of no return when it comes to gradle vs ant.

**Comment by DanVanAtta** [comment]
Another small point, it's easy to roll back commits, no need to bundle things into a PR to get that benefit.

**Pull request closed without merging**
