### PR TITLE
Clean rework of mapXmlCreator package 

### PR DESCRIPTION
**Pull request by frigoref**
This change is [Reviewable](https://reviewable.io/reviews/triplea-game/triplea/580)

### CODE REVIEW

**Comment by frigoref** [comment]
I get the following error when executing Gradle Task 'build' or 'compileJava':
"invalid source release: 1.8
Could not execute build using Gradle distribution 'https://services.gradle.org/distributions/gradle-2.10-all.zip'."
This refers to the file gradle/wrapper/gradle-wrapper.properties I guess, but what should I do? Any idea what is mean with "source release" (Java or Gradle Services Distribution) and whether an upgrade to gradle-2.13-all.zip would help?
The triplea application is running fine on my computer.

**Comment by RoiEXLab** [comment]
I created a Pull request on your fork fixing a missing import of the Assert package.
This should fix the building Issue.

**Comment by frigoref** [comment]
I have tried it locally, but this does not fix the issue. And even if it would, then this is a gradle issue as the project can be compiled in eclipse without problems.

**Comment by frigoref** [comment]
I solved it locally with an eclipse setting for Gradle (STS):
It was set to "Use Gradle wrapper's default" and I changed it to use a specific jdk1.8. 

Now I am just getting the following warnings:
C:\Users\User\git\triplea\src\games\strategy\net\nio\ServerQuarantineConversation.java:14: warning: SocketAdaptor is internal proprietary API and may be removed in a future release
import sun.nio.ch.SocketAdaptor;
                 ^
C:\Users\User\git\triplea\src\games\strategy\util\ClassLoaderUtil.java:15: warning: URLClassPath is internal proprietary API and may be removed in a future release
import sun.misc.URLClassPath;
               ^
C:\Users\User\git\triplea\src\util\triplea\mapXmlCreator\MapXmlCreator.java:66: warning: ParseException is internal proprietary API and may be removed in a future release
import com.sun.org.apache.xerces.internal.impl.xpath.regex.ParseException;
                                                          ^
C:\Users\User\git\triplea\src\games\strategy\net\nio\ServerQuarantineConversation.java:117: warning: SocketAdaptor is internal proprietary API and may be removed in a future release
              ((SocketAdaptor) m_channel.socket()).getInetAddress().getHostAddress(), m_remoteMac);
                ^
C:\Users\User\git\triplea\src\games\strategy\util\ClassLoaderUtil.java:69: warning: URLClassPath is internal proprietary API and may be removed in a future release
    loadersField = getField(URLClassPath.class, URLCLASSPATH_LOADERS_FIELD_NAME);
                            ^
C:\Users\User\git\triplea\src\games\strategy\util\ClassLoaderUtil.java:70: warning: URLClassPath is internal proprietary API and may be removed in a future release
    urlsField = getField(URLClassPath.class, URLCLASSPATH_URLS_FIELD_NAME);
                         ^
C:\Users\User\git\triplea\src\games\strategy\util\ClassLoaderUtil.java:71: warning: URLClassPath is internal proprietary API and may be removed in a future release
    lmapField = getField(URLClassPath.class, URLCLASSPATH_LMAP_FIELD_NAME);
                         ^
C:\Users\User\git\triplea\src\games\strategy\util\ClassLoaderUtil.java:72: warning: URLClassPath is internal proprietary API and may be removed in a future release
    jarLoaderInnerClass = getInnerClass(URLClassPath.class, URLCLASSPATH_JARLOADER_INNER_CLASS_NAME);
                                        ^
C:\Users\User\git\triplea\src\games\strategy\util\ClassLoaderUtil.java:151: warning: URLClassPath is internal proprietary API and may be removed in a future release
      final URLClassPath ucp = (URLClassPath) jcpField.get(classLoader);
            ^
C:\Users\User\git\triplea\src\games\strategy\util\ClassLoaderUtil.java:151: warning: URLClassPath is internal proprietary API and may be removed in a future release
      final URLClassPath ucp = (URLClassPath) jcpField.get(classLoader);
                                ^
C:\Users\User\git\triplea\src\util\triplea\mapXmlCreator\MapXmlCreator.java:1110: warning: ParseException is internal proprietary API and may be removed in a future release
    } catch (final IOException | HeadlessException | ParserConfigurationException | ParseException | SAXException e) {
                                                                                    ^
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
11 warnings

However, how do we convince the server now to accept the pull request? Do we have to change something on the gradle-wrapper.properties file (http://stackoverflow.com/questions/18487406/how-do-i-tell-gradle-to-use-specific-jdk-version)?

**Comment by RoiEXLab** [comment]
Those warnings are normal... They are triggered because of deprecated APIs and some deprecated distance calculating functions...

**Comment by DanVanAtta** [comment]
@frigoref  -- check https://github.com/frigoref/triplea/issues/2, it updates this branch

The build error was in the travis log:
```
/home/travis/build/triplea-game/triplea/src/util/triplea/mapXmlCreator/GameSequencePanelTest.java:9: error: cannot find symbol
  @Test
   ^
  symbol:   class Test
```

Problem was a test file was located in:
/home/travis/build/triplea-game/triplea/**src**/util/triplea/mapXmlCreator/GameSequencePanelTest.java:9: 

Instead of:
/home/travis/build/triplea-game/triplea/**test**/util/triplea/mapXmlCreator/GameSequencePanelTest.java:9: 


After merging that PR, you're going to have to deal with:
```
util.triplea.mapXmlCreator.CanalDefinitionsPanelTest > testLayout FAILED
    java.awt.HeadlessException: 
    No X11 DISPLAY variable was set, but this program performed an operation which requires it.
util.triplea.mapXmlCreator.GameSequencePanelTest > testLayout FAILED
    java.awt.HeadlessException: 
    No X11 DISPLAY variable was set, but this program performed an operation which requires it.
```

**Comment by DanVanAtta** [comment]
@frigoref , that last error is from running tests that require a UI from a headless console. It's not easy to fix, you can't launch any swing components in your test. essentially you need to mock them pretty aggressively. Likely that won't be easy. Fixes are: Deleting the tests or reworking them, or maybe @ignore them (which is effectively deleting them the lazy way)

**Comment by DanVanAtta** [comment]
Hmm, these classes are really isolated from the rest of the code... I think this is a good time to pause and consider if the mapXml creator should just get its own repo. We could not share code as easily until a jar build was set up. But, there would not be merge conflicts, and we would have good isolation of areas of concern - game engine in one repo, map XML tool in another repo. 

Another benefit is that the releases would be decoupled too. Also, the CR process would be completely different, much more on demand otherwise @frigoref  I think could run free in that code for the most part. 

@frigoref , thoughts on just grabbing a new repo for the map XML maker?

**Comment by DanVanAtta** [comment]
@frigoref , why closed?

**Pull request closed without merging**
