### PR TITLE
Add ww2v6_variants

### PR DESCRIPTION
**Pull request by RogerCooper**

### CODE REVIEW

**Comment by Cernelius** [comment]
I wouldn't add these in the repository or anywhere. They were meant soley for demostrating features using a simple base map.

**Comment by RogerCooper** [comment]
I think that demonstration scenarios belong in the experimental category. They were called Cernel **Experiments**.

**Comment by Cernelius** [comment]
It depends if the repository is assumed to host only maps meant to be played.

Although these games may be playable, they have not been made to be played but just to test features.

**Comment by bacrossland** [comment]
The repository is meant to hold playable and experimental games. There are 77 experimental games on the list of that file already. This would be the 78th. There is nothing wrong with merging this into in.

**Comment by DanVanAtta** [comment]
It is fine to also have in-development maps be added and made available. These are cases where the 'experimental' category is a very accurate description of the map. OTOH maps that serve no real purpose and are just abandoned in a very incomplete state, perhaps we can and should prune those.

**Comment by RogerCooper** [comment]
I have been reviewing a lot of old scenarios, cleaning them up and posting them.

**Pull request merged**
