### PR TITLE
[JavaFX] Use Borderless Fullscreen as only and default option

### PR DESCRIPTION
**Pull request by RoiEXLab**
Also a minor refactoring change to avoid confusion

### CODE REVIEW

**Comment by ron-murhammer** [comment]
@RoiEXLab Didn't test this but would this make the game launch in full screen and have that as the only option?

**Comment by ron-murhammer** [comment]
I think we need to leave a windowed option and make sure we can properly exit from it if its default.

**Comment by ssoloff** [comment]
@RoiEXLab Any reason we can't have a key to toggle between full screen and windowed mode?  The following hack uses <kbd>F11</kbd> to enter full screen mode and the platform default key (<kbd>Esc</kbd> for me) to exit full screen mode:

```diff
diff --git a/src/main/java/org/triplea/client/ui/javafx/TripleA.java b/src/main/java/org/triplea/client/ui/javafx/TripleA.java
index 2f393d2e8..5d65aa5d7 100644
--- a/src/main/java/org/triplea/client/ui/javafx/TripleA.java
+++ b/src/main/java/org/triplea/client/ui/javafx/TripleA.java
@@ -52,7 +53,11 @@ public class TripleA extends Application {
   }
 
   private void setupStage(final Stage stage, final Scene scene) {
-    stage.setFullScreenExitKeyCombination(KeyCombination.NO_MATCH);
+    scene.setOnKeyPressed(event -> {
+      if (event.getCode() == KeyCode.F11) {
+        stage.setFullScreen(true);
+      }
+    });
     stage.setFullScreen(true);
 
     Font.loadFont(TripleA.class.getResourceAsStream(FxmlManager.FONT_PATH.toString()), 14);
```

There's probably a better way to do that via the FXML.

**Comment by RoiEXLab** [comment]
@ssoloff @ron-murhammer
Well the game can be exited by clicking on the big exit button on the main menu.
Also I don't want to have this option as the only option available in the final version, but I wanted it to be like this until I can make it a setting.

And I agree F11 should be a fullscreen toggle.

**Comment by ssoloff** [comment]
@RoiEXLab Sounds like a plan.

**Pull request merged**
