### PR TITLE
CRLF fixup 

### PR DESCRIPTION
**Pull request by gaborbernat**
[Review on Reviewable](https://reviewable.io/reviews/triplea-game/triplea/151)

### CODE REVIEW

**Comment by DanVanAtta** [comment]
Confirming I can reproduce this fix.

**Comment by veqryn** [comment]
@gaborbernat @DanVanAtta 
Does changing to `text=auto` cause issues?
Wouldn't this mean that on Windows, all text files will come with CRLF, even when we specifically want some to come with only LF (the *.sh files, plus the Mac os text file)?

**Comment by gaborbernat** [comment]
Technically that shouldn't be the case, the auto is just there that for
checkout use the OS for all files. Subsequent filters are stronger and
those will be applied. And yes the sh files are unhandled, however any
Linux system is smart enough to not complain about it. Nevertheless we can
force it.

Bernát GÁBOR

**Comment by veqryn** [comment]
Letting *.sh files have CRLF on windows is part of how we got into this mess in the first place.
We should explicitly force all files to either be CRLF or LF, depending on their need, so that there is never any question in the future.  And most importantly, so that noone is able to get a loose CRLF in a file that should only have LF, or the other way around, regardless of which OS they are on, or what their git settings are.

Can you add the following to the .gitattributes file please?
```# Declare files that will always have LF line endings on checkout.
MacOS_users_read_this_first.txt eol=lf
*.sh
*.java
```

**Comment by gaborbernat** [comment]
Why the Java files?

On 9/9/15, Chris Duncan <notifications@github.com> wrote:
> Letting *.sh files have CRLF on windows is part of how we got into this mess
> in the first place.
> We should explicitly force all files to either be CRLF or LF, depending on
> their need, so that there is never any question in the future.  And most
> importantly, so that noone is able to get a loose CRLF in a file that should
> only have LF, or the other way around, regardless of which OS they are on,
> or what their git settings are.
>
> Can you add the following to the .gitattributes file please?
> ```# Declare files that will always have LF line endings on checkout.
> MacOS_users_read_this_first.txt eol=lf
> *.sh
> *.java
> ```
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/triplea-game/triplea/pull/151#issuecomment-138789562


-- 
 Bernát Gábor
Student -  Budapest University of Technology and Economics - Computer
Engineering, M.Sc. - Budapest, Hungary
System Integrator - Gravity R&D | Rock Solid Recommendations - Budapest
office | 5-7 Expo ter | H-1101 | Budapest | Hungary

**Comment by veqryn** [comment]
Consistency

**Comment by gaborbernat** [comment]
You haven't convinced me, why would it be consistent to have them as LF?

On 9/9/15, Chris Duncan <notifications@github.com> wrote:
> Consistency
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/triplea-game/triplea/pull/151#issuecomment-138790186


-- 
 Bernát Gábor
Student -  Budapest University of Technology and Economics - Computer
Engineering, M.Sc. - Budapest, Hungary
System Integrator - Gravity R&D | Rock Solid Recommendations - Budapest
office | 5-7 Expo ter | H-1101 | Budapest | Hungary

**Comment by DanVanAtta** [comment]
Careful about the problem of line endings on various OS, it was stated in reverse. To be clear, this is the bug report we are trying to avoid: "http://tripleadev.1671093.n2.nabble.com/DOS-line-terminators-for-triplea-unix-sh-in-1-8-0-7-td7589185.html"   It is a defect to have CRLF on unix for shell scripts, but it is a visual annoyance to have LF only on windows.

To be explicit, the problems of wrong line endings on different OS look like this:
LF only on windows => notepad and other windows editors sees no line breaks
CRLF on unix => shell scripts stop working since "/bin/bash^M" DNE -  some Java parsers that do not trim their input will have an unexpected character at the end of the line - and grep regex needs to be expanded to allow for an optional character that is not always expected (and that seems to be pretty much the  extent of it)

If you are executing a shell script in windows, then chances are it is in cygwin, which is happy dealing with a mix of CRLF and LF. If it is a bat file, I'm not sure if it matters if it is CRLF or LF. 



Why LF in Java files? This is to not force CRLF, a windows only thing on the rest of the world. No other OS needs that, and so they then have to do something to avoid causing a sprinkling of LF only whenever they edit code. This then looks really weird since some lines are not formatted correctly in windows, and there are constant whitespace only changes polluting diffs. To address this windows OS developers do work (and generally there is none since most windows IDE do not mind LF only), to ensure they do not add CRLF into source. Since source is typically run by linux systems, not bundling windows line endings in Jar files that are then run on linux systems is then one fewer things to go wrong.

**Comment by veqryn** [comment]
The reason to force *.java files to have LF only, is basically to simplify diff's.
Any time a windows person makes a new class, it would have CRLF by default of the OS, and then the next time a person on Linux edited this file, the diff would show the entire file changed (instead of just the edited part) because the Linux person's git would probably be automatically stripping the CR.

**Comment by veqryn** [comment]
The following should be added to the binary part:
```
*.bmp  binary
*.icns binary
*.nsi  binary
*.pdn  binary
*.xlsx binary
```

And the following I am unsure where they should go, but they need to go somewhere:
```
*.gradle
*.gradlew
*.settings
*.yml
*.md
*.plist
*.xslt
```

**Comment by DanVanAtta** [comment]
Getting same merge conflict now, it's pretty bad news. I think the same fix needs to be re-applied again from a fresh master. I have one PR built on #151 and have to resort to the .gitattribute auto-modify work-around to prevent the end of lines from being corrected.

@gaborbernat , can you re-apply your fix or update this PR?

@veqryn Can we get this one merged once updated relatively soon? It is a good fix, and let's us move on  *with* the .gitattributes file, win/win.

**Comment by DanVanAtta** [comment]
LF:
*.gradlew, *.gradle, *.yml, *.md

`*.gradlew` is a shell wrapper script executed by *nix,  LF unless specific reason otherwise, same with .gradle, 

`*.yml`, applies to travis files, no good reason to introduce CRLF there without reason.

`*.md` These are github md files, LF unless reason for CRLF

Doesn't matter: *.xslt
`*.xslt` xml style sheet transform, we have all the other meta XML doc types as CRLF, so doesn't matter.

I don't have these files:
*.settings, *.plist

**Comment by gaborbernat** [comment]
Still not convinced. If the auto is specified GIT always uses the OS
specific line endings in the working directory, and converts it to LF
inside its internal database. So no conflicts present there. The only
reason to force something to be some way if that can be packaged in the
release package and hence, the end user has a different OS than on what the
package was created. Java files are not added to the release (installer
files and readmes yes). So why force some specific line ending on them?

Bernát GÁBOR

**Comment by DanVanAtta** [comment]
Maybe I've been looking at the question from the wrong angle. Forcing Java with LF prevents windows from adding CRLF unintentionally. A  benefit.

A second benefit, allows VI sessions without seeing ugly "^M" all over the place and simplifies regex. (The the record and replay mode in VI is really powerful, so that is an actual use case not covered by eclipse).  Given the audience for viewing java source files is only 4 people, it's a less hypothetical of a consideration than for other files at least.

Unless there is absolute good reason for not specifying java files as LF (please state it explicilty), let's move forward.

**Comment by DanVanAtta** [comment]
Ugh, read the comments on gitter.. Yeah, I agree that I think we are being aggressive in specifying every file and not just release files. That is pretty good reason to not force java files to "^M". That does not mean linux users will have to see "^M" all over the place. 

@gaborbernat , does that prevent windows users from adding CRLF into the repo for java files if we don't specify java files as LF?

**Comment by gaborbernat** [comment]
if we add auto on Linux and MAC all java files will have LF only,
regardless of how the user have committed it on Windows. Hence, my
confusion :) At commit time with auto git will convert on Windows CRLF
to LF, and keep the LF on Linux/MAC.

On 9/9/15, Dan Van Atta <notifications@github.com> wrote:
> Maybe I've been looking at the question from the wrong angle. Forcing Java
> with LF prevents windows from adding CRLF unintentionally. A  benefit.
>
> A second benefit, allows VI sessions without seeing ugly "^M" all over the
> place and simplifies regex. (The the record and replay mode in VI is really
> powerful, so that is an actual use case not covered by eclipse).  Given the
> audience for viewing java source files is only 4 people, it's a less
> hypothetical of a consideration than for other files at least.
>
> Unless there is absolute good reason for not specifying java files as LF
> (please state it explicilty), let's move forward.
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/triplea-game/triplea/pull/151#issuecomment-138850202


-- 
 Bernát Gábor
Student -  Budapest University of Technology and Economics - Computer
Engineering, M.Sc. - Budapest, Hungary
System Integrator - Gravity R&D | Rock Solid Recommendations - Budapest
office | 5-7 Expo ter | H-1101 | Budapest | Hungary

**Comment by DanVanAtta** [comment]
auto sounds like what we want

**Comment by veqryn** [comment]
Ok, so just add these then?

```
# Declare files that will always have LF line endings on checkout.
*.sh   eol=lf
MacOS_users_read_this_first.txt eol=lf

*.bmp  binary
*.icns binary
*.nsi  binary
*.pdn  binary
*.xlsx binary
```

**Comment by DanVanAtta** [comment]
Sounds like things are getting closer.

The `MacOS_users_read_this_first` does not need to be specified. Testing the Mac DMG in last release I was surprised to learn you can't actually read that file until *after* you have installed. Considering it tells you *how* to installer, *after* the fact, it is not terribly useful in its current location.

**Comment by veqryn** [comment]
Then ant/gradle should be updated to place it somewhere more useful.  
In either case, it should still be LF only.  But I'm not going to beat this point to death since it isn't a script file, just a text file for viewing.

**Comment by gaborbernat** [comment]
There is nowhere more useful. An installer is a runnable. So you
cannot place it anywhere in the installer. I think it should be
present on the web, where the user downloads the installer.

On 9/9/15, Chris Duncan <notifications@github.com> wrote:
> Then ant/gradle should be updated to place it somewhere more useful.
> In either case, it should still be LF only.  But I'm not going to beat this
> point to death since it isn't a script file, just a text file for viewing.
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/triplea-game/triplea/pull/151#issuecomment-138996189


-- 
 Bernát Gábor
Student -  Budapest University of Technology and Economics - Computer
Engineering, M.Sc. - Budapest, Hungary
System Integrator - Gravity R&D | Rock Solid Recommendations - Budapest
office | 5-7 Expo ter | H-1101 | Budapest | Hungary

**Comment by veqryn** [comment]
@gaborbernat: just waiting for the updated .gitattributes file, so i can test this on both windows and linux

**Comment by veqryn** [comment]
@gaborbernat: @DanVanAtta:
So, two issues:
1. I am still waiting for you to update this PR with the changes .gitattributes
2. I can not seem to test your PR because whenever I try to test it, I get the following error:
(delete my whole directory, git clone triplea)
git status (shows a bunch of files have changed, probably because of the .gitattributes)
git checkout -b gaborbernat-master master (successful)
git pull https://github.com/gaborbernat/triplea.git master
gives this error:
error: Your local changes to the following files would be overwritten by merge: ...
Please commit your changes or stash them before you can merge.  Aborting.
I tried stash, that didn't work.  I tried git commit -a, and that just means when I try to pull the changes in, I get:
Conflict: Merge conflict in ...

**Comment by gaborbernat** [comment]
updated :)

**Comment by veqryn** [comment]
@gaborbernat: ok, now i am super confused.  it looks like .gitattributes is no longer a part of your PR at all...

**Comment by gaborbernat** [comment]
everything should be okay now :) the merge removed some amendment to the file, however now it's fine.

**Comment by veqryn** [comment]
Ok, so can I just confirm what all this PR is?
This PR is some changes to .gitattributes,
plus you've deleted all CR from ALL text files.
right, or no?

**Comment by gaborbernat** [comment]
I updated the .gitattributes, plus converted all files to the correct format :)

**Comment by veqryn** [comment]
What is the correct format, and how did you do this?

**Comment by gaborbernat** [comment]
the correct format is what it is stated in the gitattributes. I'm on Linux so all is LF, except what is stated as CRLF in  the gitattribute. This will ensure the behavior we want. On Windows Java files will get checked out as CRLF.

**Comment by veqryn** [comment]
So, how is this PR any different than https://github.com/triplea-game/triplea/pull/148 ?

**Comment by gaborbernat** [comment]
Well the structure of the .gitattributes is somehow different, and this way it seems to work for me and Dan on Linux and Mac (confirmed). Not sure why the #148 is not working for us, however it does not. Maybe it has something to do with the different gitattribute structure, no idea.

**Comment by veqryn** [comment]
It looks like you've changed the .gitattributes from what it looked like an hour ago.
I think perhaps the thing that made it work for you and Dan was the: `* text=auto`

**Comment by gaborbernat** [comment]
Damn, that's a bug... crazy rebasing, just a second fixing that.

**Comment by gaborbernat** [comment]
Done :)

**Comment by veqryn** [comment]
So, where are there 105 files showing changes?
If i run the following (which would put all files to their correct line endings) I only see around 73 files changed:
```

find ./ -type f -name "*.bat" -exec unix2dos {} \;
find ./ -type f -name "*.txt" -exec unix2dos {} \;
find ./ -type f -name "*.ini" -exec unix2dos {} \;
find ./ -type f -name "*.properties" -exec unix2dos {} \;
find ./ -type f -name "*.xml" -exec unix2dos {} \;
find ./ -type f -name "*.html" -exec unix2dos {} \;
find ./ -type f -name "*.css" -exec unix2dos {} \;
find ./ -type f -name "*.dtd" -exec unix2dos {} \;
find ./ -type f -name "*.xslt" -exec unix2dos {} \;

dos2unix gradlew
find ./ -type f -name "*.sh eol=lf" -exec dos2unix {} \;
find ./ -type f -name "*.plist eol=lf" -exec dos2unix {} \;
find ./ -type f -name "*.gradle" -exec dos2unix {} \;
find ./ -type f -name "*.settings" -exec dos2unix {} \;
find ./ -type f -name "*.yml" -exec dos2unix {} \;
find ./ -type f -name "*.md" -exec dos2unix {} \;
find ./ -type f -name "*.java" -exec dos2unix {} \;
```

**Comment by gaborbernat** [comment]
you're too restrictive, I ran on m Linux machine dos2unix **/* and after only the dos2unix parts :) to cover all cases.

**Comment by veqryn** [comment]
Can you tell me the exact commands you used, all of them, in order?

**Comment by gaborbernat** [comment]
```
dos2unix **/*
unix2dos **/*.bat
unix2dos **/*.txt
unix2dos **/*.ini
unix2dos **/*.properties
unix2dos **/*.xml
unix2dos **/*.html
unix2dos **/*.css
unix2dos **/*.dtd
```

**Comment by veqryn** [comment]
Ok, so i can confirm that this does not work on centos 6.6, git version 1.7.1
I will now test it on a more recent version of fedora.

**Comment by gaborbernat** [comment]
well the .gitattributes support was finalized sometime around 1.8.4; so git 1.7.1 is like ancient old :)

**Comment by veqryn** [comment]
sadly, that is the most recent version supported by yum on centos 6

**Comment by gaborbernat** [comment]
exactly, why I would not recommend to anyone using centos for development :)

**Comment by veqryn** [comment]
I use that os in general because my work place uses it. If this works on my fedora vm and my windows, then I'll stop using it for triplea.

**Comment by veqryn** [comment]
ok, as far as i can tell, this works
i will commit this, and hopefully things won't go bonkers when we start doing stuff on top of it in windows and linux/mac

**Pull request merged**
