### PR TITLE
Veqryn final cleanup

### PR DESCRIPTION
**Pull request by veqryn**
[Review on Reviewable](https://reviewable.io/reviews/triplea-game/triplea/65)

### CODE REVIEW

**Comment by DanVanAtta** [comment]
This looks good. Except, looks like eclipse formatter needs to be updated to go to 120 lines.




#54 will help with this, but we have some places where we update dead code:
```
   * {
    * //if (m_property == null || m_value == null || m_oldValue == null)
    * //throw new IllegalStateException("SetPropertyChange may not have null arguments");
-   *
    * return m_property + " changed from " + m_oldValue.toString() + " to " + m_value.toString();
    * }
    */
```

As a big plus, when reviewing the changes (I checked out the branch and did the diff there), there were some red (removed) lines that did not fit. All green lines did though :+1: 

So even if i'll have some merge conflicts to fix, I like the change and think it can be merged now. We can update the eclipse line to 120 as this PR or a new one.

**Comment by DanVanAtta** [comment]
Changing my opinion now that I'm working through merge conflicts. #54 has 90 merge conflicts. Since #54 was done by hand, I'd like to see that get merged first then this done after that. If this gets merged first though I won't be too unhappy, I'm finding some good extra stuff to clean while fixing the conflicts.

**Comment by DanVanAtta** [comment]
I've been using this script to squash my commits:
```
$ cat ~/bin/git_squash 
#!/bin/bash

function usage() {
  echo "$(basename $0) <commits_to_squash>"
  echo "  commits_to_squash = how many prior commits in local history to squash"
  exit -1
}

HOW_MANY_COMMITS=$1
if [ -z "$HOW_MANY_COMMITS" ]; then
  usage
fi

git reset --soft HEAD~${HOW_MANY_COMMITS} && 
git commit --edit -m"$(git log --format=%B --reverse HEAD..HEAD@{1})"
```

You can still squash your commits even:
```
# from local
$ ~/bin/git_squash 4
$ git push origin -f <branch_name>  (-f force the history overwrite)
```

There's probably better more git native ways to do the same, but figured I'd share.

**Comment by DanVanAtta** [comment]
Why is squash good? One commit can be pulled out easily and keeps the history linear (avoids the zipper merge of commits by create date scattered in time between different branches). With squash, the commits are shrunk to one, so they are then done in one go. Easy to undo, history is linear, commit log is cleaner.

**Comment by veqryn** [comment]
I had actually had changed the format style xml, but that was part of the changes when i had incorrectly checked out this branch on my windows machine.
I am having to bounce between machines, and did not know how to check out and change a branch correctly, so my change was lost.

I do not think squash is necessary, because github squashes automatically when you merge a pull request.  Right?  And when you review a pull request, you can review all the differences, or the commits separately.

**Comment by gaborbernat** [comment]
No automatic squash :) just adds another merge commit :)

**Comment by veqryn** [comment]
@DanVanAtta so, which pull to do first?

**Comment by DanVanAtta** [comment]
@veqryn  #54 first please

**Pull request closed without merging**
