### PR TITLE
Bump game version to 1.9.0.1 and mark that as latest

### PR DESCRIPTION
**Pull request by DanVanAtta**

### CODE REVIEW

**Comment by ron-murhammer** [comment]
@DanVanAtta Do we need to go to 1.9.1.0 instead? Are save games broken?

**Comment by DanVanAtta** [comment]
Not as far as I know.

**Comment by simon33-2** [comment]
I'm in favour of this. There are too many builds of 1.900 out there.

**Comment by ron-murhammer** [comment]
@DanVanAtta So which compatibility was broken? Just lobby?

**Comment by DanVanAtta** [comment]
Apparently a problem during placement phase that is most likely triggered by different versions. I have no further details.

**Pull request merged**
