### PR TITLE
JavaFX additions

### PR DESCRIPTION
**Pull request by RoiEXLab**
Normally this should really be a no-brainer, until I realized the icons I was using in this PR were licensed under [The Apache license 2.0](https://www.iconfu.com/apache_license_2_0), which is incompatible with GPL 2.0 , but not with GPL 3.0.
However we're already depending on guava, so we might need to reconsider a couple of things.

Also a minor issue: the icons look pixelated in the GUI, although their resolution is pretty high.

### CODE REVIEW

**Comment by ssoloff** [comment]
> The Apache license 2.0, which is incompatible with GPL 2.0 , but not with GPL 3.0.

I missed that qualifier on the [GNU site](https://www.gnu.org/licenses/license-list.en.html#apache2).  Ugh... 🤕

**Comment by RoiEXLab** [comment]
@ssoloff @ron-murhammer Thoughts?

**Comment by ssoloff** [comment]
@RoiEXLab Looks good, but what is the Host Networked Game image supposed to represent?  It looks like a Rorschach inkblot to me. :smile:

**Comment by RoiEXLab** [comment]
@ssoloff It's supposed to be a globe ^^

**Comment by ssoloff** [comment]
@RoiEXLab Well, if that's supposed to be North and South America, I guess I can see it if I cross my eyes a bit.  Otherwise, I failed the inkblot test. :smile:

**Comment by RoiEXLab** [comment]
@ssoloff If you prefer other images we can use those as well :D
This was just the first free icons I could get my hands on ^^

**Comment by ron-murhammer** [comment]
@RoiEXLab Is this still behind a beta flag? For images, we could also reach out to some of our wonderful mapmakers for input as a few of them are great with graphics.

**Comment by RoiEXLab** [comment]
@ron-murhammer The images are just for JavaFX, so alpha flag is more appropriate.
Good idea.
I'll create a Thread later this day.

**Pull request merged**
