### PR TITLE
Fix null pointers

### LINKED ISSUE #3369: Bot logs:  java.lang.NullPointerException at DefaultNamed.java:33
Looking at logs, ran across the following:

```
Apr 14 17:32:00 localhost run_bot[28113]: Apr 14, 2018 5:32:00 PM games.strategy.net.ServerMessenger socketUnqaurantined
Apr 14 17:32:00 localhost run_bot[28113]: INFO: Connection added to:akaroadman port:50970 ip:xx.xx.xxx.xxx
Apr 14 17:32:00 localhost run_bot[28113]: Apr 14, 2018 5:32:00 PM games.strategy.engine.chat.ChatController joinChat
Apr 14 17:32:00 localhost run_bot[28113]: INFO: Chatter:akaroadman port:50970 ip:96.59.217.232 is joining chat:games.strategy.engine.framework.ui.ServerStartup.CHAT_NAME
Apr 14 17:32:02 localhost run_bot[28113]: Failed to join game
Apr 14 17:32:02 localhost run_bot[28113]: java.lang.NullPointerException
Apr 14 17:32:02 localhost run_bot[28113]:         at games.strategy.engine.data.DefaultNamed.equals(DefaultNamed.java:33)
Apr 14 17:32:02 localhost run_bot[28113]:         at java.util.HashMap.putVal(HashMap.java:635)
Apr 14 17:32:02 localhost run_bot[28113]:         at java.util.HashMap.put(HashMap.java:612)
Apr 14 17:32:02 localhost run_bot[28113]:         at java.util.HashSet.readObject(HashSet.java:342)
Apr 14 17:32:02 localhost run_bot[28113]:         at jdk.internal.reflect.GeneratedMethodAccessor6.invoke(Unknown Source)
Apr 14 17:32:02 localhost run_bot[28113]:         at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
Apr 14 17:32:02 localhost run_bot[28113]:         at java.lang.reflect.Method.invoke(Method.java:564)
Apr 14 17:32:02 localhost run_bot[28113]:         at java.io.ObjectStreamClass.invokeReadObject(ObjectStreamClass.java:1160)
Apr 14 17:32:02 localhost run_bot[28113]:         at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2211)
Apr 14 17:32:02 localhost run_bot[28113]:         at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2082)
```

### Engine version
9480

### My Operating System
Bot

### Map name
n/a

### Can you describe how to trigger the error? (eg: what sequence of actions will recreate it?)
unknown

### LINKED ISSUE #3371: Bot startup -  java.lang.NullPointerException at  speakerAdded(Chat.java:295)
Notice the NPE below. See this often on bot startup (if not always). Does not seem to be impactful, but noting the exception here so it can be tracked/fixed:

```
Apr 16 08:39:42 bot35_frankfurt_de run_bot.sh: Apr 16, 2018 8:39:42 AM games.strategy.engine.message.unifiedmessenger.UnifiedMessenger invoke
Apr 16 08:39:42 bot35_frankfurt_de run_bot.sh: WARNING: null
Apr 16 08:39:42 bot35_frankfurt_de run_bot.sh: java.lang.NullPointerException
Apr 16 08:39:42 bot35_frankfurt_de run_bot.sh: #011at games.strategy.engine.chat.Chat$1.speakerAdded(Chat.java:295)
Apr 16 08:39:42 bot35_frankfurt_de run_bot.sh: #011at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
Apr 16 08:39:42 bot35_frankfurt_de run_bot.sh: #011at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
Apr 16 08:39:42 bot35_frankfurt_de run_bot.sh: #011at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
Apr 16 08:39:42 bot35_frankfurt_de run_bot.sh: #011at java.lang.reflect.Method.invoke(Method.java:498)
Apr 16 08:39:42 bot35_frankfurt_de run_bot.sh: #011at games.strategy.engine.message.unifiedmessenger.EndPoint.invokeSingle(EndPoint.java:157)
Apr 16 08:39:42 bot35_frankfurt_de run_bot.sh: #011at games.strategy.engine.message.unifiedmessenger.EndPoint.invokeMultiple(EndPoint.java:140)
Apr 16 08:39:42 bot35_frankfurt_de run_bot.sh: #011at games.strategy.engine.message.unifiedmessenger.EndPoint.invokeLocal(EndPoint.java:126)
Apr 16 08:39:42 bot35_frankfurt_de run_bot.sh: #011at games.strategy.engine.message.unifiedmessenger.UnifiedMessenger.invoke(UnifiedMessenger.java:152)
Apr 16 08:39:42 bot35_frankfurt_de run_bot.sh: #011at games.strategy.engine.message.UnifiedInvocationHandler.invoke(UnifiedInvocationHandler.java:48)
Apr 16 08:39:42 bot35_frankfurt_de run_bot.sh: #011at com.sun.proxy.$Proxy2.speakerAdded(Unknown Source)
Apr 16 08:39:42 bot35_frankfurt_de run_bot.sh: #011at games.strategy.engine.chat.ChatController.joinChat(ChatController.java:116)
Apr 16 08:39:42 bot35_frankfurt_de run_bot.sh: #011at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
Apr 16 08:39:42 bot35_frankfurt_de run_bot.sh: #011at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
Apr 16 08:39:42 bot35_frankfurt_de run_bot.sh: #011at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
Apr 16 08:39:42 bot35_frankfurt_de run_bot.sh: #011at java.lang.reflect.Method.invoke(Method.java:498)
Apr 16 08:39:42 bot35_frankfurt_de run_bot.sh: #011at games.strategy.engine.message.unifiedmessenger.EndPoint.invokeSingle(EndPoint.java:157)
Apr 16 08:39:42 bot35_frankfurt_de run_bot.sh: #011at games.strategy.engine.message.unifiedmessenger.EndPoint.invokeMultiple(EndPoint.java:140)
Apr 16 08:39:42 bot35_frankfurt_de run_bot.sh: #011at games.strategy.engine.message.unifiedmessenger.EndPoint.invokeLocal(EndPoint.java:126)
Apr 16 08:39:42 bot35_frankfurt_de run_bot.sh: #011at games.strategy.engine.message.unifiedmessenger.UnifiedMessenger.invokeAndWait(UnifiedMessenger.java:105)
Apr 16 08:39:42 bot35_frankfurt_de run_bot.sh: #011at games.strategy.engine.message.UnifiedInvocationHandler.invoke(UnifiedInvocationHandler.java:52)
Apr 16 08:39:42 bot35_frankfurt_de run_bot.sh: #011at com.sun.proxy.$Proxy1.joinChat(Unknown Source)
Apr 16 08:39:42 bot35_frankfurt_de run_bot.sh: #011at games.strategy.engine.chat.Chat.<init>(Chat.java:83)
Apr 16 08:39:42 bot35_frankfurt_de run_bot.sh: #011at games.strategy.engine.chat.HeadlessChat.<init>(HeadlessChat.java:33)
Apr 16 08:39:42 bot35_frankfurt_de run_bot.sh: #011at games.strategy.engine.framework.startup.mc.ServerModel.createServerMessenger(ServerModel.java:280)
Apr 16 08:39:42 bot35_frankfurt_de run_bot.sh: #011at games.strategy.engine.framework.startup.mc.ServerModel.lambda$createServerMessenger$1(ServerModel.java:250)
Apr 16 08:39:42 bot35_frankfurt_de run_bot.sh: #011at java.util.Optional.map(Optional.java:215)
Apr 16 08:39:42 bot35_frankfurt_de run_bot.sh: #011at games.strategy.engine.framework.startup.mc.ServerModel.createServerMessenger(ServerModel.java:250)
Apr 16 08:39:42 bot35_frankfurt_de run_bot.sh: #011at games.strategy.engine.framework.headlessGameServer.HeadlessServerSetupPanelModel.showSelectType(HeadlessServerSetupPanelModel.java:24)
Apr 16 08:39:42 bot35_frankfurt_de run_bot.sh: #011at games.strategy.engine.framework.headlessGameServer.HeadlessGameServer.lambda$new$1(HeadlessGameServer.java:95)
Apr 16 08:39:42 bot35_frankfurt_de run_bot.sh: #011at java.lang.Thread.run(Thread.java:748)
Apr 16 08:39:42 bot35_frankfurt_de run_bot.sh: host:66.175.213.79 port:7000
Apr 16 08:39:42 bot35_frankfurt_de run_bot.sh: host:66.175.213.79 port:7000
```

### PR DESCRIPTION
**Pull request by RoiEXLab**
Should fix #3369 and fix #3371 
I'm open for discussions if you think simply "suppressing" the error message is not enough.

### CODE REVIEW

**Comment by RoiEXLab** [comment]
Interestingly enough a test is failing.
The weird thing is that I can't reproduce this failure on my machine.
I'll rever the change I assume to be the cause of this failure, but if anyone has an idea what might be the reason for this weird behaviour I'd like to hear it.
I assume it has something to do with latency.

**Comment by RoiEXLab** [comment]
This didn't fix the issue.
I have no idea what could be causing this then...

**Comment by RoiEXLab** [comment]
If someone has an idea, feel free to push to this branch directly, and to merge afterwards.

**Comment by RoiEXLab** [comment]
I have absolutely no idea why the tests are failing.
They work absolutely fine on my machine.
Please have a look and check if the test fails on your machine as well @ron-murhammer @DanVanAtta @ssoloff 
If it works fine, we'll probably have to change the test to something else...

**Comment by RoiEXLab** [comment]
@DanVanAtta it's still weird that all the tests pass on my machine.

**Comment by DanVanAtta** [comment]
Are you sure you're running the integration tests? There could be a bug in the test where something is aborting/terminating early but not failing the test

**Comment by RoiEXLab** [comment]
@DanVanAtta pretty sure, 'gradle check' passed and I ran the failing test explicitly both succeeded.

**Comment by RoiEXLab** [comment]
@DanVanAtta Switched to the fix-null-pointers-branch and edited the test to print "Success" at the end.
Here's the log:
```
Apr 24, 2018 6:59:30 PM games.strategy.net.ServerMessenger socketUnqaurantined
INFORMATION: Connection added to:client1 port:50051 ip:127.0.0.1
Apr 24, 2018 6:59:30 PM games.strategy.net.ServerMessenger socketUnqaurantined
INFORMATION: Connection added to:client2 port:50056 ip:127.0.0.1
Apr 24, 2018 6:59:30 PM games.strategy.engine.chat.ChatController joinChat
INFORMATION: Chatter:Server port:50042 ip:192.168.2.110 is joining chat:c
Apr 24, 2018 6:59:30 PM games.strategy.engine.chat.ChatController joinChat
INFORMATION: Chatter:client1 port:50051 ip:127.0.0.1 is joining chat:c
Apr 24, 2018 6:59:30 PM games.strategy.engine.chat.ChatController joinChat
INFORMATION: Chatter:client2 port:50056 ip:127.0.0.1 is joining chat:c
Apr 24, 2018 6:59:30 PM games.strategy.engine.chat.ChatController leaveChatInternal
INFORMATION: Chatter:client1 port:50051 ip:127.0.0.1 has left chat:c
Apr 24, 2018 6:59:30 PM games.strategy.engine.chat.ChatController leaveChatInternal
INFORMATION: Chatter:client2 port:50056 ip:127.0.0.1 has left chat:c
Success
```

**Comment by RoiEXLab** [comment]
@DanVanAtta I ran the tests uing gradle over the Windows 10 Ubuntu bash shell, still succeeds without any errors.
I believe @ron-murhammer is using Windows as well, so if tests succeed for him this might indicate an os related issue.

In any case, would you mind taking over this PR @DanVanAtta ? For obvious reasons it would be really annoying to have to rely on travis to see if the applied changes actually worked.

**Comment by RoiEXLab** [comment]
@DanVanAtta Tested again on another Windows machine.
All tests successfully execute.
There's not much I can do here without doing wild guesses.
Closing, hopefully someone picks this up

**Pull request closed without merging**
