### PR TITLE
Checkstyle: Fix abbreviation violations in local variables (part 4)

### PR DESCRIPTION
**Pull request by ssoloff**
This PR fixes violations of the Checkstyle AbbreviationAsWordInName rule in local variables.

For the most part, I did **not** expand abbreviations where they caused a violation; I simply converted them using the abbreviation naming convention established in #1659.  Please advise if any should be expanded.

The abbreviations that were expanded included:

* `AA` --> `AntiAir`
* `IT` --> `IndustrialTechnology`

Due to the large number of violations that fall under this category, the fixes are being split over multiple PRs to keep the review size reasonable.

### CODE REVIEW

**Comment by ron-murhammer** [comment]
@ssoloff I'm a little mixed on AA -> AntiAir as AA is a pretty common abbreviation.

**Comment by ssoloff** [comment]
@ron-murhammer I originally started expanding `AA` to `AntiAir` because `Aa` just looked weird.  Do you have any other suggestions?

**Comment by ron-murhammer** [comment]
@ssoloff Might want to put this one to a vote. I think I prefer Aa even though it looks a little funky but I could be the minority here.

**Comment by DanVanAtta** [comment]
IMO `Aa` in class names over `AntiAir` pretty easily. Though for variable names, it is marginal IMO. I'm quite okay with `Aa`, but am not opposed `antiAir` either.

**Comment by ssoloff** [comment]
@ron-murhammer Instances of `AntiAir` have been renamed to `Aa`, as requested.

**Pull request merged**
