### PR TITLE
[Add a SystemChecker] Add classes that support running local system checks at game launch

### PR DESCRIPTION
**Pull request by DanVanAtta**
[Add a SystemChecker] Add classes that support running local system checks at game launch. So far we check that we are able to create temporary files and able to connect to the internet. The goal behind this is to let users know earlier rather than later that some features may not work. This then allows us to focus on slightly more detailed error messages up front, and slightly less detailed messages later as we potentially encounter various error scenarios.

[Review on Reviewable](https://reviewable.io/reviews/triplea-game/triplea/436)

### CODE REVIEW

**Comment by gaborbernat** [comment]
overall I like what you added here, however I propose that we also say what features may not work instead of saying what does not works. Also can't connect to internet should state clearly that can't connect to Github/will not be able to download/update maps, as Github may be down. Also I propose we check with the URL an actual file from our repo in case with that happens something. 

---

Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/triplea-game/triplea/436#-:-KAOv4wAFEJKNIIaTokk:640428505)*

**Comment by DanVanAtta** [comment]
The vague message is partly intentional since:
 -  we may add more dependencies to github, a vague message will not need updating
-  I expect more often the problem will be 'wifi is off' rather than 'github is down'. In the first case there is no internet connection at all, so other things not on the list will also not work. When those items do not work, and the list did not mention it, it'll make the list seem wrong/buggy.

So perhaps the trick might be to to update the messaging more to: "Could not connect to Github, some game features may not work, please verify your internet connection. "


I'm considering the file URL suggestion, but have some concerns/questions:
- do we gain much benefit?
- it's an unexpected thing to update if the location/name of the file were to change
- files are hosted on a different domain in github. I suspect Github is able to achieve higher availability on their relatively simpler http website rather than where they host files/storage. In the case where Github file availability storage is not avaialble, I would want that feature to fail at the time of use. Consider example if a user does not use the feature at all - the problem would go completely unnoticed (worth a lot IMO). Another consideration, github could fail or internet could go out after game launch, so we still have to handle each component in the system as not being available.

So, what it gets down to: 
- we want to check if we have simple client network connectivity. This is so we can front load that help message at the start, rather than having to give a full detailed explanation everywhere network might fail. 

So perhaps really we should also be checking that we have access to a second high availability site (or maybe checking if we can hit a DNS server, if we have an IP). But at that point it seems like it's getting needlessly complicated (particularly since Github is likely a 99.999% available site, 10 minutes a year or less of downtime a year, shouldn't ever be an issue for long)

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/triplea-game/triplea/436#-:-KAP2daetBvaF1uy5QdZ:-325474845)*

**Comment by gaborbernat** [comment]
Okay, I see your point. I was thinking of making this a list and just add on new feature lines as we go. I would prefer to keep it in game. But we can keep it for now as general as possible. 

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/triplea-game/triplea/436#-:-KAPG3do_ks27vic-3pZ:-505898042)*

**Comment by DanVanAtta** [comment]
I cut this branch in the wrong spot. I added a commit to update the message to mention github and what was being checked for. See #446 for the updated PR

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/triplea-game/triplea/436#-:-KARBJ1wk4uVsU6yPj7z:1040476130)*

**Pull request closed without merging**
