### PR TITLE
Automatic Air Raids

### PR DESCRIPTION
**Pull request by simon33-2**
Just automate air raids so their always first and don't require clicks.

### CODE REVIEW

**Comment by DanVanAtta** [comment]
Can you fix the "+14,697 −15,172", the diff should not be that large, (and that's too much to review as well)

**Comment by simon33-2** [comment]
I'm not clear on how to do that @DanVanAtta 

Seems to be mostly white space differences.

**Comment by simon33-2** [comment]
I reapplied changes to the BattleTracker rather than including the commit which had them.

**Comment by DanVanAtta** [comment]
Looks like a lot of it is coming from "test_data/ww2_g40_balanced.xml". Probably line endings were auto-converted for you there. Which Git client are you using? You should be able to back out that one file, then redo the changes on it and recommit it.

**Comment by DanVanAtta** [comment]
Ah, I see you got it in #1426, thanks.

**Pull request closed without merging**
