### PR TITLE
Do not kill game when failing to find icon on Mac operating systems, …

### PR DESCRIPTION
**Pull request by DanVanAtta**
…instead print a warning message to the console.

[Review on Reviewable](https://reviewable.io/reviews/triplea-game/triplea/88)

### CODE REVIEW

**Comment by ron-murhammer** [comment]
@DanVanAtta would it make more sense to just make a single pull request to the release 1807 branch for all fixes related to that release. Then we can just merge all those changes into master. Otherwise we end up with lots of duplicate pull requests.

**Comment by veqryn** [comment]
Make all changes to the release_1_8_0_7 branch, then when we are done, we will merge it with master

**Comment by DanVanAtta** [comment]
@ron-murhammer No, it doesn't necessarily make more sense. At this point the current release branch I would completely throw away and re-cut.  Then again, I would not let anyone except for a beta user get access to it knowing it's yet to be regression tested on all platforms.

**Comment by DanVanAtta** [comment]
I opened an issue #94 to discuss in more detail how to do bug patches into master.

**Pull request closed without merging**
