### PR TITLE
Update asset download for missing unit scroller images

### PR DESCRIPTION
**Pull request by ron-murhammer**
Missing unit scroller images causing errors

### CODE REVIEW

**Comment by ron-murhammer** [comment]
@DanVanAtta I think this unfortunately shows another down side of splitting those assets out and any update to them then requires devs to remember to update the gradle build to pull a new version. Merging this.

**Comment by DanVanAtta** [comment]
Which image was missing?
I don't think it necessarily mattered that the logic was split if the image reference was just wrong. Having the assets split does have advantages, notably that we can update image names and choose when we pick them up. The build also automatically updates images to be losslessly compressed, that would be painful on the 'main build'. And to another extent, we simply do not have much space left in the main repo, it's slow to clone and we are not that far away from 1 gig, it's not viable to keep assets there.

> them then requires devs to remember to update the gradle build to pull a new version. 

IE, this is actually a feature, I wonder where the issue was as I was not aware that the names had changed. There was also a PR for this update, I wonder what happened to it.

**Comment by DanVanAtta** [comment]
It is also nice to be able to work on images without needing to put those as part of the PR that uses them. Blocking code+image work on review is more painful compared to iterating on images and allow those to be updated without dependency on code. For example the 'wake-all' image is committed but not used. IF it were part of the code base, it'd be a dead asset and should never have been merged (and if merged, it re-opens the slippery slope where we had accumulated many unused assets, it was a task to identify how many were unused, there were quite a number. It's also painful to have those as one would be nervous update updating them in case it breaks something non-obvious. Support for dead-code, or dead-images is quite demoralizing and inefficient).

**Comment by DanVanAtta** [comment]
The update was in-flight: https://github.com/triplea-game/triplea/pull/5474

Looks like we needed to merge in-order, or include the update with the dependency change. Probably the latter, I'm not sure if it was realized there was actually a dependency change. So a few things came along to contribute here, because we had a problem, we should not ignore there are many benefits. For example, update no20 in assets was ignored and reverted, it was *really* good to not have to do that experimentation in the main repo, wasting space and time, and was *really* good to have a place where we can avoid CR delay.

**Pull request merged**
